### PR TITLE
Fix for Github issue 2530

### LINKED ISSUE #2530: MolChemicalFeature.GetPos() returns value for molecule's default conformer
**Description:**

Reported on the mailing list here: https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg09001.html

The python wrapper needs an overload of `MolChemicalFeature.GetPos()` that takes no arguments (instead of the current code, which defaults the confId to -1).

### PR DESCRIPTION
**Pull request by MaxGreil**
#### Reference Issue
Fixes #2530

#### What does this implement/fix? Explain your changes.
- Added a second method to the python wrapper (in the Wrap/MolChemicalFeature.cpp file) that takes no arguments and that points to the overload MolChemicalFeature::getPos().
- Remove the default value from the method.
- Added tests for new functionality

### CODE REVIEW

**Comment by greglandrum** [comment]
Hi @MaxGreil : thanks for the contribution!
The failing CI builds are indicating that the changes you made are causing one of the existing unit tests to fail. Please take a look at that; once the CI builds are working we'll do the code review.

**Comment by MaxGreil** [comment]
Hi @greglandrum, the CI builds are now working.

File: Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeature.cpp [hunk 1]
```diff
@@ -54,8 +54,13 @@ struct feat_wrapper {
         .def("GetPos",
              (RDGeom::Point3D(MolChemicalFeature::*)(int) const) &
                  MolChemicalFeature::getPos,
-             (python::arg("self"), python::arg("confId") = -1),
+             (python::arg("self"), python::arg("confId")),
              "Get the location of the chemical feature")
+        .def("GetPosDefault",
```
Comment (greglandrum) [inline Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeature.cpp:59]: I'm curious why you went the route of adding a new method name for this.

Given that you it would be possible to just have an an overload of `GetPos()`, and that this change breaks existing code, I wonder why you chose to go this way.

Comment (MaxGreil) [reply Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeature.cpp]: You are correct. I changed it.

**Review by greglandrum — APPROVED** [review]

**Comment by greglandrum** [comment]
Thanks @MaxGreil !
