### PR TITLE
Fixes #5156

### LINKED ISSUE #5156: KekulizeException of molecule from Smarts pattern with new RDKit release
**Describe the bug**
With the new release of RDKit (2022.03.1) we observed a KekulizeException that was not thrown by the previous RDKit release (2021.09.5), which prevents the rendering of a certain Smarts pattern with the `Draw.MolsToGridImage` functionality.

**To Reproduce**
```
from rdkit import Chem
mol = Chem.MolFromSmarts("[#6](:,-[#6]-,:[#7]-,:[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1):,-[#6]:,-[#7]:,-[#6]")
Chem.Kekulize(m1)
```

**Expected behavior**
Both version behave consistent.

**Configuration (please complete the following information):**
 - RDKit versions: 2022.03.1 and 2021.09.5
 - OS: Ubuntu 20.04, MacOS, Windows
 - Python 3.7 - 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge  

**Additional context**
If the KekulizeException is correctly thrown for this Smarts pattern in the new RDKit version, it would be great to still be able to visualize it with `Draw.MolsToGridImage`. However, I cannot find a possibility to prevent the kekulization of the given molecules in this function, so the KekulizeError always gets thrown.

Thanks in a advance,
David

### PR DESCRIPTION
**Pull request by greglandrum**
The setting `prepareMolsBeforeDrawing` was being ignored for molecules which don't have a conformer. This modifies `initDrawMolecule()` to have it explicitly generate 2D coordinates for cases where they are needed and `prepareMolsBeforeDrawing` is set to False

There's also a small change to call `mol.updatePropertyCache()` from  `RDDepictor::compute2DCoords()` when necessary.

### CODE REVIEW

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 1]
```diff
@@ -141,9 +142,13 @@ void DrawMol::finishCreateDrawObjects() {
...
 void DrawMol::initDrawMolecule(const ROMol &mol) {
   drawMol_.reset(new RWMol(mol));
-  if (!isReactionMol_ &&
-      (drawOptions_.prepareMolsBeforeDrawing || !mol.getNumConformers())) {
-    MolDraw2DUtils::prepareMolForDrawing(*drawMol_);
+  if (!isReactionMol_) {
+    if (drawOptions_.prepareMolsBeforeDrawing) {
+      MolDraw2DUtils::prepareMolForDrawing(*drawMol_);
+    } else if (!mol.getNumConformers()) {
+      const bool canonOrient = true;
```
Comment (bp-kelley) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:149]: I'm a little bit unclear of the difference here, but if there are no conformers, wouldn't you still want to call prepareMolForDrawing?  I'm not seeing the use case for just making coords without calling prepare.

Comment (greglandrum) [reply Code/GraphMol/MolDraw2D/DrawMol.cpp:149]: We don't want to call `prepareMolForDrawing()` because it does a bunch of stuff other than just adding coordinates: kekulizing, adding chiral Hs, wedging bonds, etc. We shouldn't ignore the caller's request to skip that stuff.

**Review by bp-kelley — APPROVED** [review]
