### PR TITLE
Fix/github6138

### LINKED ISSUE #6138: Round-tripping a reaction through pickle changes the outputs from RunReactants
**Describe the bug**

RDKit's reaction objects can be pickled/unpickled, but in some cases running the unpickled reaction can produce slightly different results than it did before the pickling. Interestingly, in my example it only happens if the reaction was ran at least once _before_ pickling, otherwise there are no issues.

**To Reproduce**
```python
import pickle
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.MolFromSmiles("COc1ccccc1Oc1nc(Nc2cc(C)[nH]n2)cc2ccccc12")
rxn = AllChem.ReactionFromSmarts("([c:1]:[n&H1&+0&D2:3]:[n:2])>>([c:1]:[n&H0&+0&D3:3](:[n:2])-C1-C-C-C-C-O-1)")

def run(r):
  return Chem.MolToSmiles(r.RunReactants((mol,))[0][0])

pickle.dump(rxn, open("tmp.pkl", "wb"))
rxn_reloaded = pickle.load(open("tmp.pkl", "rb"))

print(run(rxn))
print(run(rxn_reloaded))

pickle.dump(rxn, open("tmp_after.pkl", "wb"))
rxn_reloaded_after_use = pickle.load(open("tmp_after.pkl", "rb"))

print(run(rxn_reloaded_after_use))
```

Outputs:
```
COc1ccccc1Oc1nc(Nc2cc(C)n(C3CCCCO3)n2)cc2ccccc12
COc1ccccc1Oc1nc(Nc2cc(C)n(C3CCCCO3)n2)cc2ccccc12
COc1ccccc1Oc1nc(Nc2cc(C)[nH](C3CCCCO3)n2)cc2ccccc12
```

While the original SMILES can be correctly parsed by RDKit, the one obtained with the unpickled reaction can no longer be parsed.

**Expected behavior**

Result after round-tripping through pickle should be the same.

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.4
 - OS: Ubuntu 16.04.6 LTS
 - Python version: 3.9.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixed #6138 

There are a few atom properties that are not pickled properly after ChemReaction::validate has been called.

These are 

 _QueryIsotope
 _QueryFormalCharge

and the like.

This ensures they are pickled if the reaction has been initialized.

### CODE REVIEW

File: Code/GraphMol/ChemReactions/ReactionPickler.cpp [hunk 1]
```diff
@@ -146,15 +146,18 @@ void ReactionPickler::_pickle(const ChemicalReaction *rxn, std::ostream &ss,
   streamWrite(ss, BEGINREACTANTS);
   for (auto tmpl = rxn->beginReactantTemplates();
        tmpl != rxn->endReactantTemplates(); ++tmpl) {
-    MolPickler::pickleMol(tmpl->get(), ss);
+    auto props = rxn->df_needsInit ? PicklerOps::PropertyPickleOptions::NoProps :
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/ReactionPickler.cpp:149]: I'd suggest pulling the definition of `props` out of the for loop here so that you don't have to repeat yourself later on line 158. Unless you can think of a scenario where you would want to use different properties for the reactants and products.

File: Code/GraphMol/ChemReactions/ReactionPickler.cpp [hunk 2]
```diff
@@ -146,15 +146,18 @@ void ReactionPickler::_pickle(const ChemicalReaction *rxn, std::ostream &ss,
...
   streamWrite(ss, ENDREACTANTS);
 
   streamWrite(ss, BEGINPRODUCTS);
   for (auto tmpl = rxn->beginProductTemplates();
        tmpl != rxn->endProductTemplates(); ++tmpl) {
-    MolPickler::pickleMol(tmpl->get(), ss,
-                          PicklerOps::PropertyPickleOptions::AtomProps);
+    auto props = rxn->df_needsInit ? PicklerOps::PropertyPickleOptions::AtomProps :
+      PicklerOps::PropertyPickleOptions::AllProps;
+    MolPickler::pickleMol(tmpl->get(), ss, props);
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/ReactionPickler.cpp:160]: Seems like we should also be doing the same thing for agents; if if that's not currently relevant.

**Review by greglandrum — CHANGES_REQUESTED** [review]
A couple of small suggestions.

File: Code/GraphMol/ChemReactions/ReactionPickler.cpp (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/ChemReactions/ReactionPickler.cpp:149]: the are different, the products default to AtomProps  and the reactants default to no props.  After initialization we need to pickle private props as well.

This was really done in the hopes that I didn't have to change every regression test that makes a reaction pickle.  I also think that the act of pickling changes the molecule which is a bigger issue that I didn't want to deal with now.

File: Code/GraphMol/ChemReactions/ReactionPickler.cpp (hunk 2 above)
Comment (bp-kelley) [reply Code/GraphMol/ChemReactions/ReactionPickler.cpp:160]: We could just save Atom props there I think, I don't think they have any private props.

File: Code/GraphMol/ChemReactions/ReactionPickler.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/ChemReactions/ReactionPickler.cpp:149]: > they are different, the products default to AtomProps and the reactants default to no props. After initialization we need to pickle private props as well.

Ah right, missed that... sorry. This looks fine then

File: Code/GraphMol/ChemReactions/ReactionPickler.cpp (hunk 2 above)
Comment (greglandrum) [reply Code/GraphMol/ChemReactions/ReactionPickler.cpp:160]: > We could just save Atom props there I think, I don't think they have any private props.

Just to make sure I'm understanding: you're planning on making this change here, right?

**Comment by bp-kelley** [comment]
Should be ready after the checks pass.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
> Should be ready after the checks pass.

Thanks!
