### PR TITLE
Fixes #8420

### LINKED ISSUE #8420: PR #8366 triggers range errors on imines with new stereo perception
A minimal example:

```
molblock = """
  MJ250100                      

  7  7  0  0  1  0  0  0  0  0999 V2000
    0.6961    0.4995    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0196    1.7395    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7332    0.4968    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.4118    0.9090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4118    1.7395    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6961    2.1583    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0196    0.9101    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  3  7  2  3  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
  2  6  1  0  0  0  0
  2  7  1  0  0  0  0
  1  4  1  0  0  0  0
  1  7  1  0  0  0  0
M  END

"""

from rdkit import Chem

# not sanitizing to prevent stereo assignment on parsing
m = Chem.MolFromMolBlock(molblock, sanitize=False)
m = Chem.RemoveHs(m)

# fails only with new stereo perception
Chem.SetUseLegacyStereoPerception(False)

# fails!
Chem.AssignStereochemistry(m)
[15:26:34] 

****
Range Error
idx2
Violation occurred on line 352 in file /Users/rodrigue/Documents/code/rdkit_builder/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: 4294967295 < 7
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 33
     30 Chem.SetUseLegacyStereoPerception(False)
     32 # fails!
---> 33 Chem.AssignStereochemistry(m)

RuntimeError: Range Error
	idx2
	Violation occurred on line 352 in file Code/GraphMol/ROMol.cpp
	Failed Expression: 4294967295 < 7
	RDKIT: 2024.09.6
	BOOST: 

```

I think this is happening because we use `Chirality::StereoInfo::NOATOM` in `StereoInfo` to signal non existing or implicit stereoatoms.

The error goes away when PR #8366 is reverted.

### PR DESCRIPTION
**Pull request by greglandrum**
The fix here applies to both legacy and non-legacy stereo and tests both.

### CODE REVIEW

File: Code/GraphMol/Chirality.cpp [hunk 1]
```diff
@@ -2494,8 +2509,18 @@ void updateDoubleBondStereo(ROMol &mol, const std::vector<StereoInfo> &sinfo,
...
-        bond->setStereoAtoms(si.controllingAtoms[0], si.controllingAtoms[2]);
+        // in cases like imines without explicit Hs, we have double bonds with
+        // Unknown stereo but with only one neighbor on the N. Catch those and
+        // clear the stereochem
+        if (si.controllingAtoms.size() == 4 &&
+            si.controllingAtoms[0] != StereoInfo::NOATOM &&
+            si.controllingAtoms[2] != StereoInfo::NOATOM) {
+          bond->setStereoAtoms(si.controllingAtoms[0], si.controllingAtoms[2]);
+          bond->setStereo(Bond::BondStereo::STEREOANY);
+          bond->setStereoAtoms(si.controllingAtoms[0], si.controllingAtoms[2]);
```
Comment (ricrogz) [inline Code/GraphMol/Chirality.cpp:2520]: I don't think we need to do this twice :)
```suggestion
```

**Review by ricrogz — APPROVED** [review]
I found a duplicate like, LGTM otherwise
