### PR TITLE
Fixes #2614

### LINKED ISSUE #2614: Pattern fingerprint failing substructure condition in very large molecules
**Description:**

example run with 2019.03.4:
```
n [2]: q = Chem.MolFromSmiles('c1ccc2ccccc2c1')                                                                                   

In [3]: m = Chem.MolFromSmiles('F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-
   ...: ](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.c1ccc2ccccc2c1')                                   

In [4]: fpq = Chem.PatternFingerprint(q)                                                                                           

In [5]: fpm = Chem.PatternFingerprint(m)                                                                                           

In [6]: qbits = set(fpq.GetOnBits())                                                                                               

In [7]: mbits = set(fpm.GetOnBits())                                                                                               

In [8]: qbits.issubset(mbits)                                                                                                      
Out[8]: False

In [9]: m.HasSubstructMatch(q)                                                                                                     
Out[9]: True
```
Note that removing one of those PF6 groups clears things up:
```
In [10]: m = Chem.MolFromSmiles('F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P
    ...: -](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.F[P-](F)(F)(F)(F)F.c1ccc2ccccc2c1')                                                    

In [13]: fpm = Chem.PatternFingerprint(m)                                                                                          

In [14]: mbits = set(fpm.GetOnBits())                                                                                              

In [15]: qbits.issubset(mbits)                                                                                                     
Out[15]: True
```

### PR DESCRIPTION
**Pull request by greglandrum**
The problem was caused by the very large number of matches for some of the patterns in these big molecules.

The solution is brute force and can be out maneuvered by running a really huge molecule through the pattern fingerprinter, but there's not really a solution to that with the current implementation.

### CODE REVIEW

File: Code/GraphMol/Fingerprints/PatternFingerprints.cpp [hunk 1]
```diff
@@ -194,40 +194,40 @@ ExplicitBitVect *PatternFingerprintMol(const ROMol &mol, unsigned int fpSize,
...
     // uniquify matches?
     //   time for 10K molecules w/ uniquify: 5.24s
     //   time for 10K molecules w/o uniquify: 4.87s
-    SubstructMatch(mol, *patt, matches, false);
+
+    SubstructMatchParameters params;
+    params.uniquify = false;
+    // raise maxMatches really high. This was the cause for github #2614.
+    // if we end up with more matches than this, we're completely hosed: :-)
+    params.maxMatches = 100000000;
```
Comment (bp-kelley) [inline Code/GraphMol/Fingerprints/PatternFingerprints.cpp]: That's a big number :)

Comment (bp-kelley) [reply Code/GraphMol/Fingerprints/PatternFingerprints.cpp]: Until we have a SubstructMatch within these atoms and bonds, I'm ok with this.
