### PR TITLE
Fixes #4700: changes default tautomer enumeration rules

### LINKED ISSUE #4700: Wrong tautomers generated
Hi,

I would like to obtain the canonical tautomer of a set of molecules preserving stereochemistry, here is my code:

```
tautomer_params = Chem.MolStandardize.rdMolStandardize.CleanupParameters()
tautomer_params.tautomerRemoveSp3Stereo = False
tautomer_params.tautomerRemoveBondStereo = False
tautomer_params.tautomerRemoveIsotopicHs = False

enumerator = rdMolStandardize.TautomerEnumerator(tautomer_params)
mol_can = standardizer.remove_hs_from_mol(Chem.MolFromSmiles(mol))
mol_can = enumerator.Canonicalize(mol_can)
```

In some instances, the obtained canonical tautomers look odd to me, as the changes in the canonical tautomer are in atoms/bonds that in my opinion should not be involved in tautomerisation. Se for instance the double bond move in `[H]C@]12SCC(CSC3=NN=NN3CCN(C)C)=C(N1C(=O)[C@H]2NC(=O)CC1=CSC(N)=N1)C(O)=O`
image
 and the phosphate groups in  `CC1=CN([C@@H]2O[C@H](COP(O)(=O)OP(O)(=O)OP(O)(O)=O)C=C2)C(=O)NC1=O`
image

Thanks for your help!

**Configuration**
RDKit version: 2021.03.5
OS: Windows 10
Python version: 3.9.7
Are you using conda? Yes
If you are using conda, which channel did you install the rdkit from? conda-forge

### PR DESCRIPTION
**Pull request by greglandrum**
The rules the tautomer enumeration code was using are derived from the ones in https://doi.org/10.1007/s10822-010-9346-4 but didn't use some of the cactvs SMARTS extensions that the rules in the paper use. Since the RDKit now supports most of those extensions (the one which is unsupported is `e`, but that only shows up in one rule), this updates the definitions.

For people who want to continue to use the old definitions: I added a new parameter object with those. This is easily accessible from C++ and Python.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I think the build error in the windows dll is real and related to missing the export for

```
using TautomerTransformDefs =
     std::vector<std::tuple<std::string, std::string, std::string, std::string>>;
```

Which doesn't make a lot of sense to me right now.

File: Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h [hunk 1]
```diff
@@ -24,6 +24,13 @@ class ROMol;
 namespace MolStandardize {
 class TautomerTransform;
 
+using TautomerTransformDefs =
```
Comment (bp-kelley) [inline Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h:27]: perhaps also #include <tuple> ?

Comment (greglandrum) [reply Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h:27]: is this a suggestion to fix the win dll builds? That was because I forgot the magic extern thing for windows.
should be fixed now

Comment (bp-kelley) [reply Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h:27]: Yep.

**Review by bp-kelley — APPROVED** [review]

File: Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h:27]: It didn't make sense to me because I didn't expect you had to export an alias, but that wasn't the issue.

**Review by bp-kelley — APPROVED** [review]

**Review by ptosco — APPROVED** [review]
LGTM. As you have also done some cleanup work on top of the new rules (like the `TautomerTransformDefs` alias), I have the impression that in `Tautomer.h`, line 401 we may turn
```
std::shared_ptr<TautomerCatalog> dp_catalog;
```
into
```
std::unique_ptr<TautomerCatalog> dp_catalog;
```
as there does not seem to be a reason why it should be a `shared_ptr`. Quite unimportant, I do realize.

**Comment by greglandrum** [comment]
> LGTM. As you have also done some cleanup work on top of the new rules (like the `TautomerTransformDefs` alias), I have the impression that in `Tautomer.h`, line 401 we may turn
> 
> ```
> std::shared_ptr<TautomerCatalog> dp_catalog;
> ```
> 
> into
> 
> ```
> std::unique_ptr<TautomerCatalog> dp_catalog;
> ```
> 
> as there does not seem to be a reason why it should be a `shared_ptr`. Quite unimportant, I do realize.

The problem with that change is that then we can't copy the dp_catalog in the copy constructor from TautomerEnumerator.

Thinking about that caused me to go back and realize that the current copy ctor from TautomerEnumerator is actually wrong in the way `dp_callback` is copied:
```
TautomerEnumerator(const TautomerEnumerator &other)
      : dp_catalog(other.dp_catalog),
        d_callback(other.d_callback.get()),
       ... snip ... {}
```

It's a really bad idea to assign the pointer from one unique_ptr to another unique_ptr since it'll likely lead to the use of memory which has already been freed and will certainly cause the same pointer to be freed twice.

`dp_callback` either needs to also be a `shared_ptr`, or we disable the copy ctor entirely (which doesn't seem sensible), or we need to ensure that callbacks are copyable.

I'll create a separate issue for this and do a fix.

**Comment by ptosco** [comment]
@greglandrum You are right - I hadn't thought of the copy constructors. Indeed they both need to be `shared_ptr` and the copy constructor change from
```
d_callback(other.d_callback.get()),
```
to
```
d_callback(other.d_callback),
```
Thanks for spotting that!

**Comment by ptosco** [comment]
@greglandrum I will take care of the `shared_ptr` fix and also put in a test for the copy constructor.

**Comment by greglandrum** [comment]
> @greglandrum I will take care of the `shared_ptr` fix and also put in a test for the copy constructor.

Great, thanks!
