### PR TITLE
Draw type of SGroups (STY) in picture.

### LINKED ISSUE #5767: Missing monomer labels when depicting `MON` SGroups
**Describe the bug**
`mon` labels are missing when depicting molfiles with monomer SGroups (`M  STY` `MON`)

**To Reproduce**
```python
from rdkit import Chem
molfile = """
  Marvin  06091012252D          

 13 11  0  0  0  0            999 V2000
   -3.5063    2.1509    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7918    2.5634    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0773    2.1509    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3628    2.5634    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6484    2.1509    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0661    2.5634    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7806    2.1509    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9984   -0.4714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2839   -0.0589    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5695   -0.4714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8550   -0.0589    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -2.9984    0.3536    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.6777   -0.1775    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
  8  9  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  1  0  0  0  0
  9 12  1  0  0  0  0
 12  8  1  0  0  0  0
M  STY  2   1 MON   2 MON
M  SAL   1  7   1   2   3   4   5   6   7
M  SDI   1  4   -3.9263    1.7309   -3.9263    2.9834
M  SDI   1  4    1.2006    2.9834    1.2006    1.7309
M  SAL   2  5   8   9  10  11  12
M  SDI   2  4   -3.4184   -0.8914   -3.4184    0.7736
M  SDI   2  4   -0.4350    0.7736   -0.4350   -0.8914
M  END
"""
mol = Chem.MolFromMolBlock(molfile)
mol
```

Screenshot 2022-11-15 at 20 47 36

**Expected behavior**
`mon` labels to show next to the brackets, like in the following example (depicted with CDK) 

Screenshot 2022-11-15 at 20 49 21

**Configuration (please complete the following information):**

RDKit version: 2022.09.01
OS: [e.g. Ubuntu 20.04] MacOS
Python version (if relevant): 3.10
Are you using conda? No
If you are not using conda: how did you install the RDKit? pip install rdkit

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
Fixes #5767

#### What does this implement/fix? Explain your changes.
This draws the contents of the STY type label for the bracket on an Group.

#### Any other comments?
It certainly fixes the issue filed (missing 'mon' label) but it may be too enthusiastic about what other STY types it puts on the drawing.  I don't know enough about CTFiles to know what should and what shouldn't be drawn.  It doesn't draw GEN/gen types because ChemDraw doesn't.

### CODE REVIEW

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 1]
```diff
@@ -668,10 +669,11 @@ void DrawMol::extractBrackets() {
         }
         annotations_.emplace_back(da);
       }
-      std::string label;
-      if (sg.getPropIfPresent("LABEL", label)) {
+      // function to draw a label at the bottom of the bracket.
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:672]: That's a lot of code for a lambda. Could this be a function in an anonymous namespace instead?

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 2]
```diff
@@ -684,6 +686,24 @@ void DrawMol::extractBrackets() {
...
+      std::string label;
+      if (sg.getPropIfPresent("LABEL", label)) {
+        auto da = drawBottomLabel(label, *postShapes_[labelBrk], horizontal);
+        annotations_.emplace_back(da);
+      } else if (sg.getPropIfPresent("TYPE", label)) {
+        if (label == "GEN") {
+          // ChemDraw doesn't draw the GEN (type=generic) label.
+          continue;
+        }
+        // draw the lowercase type if there's no label to go there.
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:704]: why lowercase?
I'm not suggesting that it's wrong, just want to understand the decision

**Review by greglandrum — APPROVED** [review]
@DavidACosgrove there's a small suggestion and a question. I'm happy to merge as-is if you think it's fine this way.

File: Code/GraphMol/MolDraw2D/DrawMol.cpp (hunk 2 above)
Comment (DavidACosgrove) [reply Code/GraphMol/MolDraw2D/DrawMol.cpp:704]: The OP had it lowercase, as does ChemDraw, and the examples in the CTFile documentation do also. I didn’t see anywhere that explicitly said it should be lowercase, but I just inferred it from this evidence.

File: Code/GraphMol/MolDraw2D/DrawMol.cpp (hunk 1 above)
Comment (DavidACosgrove) [reply Code/GraphMol/MolDraw2D/DrawMol.cpp:672]: It seemed like it was only relevant for this function, so I thought I’d make it a lambda so as not to bloat the number of functions in the global namespace. But you’re right, it is a fair few lines of code.  I can move it out into the main body if you think it would be tidier. I guess that it does make the enclosing function break the rule of thumb that functions should be fully visible in the screen in one go, except that I have a large screen and a small font so it does for me 😀.

File: Code/GraphMol/MolDraw2D/DrawMol.cpp (hunk 2 above)
Comment (greglandrum) [reply Code/GraphMol/MolDraw2D/DrawMol.cpp:704]: ok

File: Code/GraphMol/MolDraw2D/DrawMol.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/MolDraw2D/DrawMol.cpp:672]: you can define in an an anonymous namespace just above this function... no crowding!
And you already have a name for it. :-)

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @DavidACosgrove !
