### PR TITLE
Fixes #5677

### LINKED ISSUE #5677: fp.ToList() fails for empty molecule
RDKit: 2021.09.5

```
from rdkit import Chem
from rdkit.Chem import AllChem
smi = ""
mol = Chem.MolFromSmiles(smi)
assert mol.GetNumAtoms() == 0
fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024)
print(fp.ToList())
```

I would expect this to produce a list of 1024 zeroes. Instead I get:

`IndexError: cannot fit 'int' into an index-sized integer`

### PR DESCRIPTION
**Pull request by bp-kelley**
Check that we actually have a bit to set when converting an ExplicitBitVect to a List

### CODE REVIEW

File: Code/DataStructs/Wrap/wrap_ExplicitBV.cpp [hunk 1]
```diff
@@ -35,10 +35,12 @@ python::list ExplicitToList(const ExplicitBitVect &sv) {
...
-    l[pos] = 1;
-    while ((pos = sv.dp_bits->find_next(pos)) !=
-           boost::dynamic_bitset<>::npos) {
+    if (pos != boost::dynamic_bitset<>::npos) {
       l[pos] = 1;
+      while ((pos = sv.dp_bits->find_next(pos)) !=
+	     boost::dynamic_bitset<>::npos) {
+	l[pos] = 1;
+      }
     }
```
Comment (greglandrum) [inline Code/DataStructs/Wrap/wrap_ExplicitBV.cpp:44]: This can be simplified to:
```
    auto pos = sv.dp_bits->find_first();
    while (pos != boost::dynamic_bitset<>::npos) {
      l[pos] = 1;
      pos = sv.dp_bits->find_next(pos);
    }
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
Simplification suggested

**Review by greglandrum — APPROVED** [review]
LGTM
