### PR TITLE
Fix an out of bounds access when replacing fragments

### LINKED ISSUE #8761: segmentation fault when parsing USPTO downloaded CDX file
I was playing a bit with RDKit's CDX parsing functionality. Only tested with USPTO applications and grants from 2025. For the moment only a single CDX file from last week's download seems to be giving serious trouble.

**Describe the bug**
Python crashes when parsing a bad boy from USPTO downloads

**To Reproduce**
```python
from rdkit import Chem

mols = Chem.MolsFromCDXMLFile("US12404367-20250902-C00017.CDX")
```

**Configuration (please complete the following information):**
 - RDKit version: 2025.3.6
 - OS: OSX
 - Python version (if relevant): 3.13
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? pip install rdkit

**Additional context**
attached the offender CDX file

[US12404367-20250902-C00017.CDX.zip](https://github.com/user-attachments/files/22257884/US12404367-20250902-C00017.CDX.zip)

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #8761 

This prevents an out of bounds exception when dealing with certain semi-chemical CDX files.

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley the CI failures here look real

**Comment by bp-kelley** [comment]
Yep, looks like a fun one too.  I won't be able to track this one down until Sunday.

**Comment by bp-kelley** [comment]
@greglandrum turns out opening in binary mode was a good idea.  I've added the remaining patents from the crashing test set as well.

**Comment by bp-kelley** [comment]
@greglandrum this is ready now

File: External/ChemDraw/chemdraw.cpp [hunk 1]
```diff
@@ -292,8 +292,15 @@ std::unique_ptr<CDXDocument> streamToCDXDocument(std::istream &inStream,
...
     CDXistream input(inStream);
     const bool doThrow = true;
-    std::unique_ptr<CDXDocument> doc(CDXReadDocFromStorage(input, doThrow));
-    return doc;
+    // if we aren't opened in binary mode on windows, we are going to have a bad time...
+    try {
+      std::unique_ptr<CDXDocument> doc(CDXReadDocFromStorage(input, doThrow));
+      return doc;
+    } catch (const std::exception &ex) {
+      throw FileParseException(
```
Comment (greglandrum) [inline External/ChemDraw/chemdraw.cpp:300]: ouch. Got to hate stuff like this

**Review by greglandrum — APPROVED** [review]
LGTM
