### PR TITLE
Fixes #2144

### LINKED ISSUE #2144: Error thrown in rdMolStandardize.ChargeParent
**Description:**

- RDKit Version: '2018.09.1'
- Platform: MacOS High Sierra

rdMolStandardize.ChargeParent gives error with no helpful info. This is reproducible if you feed the output of one call to ChargeParent back into the same function.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: unidentifiable C++ exception

```
molx = Chem.MolFromSmiles("c1ccccn1")
moly = rdMolStandardize.ChargeParent(molx)
molz = rdMolStandardize.ChargeParent(moly)
```

### PR DESCRIPTION
**Pull request by greglandrum**
There was no `RWMol(const RWMol &)` ctor. This adds one and a couple of tests

### CODE REVIEW

File: Code/GraphMol/RWMol.h [hunk 1]
```diff
@@ -46,6 +46,7 @@ class RDKIT_GRAPHMOL_EXPORT RWMol : public ROMol {
       : ROMol(other, quickCopy, confId) {
     d_partialBonds.clear();
   };
+  RWMol(const RWMol &other) : ROMol(other){};
```
Comment (bp-kelley) [inline Code/GraphMol/RWMol.h]: Not that I understand it, but all the other ctors have d_partialBonds.clear().

Comment (bp-kelley) [reply Code/GraphMol/RWMol.h]: I'm assuming that this (d_partialBonds.clear()) isn't necessary in the "default" constructor.

Comment (greglandrum) [reply Code/GraphMol/RWMol.h]: I believe that you're guaranteed that the unitialized container is empty.
