### PR TITLE
Rascal bond label error

### LINKED ISSUE #8198: Rascal MCES missing an atom when ignoreAtomAromaticity is True
**Describe the bug**
Sometimes, when ignoreAtomAromaticity is True, a bond is missed in the MCES.

**To Reproduce**
```
mol1 = Chem.MolFromSmiles("c3ccccc3C")
mol2 = Chem.MolFromSmiles("c3ccccc3C4CC4")
opts = rdRascalMCES.RascalOptions()
opts.ignoreAtomAromaticity = False
opts.similarityThreshold = 0.1
matches = rdRascalMCES.FindMCES(mol1, mol2, opts)
IPythonConsole.drawOptions.addBondIndices = True
if matches:
    am1 = [a[0] for a in matches[0].atomMatches()]
    am2 = [a[1] for a in matches[0].atomMatches()]
    img = Draw.MolsToGridImage([mol1, mol2], subImgSize=(400,400), highlightAtomLists=[am1, am2])
else:
    img = "No matches"
img
```

gives

Image

**Expected behavior**
The first aliphatic carbon should be in the MCES also.

Image

**Configuration (please complete the following information):**
 - RDKit version: 2024.09.4 and confirmed on current master
 - OS: [e.g. Ubuntu 20.04] macOS
 - Python version (if relevant):
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? ronda-forge
 - If you are not using conda: how did you install the RDKit? Also built from source

**Additional context**
This was spotted by Lauren Reid at MedChemica.

Fix incoming.

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
Fixes #8198 

#### What does this implement/fix? Explain your changes.
The order of the atoms in the bond label being set by properties of the atoms, whereas the key issue is that the final label is always consistent so it makes more sense to use the atom labels and put them in alphanumeric order.

### CODE REVIEW

File: Code/GraphMol/RascalMCES/RascalMCES.cpp [hunk 1]
```diff
@@ -265,22 +265,14 @@ void getBondLabels(const ROMol &mol, const RascalOptions &opts,
...
     }
-    if (b->getBeginAtom()->getAtomicNum() == b->getEndAtom()->getAtomicNum()) {
-      if (b->getEndAtom()->getDegree() < b->getBeginAtom()->getDegree()) {
-        bondLabels[b->getIdx()] = atomLabels[b->getEndAtomIdx()] + bondType +
-                                  atomLabels[b->getBeginAtomIdx()];
-      } else {
-        bondLabels[b->getIdx()] = atomLabels[b->getBeginAtomIdx()] + bondType +
-                                  atomLabels[b->getEndAtomIdx()];
-      }
+    // The atom labels need to be in consistent order irrespective
```
Comment (greglandrum) [inline Code/GraphMol/RascalMCES/RascalMCES.cpp:268]: Seems like this would be clearer as:
```
    auto lbl1 = atomLabels[b->getBeginAtomIdx()];
    auto lbl2 = atomLabels[b->getEndAtomIdx()];
    if(lbl1 < lbl2) {
      std::swap(lbl1, lbl2);
    }
    bondLabels[b->getIdx()] = lbl1 + bondType + lbl2;
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
One suggested change that I don't feel strongly about.
If you disagree with it, let me know and we can push this as is.

File: Code/GraphMol/RascalMCES/RascalMCES.cpp (hunk 1 above)
Comment (DavidACosgrove) [reply Code/GraphMol/RascalMCES/RascalMCES.cpp:268]: I assume the swap is very cheap.  In which case the intent is clearer, so yes.  And I guess when the next stage is exponential in N, the set-up time is largely immaterial.

**Comment by DavidACosgrove** [comment]
@greglandrum I've made the change, even though GitHub doesn't seem to think so.
