### PR TITLE
Throw error when V2000 coords are out of range

### LINKED ISSUE #8265: MolBlocks should fail to write when given coordinates that are too large
**Describe the bug**
MolToMolBlock will output numbers that are too large for the format generating mol blocks that cannot be read back in.

**To Reproduce**

Example:

```
mb = Chem.MolFromSmiles("[B]")
c = Chem.Conformer(1)
c.SetAtomPosition(0, (9580052, -52747960, 0))
mb.AddConformer(c)
Chem.MolFromMolBlock(Chem.MolToMolBlock(mb))
```

Results in

```
[10:41:32] Cannot convert ' B ' to int on line 5
```

Generates a mol block that cannot be parsed

**Expected behavior**

There should be an exception when making the mol block similar to the 999 bonds limit.

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #8265 

Simple fix to check for out of range coordinates.

### CODE REVIEW

File: Code/GraphMol/FileParsers/MolFileWriter.cpp [hunk 1]
```diff
@@ -595,6 +595,8 @@ void GetMolFileAtomProperties(const Atom *atom, const Conformer *conf,
   }
 }
 
+const double MAX_V2000_COORD = 1000000.;
+const double MIN_V2000_COORD = -100000.;
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MolFileWriter.cpp:599]:
```suggestion
constexpr double MAX_V2000_COORD = 1000000.;
constexpr double MIN_V2000_COORD = -100000.;
```

Comment (greglandrum) [reply Code/GraphMol/FileParsers/MolFileWriter.cpp:599]: I also wonder if these values are correct.
The CTAB spec says that the format is:
`xxxxx.xxxx`
I think that means that the ranges are:
```
constexpr double MAX_V2000_COORD = 100000.;
constexpr double MIN_V2000_COORD = -10000.;
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
I think the values are off by a factor of ten, see the comment.

Also: maybe it would make sense to add a check around line 1303 (original line numbering) where we have the logic to automatically switch to v3000 when no format is specified?
```
  if (whichFormat == MolFileFormat::V3000) {
    isV3000 = true;
  } else if (whichFormat == MolFileFormat::unspecified &&
             (hasDative || nAtoms > 999 || nBonds > 999 || nSGroups > 999 ||
              !tmol.getStereoGroups().empty() || coordinates_are_too_big(conf))) {
    isV3000 = true;
  }
```

File: Code/GraphMol/FileParsers/MolFileWriter.cpp (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MolFileWriter.cpp:599]: These are the first bad values, everything below or above these should work.  I.e. 99999.9999

Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MolFileWriter.cpp:599]: MAX coord is a bit misleading I agree

Comment (greglandrum) [reply Code/GraphMol/FileParsers/MolFileWriter.cpp]: > These are the first bad values, everything below or above these should work.  I.e. 99999.9999

I don't believe that this is true. I think you have an extra digit

Comment (greglandrum) [reply Code/GraphMol/FileParsers/MolFileWriter.cpp]: > > These are the first bad values, everything below or above these should work.  I.e. 99999.9999
> 
> I don't believe that this is true. I think you have an extra digit 

You only get 5 digits before the decimal point

**Comment by bp-kelley** [comment]
I had trouble with the format as well, so I just found the first failures on either end using the below code:

```
from rdkit import Chem
c = Chem.Conformer(1)

MIN = None
MAX = None

# find MIN
x = -99999.0
one_worked = False # make sure at least one parses
while 1:
    mb = Chem.MolFromSmiles("[B]")
    c.SetAtomPosition(0, (x, 0, 0))
    mb.AddConformer(c)
    molblock = Chem.MolToMolBlock(mb)
    m = Chem.MolFromMolBlock(molblock)
    if not m:
        MIN = x
        break
    else:
        one_worked = True
    x-=1
assert one_worked
x = 1000000.0 - 1

one_worked = False
while 1:
    mb = Chem.MolFromSmiles("[B]")
    c.SetAtomPosition(0, (x, 0, 0))
    mb.AddConformer(c)
    molblock = Chem.MolToMolBlock(mb)
    m = Chem.MolFromMolBlock(molblock)
    if not m:
        MAX = x
        break
    else:
        one_worked = True
    x+=1
assert one_worked

print(f"const double MAX_V2000_COORD = {MAX};")
print(f"const double MIN_V2000_COORD = {MIN};")
```

Results

```
const double MAX_V2000_COORD = 1000000.0;
const double MIN_V2000_COORD = -100000.0;

```

**Comment by bp-kelley** [comment]
So, at least for the RDKit I think the numbers are correct.

**Comment by greglandrum** [comment]
> So, at least for the RDKit I think the numbers are correct.

Now I understand what the disconnect is: you are just looking at what the RDKit will parse, while I'm looking at what the format spec says. 
In this case the RDKit is being overly permissive and parsing things that are technically wrong. I think it's ok to do that, but we should not write those values.

Look at what happens in the output mol block.
Here's a mol block with correct values:
```
In [26]: m = Chem.MolFromSmiles('C')

In [27]: print(Chem.MolToMolBlock(m))

     RDKit          2D

  1  0  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
M  END
```
notice that the `.` from the x coordinate is under the second `0` of the counts line.

And for your suggested max value:
```
In [28]: x = 1000000.0 - 1

In [29]: conf = Chem.Conformer(1)

In [30]: conf.SetAtomPosition(0,(x,0,0))

In [31]: m.AddConformer(conf)
Out[31]: 0

In [32]: print(Chem.MolToMolBlock(m))

     RDKit          3D

  1  0  0  0  0  0  0  0  0  0999 V2000
999999.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
M  END
```
now the decimal point for the x coordinate (and all the other coordinates) is shifted one to the right.

This is definitely not compatible with the CTAB spec, so I think the max val needs to have one fewer digit:
```
In [33]: x2 = 100000.0 - 1

In [34]: conf = Chem.Conformer(1)

In [35]: conf.SetAtomPosition(0,(x2,0,0))

In [36]: m.RemoveAllConformers()

In [37]: m.AddConformer(conf)
Out[37]: 0

In [38]: print(Chem.MolToMolBlock(m))

     RDKit          3D

  1  0  0  0  0  0  0  0  0  0999 V2000
99999.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
M  END
```

**Comment by bp-kelley** [comment]
That makes a lot of sense and is why I ended up writing that test.  I’ll make the change.

**Review by greglandrum — APPROVED** [review]
LGTM
