### PR TITLE
Fixes #3019

### LINKED ISSUE #3019: SegmentationFault on EmbedMolecule
EmbedMolecule crashes with segmentation fault on large molecules.

```
# rdkit version 2019.09.3
from rdkit import Chem
from rdkit.Chem import AllChem
smiles = 'C'*900
mol = Chem.MolFromSmiles(smiles)
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol)
```

### PR DESCRIPTION
**Pull request by greglandrum**
Use an unsigned long for the index into cisPaths and transPaths

### CODE REVIEW

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 1]
```diff
@@ -72,8 +72,10 @@ class ComputedData {
     bondAdj.reset(bAdj);
     auto *bAngles = new RDNumeric::DoubleSymmMatrix(nBonds, -1.0);
     bondAngles.reset(bAngles);
-    cisPaths.resize(nBonds * nBonds * nBonds);
-    transPaths.resize(nBonds * nBonds * nBonds);
+    unsigned long capacity =
+        static_cast<unsigned long>(nBonds) * nBonds * nBonds;
+    cisPaths.resize(capacity);
```
Comment (bp-kelley) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: The final target for resize is (BITSET::size_type), 

```
BITSET::resize(size_type)
```

perhaps we could use this over unsigned long here.  Otherwise if you wanted to add a check you could do:

```
BITSET::size_type capacity = boost::numeric_cast<BITSET::size_type>( 
    static_cast<unsigned long>(nBonds) * nBonds * nBonds );
```

I don't think this really matters though as we'll run out of memory long before the value overflows.

Comment (greglandrum) [reply Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: Using that form totally makes sense. It should theoretically also catch problems if the code is somehow run on a system where BITSET::size_type is too small.
