### PR TITLE
Fixes #7873

### LINKED ISSUE #7873: Setting an atom's pdb residue number with None segfaults
**Describe the bug**
Setting a PDB residue to None seg faults

**To Reproduce**
```
Chem.MolFromSmiles("C").GetAtomWithIdx(0).SetPDBResidueInfo(None)
```

**Configuration (please complete the following information):**
 - RDKit version: master (2024.9+)
 - OS: OSX

### PR DESCRIPTION
**Pull request by bp-kelley**
This fixes two issues, one when calling setMonomorInfo with a nullptr would leak an existing residue, second, the python API would try to dereference a nullptr causing a segmentation fault.

Both are resolved.

### CODE REVIEW

File: Code/GraphMol/Wrap/Atom.cpp [hunk 1]
```diff
@@ -104,14 +104,24 @@ std::string AtomGetSmarts(const Atom *atom, bool doKekule, bool allHsExplicit,
 }
 
 void SetAtomMonomerInfo(Atom *atom, const AtomMonomerInfo *info) {
-  atom->setMonomerInfo(info->copy());
+  if(!info) {
+    atom->setMonomerInfo(nullptr);
+  } else {
+    atom->setMonomerInfo(info->copy());
+  }
 }
```
Comment (greglandrum) [inline Code/GraphMol/Wrap/Atom.cpp:112]: @ptosco would do this with a ternary operator, but I think it's fine like this.
;-)

**Review by greglandrum — CHANGES_REQUESTED** [review]
The changes look good, but I think that there should be a C++ test in addition to the python testing.

File: Code/GraphMol/Wrap/Atom.cpp (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/Wrap/Atom.cpp:112]: Since the crash was caused by the python wrapper I’m not sure what a c++ check would accomplish.

the c++ change is a mem leak fix which is also hard to test.

Comment (bp-kelley) [reply Code/GraphMol/Wrap/Atom.cpp:112]: As for the ternary, I was going to throw an exception but then I fixed the memory leak and thought better of it

File: Code/GraphMol/Wrap/Atom.cpp [hunk 2]
```diff
@@ -104,14 +104,24 @@ std::string AtomGetSmarts(const Atom *atom, bool doKekule, bool allHsExplicit,
...
 
 AtomMonomerInfo *AtomGetMonomerInfo(Atom *atom) {
   return atom->getMonomerInfo();
 }
 
 void AtomSetPDBResidueInfo(Atom *atom, const AtomMonomerInfo *info) {
```
Comment (bp-kelley) [inline Code/GraphMol/Wrap/Atom.cpp:118]: This I can add a c++ test for.

Comment (greglandrum) [reply Code/GraphMol/Wrap/Atom.cpp:118]: yeah, that's what I meant

Comment (bp-kelley) [reply Code/GraphMol/Wrap/Atom.cpp:118]: done

**Review by greglandrum — APPROVED** [review]
LGTM

will merge after the CI builds pass
