### PR TITLE
Fixes #6973

### LINKED ISSUE #6973: MaeMolSupplier cannot read dummy atoms from Maestro files
In Maestro files dummy atoms are encoded with atomic number `-2`, and `MaeMolSupplier` currently can't read them:
```python
maeb = """f_m_ct {
 s_m_title
 i_m_ct_stereo_status
 i_m_ct_format
 :::
 COCH3
  1
  2
 m_atom[7] {
  # First column is atom index #
  i_m_mmod_type
  r_m_x_coord
  r_m_y_coord
  r_m_z_coord
  i_m_color
  i_m_atomic_number
  s_m_color_rgb
  s_m_atom_name
  i_m_mass_number
  :::
  1 61 -0.536336 0.931891 -0.000000 10 -2 1EE11E  DU1  1
  2 2 0.000000 0.000000 0.000000 2 6 A0A0A0  C2  <>
  3 3 1.500000 0.000000 0.000000 2 6 A0A0A0  C3  <>
  4 15 -0.623038 -1.078345 -0.000420 70 8 FF2F2F  O4  <>
  5 41 1.863333 -1.027662 -0.000000 21 1 FFFFFF  H5  <>
  6 41 1.863333 0.513831 -0.889981 21 1 FFFFFF  H6  <>
  7 41 1.863333 0.513831 0.889981 21 1 FFFFFF  H7  <>
  :::
 }
 m_bond[6] {
  # First column is bond index #
  i_m_from
  i_m_to
  i_m_order
  :::
  1 1 2 1
  2 2 3 1
  3 2 4 2
  4 3 5 1
  5 3 6 1
  6 3 7 1
  :::
 }
}"""
supplier = Chem.MaeMolSupplier()
supplier.SetData(maeb)
m = next(supplier)
[14:48:59] 

****
Pre-condition Violation
Atomic number not found
Violation occurred on line 159 in file /tmp/rdkit_builder/rdkit/Code/GraphMol/PeriodicTable.h
Failed Expression: atomicNumber < byanum.size()
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 47
     45 supplier = Chem.MaeMolSupplier()
     46 supplier.SetData(maeb)
---> 47 m = next(supplier)

RuntimeError: File parsing error: Atomic number not found
```

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #6973.

The fix is trivial: just check for atomic number `-2`, and translate it to `0`, and do the opposite for `MaeWriter`.

### CODE REVIEW

File: Code/GraphMol/FileParsers/MaeMolSupplier.cpp [hunk 1]
```diff
@@ -312,21 +312,27 @@ void set_atom_properties(Atom &atom, const mae::IndexedBlock &atom_block,
...
   PDBInfo pdb_info(atom_block);
 
   bool nonzeroZ = false;
   for (size_t i = 0; i < size; ++i) {
-    Atom *atom = new Atom(atomic_numbers->at(i));
+    auto atomicNumber = atomicNumbers->at(i);
+    if (atomicNumber == -2) {
+      // Maestro files use atomic number -2 to indicate a dummy atom.
+      atomicNumber = 0;
+    }
```
Comment (cdvonbargen) [inline Code/GraphMol/FileParsers/MaeMolSupplier.cpp:333]: The ancient code in atom.typ says:
```
Lone pairs get atomic number -1, dummy atoms -2. The values -3 and 0 are reserved for use by MacroModel; user attempts to specify these may or may not lead to desired effects, please avoid them.
```
I assume we should at lease throw an exception warning about lack of support for 0/-1/3? Or does it make sense to turn those all into rdkit atomicNumber=0?

Comment (ricrogz) [reply Code/GraphMol/FileParsers/MaeMolSupplier.cpp]: Let's throw a warning and remove the atoms one we have finished parsing the mol (just not adding would cause trouble with parsing the bonds, even more if one of these atoms was bonded).

**Review by cdvonbargen — COMMENTED** [review]
This makes sense to me! Thank you!

**Review by greglandrum — APPROVED** [review]
LGTM
