### PR TITLE
Fixes #3150

### LINKED ISSUE #3150: MolOps::removeHs() removes hydrides
RDKit version 2020.03.1 from condaforge in Google Colab
```
m = Chem.MolFromSmiles('[H-]')
print(Chem.GetFormalCharge(m))
m = Chem.MolFromSmiles('[OH+][H-]')
print(Chem.GetFormalCharge(m))
m = Chem.MolFromSmiles('[Fe+2]<-[H-]')
print(Chem.GetFormalCharge(m))
m = Chem.MolFromSmiles('[Fe+2]<-[OH-]')
print(Chem.GetFormalCharge(m))
````
-1 (correct)
1 (wrong)
2 (wrong)
1 (correct)

### PR DESCRIPTION
**Pull request by manangoel99**
Fixes #3150 
Fixes removeHs removing Hydrides by adding a removeHydrides flag to RemoveHsParameters.
If removeHydrides is false, Hydrogen atoms with formal charge -1 and degree less than or equal to 1 are kept
removeHydrides is kept true by default

### CODE REVIEW

File: Code/GraphMol/MolOps.h [hunk 1]
```diff
@@ -249,6 +249,7 @@ struct RDKIT_GRAPHMOL_EXPORT RemoveHsParameters {
   bool removeNonimplicit = true; /**< DEPRECATED equivalent of implicitOnly */
   bool updateExplicitCount =
       false; /**< DEPRECATED equivalent of updateExplicitCount */
+  bool removeHydrides = true; /**<Removing Hydrides>**/
```
Comment (greglandrum) [inline Code/GraphMol/MolOps.h:252]: please keep the formatting of these comments consistent:
```suggestion
  bool removeHydrides = true; /**< Removing Hydrides */
```

File: Code/GraphMol/catch_graphmol.cpp [hunk 2]
```diff
@@ -1486,3 +1486,61 @@ TEST_CASE("github #2890", "[bug][molops][stereo]") {
...
+
+
+TEST_CASE("github #3150 MolOps::removeHs removes hydrides", "[bug][molops]") {
+  SmilesParserParams smilesPs;
+  smilesPs.removeHs = false;
+  
+  SECTION("Hydride ion") {
+    // auto m = "[H-]"_smiles;
+
+    // CHECK(m->getNumAtoms() == 1);
```
Comment (greglandrum) [inline Code/GraphMol/catch_graphmol.cpp:1498]: Please clean up the extraneous comments in this file

File: Code/GraphMol/catch_graphmol.cpp [hunk 3]
```diff
@@ -1486,3 +1486,61 @@ TEST_CASE("github #2890", "[bug][molops][stereo]") {
     CHECK(bond->getStereo() == Bond::STEREOANY);
     CHECK(bond->getStereoAtoms().size() == 2);
 }
+
+
+TEST_CASE("github #3150 MolOps::removeHs removes hydrides", "[bug][molops]") {
```
Comment (greglandrum) [inline Code/GraphMol/catch_graphmol.cpp:1491]: The tests here are good, but I'd like to also see what happens in each case when `ps.removeHydrides` is `true`.

File: Code/GraphMol/AddHs.cpp [hunk 4]
```diff
@@ -707,6 +707,9 @@ void removeHs(RWMol &mol, const RemoveHsParameters &ps, bool sanitize) {
     if (!ps.removeMapped && atom->getAtomMapNum()) {
       continue;
     }
+    if (!ps.removeHydrides && atom->getAtomicNum() == 1 && atom->getFormalCharge() == -1) {
```
Comment (greglandrum) [inline Code/GraphMol/AddHs.cpp:710]: Ah, missed this one. Sorry:
you don't need to test the atomic number here. that's taken care of above on line 683.

**Comment by greglandrum** [comment]
You should also be sure the `removeAllHs()` removes hydrides. Please also add a test for that too.

I am working in the same code, so I'm noticing these things. :-)

**Comment by greglandrum** [comment]
You'll also need to expose the new parameter to Python in `$RDBASE/Code/GraphMol/Wrap/MolOps.cpp`

File: Code/GraphMol/MolOps.h [hunk 5]
```diff
@@ -249,7 +249,7 @@ struct RDKIT_GRAPHMOL_EXPORT RemoveHsParameters {
   bool removeNonimplicit = true; /**< DEPRECATED equivalent of implicitOnly */
   bool updateExplicitCount =
       false; /**< DEPRECATED equivalent of updateExplicitCount */
-  bool removeHydrides = true; /**<Removing Hydrides>**/
+  bool removeHydrides = true; /**<Removing Hydrides>*/
```
Comment (greglandrum) [inline Code/GraphMol/MolOps.h:252]: this formatting still isn't consistent with the other variables.
```suggestion
  bool removeHydrides = true; /**< Removing Hydrides */
```

File: Code/GraphMol/Wrap/MolOps.cpp [hunk 6]
```diff
@@ -1090,6 +1090,9 @@ struct molops_wrapper {
         .def_readwrite("removeNonimplicit",
                        &MolOps::RemoveHsParameters::removeNonimplicit,
                        "DEPRECATED")
+        .def_readwrite("removeHydrids",
```
Comment (greglandrum) [inline Code/GraphMol/Wrap/MolOps.cpp:1093]: hydrides is mis-spelled
```suggestion
        .def_readwrite("removeHydrides",
```

File: Code/GraphMol/catch_graphmol.cpp [hunk 7]
```diff
@@ -1486,3 +1486,118 @@ TEST_CASE("github #2890", "[bug][molops][stereo]") {
...
+  }
+
+  SECTION("Hydride ion remove Hydrides true") {
+    std::unique_ptr<RWMol> m{SmilesToMol("[H-]", smilesPs)};
+    REQUIRE(m);
+    MolOps::RemoveHsParameters ps;
+    ps.removeHydrides = true;
+    RWMol cp(*m);
+    MolOps::removeHs(cp, ps);
+    CHECK(cp.getNumAtoms() == 1);
```
Comment (greglandrum) [inline Code/GraphMol/catch_graphmol.cpp:1513]: Since this seems like a surprising result (there is a hydride here, but it doesn't get removed), it is worth adding a note explaining why the H wasn't removed

File: Code/GraphMol/catch_graphmol.cpp [hunk 8]
```diff
@@ -1486,3 +1486,118 @@ TEST_CASE("github #2890", "[bug][molops][stereo]") {
...
+    REQUIRE(m);
+    MolOps::RemoveHsParameters ps;
+    ps.removeHydrides = true;
+    RWMol cp(*m);
+    MolOps::removeHs(cp, ps);
+    CHECK(cp.getNumAtoms() == 2);
+    CHECK(MolOps::getFormalCharge(cp) == 1);
+  }
+
+  SECTION("Remove All Hs in Hydrides Ferrous Hydride") {
```
Comment (greglandrum) [inline Code/GraphMol/catch_graphmol.cpp:1583]: It's good that you added these tests, and they look right, but I would suggest, just to be extremely explicit, that you also update the code in `removeAllHs()` to explicitly set `removeHydrides` to true.

It's not *necessary* to do this since the default value is currently true and if that ever changes these tests will catch that something went wrong, but it's always good to anticipate that kind of possible future problem and solve it in advance.

**Comment by manangoel99** [comment]
I apologize, I didn't look at it closely. I'll make sure this doesn't happen again
