### PR TITLE
Fixes #7552

### LINKED ISSUE #7552: AllChem.EmbedMolecule returns -1
Howdy,

I want to get the 3D conformation information for any given molecule; however, some molecules fail to produce the conformer. Following is the code that reproduces the issue.

`from rdkit import Chem`
`from rdkit.Chem import AllChem`
`sample_smiles = 'O=CCC1OC2COC12'`
`mol = Chem.AddHs(Chem.MolFromSmiles(sample_smiles))`
`AllChem.EmbedMolecule(mol) # -1`

If the molecule can generate conformation information, `AllChem.EmbedMolecule()` would return 0; I have identified many smiles/molecules that result in -1 when calling `AllChem.EmbedMolecule(mol)` , you may find some of those smiles in the picture below.

image

Appreciate any suggestions!

### PR DESCRIPTION
**Pull request by greglandrum**
This adds code to recognize tetrahedral centers which are involved in more than one ring with < members and be more tolerant when checking their geometries.

### CODE REVIEW

File: Code/GraphMol/DistGeomHelpers/Embedder.cpp [hunk 1]
```diff
@@ -1035,19 +1044,32 @@ void findChiralSets(const ROMol &mol, DistGeom::VECT_CHIRALSET &chiralCenters,
           nbrs.insert(nbrs.end(), atom->getIdx());
         }
 
+        // set a flag for tetrahedral centers that are in multiple small rings
+        auto numSmallRings = 0u;
+        for (const auto sz : mol.getRingInfo()->atomRingSizes(atom->getIdx())) {
+          if (sz < 5) {
```
Comment (bp-kelley) [inline Code/GraphMol/DistGeomHelpers/Embedder.cpp:1050]: Might make sense to name the 5
```
const auto SMALL_RING_SIZE = 5;
```

**Review by bp-kelley — APPROVED** [review]
LGTM with small suggestions
