### PR TITLE
Fix a couple CDXML issues

### LINKED ISSUE #6461: Molecules from CDXML Parser have inverted, unrealistic atomic coordinates
First the illustration. Here's a simple molecule in Chemdraw:
image
This is what it looks like if you read that CDXML into the RDKit:
image

There are two things going on here:
1. The coordinates are all much too large
2. The coordinate system is inverted: y increases from top to bottom instead of bottom to top

**Configuration (please complete the following information):**
 - RDKit version: release and master
 - OS: all

### LINKED ISSUE #6462: CDXML Parser does not preserve information about bond wedging
Wedged or dashed bonds from mol files have the property `_MolFileBondCfg` or `_MolFileBondStereo` set. This allows us to restore the original wedging if desired.
This information is not stored by the CDXML parser, but it should be

**Configuration (please complete the following information):**
 - RDKit version: release and master
 - OS: all

### PR DESCRIPTION
**Pull request by greglandrum**
Fixes #6461 
Fixes #6462

### CODE REVIEW

File: Code/GraphMol/FileParsers/CDXMLParser.cpp [hunk 1]
```diff
@@ -538,24 +571,29 @@ std::vector<std::unique_ptr<RWMol>> CDXMLDataStreamToMols(
...
               for (auto &atm : res->atoms()) {
+                RDGeom::Point3D p{0.0, 0.0, 0.0};
+
                 if (atm->hasProp(CDX_ATOM_POS)) {
                   hasConf = true;
                   const std::vector<double> coord =
                       atm->getProp<std::vector<double>>(CDX_ATOM_POS);
 
-                  RDGeom::Point3D p;
                   if (coord.size() == 2) {
```
Comment (bp-kelley) [inline Code/GraphMol/FileParsers/CDXMLParser.cpp:584]: Can coords be 3D?

File: Code/GraphMol/FileParsers/CDXMLParser.cpp [hunk 2]
```diff
@@ -538,24 +571,29 @@ std::vector<std::unique_ptr<RWMol>> CDXMLDataStreamToMols(
...
                   }
-                  conf->setAtomPos(atm->getIdx(), p);
-                  atm->clearProp(CDX_ATOM_POS);
                 }
+                conf->setAtomPos(atm->getIdx(), p);
+                atm->clearProp(CDX_ATOM_POS);
               }
+
               if (hasConf) {
+                scaleBonds(*res, *conf, 1.5, bondLength);
```
Comment (bp-kelley) [inline Code/GraphMol/FileParsers/CDXMLParser.cpp:596]: Maybe make 1.5 a constant
```
    const double RDKIT_DEPICT_BONDLENGTH = 1.5;
    scaleBonds(*res, *conf, RDKIT_DEPICT_BONDLENGTH, bondLength);
```

**Review by bp-kelley — APPROVED** [review]
One small minor suggestion
