### PR TITLE
Fixes #7327

### LINKED ISSUE #7327: SaltRemover may clear computed properties even if no atoms are removed
This is causing problems in mmpdb.

An example:
```python3
from rdkit import Chem
from rdkit.Chem import SaltRemover

m = Chem.MolFromSmiles('C=CC=O')

# Rotatable bond definition from mmpdb
q = Chem.MolFromSmarts(
    '[!$([NH]!@C(=O))&!D1&!$(*#*)]-&!@[!$([NH]!@C(=O))&!D1&!$(*#*)]')

expected_matches = ((1, 2),)

assert m.GetNumAtoms() == 4

# This works
assert m.GetSubstructMatches(q) == expected_matches

# But after removing salts...
remover = SaltRemover.SaltRemover()
m = remover.StripMol(m)

assert m
assert m.GetNumAtoms() == 4
assert m.GetSubstructMatches(q) == expected_matches
--------------------------------------
[17:52:29] 

****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 129 in file /Users/rodrigue/Documents/code/rdkit_builder/rdkit/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****

Traceback (most recent call last):
  File "/Users/rodrigue/Documents/cases/SHARED-10706/strip_salt.py", line 23, in <module>
    assert m.GetSubstructMatches(q) == expected_matches
           ^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 129 in file Code/GraphMol/RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2024.09.1pre
	BOOST: 1_81

```

The problem seems to be happening inside `Chem.DeleteSubstructs()`, as I have been able to reduce the example to this minimal reproducible:

```python3
from rdkit import Chem
from rdkit.Chem import SaltRemover

m = Chem.MolFromSmiles('C=CC=O')

# Rotatable bond definition from mmpdb
q = Chem.MolFromSmarts(
    '[!$([NH]!@C(=O))&!D1&!$(*#*)]-&!@[!$([NH]!@C(=O))&!D1&!$(*#*)]')

# From salt remover
salt = Chem.MolFromSmarts('[O,N]')
m = Chem.DeleteSubstructs(m, salt, True)

# No atoms removed
assert m.GetNumAtoms() == 4

assert m.GetSubstructMatches(q)
--------------------------------------
[17:56:59] 

****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 129 in file /Users/rodrigue/Documents/code/rdkit_builder/rdkit/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****

Traceback (most recent call last):
  File "/Users/rodrigue/Documents/cases/SHARED-10706/strip_salt.py", line 40, in <module>
    assert m.GetSubstructMatches(q)
           ^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 129 in file Code/GraphMol/RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2024.09.1pre
	BOOST: 1_81


```

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #7327

The fix is easy: the computed props are cleared in the call to `commitBatchEdit()`, so we just need to return before the batch edits if there's no atoms to delete.

### CODE REVIEW

**Review by greglandrum — APPROVED** [review]
LGTM

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp [hunk 1]
```diff
@@ -116,50 +112,54 @@ ROMol *deleteSubstructs(const ROMol &mol, const ROMol &query, bool onlyFrags,
...
-    for (mxi = matches.begin(); mxi != matches.end(); mxi++) {
+    for (auto mxi : matches) {
       INT_VECT tmp;
-      Union((*mxi), delList, tmp);
+      Union(mxi, delList, tmp);
       delList = tmp;
     }
   }
 
+  if (delList.empty()) {
```
Comment (d-b-w) [inline Code/GraphMol/ChemTransforms/ChemTransforms.cpp:159]: Makes sense.

Should `commitBatchEdit()` _also_ early return if there is nothing added or deleted? Otherwise this seems like a bit of a footgun down the road.

**Review by d-b-w — COMMENTED** [review]
nice. lgtm
