### PR TITLE
Fix #8945

### LINKED ISSUE #8945: N#N=O and O=N#N parse to different mol
**Describe the bug**
As mentioned in https://github.com/rdkit/rdkit/discussions/8942 , the SMILES for nitrous oxide `N#N=O` and`O=N#N` get parsed differently. 

**To Reproduce**

```python
from rdkit import Chem
for smi in ["N#N=O","O=N#N"]:
    print(Chem.MolToSmiles(Chem.MolFromSmiles(smi)))
```
gives the output:
```
[N-]=[N+]=O
N#[N+][O-]
```
two distinct resonance forms of nitrous oxide.

**Expected behavior**
Both SMILES to parse to the same resonance form.

**Configuration (please complete the following information):**
 - RDKit version:  2025.09.2
 - OS: [e.g. Ubuntu 20.04] Ubuntu 22.04
 - Python version (if relevant): 3.10
 - Are you using conda? y
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? n/a

**Additional context**
This behavior is probably due to different order of application of the pentavalent nitrogen cleanUp rules.

### PR DESCRIPTION
**Pull request by greglandrum**
Instead of going through the atoms once and looking at each possible transformation for each atom, this goes through the atoms for each transformation. So all `N=O -> [N+]-[O-]` transformations are done before the `N#N -> [N+]=[N-]` transformations

### CODE REVIEW

File: Code/GraphMol/MolOps.cpp [hunk 1]
```diff
@@ -89,42 +95,75 @@ void nitrogenCleanup(RWMol &mol, Atom *atom) {
...
   //   C=P(=O)X -> C=[P+]([O-])X
-  PRECONDITION(atom, "bad atom");
 
-  // we only want to do neutrals
-  if (atom->getFormalCharge()) {
-    return;
-  }
+  // we aren't currently using this; it's there in case
+  // we want to add more P cases later.
+  boost::dynamic_bitset<> atomsToConsider(mol.getNumAtoms());
```
Comment (ricrogz) [inline Code/GraphMol/MolOps.cpp]: Hm, looks like this is never used ? It seems there aren't any real changes to what we were doing in this function, are they?

Comment (greglandrum) [reply Code/GraphMol/MolOps.cpp]: Correct, as the comment says, that's not being used. I put it there to be consistent with the nitrogen cleanup code above.

At the moment this changes to this function are only to have it go over all atoms and pick out the Ps instead of having just Ps handed to it. I think it's non unreasonable to expect that we will eventually end up adding additional cleanup cases for P, so I thought it was worth getting ahead of things and updating this code now.

If it bothers, I can revert these changes and we can wait until another P cleanup scenario appears.

Comment (ricrogz) [reply Code/GraphMol/MolOps.cpp]: Yes, I think I'd prefer leaving this case for when we actually need to do it. I find it makes it a bit more confusing to read the code, as it hasn't yet a purpose for being there. And also the case where we need this might never come :)

Comment (greglandrum) [reply Code/GraphMol/MolOps.cpp]: Ok; will update it later
