### PR TITLE
Fixes #6050

### LINKED ISSUE #6050: stereogroups not combined when parsing CXSMILES
**Describe the bug**

Here's a demo (the SMILES is from the tests for the RegistrationHash):
```
In [2]: m = Chem.MolFromSmiles('C[C@@H](O)[C@H](C)[C@@H](C)[C@@H](C)O |&3:3,o1:7,&2:1,&3:5,r|')

In [3]: sgs = m.GetStereoGroups()

In [6]: for sg in sgs:
   ...:     print([x.GetIdx() for x in sg.GetAtoms()],sg.GetGroupType())
   ...: 
[3] STEREO_AND
[7] STEREO_OR
[1] STEREO_AND
[5] STEREO_AND
```
The two occurences of `&3` in the SMILES should be merged so that the molecule only has three stereo groups

**Configuration (please complete the following information):**
 - RDKit version: release and master
 - OS: all

### PR DESCRIPTION
**Pull request by greglandrum**
We need to keep track of the group IDs of the stereo groups as the molecule is being built.

### CODE REVIEW

File: Code/GraphMol/SmilesParse/CXSmilesOps.cpp [hunk 1]
```diff
@@ -1352,8 +1353,34 @@ bool parse_enhanced_stereo(Iterator &first, Iterator last, RDKit::RWMol &mol,
...
   if (!atoms.empty()) {
+    // we need to do a bit of work to check whether or not we've already seen
+    // this particular StereoGroup (was Github #6050)
+    group_id = 10 * group_id + static_cast<unsigned int>(group_type);
+    std::vector<unsigned int> sgTracker;
+    mol.getPropIfPresent(cxsgTracker, sgTracker);
     std::vector<StereoGroup> mol_stereo_groups(mol.getStereoGroups());
-    mol_stereo_groups.emplace_back(group_type, std::move(atoms));
+    TEST_ASSERT(mol_stereo_groups.size() == sgTracker.size());
+    bool found = false;
```
Comment (bp-kelley) [inline Code/GraphMol/SmilesParse/CXSmilesOps.cpp:1363]: using std::find I think would make this code simpler.

```
   auto index = std::find(sgTracker.start(), sgTracker.end(), group_id);
   if( index != sgTracker.end()) {
         auto gAtoms = mol_stereo_groups[*index].getAtoms();
         gAtoms.insert(gAtoms.end(), atoms.begin(), atoms.end());
         mol_stereo_groups[*index] =
             StereoGroup(mol_stereo_groups[*index].getGroupType(), std::move(gAtoms));
   } else {
      // not seen this before, create a new stereogroup
       mol_stereo_groups.emplace_back(group_type, std::move(atoms));
       sgTracker.resize(mol_stereo_groups.size());
       sgTracker.back() = group_id;
   }
  mol.setProp(cxsgTracker, sgTracker);
```

File: Code/GraphMol/SmilesParse/CXSmilesOps.cpp [hunk 2]
```diff
@@ -1352,8 +1353,34 @@ bool parse_enhanced_stereo(Iterator &first, Iterator last, RDKit::RWMol &mol,
     }
   }
   if (!atoms.empty()) {
+    // we need to do a bit of work to check whether or not we've already seen
+    // this particular StereoGroup (was Github #6050)
+    group_id = 10 * group_id + static_cast<unsigned int>(group_type);
+    std::vector<unsigned int> sgTracker;
+    mol.getPropIfPresent(cxsgTracker, sgTracker);
```
Comment (bp-kelley) [inline Code/GraphMol/SmilesParse/CXSmilesOps.cpp:1360]: Should sgTracker be part of the StereoGroup object?  This would remove the need for the implicit copy here.

Comment (greglandrum) [reply Code/GraphMol/SmilesParse/CXSmilesOps.cpp:1360]: I don't think the IDs should be part of the stereogroups. They only important here when parsing and can then simply be added when writing the groups out (which may not be in the order in which they were read or stored).

**Review by bp-kelley — APPROVED** [review]
