### PR TITLE
fixes #1023

### LINKED ISSUE #1023: GetSSSR interrupts by segmentation fault
When I'm trying to get the smallest set of simple rings in order to initialize RingInfo for a specific molecule the program interrupts with segmentation faul.

```
In [1]: from rdkit.Chem import AllChem

In [2]: mol = AllChem.MolFromPDBFile(/home/piotr/Desktop/test.pdb.txt', sanitize=False)

In [3]: mol is not None
Out[3]: True

In [4]: AllChem.GetSSSR(mol)
Segmentation fault
```
Error code printed by PyCharm:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Molecule that causes the problem:
[test.pdb.txt](https://github.com/rdkit/rdkit/files/415176/test.pdb.txt)

### PR DESCRIPTION
**Pull request by greglandrum**
This is a fix in the sense that the code no longer crashes. The algorithm is still not capable of finding rings in systems as non-chemical as this one, but that's not really a concern.

### CODE REVIEW

File: Code/GraphMol/FindRings.cpp [hunk 1]
```diff
@@ -745,15 +747,17 @@ bool _atomSearchBFS(const ROMol &tMol, unsigned int startAtomIdx,
     while (nbrIdx != endNbrs) {
       if (*nbrIdx == endAtomIdx) {
         if (currAtomIdx != startAtomIdx) {
-          tv.push_back(rdcast<unsigned int>(*nbrIdx));
+          INT_VECT nv(tv);
```
Comment (bp-kelley) [inline Code/GraphMol/FindRings.cpp]: I'm quite unclear why this fixed the issue.

File: Code/GraphMol/FindRings.cpp [hunk 2]
```diff
@@ -745,15 +747,17 @@ bool _atomSearchBFS(const ROMol &tMol, unsigned int startAtomIdx,
...
           // make sure the ring we just found isn't already in our set
           // of rings (this was an extension of sf.net issue 249)
           boost::uint32_t invr =
-              RingUtils::computeRingInvariant(tv, tMol.getNumAtoms());
+              RingUtils::computeRingInvariant(nv, tMol.getNumAtoms());
           if (invars.find(invr) == invars.end()) {
             // we're done!
-            res.resize(tv.size());
-            std::copy(tv.begin(), tv.end(), res.begin());
+            res.resize(nv.size());
```
Comment (bp-kelley) [inline Code/GraphMol/FindRings.cpp]: Can't we just:
```
res = tv;
...
res.push_back( ...);
```

And void the other copies?

File: Code/GraphMol/FindRings.cpp (hunk 1 above)
Comment (greglandrum) [inline Code/GraphMol/FindRings.cpp]: `tv` was potentially being modified on every pass through the loop starting at line 747. This is wrong and was leading to problems in rare cases. The hyper-connected PDB file that lead to the bug report happened to be one of those.

File: Code/GraphMol/FindRings.cpp (hunk 2 above)
Comment (greglandrum) [inline Code/GraphMol/FindRings.cpp]: Nope, because then `res` is modified even if the function returns false.
Besides it's saving one copy (the one at line 760) out of many in a function that's not called very much.

File: Code/GraphMol/FindRings.cpp (hunk 1 above)
Comment (bp-kelley) [inline Code/GraphMol/FindRings.cpp]: Ah, so the old line: // ignore this one wasn't popping.  That makes sense.

File: Code/GraphMol/FindRings.cpp (hunk 2 above)
Comment (bp-kelley) [inline Code/GraphMol/FindRings.cpp]: And after expanding the full diff, I see that now.
