### PR TITLE
Reactions should not use strict implicit valence calculations

### LINKED ISSUE #3097: RunReactants triggers strict calculation of explicit valence
**Configuration:**
- RDKit Version: 2020.09 (present in 2019.09+)
- Operating system: MacOS

**Description:**
RunReactants should just apply the transformation and return unsanitized mols, instead it is forcing calculation of explicit valence in strict mode, thus producing error. This is a regression that happened somewhere after 2019.03 release.

**Expected behavior:**
The reaction should not fail in such way, even with messed up (but still valid) SMARTS.

**Example**
I understand that the SMARTS is not ideal, although that is the minimal example that triggers the error. 
```python
rxn = AllChem.ReactionFromSmarts('[c:6][n:7][c:8].[N:14]#[N:15]>>[C:6].[C:8][N:7]=[N+:14]=[N-:15]')                                                                                                                                                              
rxn.RunReactants((Chem.MolFromSmiles('c1cc[nH]c1'), Chem.MolFromSmiles('N#N')))                                                                                                                                                                                  
```
**Error:** `[14:57:42] Explicit valence for atom # 1 N, 4, is greater than permitted`

### PR DESCRIPTION
**Pull request by mwojcikowski**
Fixes #3097 by disabling strict flag on `calcImlicitValence` in reactions

### CODE REVIEW

File: Code/GraphMol/ChemReactions/ReactionRunner.cpp [hunk 1]
```diff
@@ -702,8 +702,8 @@ void updateStereoBonds(RWMOL_SPTR product, const ROMol &reactant,
       Atom *pStart = pBond->getBeginAtom();
       Atom *pEnd = pBond->getEndAtom();
 
-      pStart->calcImplicitValence(true);
-      pEnd->calcImplicitValence(true);
+      pStart->calcImplicitValence(false);
+      pEnd->calcImplicitValence(false);
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/ReactionRunner.cpp:706]: These changes make sense to me.
@ricrogz : you wrote (I think ) the original version of this as part of #2553 
Do you see any reason to not make the change?

Comment (ricrogz) [reply Code/GraphMol/ChemReactions/ReactionRunner.cpp:706]: @greglandrum, @mwojcikowski, I did indeed write that, but I cannot remember why I required strict valence calculation, nor can I think of a reason for it. I think it might even be a typo. I'm ok with this change.

File: Code/GraphMol/ChemReactions/testReaction.cpp [hunk 2]
```diff
@@ -7390,6 +7390,24 @@ void testDblBondCrash() {
   }
 }
 
+void testGithub3097() {
+  BOOST_LOG(rdInfoLog) << "-------------------------------------" << std::endl;
+  BOOST_LOG(rdInfoLog) << "Testing Github issue # 3097" << std::endl;
+
+  std::string smi =
+      "[c:6][n:7][c:8].[N:14]#[N:15]>>[C:6].[C:8][N:7]=[N+:14]=[N-:15]";
+  ChemicalReaction *rxn = RxnSmartsToChemicalReaction(smi);
```
Comment (ricrogz) [inline Code/GraphMol/ChemReactions/testReaction.cpp:7399]: Oh, please make sure `rxn` does not leak:

```suggestion
  std::unique_ptr<ChemicalReaction> rxn{RxnSmartsToChemicalReaction(reaction)};
```

**Comment by mwojcikowski** [comment]
@ricrogz Thanks for spotting that. Committed the suggested solution. 

@greglandrum The build failure is due to connection error, can you restart the Ubuntu 16 build, or do we want to merge the PR?

**Comment by greglandrum** [comment]
@mwojcikowski I'm fine merging as is

**Comment by greglandrum** [comment]
Thanks @mwojcikowski !
