### PR TITLE
Trim spaces from RDProp strings to simulate reading from SDFiles

### LINKED ISSUE #8546: Mol.GetDoubleProp() fails if any spaces in tag value
**Describe the bug**
If there there are any prefixing or suffixing spaces in an SDF tag value, Mol.GetDoubleProp() fails.

**Expected behavior**
One would expect that the context implied by a method GetDoubleProp() means that it is reasonable enough to strip spaces from the front or back of a string before attempting conversion to a floating point value.

**To Reproduce**

```python
`--> python
Python 3.13.2 | packaged by conda-forge | (main, Feb 17 2025, 14:10:22) [GCC 13.3.0] on linux
>>> import rdkit
>>> rdkit.__version__
'2025.03.2'
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("CCC")
>>> mol.SetProp("A", "1.23")
>>> mol.SetProp("B", "3.14159 ")
>>> mol.GetDoubleProp("A")
1.23
>>> float(mol.GetProp("A"))
1.23
>>> float(mol.GetProp("B"))
3.14159
>>> mol.GetDoubleProp("B")
Traceback (most recent call last):
...
ValueError: key `B` exists but does not result in a double value reason: bad any_cast
>>> mol.SetProp("C", " 3.14159")
>>> mol.GetDoubleProp("C")
Traceback (most recent call last):
...
ValueError: key `C` exists but does not result in a double value reason: bad any_cast
>>>
>>> mol.SetProp("D", "123 ")
>>> int(mol.GetProp("D"))
123
>>> mol.GetIntProp("D")
Traceback (most recent call last):
...
ValueError: key `D` exists but does not result in an integer value reason: bad any_cast
```

**Screenshots**
(code above)

**Configuration:**
 - RDKit version:  2025.3.2
 - OS: Rocky Linux release 9.4 (Blue Onyx)
 - Python version (if relevant): 3.13.2
 - Are you using conda?  Using Mamba
 - If you are using conda, which channel did you install the rdkit from? rdkit (via "mamba create --channel rdkit")
 - If you are not using conda: how did you install the RDKit? N/A

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #8546 

By default, when converting to double/floats this trims the right hand white space.  This simulates round tripping through SDFiles which automatically do this.

When converting to a python dictionary, the rdkit will be more aggressive and trim all spaces.

```
mol.SetDoubleProp("foo", "123.0 ")
mol.GetDoubleProp("foo") == 123.
mol.SetDoubleProp("bar", " 123.0 ")
mol.GetDoubleProp("bar) # throws exception
mol.GetPropsAsDict()["bar"] == 123.
```

### CODE REVIEW

**Comment by jbbrownlsi** [comment]
If an SDF-producing software writes multiple values to an SDF file, using newline characters to write the separate values (e.g. this is an option in Certara's D360 software, for something such as multiple measurements of an assay) , then what happens as a result of this new rhs whitespace strip behavior? Does only the final whitespace get stripped, and all newlines up to the final non-whitespace line in the tag value are preserved?

Just confirming to be safe.

**Comment by bp-kelley** [comment]
Anything with white space separated values won’t resolve to a numeric value.

**Comment by bp-kelley** [comment]
But we can put in a test for this if you like

**Comment by jbbrownlsi** [comment]
I didn't realize the context was constrained to GetDoubleProp()/GetIntProp() calls.
If this PR is intended for use only with such, then everything is fine.

Some may view it as excessive, but it might be a good, explicit self-documentation if a doctest demonstrates that a multi-line numeric value will fail to work when GetIntProp()/GetDoubleProp() is called. Perhaps:

```
mol = Chem.MolFromSmiles("CC")
mol.SetProp("my_property", "3")
mol.GetIntProp("my_property")
3
mol.SetProp("my_property", "3\n4")  # Multiple measurements
mol.GetIntProp("my_property")
Traceback (most recent call last):
...
ValueError: ...
```

File: Code/GraphMol/Wrap/Atom.cpp [hunk 1]
```diff
@@ -446,12 +446,12 @@ struct atom_wrapper {
               python::arg("includeComputed") = true,
               python::arg("autoConvertStrings") = true),
              "Returns a dictionary of the properties set on the Atom.\n"
+	     "When possible, string values will be trimmed and converted to integers and doubles\n"
```
Comment (greglandrum) [inline Code/GraphMol/Wrap/Atom.cpp]: I think you intended to include the `getPropsAsDictDocString` thing here.

File: Code/GraphMol/Wrap/Atom.cpp [hunk 2]
```diff
@@ -446,12 +446,12 @@ struct atom_wrapper {
...
              " n.b. some properties cannot be converted to python types.\n")
 
         .def("UpdatePropertyCache", &Atom::updatePropertyCache,
              (python::arg("self"), python::arg("strict") = true),
-             "Regenerates computed properties like implicit valence and ring "
-             "information.\n\n")
+	     getPropsAsDictDocString.c_str())
```
Comment (greglandrum) [inline Code/GraphMol/Wrap/Atom.cpp]: this is the wrong doc string

**Review by greglandrum — CHANGES_REQUESTED** [review]
It looks like there's a mistake in Atom.cpp, but otherwise the change seems fine
