### PR TITLE
Fixes #8644

### LINKED ISSUE #8644: `MultithreadedSDMolSupplier` occasionally returns extra `None` entries
When reading an SDF file with `MultithreadedSDMolSupplier`, it sometimes returns extra `None` entries, even for a valid file.
This behavior appears to be non-deterministic and becomes more frequent as the number of threads increases.

### Minimal reproducible example:
- Input: SDF file containing just one molecule
- File contents:
```
CHEMBL153534
     RDKit          2D

 16 17  0  0  0  0  0  0  0  0999 V2000
    7.6140  -22.2702    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7047  -23.1991    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.1806  -22.5282    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    6.9604  -22.7690    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.8790  -23.2163    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    8.2791  -21.1119    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    7.5280  -21.4445    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.4225  -22.4364    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.8353  -21.7198    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.2035  -23.8527    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
    4.0534  -23.2163    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.9776  -23.5889    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6406  -22.4938    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.6406  -23.9215    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    8.4397  -20.3035    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.6552  -21.6280    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  3  2  0
  3  4  1  0
  4  1  1  0
  5  2  1  0
  6  7  1  0
  7  1  2  0
  8  1  1  0
  9  8  2  0
 10 12  1  0
 11  5  2  3
 12  4  2  0
 13 11  1  0
 14 11  1  0
 15  6  1  0
 16  9  1  0
  6  9  1  0
 10  2  1  0
M  END
> <chembl_id>
CHEMBL153534

$$$$
```

- Test: Load the file 1000 times, both with `SDMolSupplier` and `MultithreadedSDMolSupplier`, and count the number of molecules returned.

### Observations:
- Using `SDMolSupplier`:
  - returned 1 mol every time
- Using `MultithreadedSDMolSupplier`:
  - With 1 thread: ~0-5 cases of `[mol, None]`
  - With 2 threads: ~10 cases.
  - With 3 threads: >200 cases.
  - With 4 threads: >700 cases.
  - With >=5 threads: >900 and approaching 1000.

So, the higher the number of threads, the more frequent the problem becomes.
Obviously, using more threads than there are molecules doesn’t make sense, but this unexpected behavior occurs even with larger files, though less dramatically.

For example:

- File with 143 molecules, 10 threads: ~25 incorrect results out of 1000 runs.
- Similar behavior observed for files with >14,000 molecules (but no large-scale tests were run due to runtime).

### End-of-file differences

Additionally, I noticed differences in how the two suppliers treat the end of the file:

- If the SDF file ends with a `\n` after the final `$$$$`, the multithreaded class always returns one extra `None`, whereas `SDMolSupplier` does not.
- If the file has no final `$$$$` separator at all, the result is similar.
- In both cases, sometimes an additional non-deterministic `None` is also returned.

The conclusion from my tests is that the results returned by the two classes, over the same file, can differ in length by up to two `None` entries.

My Configuration:
- RDKIT: 2024.9.5
- OS:  Windows 11
- Python: 3.11
- Environment: PyCharm

I'm happy to provide more details if needed.

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #8644

~This is still a work in progress. I still need to check the Multithreaded supplier Python tests, and write a specific test for this issue, but I think this might be a satisfactory fix.~

Ok, the initial fix solved the issue by checking EOF after attempting to read. This is not really satisfying, since in certain scenarios we'd have to do ugly stuff like what I did in the test:

```
    while not smiSup.atEnd():
      try:
        mol = next(smiSup)
      except StopIteration:
        pass
      if (mol):
        i += 1
 ```
 
 I think this new fix is more satisfying, since it actually addresses the cause of the issue, so we don't have to rely on `getEOFHitOnRead()` to know when we really processed all inputs. And also we don't need the `try`/`catch` above.
 
The reason for which we got the "extra" results is that the writer threads do not block the main thread. So, when the last mol is pushed to the output queue, that writer thread will make a last iteration, going into `pop()`, receiving a `false`, leaving the `while` block, and then finally calling `setDone()` to close the output thread and cause `atEnd()` to return `true`.

It seems that, during this time, the main thread can retrieve the last mol, and then hit `atEnd()` again before `setDone()` happens, triggering a last `next()` call, which, this time, will receive a `false`, causing it to directly hit the `return nullptr` instruction returning a final, extra, "non-mol" from the supplier, which we can't distinguish in any way from a parsing failure, as it was mentioned in the issue.

In this new version of the patch I change the way we detect if the supplier is "at end", by simply keeping track of the number of structures we have seen both at the input (there's always just one reader thread, which can count how many text blocks it puts into the input queue), and how many molecules (or `nullptrs`) the `next()` method has returned (this counting will also always take place in a single thread, the main one, so there isn't any need of mutexes or atomics in this one either). This allows us to correctly detect when all mols have been returned, and given than the spurious `nullptr`s or `None`s always happen at the end, we can avoid them, since we will know that we are "at the end" right after returning the last mol.

### CODE REVIEW

File: Code/GraphMol/FileParsers/MultithreadedMolSupplier.h [hunk 1]
```diff
@@ -101,6 +97,8 @@ class RDKIT_FILEPARSERS_EXPORT MultithreadedMolSupplier : public MolSupplier {
     readCallback = cb;
   }
 
+  bool getEOFHitOnRead() const { return df_eofHitOnRead; }
```
Comment (bp-kelley) [inline Code/GraphMol/FileParsers/MultithreadedMolSupplier.h]: Nice, this was the missing piece I think.

**Comment by ricrogz** [comment]
Ok, I think I got a better fix (at least, it's more satisfactory to me, because we don't have to use `getEOFHitOnRead()`.

See the updated description for the explanation.
