### PR TITLE
Fixes #3349

### LINKED ISSUE #3349: Incorrect resonance structures in presence of dative bonds
If an atom which is a part of a conjugated system forms a dative bond, it drops out of the resonance:

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('CC(=O)[O-]')
print(len(Chem.ResonanceMolSupplier(mol)))
> 2
mol = Chem.MolFromSmiles('CC(=O)[O-]->[*]')
print(len(Chem.ResonanceMolSupplier(mol)))
> 1
```

I think, if an atom forms a dative bond as a donor, then such dative bonds must be ignored.

### PR DESCRIPTION
**Pull request by ptosco**
- Fixed #3349
- fixed a few typos
- removed `const` from `ResonanceMolSupplierCallback::operator()`, which should be allowed to modify the owning object
- added missing `const` to some getters

### CODE REVIEW

File: Code/GraphMol/Resonance.cpp [hunk 1]
```diff
@@ -297,12 +297,19 @@ void fixExplicitImplicitHs(ROMol &mol) {
...
       d_fc(0),
       d_flags(0),
       d_atom(a),
       d_parent(parent) {
   PRECONDITION(d_atom, "d_atom cannot be NULL");
+  d_tv = static_cast<std::uint8_t>(a->getTotalDegree());
+  const ROMol &mol = d_atom->getOwningMol();
+  for (const auto &bNbri :
+       boost::make_iterator_range(mol.getAtomBonds(d_atom))) {
+    if (d_tv && mol[bNbri]->getBondType() >= Bond::DATIVEONE) {
```
Comment (greglandrum) [inline Code/GraphMol/Resonance.cpp:309]: since you mention zero-order bonds in a comment in the tests: maybe it's worth including a check for those here too?

**Review by greglandrum — APPROVED** [review]
There's a comment/suggestion that I think would help, but isn't necessary.
I'm ok to merge as is.

File: Code/GraphMol/Resonance.cpp (hunk 1 above)
Comment (ptosco) [reply Code/GraphMol/Resonance.cpp:309]: @greglandrum  Wouldn't `>=DATIVEONE` cover also `ZERO`? Or am I misunderstanding your question?

Comment (greglandrum) [reply Code/GraphMol/Resonance.cpp:309]: oops. Bad reading comprehension on my part. Sorry about that.
