### PR TITLE
Fixes #9068: raise a ValueError when trying to set properties with empty names

### LINKED ISSUE #9068: SDWriter writes empty property names, but SDMolSupplier fails to parse them and skips other properties
**Describe the bug**
When an RDKit molecule has an empty property name, the behavior between writing and reading SDF files is inconsistent.

`mol.SetProp('', value)` is allowed

`Chem.SDWriter` writes the empty property name into the SDF

`Chem.SDMolSupplier` fails to parse the SDF and loss other properties.

**To Reproduce**
```python
from rdkit import Chem
path = './cpd0001.sdf'
mol = Chem.MolFromSmiles('C1CCCC1')
mol.SetProp('prop1', 'value1')
mol.SetProp('', '2') # Set empty property name
mol.SetProp('prop3', 'value3')
print(mol.GetPropsAsDict())

with Chem.SDWriter('./cpd0001.sdf') as fw:
    fw.write(mol)

sdf_mols = Chem.SDMolSupplier(path)
print(sdf_mols[0].GetPropsAsDict())
```
Console output:
```
{'prop1': 'value1', '': 2, 'prop3': 'value3'}
[13:46:31] ERROR: End of data field name not found
[13:46:31] ERROR: moving to the beginning of the next molecule
{'prop1': 'value1'}
```

```bash
$ cat ./cpd0001.sdf

     RDKit          2D

  5  5  0  0  0  0  0  0  0  0999 V2000
    1.2760    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3943    1.2135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0323    0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0323   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3943   -1.2135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  1  1  0
M  END
>  <prop1>  (1) 
value1

>  <>  (1) 
2

>  <prop3>  (1) 
value3

$$$$
```
**Expected behavior**
Since RDKit allows setting properties with empty string names via `Mol.SetProp`,
`SDMolSupplier` should be able to correctly parse SDF files written by `SDWriter`
that contain such properties.

In other words, writing a molecule to SDF and reading it back should be a
lossless round-trip, even if a property name is an empty string.

**Configuration (please complete the following information):**
 - RDKit version: 2025.09.4
 - OS: Centos7.6
 - Python version (if relevant): Python 3.13
 - Are you using conda?
 yes, conda-forge

### PR DESCRIPTION
**Pull request by greglandrum**
Modifies both the `RDProps` and `Dict` classes to not allow properties with empty names to be set.

### CODE REVIEW

File: Code/RDGeneral/Dict.h [hunk 1]
```diff
@@ -291,20 +294,45 @@ class RDKIT_RDGENERAL_EXPORT Dict {
...
+    if (what.empty()) {
+      throw ValueErrorException("Cannot set value with empty key");
+    }
+    setPODVal(what, val);
+  }
 
   void setVal(const std::string_view what, unsigned int val) {
+    if (what.empty()) {
+      throw ValueErrorException("Cannot set value with empty key");
+    }
```
Comment (ricrogz) [inline Code/RDGeneral/Dict.h:330]: Why not add just one check to `setPODVal()` instead ?

Comment (greglandrum) [reply Code/RDGeneral/Dict.h:330]: Since it's a short and quick check, I thought it would make sense to add it everywhere in case we change implementation details in the future.

I should definitely also add it to `setPODVal()`
