### PR TITLE
fix problems with template matching

### LINKED ISSUE #8121: symmetric ring finding not returning correct results for molecules with fragments
**Describe the bug**
The code that does the ring symmetrization does not end up adding the extra rings for fragments beyond the first one. Here's the demo:
```
# cubane
In [2]: m = Chem.MolFromSmiles('C12C3C4C1C5C2C3C45')

# two cubanes
In [3]: m2 = Chem.MolFromSmiles('C12C3C4C1C5C2C3C45.C12C3C4C1C5C2C3C45')

In [7]: ri = m.GetRingInfo()

In [8]: ri.NumRings()
Out[8]: 6

In [9]: ri2 = m2.GetRingInfo()

In [10]: ri2.NumRings()
Out[10]: 11

```

This was identified by @ZontaNicola 

**Configuration (please complete the following information):**
 - RDKit version: master and release
 - OS: all

### PR DESCRIPTION
**Pull request by ZontaNicola**
#### Reference Issue
https://github.com/rdkit/rdkit/issues/6753 CRDGEN-371 CRDGEN-300

#### What does this implement/fix? Explain your changes.
this fixes a bug in templates matching, where only the last fragment gets matched in a multi-fragment molecule (e.g. C12C3C4C1C1C2C3C41.C12C3C4C1C1C2C3C41)

I also removed an unused variable so that my build could complete

the other issues mentioned in CRDGEN-371 are now dealt with here https://github.com/rdkit/molecular_templates/pull/12

Fixes #8121

### CODE REVIEW

File: Code/GraphMol/Depictor/Templates.h [hunk 1]
```diff
@@ -69,11 +72,147 @@ class RDKIT_DEPICTOR_EXPORT CoordinateTemplates {
...
+      if (atom->getDegree() < 1) {
+        continue;
+      }
+      auto coordinates = mol->getConformer().getAtomPos(atom->getIdx());
+      for (const auto &nbrIdx :
+           boost::make_iterator_range(mol->getAtomNeighbors(atom))) {
+        point += mol->getConformer().getAtomPos(nbrIdx);
+      }
+      point /= mol->getAtomDegree(atom);
+      point = coordinates + (point - coordinates) * (-0.3);
```
Comment (ZontaNicola) [inline Code/GraphMol/Depictor/Templates.h:193]: note to self: the length here is dependent on the angle of substituents... should probably normalize it. Not a big deal since we only need it to be "short"

**Comment by ZontaNicola** [comment]
@greglandrum I think this is ready for your review.

**Comment by greglandrum** [comment]
@ZontaNicola sorry I was so slow reviewing this.

I just did a PR against your branch that adds a test for the bug you fixed with the ring finding.
If you merge that, this PR will be automatically updated and I will merge it here.

**Comment by greglandrum** [comment]
I don't see how this fix (which is great, by the way!) affects #6753

**Comment by greglandrum** [comment]
@ZontaNicola can you please take a look at the PR I made against your branch (https://github.com/ZontaNicola/rdkit/pull/4) and see if you agree with it?

**Comment by ZontaNicola** [comment]
sorry, should be merged now
