### PR TITLE
Fixes #3774

### LINKED ISSUE #3774: MolToSmarts inverts direction of dative bond
Transforming the molecule containing dative bonds results in reversion of their direction (rdkit 2020.09.4, win-64):

```python
from rdkit import Chem
Chem.MolToSmarts(Chem.MolFromSmiles('N->[Cu+]'))
> '[#7]<-[Cu+]'
Chem.MolToSmarts(Chem.MolFromSmiles('N<-[Cu+]'))
> '[#7]->[Cu+]'
```

This works for all tested complexes without any exception.

### PR DESCRIPTION
**Pull request by greglandrum**
also speeds up compiles of the SMILES catch tests by using the catch_main.cpp in GraphMol

This is a simple fix since we had the logic for writing dative bonds to SMARTS exactly backwards.

### CODE REVIEW

File: Code/GraphMol/SmilesParse/SmartsWrite.cpp [hunk 1]
```diff
@@ -393,7 +393,7 @@ std::string getBondSmartsSimple(const Bond *bond,
   } else if (descrip == "BondOrder") {
     bool reverseDative =
         (atomToLeftIdx >= 0 &&
-         bond->getBeginAtomIdx() == static_cast<unsigned int>(atomToLeftIdx));
+         bond->getBeginAtomIdx() != static_cast<unsigned int>(atomToLeftIdx));
```
Comment (bp-kelley) [inline Code/GraphMol/SmilesParse/SmartsWrite.cpp:396]: Whups!

**Review by bp-kelley — APPROVED** [review]
