### PR TITLE
Fixes #1294

### LINKED ISSUE #1294: ring stereochemistry perception failing for spiro centers
reported by James Davidson here: http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06548.html

```
In [2]: print(Chem.CanonSmiles('O[C@H]1CC[C@]11CC[C@@](Cl)(Br)CC1'))
O[C@H]1CCC12CCC(Cl)(Br)CC2
```
the molecule:
image

### PR DESCRIPTION
**Pull request by greglandrum**
There was no reason to require only two ring bonds.

### CODE REVIEW

File: Code/GraphMol/Chirality.cpp [hunk 1]
```diff
@@ -402,9 +402,17 @@ void findAtomNeighborsHelper(const ROMol &mol, const Atom *atom,
   }
 }
 
+// conditions for an atom to be a candidate for ring stereochem:
```
Comment (bp-kelley) [inline Code/GraphMol/Chirality.cpp]: Yay, more docs :)

File: Code/GraphMol/Chirality.cpp [hunk 2]
```diff
@@ -402,9 +402,17 @@ void findAtomNeighborsHelper(const ROMol &mol, const Atom *atom,
...
+//   1) two non-ring neighbors that have different ranks
+//   2) one non-ring neighbor and two ring neighbors (the ring neighbors will
+//      have the same rank)
+//   3) four ring neighbors with three different ranks
```
Comment (bp-kelley) [inline Code/GraphMol/Chirality.cpp]: pedantic:  with at least three different ranks (and with at least two different ranks below)

Comment (greglandrum) [inline Code/GraphMol/Chirality.cpp]: Hmm, no. If it had four different ranks it would be chiral and we wouldn't be here. The code does say >=3, but it really could be ==3.

Comment (greglandrum) [inline Code/GraphMol/Chirality.cpp]: Is it worth changing? I lean towards "no"

**Comment by bp-kelley** [comment]
I'm fine either way, but as written the code doesn't quite match the comment :)

----
Brian Kelley
