### PR TITLE
Initial Rascal results sort the wrong way round on number of atoms and bonds.

### LINKED ISSUE #8255: Rascal - Missing atoms in MCESs
Hi,

I have a couple of example molecules that return unexpected Rascal MCESs.

**Example 1**

Here, the first 3 MCESs contain 20 atoms and the last one contains 19 atoms. Why doesn't the best MCES contain 22 atoms? 

For example, why doesn't the first returned MCES also include atom matches (13, 14) and (17, 16)?

```
opts = rdRascalMCES.RascalOptions()
opts.singleLargestFrag = True
opts.allBestMCESs = True
opts.ignoreAtomAromaticity = True
opts.ringMatchesRingOnly = False
opts.completeAromaticRings = False

mola = Chem.MolFromSmiles("Cc1ccc(cn1)-c1ccc(cn1)-c1ccc2ccccc2n1")
molb = Chem.MolFromSmiles("Cc1ccc(cn1)-c1ccc(cn1)-c1cc2ccccc2[nH]1")
rascal_matches = rdRascalMCES.FindMCES(mola, molb, opts)

atom_matches = []
mols = []
for rascal_result in rascal_matches:
    atom_match_a = [a[0] for a in rascal_result.atomMatches()]
    atom_match_b = [a[1] for a in rascal_result.atomMatches()]
    atom_matches.append(atom_match_a)
    atom_matches.append(atom_match_b)
    mols.append(mola)
    mols.append(molb)

Draw.MolsToGridImage(mols, molsPerRow=2, subImgSize=(400,200), highlightAtomLists=atom_matches, useSVG=True)
```

Image

**Example 2**

Why is there a 3rd MCES with 1 fewer atom?

```
opts = rdRascalMCES.RascalOptions()
opts.singleLargestFrag = True
opts.allBestMCESs = True
opts.ignoreAtomAromaticity = True
opts.ringMatchesRingOnly = False
opts.completeAromaticRings = False

mola = Chem.MolFromSmiles("Cc1ncc(cc1)c2ncc(cc2)c3ccc4c(c3)cn[nH]4")
molb = Chem.MolFromSmiles("Cc1ncc(cc1)c2ncc(cc2)c3ccc4c(c3)nccn4")
rascal_matches = rdRascalMCES.FindMCES(mola, molb, opts)

atom_matches = []
mols = []
for rascal_result in rascal_matches:
    atom_match_a = [a[0] for a in rascal_result.atomMatches()]
    atom_match_b = [a[1] for a in rascal_result.atomMatches()]
    atom_matches.append(atom_match_a)
    atom_matches.append(atom_match_b)
    mols.append(mola)
    mols.append(molb)

Draw.MolsToGridImage(mols, molsPerRow=2, subImgSize=(400,200), highlightAtomLists=atom_matches, useSVG=True)
```

Image

**Configuration (please complete the following information):**
 - RDKit version: 2024.09.5
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
Fixes #8255

#### What does this implement/fix? Explain your changes.
In the singleLargestFrag = true option, the initial sort of the results should have been in descending order of number of bonds and number of atoms but was ascending so the removal of smaller hits failed.

#### Any other comments?
Doh!

### CODE REVIEW

**Comment by DavidACosgrove** [comment]
It wasn't quite a simple as first thought (is it ever?).  This may change the results in some cases compared with previous versions.  If there are 2 cliques of the same number of bonds, it will now prefer the one with fewer fragments, which may have fewer atoms.  Personally, I think that's a better answer, for example in this pair of compounds, it will prefer the first result over the second:
image
The second one matches bond 21 to bond 0 so gets the extra methyl group and 1 more atom, but at the expense of leaving the fused ring floating.  If the user uses allBestMCESs = True, the same results will be returned but in a different order.  If just returning a single MCES they may get a different result.

File: Code/GraphMol/RascalMCES/RascalMCES.cpp [hunk 1]
```diff
@@ -1126,15 +1126,25 @@ std::vector<RascalResult> findMCES(RascalStartPoint &starter,
...
+          if (r1.getAtomMatches().size() == r2.getAtomMatches().size()) {
+            if (r1.getBondMatches().size() == r2.getBondMatches().size()) {
+              if (r1.getAtomMatches() == r2.getAtomMatches()) {
+                return (r1.getBondMatches() < r2.getBondMatches());
+              }
+              return r1.getAtomMatches() < r2.getAtomMatches();
+            }
+            return r1.getBondMatches().size() > r2.getBondMatches().size();
+          }
+          return (r1.getAtomMatches().size() > r2.getAtomMatches().size());
```
Comment (greglandrum) [inline Code/GraphMol/RascalMCES/RascalMCES.cpp:1146]: why do the first two return statements here return r1 < r2 and the second two return r1 > r2?

File: Code/GraphMol/RascalMCES/RascalMCES.cpp [hunk 2]
```diff
@@ -1126,15 +1126,25 @@ std::vector<RascalResult> findMCES(RascalStartPoint &starter,
                      opts.maxFragSeparation, opts.exactConnectionsMatch,
                      opts.equivalentAtoms, opts.ignoreBondOrders));
   }
+  // If 2 cliques are the same size, this sort puts the one with the smaller
+  // number of fragments first, which may have fewer atoms.
+  std::sort(results.begin(), results.end(), details::resultCompare);
```
Comment (greglandrum) [inline Code/GraphMol/RascalMCES/RascalMCES.cpp:1132]: When `singleLargestFrag` is set, you are sorting `results` twice.
Can't you put this sort in an `else` on the `if (opts.singleLargestFrag) {` and include the comparison of the number of fragments in your sort on line 1134?

**Review by greglandrum — CHANGES_REQUESTED** [review]
one question/suggestion and something that I think is wrong

File: Code/GraphMol/RascalMCES/RascalMCES.cpp (hunk 1 above)
Comment (DavidACosgrove) [reply Code/GraphMol/RascalMCES/RascalMCES.cpp:1146]: It's sorting in descending number of bonds and atoms, ascending order of atom and bond indices.  The sort on vector size is important, on index less so but I prefer lower indices first for no good reason.

File: Code/GraphMol/RascalMCES/RascalMCES.cpp (hunk 2 above)
Comment (DavidACosgrove) [reply Code/GraphMol/RascalMCES/RascalMCES.cpp:1132]: I've moved the first sort to an else.  In the sort on 1134 (now 1130) there is only 1 fragment at this stage - singleLargestFrag has already been applied by the time it gets there.  That was in fact the original bug - having applied singleLargestFrag, there were then cliques of different sizes left and we only want to keep the largest of them.

**Review by greglandrum — APPROVED** [review]
LGTM
