### PR TITLE
Github6968

### LINKED ISSUE #6968: Highlights of triple bonds come out wrong
**Describe the bug**
This is from discussion #6967 

**To Reproduce**
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
mol = Chem.MolFromSmiles('ClCC#CCOC(=O)Nc1cccc(c1)Cl')
pat = Chem.MolFromSmarts('ClCC#CC')
mol.GetSubstructMatches(pat)
mol

**Expected behavior**
The bond highlights should be rectangular rather than triangular.

**Screenshots**
image

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.2
 - OS: macOS 14
 - Python version (if relevant):
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? ronda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
I'll work on a fix in the next few days.  I dare say the linear arrangement is messing with the direction of the perpendiculars defining the rectangle.

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
Fixes #6968

#### What does this implement/fix? Explain your changes.
The linear system about the triple bond was confusing the code that matched the ends of the highlight rectangles up.  This just rotates one of the atoms a bit to break the linearity during construction.  Obviously not permanently.

#### Any other comments?
It now looks like this (bonds highlighted only).
image

I suspect that in the process of discussing and filing the bug, @thwelln's credit for the report has got lost.

### CODE REVIEW

**Comment by greglandrum** [comment]
> I suspect that in the process of discussing and filing the bug, @thwelln's credit for the report has got lost.

Yeah, the only way this works is if they submit the issue

File: Code/GraphMol/MolDraw2D/catch_tests.cpp [hunk 1]
```diff
@@ -9310,3 +9313,58 @@ TEST_CASE("Github 6749 : various bad things in the lasso highlighting") {
...
+      std::vector<int> highlightAtoms = {};
+      // Helpfully, the atoms are scrambled but not the bonds.
+      std::vector<int> highlightBonds = {1, 2, 3};
+
+      drawer.drawOptions().addAtomIndices = true;
+      drawer.drawOptions().addBondIndices = true;
+      drawer.drawMolecule(*mol, "", &highlightAtoms, &highlightBonds);
+      drawer.finishDrawing();
+      auto text = drawer.getDrawingText();
+      std::ofstream outs("testGithub6869.svg");
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/catch_tests.cpp:9340]:
```suggestion
      std::ofstream outs("testGithub6968.svg");
```

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 2]
```diff
@@ -3370,6 +3370,19 @@ void DrawMol::makeHighlightEnd(const Atom *end1, const Atom *end2,
...
+    auto b1 = end2Cds.directionVector(end1Cds);
+    auto b2 = end2Cds.directionVector(end3Cds);
+    if (1.0 - fabs(b1.dotProduct(b2)) < 1.0e-4) {
+      // rotate end3 about end2 by a small amount to create
+      // an inner and outer
+      end3Cds -= end2Cds;
+      RDGeom::Transform2D trans;
+      trans.SetTransform(Point2D(0, 0), M_PI / 20.0);
+      trans.TransformPoint(end3Cds);
+      end3Cds += end2Cds;
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:3382]: I haven't tested extensively, but wouldn't this be simpler/more efficient if you just offset end3Cds a short distance along the perpendicular?
```suggestion
      auto d32 = end3Cds - end2Cds;
      Point2D d32transp(d32.y, -d32.x);
      d32transp *= 0.1;
      end3Cds += d32transp;
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
a minor suggestion and a question

File: Code/GraphMol/MolDraw2D/DrawMol.cpp (hunk 2 above)
Comment (DavidACosgrove) [reply Code/GraphMol/MolDraw2D/DrawMol.cpp]: Originally I thought I'd have to move the new ends back the other way, hence the rotation.  That turned out not to be necessary.
I don't think efficiency is a big concern because this isn't going to happen very often.  Having to do the dot-product every time just in case this unusual thing might have cropped up has had more of an impact on efficiency, I would imagine.  Still, there's no harm in keeping it simpler.

**Review by greglandrum — APPROVED** [review]
LGTM
