### PR TITLE
Don't do the fancy merging of solid wedges and bond lines for triple …

### LINKED ISSUE #7620: Bad solid wedge to alkyne group
**Describe the bug**
image

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import rdmolops
from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
IPythonConsole.molSize = (300,300)
rdDepictor.SetPreferCoordGen(True)
print(rdBase.rdkitVersion)
mol = rdmolops.AddHs(Chem.MolFromSmiles('O=C1Nc2ccc(Cl)cc2[C@@](C#CC2CC2)(C(F)(F)(F))O1'))
mol
```

**Expected behavior**
The wedged bond should be a solid triangle.

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.4
 - OS: [e.g. Ubuntu 20.04] macOS
 - Python version (if relevant): 
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? ronda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
The dashed wedge alternative is fine.  Some orientations/layouts of the molecule give better or worse wedges.
I will attempt to get a fix in in the next week.

### PR DESCRIPTION
**Pull request by DavidACosgrove**
…bonds.
#### Reference Issue
Fixes #7620 

#### What does this implement/fix? Explain your changes.
The problem was due to the merging of bond lines incident on the wedge.  It turned out that it was related to #7036 and also manifested itself in that test code when RDDepict::preferCoordGen as true.  I have altered that test instead so there is no explicit test for the fix of #7620.  The fix is to not do the merging at all for triple bonds.  The #7036 fix just skipped it for co-linear bonds.  In the molecule in #7620, the bonds weren't exactly co-linear due to clutter in the layout so the underlying problem re-emerged.

#### Any other comments?
Many of the tests in catch_tests.cpp are affected by changing the global RDDepict::preferCoordGen, depending on the order the tests are run by the test runner.  There is probably something to be said for always putting it back as it was at the outset of each test.  That feels like it should be a separate PR, however.

### CODE REVIEW

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 1]
```diff
@@ -3231,9 +3231,16 @@ void DrawMol::findOtherBondVecs(const Atom *atom, const Atom *otherAtom,
...
     auto thirdAtom = otherNeighbor(atom, otherAtom, i - 1, *drawMol_);
-    Point2D const &at1_cds = atCds_[atom->getIdx()];
-    Point2D const &at2_cds = atCds_[thirdAtom->getIdx()];
-    otherBondVecs.push_back(at1_cds.directionVector(at2_cds));
+    auto bond =
+        drawMol_->getBondBetweenAtoms(atom->getIdx(), thirdAtom->getIdx());
+    // Don't do anything if the wedge is to a triple bond.  It gets
+    // really messed up especially if the two bonds aren't exactly
+    // co-linear which happens sometimes in a cluttered layout (Github 7620).
+    if (bond->getBondType() != 3) {
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:3239]:
```suggestion
    if (bond->getBondType() != Bond::BondType::TRIPLE) {
```

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 2]
```diff
@@ -3248,7 +3255,12 @@ void DrawMol::adjustBondsOnSolidWedgeEnds() {
           otherNeighbor(bond->getEndAtom(), bond->getBeginAtom(), 0, *drawMol_);
       auto bond1 = drawMol_->getBondBetweenAtoms(bond->getEndAtomIdx(),
                                                  thirdAtom->getIdx());
-      // If the bonds a co-linear, don't do anything (Github7036)
+      // Don't do anything if it's a triple bond.  Moving the central
+      // line to the wedge corner is clearly wrong.
+      if (bond1->getBondType() == 3) {
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:3260]:
```suggestion
      if (bond1->getBondType() == Bond::BondType::TRIPLE) {
```

File: Code/GraphMol/MolDraw2D/catch_tests.cpp [hunk 3]
```diff
@@ -9406,16 +9407,24 @@ TEST_CASE("Github7036 - triple bond to wedge not right") {
   // ends in the wrong place when the incident bond is
   // a wedge.  Wedge to single bond included for visual
   // check that that isn't broken in the fix.
+  // Make sure it works for both coords generators.
+  // Tracking down issue 7620 demonstrated this was not
+  // always the case.
```
Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/catch_tests.cpp:9412]: This is ok as is, but it would have been a bit nicer to include a CXSMILES with coordinates (or a mol block) for a molecule with the layout that triggered the bug.

**Review by greglandrum — CHANGES_REQUESTED** [review]
small changes requested

File: Code/GraphMol/MolDraw2D/catch_tests.cpp (hunk 3 above)
Comment (DavidACosgrove) [reply Code/GraphMol/MolDraw2D/catch_tests.cpp:9412]: This and #7739 are pretty much the same bug. I’ll send a fix in for that that merges this one in as well.  They will conflict if merged separately in any case. I’ll add the extra test case at that point as well. An algorithmic test will be fiddly- this is obviously wrong visually but less clear to pick out on the SVG.

Comment (DavidACosgrove) [reply Code/GraphMol/MolDraw2D/catch_tests.cpp:9412]: Scrap that - I've decided to leave them as 2 PRs as they are a bit different.  This one should probably be merged first, since it's already reviewed.  I expect there'll be a conflict when merging the 2nd.  Sorry for the mucking about.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @DavidACosgrove
