### PR TITLE
Fixes Issue 6437

### LINKED ISSUE #6437: Removing Hs on a pyrrol-like structure throws kekulization error
A minimal reproducible:

```python
In [1]:
   ...: from rdkit import Chem
   ...: 
   ...: mb = """
   ...:      RDKit          3D
   ...: 
   ...:   0  0  0  0  0  0  0  0  0  0999 V3000
   ...: M  V30 BEGIN CTAB
   ...: M  V30 COUNTS 10 10 0 0 1
   ...: M  V30 BEGIN ATOM
   ...: M  V30 1 C 3.080550 -0.830350 2.955935 0
   ...: M  V30 2 C 1.665136 -0.838141 2.947220 0
   ...: M  V30 3 C 1.247504 0.474081 2.948961 0
   ...: M  V30 4 C 2.361202 1.272855 2.958419 0 CHG=-1
   ...: M  V30 5 C 3.483658 0.486391 2.962730 0
   ...: M  V30 6 H 2.355611 2.284759 2.961704 0
   ...: M  V30 7 H 1.020283 -1.707337 2.940409 0
   ...: M  V30 8 H 0.256169 0.906820 2.944294 0
   ...: M  V30 9 H 3.734967 -1.692394 2.957125 0
   ...: M  V30 10 H 4.470152 0.930015 2.970242 0
   ...: M  V30 END ATOM
   ...: M  V30 BEGIN BOND
   ...: M  V30 1 1 2 1
   ...: M  V30 2 2 3 2
   ...: M  V30 3 1 4 3
   ...: M  V30 4 2 5 1
   ...: M  V30 5 1 5 4
   ...: M  V30 6 1 6 4
   ...: M  V30 7 1 7 2
   ...: M  V30 8 1 8 3
   ...: M  V30 9 1 9 1
   ...: M  V30 10 1 10 5
   ...: M  V30 END BOND
   ...: M  V30 END CTAB
   ...: M  END"""
   ...: 
   ...: m = Chem.MolFromMolBlock(mb, removeHs=False)
   ...: 
   ...: m = Chem.RemoveHs(m)
   ...: 
[16:20:21] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
---------------------------------------------------------------------------
KekulizeException                         Traceback (most recent call last)
Cell In[4], line 39
      4 mb = """
      5      RDKit          3D
      6 
   (...)
     34 M  V30 END CTAB
     35 M  END"""
     37 m = Chem.MolFromMolBlock(mb, removeHs=False)
---> 39 m = Chem.RemoveHs(m)

KekulizeException: Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
```

The issue doesn't happen for true pyrrol, we have code in place to handle that specific case.

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #6437

The issue with pyrrole and pseudo-pyrroles like the one described in the issue is that the problematic atom has to satisfy a valence of 3 during kekulization (note that to trigger the issue, the mol has to start in the aromatic form!), and this can happen in two ways:
- With a single and a double bond to neighboring atoms in the aromatic cycle.
- With three single bonds, 2 to neighbors in the aromatic cycle, and one to a H.

If the input mol has the H atom attached, and we remove it without turning it into explicit H, then the kekulization routine will not have any way to disambiguate between both possibilities, and will therefore fail.

As mentioned in the issue, we have code in place to add the explicit H to the pyrrole case, so I'm just adding an extra case to the check. This case checks for the conditions above: we only hit it for heavy atoms attached to H atoms being removed, and the only way to satisfy a valence of 3 with 1 single + 2 aromatic bonds is that these kekulize into single bonds.

### CODE REVIEW

File: Code/GraphMol/AddHs.cpp [hunk 1]
```diff
@@ -136,6 +136,22 @@ std::map<unsigned int, std::vector<unsigned int>> getIsoMap(const ROMol &mol) {
   return isoMap;
 }
 
+bool is_atom_n_pyrrol_like(const ROMol &mol, const Atom *atom) {
```
Comment (greglandrum) [inline Code/GraphMol/AddHs.cpp:139]: The name of this keeps confusing me, so maybe we can change it.
I know the current naming is because the original special case was pyrroles, but we're beyond that and "pyrrole-like" sounds to me like it needs to be a heteroatom.

How about: `may_need_extra_H()`?

**Review by greglandrum — APPROVED** [review]
LGTM
