### PR TITLE
Fixes #5883

### LINKED ISSUE #5883: Conformer Generation Fails if Stereocenters are Specified
**Describe the bug**
RDKit doesn't seem to be able to generate conformers for a three-membered ring with two nitrogen atoms if stereocenters are specified.

**To Reproduce**

```python
from rdkit.Chem import AllChem

mol = AllChem.AddHs(AllChem.MolFromSmiles("N1NC1"))

c1 = AllChem.Mol(mol, quickCopy=False)
AllChem.AssignStereochemistry(c1, flagPossibleStereoCenters=False)

for isomer in AllChem.EnumerateStereoisomers(c1):
    AllChem.EmbedMolecule(isomer)
    assert isomer.GetNumConformers() == 1

c2 = AllChem.Mol(mol, quickCopy=False)
AllChem.AssignStereochemistry(c2, flagPossibleStereoCenters=True)  # flagPossibleStereoCenters

for isomer in AllChem.EnumerateStereoisomers(c2):
    AllChem.EmbedMolecule(isomer)
    assert isomer.GetNumConformers() == 1  # Fails
```

**Configuration**
 - RDKit version: 2022.09.1, py38h5acb366_1, conda-forge
 - OS: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by greglandrum**
The fix here is to recognize that the expected chiral volume for three-coordinate atoms is smaller than that for four-coordinate atoms.
The corrected value here is empirical

### CODE REVIEW

**Comment by greglandrum** [comment]
@sriniker can you please take a look at this very small, conformer-generation related, PR?

**Review by sriniker — APPROVED** [review]
This looks good to me.

**Review by sriniker — APPROVED** [review]

**Review by bp-kelley — APPROVED** [review]

File: Code/GraphMol/DistGeomHelpers/Embedder.cpp [hunk 1]
```diff
@@ -1016,21 +1017,29 @@ void findChiralSets(const ROMol &mol, DistGeom::VECT_CHIRALSET &chiralCenters,
...
           nbrs.insert(nbrs.end(), atom->getIdx());
         }
 
         // now create a chiral set and set the upper and lower bound on the
         // volume
         if (chiralType == Atom::CHI_TETRAHEDRAL_CCW) {
           // positive chiral volume
-          auto *cset = new DistGeom::ChiralSet(atom->getIdx(), nbrs[0], nbrs[1],
-                                               nbrs[2], nbrs[3], 5.0, 100.0);
+          auto *cset =
```
Comment (bp-kelley) [inline Code/GraphMol/DistGeomHelpers/Embedder.cpp:1034]: I'm assuming here that CHI_TETRAHEDRAL_CCW assumes nbrs.size() == 4 but perhaps this should be a runtime check in case someone futzed with the molecule.

Comment (bp-kelley) [reply Code/GraphMol/DistGeomHelpers/Embedder.cpp:1034]: (This isn't related to this PR directly)

Comment (greglandrum) [reply Code/GraphMol/DistGeomHelpers/Embedder.cpp:1034]: You can have tetrahedral stereo with only three neighbors. There's a test a few lines higher up that makes sure that `nbrs` has four members: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/DistGeomHelpers/Embedder.cpp#L1019
