### PR TITLE
Fix for Issue #2174.

### LINKED ISSUE #2174: PgSQL: mol_to_svg() changes input molecule.
**Description:**

Latest RDKit source as of 2018-11-24.

mol_to_svg() changes the input mol, e.g. do this:
```
with t as (
  select 'C[C@H]1CC[C@H]2CCCCC12'::mol as the_mol
) 
select
    substring(mol_to_ctab(the_mol)::text, 1, 65) as before_mol
  , substring(mol_to_svg(the_mol)::text, 1, 20) as the_svg
  , substring(mol_to_ctab(the_mol)::text, 1, 65) as after_mol
  from t;
```
and the result is:
```
               before_mol                |       the_svg        |                after_mol                
-----------------------------------------+----------------------+-----------------------------------------
                                        +| <?xml version='1.0'  |                                        +
      RDKit          2D                 +|                      |      RDKit          2D                 +
                                        +|                      |                                        +
  10 11  0  0  0  0  0  0  0  0999 V2000+|                      |  11 12  0  0  0  0  0  0  0  0999 V2000+
                                         |                      | 
(1 row)
```
Note the change of the atom+bond count from '10 11' to '11 12'.

Fix is known. Pull request is incoming.

### PR DESCRIPTION
**Pull request by janholstjensen**
#### Reference Issue
Fixes #2174

#### What does this implement/fix? Explain your changes.
Change MolGetSVG to work on a copy of the input molecule.

### CODE REVIEW

File: Code/PgSQL/rdkit/adapter.cpp [hunk 1]
```diff
@@ -688,7 +688,14 @@ extern "C" CROMol MolAdjustQueryProperties(CROMol i, const char *params) {
...
 extern "C" char *MolGetSVG(CROMol i, unsigned int w, unsigned int h,
                            const char *legend, const char *params) {
-  RWMol *im = (RWMol *)i;
+  // SVG routines need an RWMol since they change the
+  // molecule as they prepare it for drawing. We don't
+  // want a plain SQL function (mol_to_svg) to have
+  // unexpected side effects, so take a copy and render
+  // (and change) that.
+  const ROMol *input_mol = (ROMol *)i;
+  RWMol input_copy = *input_mol;
```
Comment (bp-kelley) [inline Code/PgSQL/rdkit/adapter.cpp]: I would prefer using a copy constructor

```
RWMol input_copy(*input_mol);
```

but otherwise this code appears to be fine.

Comment (bp-kelley) [reply Code/PgSQL/rdkit/adapter.cpp]: @greglandrum Perhaps we should also have a const drawing convenience API?

Comment (greglandrum) [reply Code/PgSQL/rdkit/adapter.cpp]: @bp-kelley : you mean something that takes a const mol and calls `prepareMolForDrawing()` with default args?

Comment (bp-kelley) [reply Code/PgSQL/rdkit/adapter.cpp]: @greglandrum Yes.  I think we hand roll things like that in the wrappers.

Comment (greglandrum) [reply Code/PgSQL/rdkit/adapter.cpp]: makes sense. I will put something in this weekend.

**Comment by greglandrum** [comment]
I made the changes @bp-kelley suggested and will merge the PR after the travis builds complete.

**Comment by janholstjensen** [comment]
Great. Thanks.

**Comment by greglandrum** [comment]
Thanks for contributing the bug fix @janholstjensen
