### PR TITLE
Fixes #8304

### LINKED ISSUE #8304: addHs should ignore queries
**Describe the bug**
RDKit's addHs operation will happily add explicit hydrogens to atoms attached to query bonds.

**To Reproduce**
A goofy example, calling addHs to 
```

     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 4 3 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -19.424242 9.181818 0.000000 0
M  V30 2 C -18.125204 9.931818 0.000000 0
M  V30 3 C -16.826166 9.181818 0.000000 0
M  V30 4 C -15.527128 9.931818 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 8 2 3
M  V30 3 1 3 4
M  V30 END BOND
M  V30 END CTAB
M  END
$$$$
```

Image

**Expected behavior**
The addHs operation should not add hydrogens to any atoms with queries or attached to a query bond.

### PR DESCRIPTION
**Pull request by greglandrum**
This does not change the default behavior of the code, but instead introduces a new option to AddHs that allows adding Hs to query atoms to be toggled off.

Rather than adding YA parameter to the standard AddHs call, I introduced an `AddHsParameters` struct and put the new option there.

### CODE REVIEW

File: Code/GraphMol/MolOps.h [hunk 1]
```diff
@@ -212,25 +234,32 @@ RDKIT_GRAPHMOL_EXPORT unsigned int getMolFragsWithQuery(
...
-                                   const UINT_VECT *onlyOnAtoms = nullptr,
-                                   bool addResidueInfo = false);
+inline ROMol *addHs(const ROMol &mol, bool explicitOnly = false,
+                    bool addCoords = false,
+                    const UINT_VECT *onlyOnAtoms = nullptr,
+                    bool addResidueInfo = false) {
+  AddHsParameters ps{explicitOnly, addCoords, addResidueInfo};
+  RWMol *res = new RWMol(mol);
+  addHs(*res, ps, onlyOnAtoms);
+  return static_cast<ROMol *>(res);
```
Comment (ricrogz) [inline Code/GraphMol/MolOps.h:244]: Can we use a `std::unique_ptr<RWMol>` and `release()`, just in case of errors?
(I'm already seeing myself making this change in the future, after an asan run...)

```suggestion
  std::unique_ptr<RWMol> res{new RWMol(mol)};
  addHs(res.get(), ps, onlyOnAtoms);
  return static_cast<ROMol *>(res.release());
```

File: Code/GraphMol/MolOps.h [hunk 2]
```diff
@@ -212,25 +234,32 @@ RDKIT_GRAPHMOL_EXPORT unsigned int getMolFragsWithQuery(
...
 //! coordinates based on the geometry of the neighbor.
 /*!
-    NOTE: this sets appropriate coordinates in all of the molecule's conformers.
-    \param mol       the molecule the atoms belong to
-    \param idx       index of the terminal atom whose coordinates are set
-    \param otherIdx  index of the bonded neighbor atom
+    NOTE: this sets appropriate coordinates in all of the molecule's
+   conformers. \param mol       the molecule the atoms belong to \param idx
+   index of the terminal atom whose coordinates are set \param otherIdx  index
+   of the bonded neighbor atom
```
Comment (ricrogz) [inline Code/GraphMol/MolOps.h:262]: Am I seeing github diff artifact, or were those `\param` pulled into the previous line ?

If it's real, we should probably put the `\param`s back into new lines.

File: Code/GraphMol/MolOps.h [hunk 3]
```diff
@@ -241,13 +270,10 @@ RDKIT_GRAPHMOL_EXPORT void setTerminalAtomCoords(ROMol &mol, unsigned int idx,
...
-   are removed
-         from the graph, the heavy atom to which they are bound will have its
-   counter of
-         explicit Hs increased.
-    \param sanitize:  (optional) If this is \c true, the final molecule will be
-   sanitized
+    \param updateExplicitCount  (optional) If this is \c true, when explicit
+   Hs are removed from the graph, the heavy atom to which they are bound will
+   have its counter of explicit Hs increased. \param sanitize:  (optional) If
+   this is \c true, the final molecule will be sanitized
```
Comment (ricrogz) [inline Code/GraphMol/MolOps.h:276]: More artifacts? (same as above).

File: Code/GraphMol/AddHs.cpp [hunk 4]
```diff
@@ -516,8 +516,21 @@ void setTerminalAtomCoords(ROMol &mol, unsigned int idx,
   }
 }
 
-void addHs(RWMol &mol, bool explicitOnly, bool addCoords,
-           const UINT_VECT *onlyOnAtoms, bool addResidueInfo) {
+namespace {
+bool isQueryAtom(const RWMol &mol, const Atom &atom) {
```
Comment (ricrogz) [inline Code/GraphMol/AddHs.cpp:520]: hm, I'm not quite happy about this function name (as we also return `true` for regular atoms with query bonds). But I can't think of anything better...

File: Code/GraphMol/MolOps.h [hunk 5]
```diff
@@ -212,25 +234,34 @@ RDKIT_GRAPHMOL_EXPORT unsigned int getMolFragsWithQuery(
...
-                                   bool addCoords = false,
-                                   const UINT_VECT *onlyOnAtoms = nullptr,
-                                   bool addResidueInfo = false);
+inline ROMol *addHs(const ROMol &mol, bool explicitOnly = false,
+                    bool addCoords = false,
+                    const UINT_VECT *onlyOnAtoms = nullptr,
+                    bool addResidueInfo = false) {
+  AddHsParameters ps{explicitOnly, addCoords, addResidueInfo};
+  std::unique_ptr<RWMol> res{new RWMol(mol)};
+  addHs(res.get(), ps, onlyOnAtoms);
```
Comment (ricrogz) [inline Code/GraphMol/MolOps.h:243]: My bad, this should have stayed as:
```suggestion
  addHs(*res, ps, onlyOnAtoms);
```

Comment (greglandrum) [reply Code/GraphMol/MolOps.h]: > My bad, this should have stayed as:

yeah, well, I could have noticed that too.
anyway... it's fixed now

**Comment by greglandrum** [comment]
@ricrogz this should now have all requested changes

**Review by ricrogz — APPROVED** [review]
LGTM
