### PR TITLE
Fixes #6492

### LINKED ISSUE #6492: In place transforms incorrectly change atomic numbers
**Describe the bug**

Here's the reproducible:
```
In [7]: rxn = rdChemReactions.ReactionFromSmarts('[n;+0!H0:1]:[a:2]:[a:3]:[c:4]=[N!$(*[O-]),O;+1H0:5]>>[n+1:1]:[*:2]:[*:3]:[*:4]-[*+0:5]')

In [8]: rxn.Initialize()

In [9]: m = Chem.MolFromSmiles('[nH]1ccc(=[N+](C)C)cc1')

In [10]: rxn.RunReactantInPlace(m)
Out[10]: True

In [11]: Chem.MolToSmiles(m)
Out[11]: 'CN(C)*1cc[nH+]cc1'
```
The dummy atom in the products should result in the atom type being preserved.

**Configuration (please complete the following information):**
 - RDKit version: release and master
 - OS: all

### PR DESCRIPTION
**Pull request by greglandrum**
This is a simple fix brought over from #6491

### CODE REVIEW

File: Code/GraphMol/ChemReactions/ReactionRunner.cpp [hunk 1]
```diff
@@ -1725,14 +1726,6 @@ bool updateBondsModifiedByReaction(
...
       }
     }
-
-    if (rAtom->getAtomicNum() != pAtom->getAtomicNum()) {
-      atom->setAtomicNum(pAtom->getAtomicNum());
-      molModified = true;
-    }
-    if (ReactionRunnerUtils::updatePropsFromImplicitProps(pAtom, atom)) {
-      molModified = true;
-    }
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/ReactionRunner.cpp:1735]: This block of code should never have been here. It's just duplicating the work which is being done at l1584
