### PR TITLE
Fixes crashes when using bad smiles in the cached smiles holders

### LINKED ISSUE #3797: SubstructLibrary Cached Smiles Holders have bad behavior with bad smiles
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

The same behavior is observed through CachedSmilesHolder and CachedTrustedSmilesHolder
```
>>> from rdkit.Chem import rdSubstructLibrary
>>> holder = rdSubstructLibrary.CachedTrustedSmilesMolHolder()
>>> for s in ["dsafsdf"]*100:
...    holder.AddSmiles(s)
>>> sss = rdSubstructLibrary.SubstructLibrary(holder)
>>> sss.GetMatches(Chem.MolFromSmiles("C"))
<spew>
Segmentation fault: 11
```

**Expected behavior**
Not seg faulting.

**Configuration (please complete the following information):**
 - RDKit version: '2020.09.1'
 - OS: all

**Additional context**
I think we can "fix" this by just checking the mol generation inside the threads and skip if a mol isn't created.

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #3797

### CODE REVIEW

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp [hunk 1]
```diff
@@ -122,6 +122,8 @@ void SubSearcher(const ROMol &in_query, const Bits &bits,
     //  returned molecule!
     const boost::shared_ptr<ROMol> &m = mols.getMol(idx);
     ROMol *mol = m.get();
+    if(!mol)
+      continue;
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp:126]:
```suggestion
    if(!mol){
      continue;
    }
```

File: Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp [hunk 2]
```diff
@@ -651,6 +651,29 @@ void testPatternHolder() {
 #endif
 }
 
+void testSegFaultInHolder() {
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp:654]: I think it's worth adding an additional case to this test:
The library contains a mix of reasonable structures and failed structures (along with a check to make sure that the `getMatches()` call returns the correct number of results).

**Review by greglandrum — CHANGES_REQUESTED** [review]
One formatting thing + a request for more thorough testing.

**Review by greglandrum — APPROVED** [review]
