### PR TITLE
Fixes #4504

### LINKED ISSUE #4504: Native 2D layout engine may generate overlapping coordinates
**Describe the bug**
1,1-disubstituted cyclobutanes give rise to overlapping atom coordinates when generating a 2D layout.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG = True
IPythonConsole.drawOptions.addAtomIndices = True

smi = "c1ccccc1CC1(CCC1)Cc1ccccc1"

rdDepictor.SetPreferCoordGen(False)
Chem.MolFromSmiles("c1ccccc1CC1(CCC1)Cc1ccccc1")
```
image

```
rdDepictor.SetPreferCoordGen(True)
Chem.MolFromSmiles("c1ccccc1CC1(CCC1)Cc1ccccc1")
```
image

**Expected behavior**
Atom coordinates should not overlap.

### PR DESCRIPTION
**Pull request by greglandrum**
The fix here is quite simple, but it's a bit buried in a *bunch* of code modernization.
I normally wouldn't do this, but the depiction code hadn't really been touched in years and I kept getting hung up on the C++98-ishness of it while trying to find the bug. Looking through all those code changes is probably a waste of time, but that's your call. :-)

The code change which fixes the bug is here:
https://github.com/greglandrum/rdkit/commit/9d53c37c2cf1e2efd46debd9045b7f3a185f2b7d#diff-6b894e21d231fd69d75e7eedd6607ede20c5698848d915d7891aef660e1f3288R705

The problem occurred when adding a fourth attachment point to an atom where the other 3 attachment points form a T: the resulting 180 degree angle screws up the code which detects where the next ligand should go. This fixes the problem by detecting the situation, trying both possibilities, and placing the ligand on the side where it causes the least collisions.

The other non-modernization change here:
The code wasn't really being particularly well tested: the majority of the tests just check to see that a conformer is created, not that the conformer is right. This commit converts one of those "tests" to actually check that the coordinates haven't changed: https://github.com/greglandrum/rdkit/commit/9098a65ef3527bf270844e7d960b380a33b7d10b#diff-6266054369a94106f70cf2cf98e33576c05a8457cf6323a6b690e32e71c89f58
Hopefully this doesn't break across platforms... the CI tests will show that.

### CODE REVIEW

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 1]
```diff
@@ -292,12 +277,11 @@ EmbeddedFrag::EmbeddedFrag(const RDKit::Bond *dblBond) {
 int EmbeddedFrag::findNumNeigh(const RDGeom::Point2D &pt, double radius) {
   // find the number of atoms in the current embedded system that are within
   // 'radius' of the specified point
-  INT_EATOM_MAP_CI efi;
   int res = 0;
-  for (efi = d_eatoms.begin(); efi != d_eatoms.end(); efi++) {
-    RDGeom::Point2D rloc = efi->second.loc;
+  for (const auto &efi : d_eatoms) {
+    RDGeom::Point2D rloc = efi.second.loc;
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:282]: This doesn't need to be a non-const copy, although I expect it really doesn't matter.

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 2]
```diff
@@ -350,10 +333,9 @@ void EmbeddedFrag::setupNewNeighs() {  // const RDKit::ROMol *mol) {
   PRECONDITION(dp_mol, "");
 
   RDKit::ROMol::ADJ_ITER nbrIdx, endNbrs;
-  INT_EATOM_MAP_I eci;
   d_attachPts.clear();
-  for (eci = d_eatoms.begin(); eci != d_eatoms.end(); eci++) {
-    unsigned int aid = eci->first;
+  for (const auto &eci : d_eatoms) {
+    unsigned int aid = eci.first;
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:338]: You've been consolidating to auto in these cases, might as well be consistent.

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 3]
```diff
@@ -737,6 +691,17 @@ void EmbeddedFrag::addAtomToAtomWithAng(unsigned int aid, unsigned int toAid) {
   rtrans.SetTransform(refLoc, currAngle);
   RDGeom::Point2D currLoc = nb2;
   rtrans.TransformPoint(currLoc);
+  if (fabs(remAngle) - M_PI < 1e-3) {
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:694]: Is this clash detection?

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 4]
```diff
@@ -982,62 +940,58 @@ void EmbeddedFrag::mergeWithCommon(EmbeddedFrag &embObj,
...
-    std::list<EmbeddedFrag> &efrags) {  //, const RDKit::ROMol *mol) {
+void EmbeddedFrag::mergeFragsWithComm(std::list<EmbeddedFrag> &efrags) {
   PRECONDITION(dp_mol, "");
   // first merge any fragments what share atoms in common
-  std::list<EmbeddedFrag>::iterator efri, nfri = efrags.end();
+  auto nfri = efrags.end();
   while (1) {
     RDKit::INT_VECT commAtms;
-    for (efri = efrags.begin(); efri != efrags.end(); efri++) {
+    for (auto efri = efrags.begin(); efri != efrags.end(); ++efri) {
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:994]: any reason not to do
```
for( const auto &efri : efrags)
```

here?

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 5]
```diff
@@ -1070,44 +1023,41 @@ void EmbeddedFrag::expandEfrag(RDKit::INT_LIST &nratms,
...
+        this->addNonRingAtom((nbri), aid);  //, mol);
         // remove this atom we just added from the nnratms list
         nratms.erase(nratmi);
       } else {
         // the neighbor atom must be part of a different embedded fragment -
         // merge that fragment with this one
-        nfri = efrags.end();
-        for (efri = efrags.begin(); efri != efrags.end(); efri++) {
+        auto nfri = efrags.end();
+        for (auto efri = efrags.begin(); efri != efrags.end(); ++efri) {
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1044]: Might as well convert to range, you're right @greglandrum, these are a bit of an eyesore now!

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 6]
```diff
@@ -1296,30 +1231,31 @@ double EmbeddedFrag::mimicDistMatAndDensityCostFunc(
...
     ddata = nullptr;
   }
-  unsigned int na = dp_mol->getNumAtoms();
-  unsigned int dsize = na * (na - 1) / 2;
+  auto na = dp_mol->getNumAtoms();
+  if (na < 2) {
+    return 0;
+  }
+  auto dsize = na * (na - 1) / 2;
   auto *ddata2D = new double[dsize];
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1239]: Switch to unique_ptr?

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 7]
```diff
@@ -1423,69 +1346,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
     nd4 = deg4nodes.size();
   }
 
-  nt = nb + nd4;
+  unsigned int nt = nb + nd4;
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1349]: auto?

File: Code/GraphMol/Depictor/RDDepictor.cpp [hunk 8]
```diff
@@ -125,7 +121,7 @@ std::list<EmbeddedFrag>::iterator _findLargestFrag(
     std::list<EmbeddedFrag> &efrags) {
   std::list<EmbeddedFrag>::iterator mfri;
   int msiz = 0;
-  for (auto efri = efrags.begin(); efri != efrags.end(); efri++) {
+  for (auto efri = efrags.begin(); efri != efrags.end(); ++efri) {
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/RDDepictor.cpp:124]: Possibly use range

File: Code/GraphMol/Depictor/Wrap/testDepictor.py [hunk 9]
```diff
@@ -54,6 +54,8 @@ def compareCoords(m, molFile):
         pos = ci.GetAtomPosition(i)
         opos = co.GetAtomPosition(i)
         if not ptEq(pos, opos):
+            print(Chem.MolToMolBlock(m))
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/Wrap/testDepictor.py:57]: Perhaps also a string indicating what the error is here?

File: Code/GraphMol/Depictor/testDepictor.cpp [hunk 10]
```diff
@@ -33,6 +33,29 @@ typedef boost::tokenizer<boost::char_separator<char>> tokenizer;
...
+  const RDKit::Conformer &conf1 = mol1->getConformer(cid1);
+  const RDKit::Conformer &conf2 = mol2->getConformer(cid2);
+
+  for (unsigned int i = 0; i < nat; i++) {
+    RDGeom::Point3D pt1 = conf1.getAtomPos(i);
+    RDGeom::Point3D pt2 = conf2.getAtomPos(i);
+    pt2 -= pt1;
+
+    if ((fabs(pt2.x) >= tol) || (fabs(pt2.y) >= tol)) {
+      std::cerr << MolToMolBlock(*mol1, cid1) << std::endl;
```
Comment (bp-kelley) [inline Code/GraphMol/Depictor/testDepictor.cpp:50]: Perhaps a string indicated what error occurred?

**Review by bp-kelley — APPROVED** [review]

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 3 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:694]: This detects the condition which could lead to the clashes.
The clashes themselves are caught in the calls to `findNumNeigh()` a couple lines down

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 4 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:994]: yeah, we need the iterator to set `nfri` a couple lines down

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 5 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:1044]: same story, need the iterator later

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 6 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:1239]: it's added to a smart pointer on the next line

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 7 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:1349]: tried that: ends up being a size_t and producing warnings later.

File: Code/GraphMol/Depictor/RDDepictor.cpp (hunk 8 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/RDDepictor.cpp:124]: same story with using the iterator elsewhere

File: Code/GraphMol/Depictor/Wrap/testDepictor.py (hunk 9 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/Wrap/testDepictor.py:57]: I thought about that, but it's likely that there are going to be a lot of mismatched atom positions when this happens and this would only show the first. I'm 99% sure that you're going to have to look at the structure anyway in order to figure out what's going on, so it just didn't seem worth it.
I can add it if you really think it'll be helpful

File: Code/GraphMol/Depictor/testDepictor.cpp (hunk 10 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/testDepictor.cpp:50]: same comment here

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 2 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:338]: yep. will do

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:282]: good catch

File: Code/GraphMol/Depictor/Wrap/testDepictor.py (hunk 9 above)
Comment (bp-kelley) [reply Code/GraphMol/Depictor/Wrap/testDepictor.py:57]: I agree it probably won't be too useful, but I like a bit of verbiage when reporting test errors.

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:282]: I think these are going to end up optimized into register anyway...

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 11]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
-    for (fi = 0; fi < nPerSample; ++fi) {
+    for (auto fi = 0u; fi < nPerSample; ++fi) {
       unsigned int ri = intRandomSrc();
       // if ri is less than the number of rotatable bonds (nb), we will flip a
       // rot bond
       if (ri < nb) {
-        bi = rotBonds[ri];
-        this->flipAboutBond(bi);
-
+        this->flipAboutBond(rotBonds[ri]);
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1371]:
```suggestion
        this->flipAboutBond(rotBonds.at(ri));
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 12]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
       } else {  // ri is >= nb we permute the bonds at a deg 4 node
         unsigned int d4i =
             ri - nb;  // so we will permute at the 'di'th degree 4 node
-        ai = deg4nodes[d4i];
+        auto ai = deg4nodes[d4i];
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1375]:
```suggestion
        auto ai = deg4nodes.at(d4i);
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 13]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
         // collect the locations for the neighbors
         VECT_C_POINT nbrLocs;
-        for (RDKit::INT_VECT_CI aci = deg4NbrAids[d4i].begin();
-             aci != deg4NbrAids[d4i].end(); aci++) {
-          nbrLocs.push_back(&(d_eatoms[*aci].loc));
+        for (auto aci : deg4NbrAids[d4i]) {
+          nbrLocs.push_back(&(d_eatoms[aci].loc));
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1379]:
```suggestion
          nbrLocs.push_back(&(d_eatoms.at(aci).loc));
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 14]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
         }
-        INT_PAIR_VECT bndPairs = findBondsPairsToPermuteDeg4(
-            d_eatoms[ai].loc, deg4NbrBids[d4i], nbrLocs);
+        auto bndPairs = findBondsPairsToPermuteDeg4(d_eatoms[ai].loc,
+                                                    deg4NbrBids[d4i], nbrLocs);
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1382]:
```suggestion
        auto bndPairs = findBondsPairsToPermuteDeg4(d_eatoms.at(ai).loc,
                                                    deg4NbrBids.at(d4i), nbrLocs);
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 15]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
+        auto rval = RDKit::getRandomVal();
         unsigned int fbi = 0;
         if (rval > 0.5) {
           fbi = 1;
         }
-        unsigned int aid1, aid2;
-        aid1 = dp_mol->getBondWithIdx(bndPairs[fbi].first)->getOtherAtomIdx(ai);
-        aid2 =
+        auto aid1 =
+            dp_mol->getBondWithIdx(bndPairs[fbi].first)->getOtherAtomIdx(ai);
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1390]:
```suggestion
            dp_mol->getBondWithIdx(bndPairs.at(fbi).first)->getOtherAtomIdx(ai);
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 16]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
+        auto aid2 =
             dp_mol->getBondWithIdx(bndPairs[fbi].second)->getOtherAtomIdx(ai);
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1392]:
```suggestion
            dp_mol->getBondWithIdx(bndPairs.at(fbi).second)->getOtherAtomIdx(ai);
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 17]
```diff
@@ -1423,69 +1345,68 @@ void EmbeddedFrag::randomSampleFlipsAndPermutations(
...
+      for (const auto &efi : d_eatoms) {
+        bestCrdMap[efi.first] = efi.second.loc;
       }
     }
   }
   // now copy the best coordinates to the fragment
-  for (efi = d_eatoms.begin(); efi != d_eatoms.end(); efi++) {
-    efi->second.loc = bestCrdMap[efi->first];
+  for (auto &efi : d_eatoms) {
+    efi.second.loc = bestCrdMap[efi.first];
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1409]:
```suggestion
    efi.second.loc = bestCrdMap.at(efi.first);
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 18]
```diff
@@ -1593,96 +1511,85 @@ void _recurseDegTwoRingAtoms(unsigned int aid, const RDKit::ROMol *mol,
...
-    int tmp = begAid;
-    begAid = endAid;
-    endAid = tmp;
+    std::swap(begAid, endAid);
   }
 
-  RDGeom::Point2D begLoc = d_eatoms[begAid].loc;
-  RDGeom::Point2D endLoc = d_eatoms[endAid].loc;
+  const auto &begLoc = d_eatoms[begAid].loc;
+  const auto &endLoc = d_eatoms[endAid].loc;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1570]:
```suggestion
  const auto &begLoc = d_eatoms.at(begAid).loc;
  const auto &endLoc = d_eatoms.at(endAid).loc;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 19]
```diff
@@ -1769,16 +1663,15 @@ void EmbeddedFrag::openAngles(const double *dmat, unsigned int aid1,
...
   PRECONDITION(dp_mol, "");
   PRECONDITION(dmat, "");
-  unsigned int deg1 = getDepictDegree(dp_mol->getAtomWithIdx(aid1));
-  unsigned int deg2 = getDepictDegree(dp_mol->getAtomWithIdx(aid2));
-  bool fixed1 = d_eatoms[aid1].df_fixed;
-  bool fixed2 = d_eatoms[aid2].df_fixed;
+  auto deg1 = getDepictDegree(dp_mol->getAtomWithIdx(aid1));
+  auto deg2 = getDepictDegree(dp_mol->getAtomWithIdx(aid2));
+  auto fixed1 = d_eatoms[aid1].df_fixed;
+  auto fixed2 = d_eatoms[aid2].df_fixed;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1669]:
```suggestion
  auto fixed1 = d_eatoms.at(aid1).df_fixed;
  auto fixed2 = d_eatoms.at(aid2).df_fixed;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 20]
```diff
@@ -1794,12 +1687,9 @@ void EmbeddedFrag::openAngles(const double *dmat, unsigned int aid1,
...
   }
 
-  // std::cerr << " openAngles: " << aid1 << "-" << aidA << "-" << aidB << "-"
-  //           << aid2 << "  type:" << type << std::endl;
-
-  RDGeom::Point2D v2 = d_eatoms[aid1].loc - d_eatoms[aidA].loc;
-  RDGeom::Point2D v1 = d_eatoms[aidB].loc - d_eatoms[aidA].loc;
-  double cross = (v1.x) * (v2.y) - (v1.y) * (v2.x);
+  auto v2 = d_eatoms[aid1].loc - d_eatoms[aidA].loc;
+  auto v1 = d_eatoms[aidB].loc - d_eatoms[aidA].loc;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1691]:
```suggestion
  auto v2 = d_eatoms.at(aid1).loc - d_eatoms.at(aidA).loc;
  auto v1 = d_eatoms.at(aidB).loc - d_eatoms.at(aidA).loc;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 21]
```diff
@@ -1832,96 +1722,78 @@ void EmbeddedFrag::openAngles(const double *dmat, unsigned int aid1,
...
-          if (doneBonds.find(*ri) == doneBonds.end()) {
-            doneBonds[*ri] = 1;
+      auto cAids = colls[0];
+      auto rotBonds = getRotatableBonds(*dp_mol, cAids.first, cAids.second);
+      auto prevDensity = this->totalDensity();
+      for (auto ri : rotBonds) {
+        if ((doneBonds.find(ri) == doneBonds.end()) ||
+            (doneBonds[ri] < NUM_BONDS_FLIPS)) {
+          if (doneBonds.find(ri) == doneBonds.end()) {
+            doneBonds[ri] = 1;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1747]:
```suggestion
        auto doneBondsRiIt = doneBonds.find(ri);
        if ((doneBondsRiIt == doneBonds.end()) ||
            (doneBondsRiIt->second < NUM_BONDS_FLIPS)) {
          if (doneBondsRiIt == doneBonds.end()) {
            doneBonds[ri] = 1;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 22]
```diff
@@ -1832,96 +1722,78 @@ void EmbeddedFrag::openAngles(const double *dmat, unsigned int aid1,
...
           } else {
-            doneBonds[*ri] += 1;
+            doneBonds[ri] += 1;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1749]:
```suggestion
            doneBondsRiIt->second += 1;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 23]
```diff
@@ -1931,17 +1803,17 @@ void EmbeddedFrag::removeCollisionsShortenBonds() {
...
     // find out which of the two offending atoms we want to move
     // we will use the one with the smallest degree
-    int aid1 = cAids.first;
-    int aid2 = cAids.second;
-    bool fixed1 = d_eatoms[aid1].df_fixed;
-    bool fixed2 = d_eatoms[aid2].df_fixed;
+    auto aid1 = cAids.first;
+    auto aid2 = cAids.second;
+    auto fixed1 = d_eatoms[aid1].df_fixed;
+    auto fixed2 = d_eatoms[aid2].df_fixed;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1816]:
```suggestion
    auto fixed1 = d_eatoms.at(aid1).df_fixed;
    auto fixed2 = d_eatoms.at(aid2).df_fixed;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 24]
```diff
@@ -1971,26 +1841,23 @@ void EmbeddedFrag::removeCollisionsShortenBonds() {
...
       path.pop_front();
 
-      int nOpen = _anyNonRingBonds(aid1, path, dp_mol);
-      // std::cerr<<"     nOpen: "<<nOpen<<std::endl;
+      auto nOpen = _anyNonRingBonds(aid1, path, dp_mol);
       if (nOpen > 0) {
         if (deg1 == 1) {
-          RDGeom::Point2D loc = d_eatoms[aid1].loc;
-          int aidA = _findDeg1Neighbor(dp_mol, aid1);
+          auto loc = d_eatoms[aid1].loc;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1847]:
```suggestion
          auto loc = d_eatoms.at(aid1).loc;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 25]
```diff
@@ -1971,26 +1841,23 @@ void EmbeddedFrag::removeCollisionsShortenBonds() {
...
-          // std::cerr << "  >>> " << aid1 << " " << loc.length() << std::endl;
           if (loc.length() > .75) {
             loc += d_eatoms[aidA].loc;
             d_eatoms[aid1].loc = loc;
           }
         }
         if (deg2 == 1 && !fixed2) {
-          RDGeom::Point2D loc = d_eatoms[aid2].loc;
-          int aidA = _findDeg1Neighbor(dp_mol, aid2);
+          auto loc = d_eatoms[aid2].loc;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1857]:
```suggestion
          auto loc = d_eatoms.at(aid2).loc;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 26]
```diff
@@ -2011,23 +1878,21 @@ void EmbeddedFrag::removeCollisionsShortenBonds() {
         // - let r1 and r2 be the ring neighbor of the current atom r0
         // - we will find the vector that bisects angle(r1, r0, r2)
         // - we will move r0 along this vector
-        RDKit::INT_VECT_CI rpi;
         RDGeom::INT_POINT2D_MAP moveMap;
-        for (rpi = rPath.begin(); rpi != rPath.end(); rpi++) {
-          if (d_eatoms[*rpi].df_fixed) {
+        for (auto rpi : rPath) {
+          if (d_eatoms[rpi].df_fixed) {
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1883]:
```suggestion
          if (d_eatoms.at(rpi).df_fixed) {
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 27]
```diff
@@ -2011,23 +1878,21 @@ void EmbeddedFrag::removeCollisionsShortenBonds() {
...
             continue;
           }
-          RDGeom::Point2D move;
-          move = d_eatoms[nbrMap[*rpi][0]].loc;
-          move += d_eatoms[nbrMap[*rpi][1]].loc;
+          auto move = d_eatoms[nbrMap[rpi][0]].loc;
+          move += d_eatoms[nbrMap[rpi][1]].loc;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1887]:
```suggestion
          move += d_eatoms.at(nbrMap.at(rpi).at(1)).loc;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 28]
```diff
@@ -2011,23 +1878,21 @@ void EmbeddedFrag::removeCollisionsShortenBonds() {
...
           move *= 0.5;
-          move -= d_eatoms[*rpi].loc;
+          move -= d_eatoms[rpi].loc;
```
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:1889]:
```suggestion
          move -= d_eatoms.at(rpi).loc;
```

File: Code/GraphMol/Depictor/RDDepictor.cpp [hunk 29]
```diff
@@ -44,19 +44,18 @@ void embedFusedSystems(const RDKit::ROMol &mol,
...
     // embed all ring and fused ring systems
-    fused.resize(0);
+    RDKit::INT_VECT fused;
     RingUtils::pickFusedRings(curr, neighMap, fused, fusDone);
     RDKit::VECT_INT_VECT frings;
     frings.reserve(fused.size());
-    for (RDKit::INT_VECT_CI rid = fused.begin(); rid != fused.end(); ++rid) {
-      frings.push_back(arings[*rid]);
+    for (auto rid : fused) {
+      frings.push_back(arings[rid]);
```
Comment (ptosco) [inline Code/GraphMol/Depictor/RDDepictor.cpp:58]:
```suggestion
      frings.push_back(arings.at(rid));
```

File: Code/GraphMol/Depictor/RDDepictor.cpp [hunk 30]
```diff
@@ -231,11 +227,10 @@ void computeInitialCoords(RDKit::ROMol &mol,
...
       // non embedded atoms use them to start a fragment
-      int mrank, rank;
-      mrank = static_cast<int>(RDKit::MAX_INT);
-      RDKit::INT_LIST_I nri, mnri;
-      for (nri = nratms.begin(); nri != nratms.end(); nri++) {
-        rank = atomRanks[*nri];
+      auto mrank = static_cast<int>(RDKit::MAX_INT);
+      RDKit::INT_LIST_I mnri;
+      for (auto nri = nratms.begin(); nri != nratms.end(); ++nri) {
+        auto rank = atomRanks[*nri];
```
Comment (ptosco) [inline Code/GraphMol/Depictor/RDDepictor.cpp:233]:
```suggestion
        auto rank = atomRanks.at(*nri);
```

**Comment by greglandrum** [comment]
> I hope I haven't done too many mistakes with my revision suggestions.

I'm looking through these now. I'm curious about all of the suggestions to switch from `d_eatoms[key]`->`d_eatoms.at(key)` when `d_eatoms` isn't const. Why do that?

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 31]
```diff
@@ -737,6 +690,17 @@ void EmbeddedFrag::addAtomToAtomWithAng(unsigned int aid, unsigned int toAid) {
   rtrans.SetTransform(refLoc, currAngle);
   RDGeom::Point2D currLoc = nb2;
   rtrans.TransformPoint(currLoc);
+  if (fabs(remAngle) - M_PI < 1e-3) {
+    RDGeom::Point2D currLoc2 = nb2;
+    rtrans.SetTransform(refLoc, -currAngle);
+    rtrans.TransformPoint(currLoc2);
+    if (findNumNeigh(currLoc, 0.5) > findNumNeigh(currLoc2, 0.5)) {
+      currLoc = currLoc2;
+      currAngle *= -1;
```
[the remark this answers is not in the document]
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:699]: why is this better?

[the remark this answers is not in the document]
Comment (ptosco) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:699]: My thinking was that it's a 1-bit change as opposed to a multiplication. I realize that the compiler might end up generating identical code, or anyway make almost no difference. If you think it's worthless, just reject it.

**Comment by ptosco** [comment]
@greglandrum
> I'm looking through these now. I'm curious about all of the suggestions to switch from d_eatoms[key]->d_eatoms.at(key) when d_eatoms isn't const. Why do that?

My reasoning was that (hopefully, if I understood the code right in my quick skimming) where I switched to `std::map::at` it was cases where a new item is not supposed to be added to the map, but it should rather be a read-only access. Thus if the key does not exist that would result in an exception, highlighting a possible bug in the code (or maybe bad input), rather than in a default value being created at that key. Again, if you think those are wrong and will rase undue exceptions because a new value is actually supposed to be created, just reject them. In a couple of cases I replaced a `CHECK_INVARIANT` `std::map::find` followed by access with `std::map::operator[]` with `std::map:;at`, and that does seem equivalent and more efficient/concise to me.

**Comment by greglandrum** [comment]
> @greglandrum
> 
> > I'm looking through these now. I'm curious about all of the suggestions to switch from d_eatoms[key]->d_eatoms.at(key) when d_eatoms isn't const. Why do that?
> 
> My reasoning was that (hopefully, if I understood the code right in my quick skimming) where I switched to `std::map::at` it was cases where a new item is not supposed to be added to the map, but it should rather be a read-only access. Thus if the key does not exist that would result in an exception, highlighting a possible bug in the code (or maybe bad input), rather than in a default value being created at that key. Again, if you think those are wrong and will rase undue exceptions because a new value is actually supposed to be created, just reject them. In a couple of cases I replaced a `CHECK_INVARIANT` `std::map::find` followed by access with `std::map::operator[]` with `std::map:;at`, and that does seem equivalent and more efficient/concise to me.

That makes perfect sense. Thanks for the clarification!

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp [hunk 32]
```diff
@@ -489,35 +464,30 @@ RDGeom::Transform2D EmbeddedFrag::computeOneAtomTrans(
 RDGeom::Transform2D EmbeddedFrag::computeTwoAtomTrans(
     unsigned int aid1, unsigned int aid2,
     const RDGeom::INT_POINT2D_MAP &nringCor) {
+  CHECK_INVARIANT(d_eatoms.find(aid1) != d_eatoms.end(), "");
+  CHECK_INVARIANT(d_eatoms.find(aid2) != d_eatoms.end(), "");
```
[the remark this answers is not in the document]
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:468]: I'm going to leave this one in. It's redundant with the changes you suggest below, but it's also a form of documentation of expectations, so I think it's worth keeping around

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 31 above)
[the remark this answers is not in the document]
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:699]: I find the `*=` form to be more immediately understandable, so I'll leave it as is.

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 27 above)
Comment (greglandrum) [reply Code/GraphMol/Depictor/EmbeddedFrag.cpp:1887]:
```suggestion
          move += d_eatoms[nbrMap.at(rpi)[1]].loc;
```

File: Code/GraphMol/Depictor/EmbeddedFrag.cpp (hunk 32 above)
Comment (ptosco) [inline Code/GraphMol/Depictor/EmbeddedFrag.cpp:468]:
```suggestion
  auto aid1It = d_eatoms.find(aid1);
  auto aid2It = d_eatoms.find(aid2);
  CHECK_INVARIANT(aid1It != d_eatoms.end(), "");
  CHECK_INVARIANT(aid2It != d_eatoms.end(), "");
```
