### PR TITLE
Fixes #4266

### LINKED ISSUE #4266: Fallback ring finding failing on molecules with multiple fragments
**Describe the bug**
Given the two SMILES strings `c1ccccc1` and `C123C45C16C21C34C561`, `MolFromSmiles` does not work when they are concatenated, `c1ccccc1.C123C45C16C21C34C561`.

**To Reproduce**
```python
from rdkit import Chem

m1 = Chem.MolFromSmiles('c1ccccc1.C123C45C16C21C34C561')
m2 = Chem.MolFromSmiles('c1ccccc1')
m3 = Chem.MolFromSmiles('C123C45C16C21C34C561')
m4 = Chem.MolFromSmiles('C1CCCCC1.C123C45C16C21C34C561')
m5 = Chem.MolFromSmiles('C123C45C16C21C34C561.c1ccccc1')
```
`m1` is `None`, all the others are valid.
Especially, making benzene non-aromatic (-> cyclohexane) works.
Also, inverting the order works.

RDKit prints the warnings
```
[10:40:23] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:40:23] non-ring atom 0 marked aromatic
```
It looks like the first warning is generated from the second species, and switching to the approximate ring finding algorithm then fails when there is an aromatic ring in the SMILES (?).

**Expected behavior**
`m1` should not be `None`.

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.2
 - OS: Mac
 - Python version (if relevant): 3.7
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? official rdkit

### PR DESCRIPTION
**Pull request by greglandrum**
Just need to be sure to return from the ring finding code after using FastFindRings.

### CODE REVIEW

File: Code/GraphMol/FindRings.cpp [hunk 1]
```diff
@@ -1099,9 +1097,11 @@ int findSSSR(const ROMol &mol, VECT_INT_VECT &res) {
             << "WARNING: could not find number of expected rings. Switching to "
                "an approximate ring finding algorithm."
             << std::endl;
+        mol.getRingInfo()->reset();
         fastFindRings(mol);
         res.clear();
         res = mol.getRingInfo()->atomRings();
+        return rdcast<int>(res.size());
```
Comment (ptosco) [inline Code/GraphMol/FindRings.cpp:1104]: By bailing out early here `FindRings::storeRingsInfo(mol, res)` is not executed. Is that intentional?

**Review by ptosco — APPROVED** [review]
I have put a comment; apart from that it looks good to me.

File: Code/GraphMol/FindRings.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/FindRings.cpp:1104]: yeah, there's no need to do that since `fastFindRings()` has already stored the rings it found.
