### PR TITLE
Fixes #2801

### LINKED ISSUE #2801: rdkit.Ched.rdFMCS.FindMCS generates invalid smarts
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: Linux laptop 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Python version (if relevant): 3.6
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda install rdkit -c rdkit

**Description:**

rdkit.Ched.rdFMCS.FindMCS generates invalid SMARTS if ringMatchesRingOnly = True and the MCS contains a query atom bonded through an "any bond" type bond. This is irrespective of the molecule bearing a ring.

```
import rdkit.Chem, rdkit.Chem.rdFMCS

mol = rdkit.Chem.MolFromSmarts('*~CCC')

# Works
args = {'ringMatchesRingOnly': False}
rdkit.Chem.MolFromSmarts(rdkit.Chem.rdFMCS.FindMCS([mol, mol], **args).smartsString)

# SMARTS Parse Error: Failed parsing SMARTS '[#0&!R]&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]' for input: '[#0&!R]&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]'
args = {'verbose': False, 'ringMatchesRingOnly': True}
rdkit.Chem.MolFromSmarts(rdkit.Chem.rdFMCS.FindMCS([mol, mol], **args).smartsString)

```

### PR DESCRIPTION
**Pull request by ptosco**
- fixes #2801
- corrects a couple of typos

Certain bond queries translate to an empty SMARTS string (e.g., `makeBondOrderEqualsQuery(Bond::UNSPECIFIED)`. In those cases, no `&`, `;` or `,` symbol should be added to connect the queries.

### CODE REVIEW

**Comment by ptosco** [comment]
The Travis build simply timed out.

File: Code/GraphMol/SmilesParse/SmartsWrite.cpp [hunk 1]
```diff
@@ -56,7 +56,8 @@ std::string _combineChildSmarts(std::string cs1, unsigned int features1,
           "binary tree");
     }
     res += cs1;
-    res += ",";
+    if (!(cs1.empty() || cs2.empty()))
```
Comment (bp-kelley) [inline Code/GraphMol/SmilesParse/SmartsWrite.cpp]: What happens if cs1 is empty and cs2 is not, doesn't this make

",<cs2>"?

Which looks wrong to me ...

Comment (ptosco) [reply Code/GraphMol/SmilesParse/SmartsWrite.cpp]: @bp-kelley No, it doesn't, unless I'm having a bad day (which may well be :-) ):
```
class std_str(str):
    def empty(self):
        return (len(self) == 0)

cs1 = std_str("")
cs2 = std_str("@")
res = std_str("")

res += cs1
if (not (cs1.empty() or cs2.empty())):
    res += ","
res += cs2

res
'@'

cs1 = std_str("@")
cs2 = std_str("")
res = std_str("")

res += cs1
if (not (cs1.empty() or cs2.empty())):
    res += ","
res += cs2

res
'@'

cs1 = std_str("-")
cs2 = std_str("@")
res = std_str("")

res += cs1
if (not (cs1.empty() or cs2.empty())):
    res += ","
res += cs2

res
'-,@'
```

Comment (bp-kelley) [reply Code/GraphMol/SmilesParse/SmartsWrite.cpp]: For some reason the if !(a|b) is messing with my head.  I find it easier to understand:

```
if ( !cs1.empty() and !cs2.empty()) 
```
