### PR TITLE
Fixes #629 - python GetSubstructureMatch thread safety

### LINKED ISSUE #629: GetSubstructMatch is not thread safe in Python
The Mol.GetSubstructMatch() method is not thread safe even when rdkit is build with RDK_BUILD_THREADSAFE_SSS=ON. Running the attached python code causes a segfault.

\# Python 2.7.10
\# BOOST 1.55.0
\# Using RDK_BUILD_THREADSAFE_SSS=ON, Rdkit Master (aba19e8a847a9e7eeb14a0703addce742aca6e20)
```python
from rdkit import Chem
import threading


def sub_match():
    ref_sdf = '\n     RDKit          3D\n\n 22 23  0  0  1  0  0  0  0  0999 V2000\n   -6.1917   -1.9517    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -5.0664   -1.3009    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.9401   -1.9499    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.8148   -1.2991    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.6885   -1.9483    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.5632   -1.2973    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.5642    0.0027    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.6905    0.6517    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.6916    1.9517    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.8158    0.0009    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.9422    0.6501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -5.0685    1.2991    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    0.5632   -1.9465    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    1.6885   -1.2955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.6874    0.0046    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8148   -1.9447    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9401   -1.2936    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9391    0.0064    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.0644    0.6572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.1907    0.0082    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.1917   -1.2918    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.0664   -1.9429    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0\n  2  3  1  0\n  3  4  1  0\n  4 10  2  0\n  4  5  1  0\n  5  6  2  0\n  6  7  1  0\n  6 13  1  0\n  7  8  2  0\n  8  9  1  0\n  8 10  1  0\n 10 11  1  0\n 11 12  3  0\n 13 14  1  0\n 14 15  2  0\n 14 16  1  0\n 16 17  1  0\n 17 22  1  0\n 17 18  2  0\n 18 19  1  0\n 19 20  2  0\n 20 21  1  0\n 21 22  2  0\nM  END'
    core_smarts = '[#6]-!@[#6]-!@[#8]-!@[#6]:1:[#6](-!@[#6]#!@[#7]):[#6](-!@[#7]):[#6]:[#6](-!@[#7]-!@[#6](-!@[#6]-!@[#6]:2:[#6]:[#6]:[#6]:[#6]:[#6]:2)=!@[#8]):[#7]:1'
    ref_mol = Chem.MolFromMolBlock(ref_sdf)
    if ref_mol is None:
        raise ValueError('Bad ref structure')
    core_mol = Chem.MolFromSmarts(core_smarts)
    if core_mol is None:
        raise ValueError('Bad core structure')
    ref_mol.GetSubstructMatch(core_mol)

for i in xrange(1, 500):
    t = threading.Thread(target=sub_match, args=())
    t.start()

print "done"
```

### PR DESCRIPTION
**Pull request by bp-kelley**
Never/ever call the Python API when the GIL is released.

Also releases the GIL during GetSubstructMatches.

Any ideas how to add a test case for this?  Do we know when to test threading?

### CODE REVIEW

**Comment by bp-kelley** [comment]
If RDK_THREADSAFE_SSS is not set, should we release the GIL at all?  The default is to always release the GIL which seems... optimistic.

**Comment by bp-kelley** [comment]
I checked the rest of the GIL releases, it appears this one was the only borked one, I'll write some MT tests over the next few days.

**Comment by greglandrum** [comment]
I've never done enough multi-threading in python to really have much of a grasp of this stuff. When I've wanted to do parallel work, I've tended to use things like multiprocessing.

I believe it only makes sense to release the GIL around substructure matching if RDK_THREADSAFE_SSS is set. If that flag is not set and there is a recursive SMARTS component of the query, it *will* generate incorrect results if that query is being applied to multiple molecules at the same time.

**Comment by greglandrum** [comment]
Re: testing
I was not able to come up with a reliable testing scenario that exposed the bug across platforms. We could fix the GIL code, try putting in something basic in terms of testing, and hope for the best?

File: Code/GraphMol/Wrap/Mol.cpp [hunk 1]
```diff
@@ -89,9 +89,11 @@ namespace RDKit {
   }
   PyObject *GetSubstructMatch(const ROMol &mol, const ROMol &query,bool useChirality=false,
                             bool useQueryQueryMatches=false){
-    NOGIL gil;
     MatchVectType matches;
-    SubstructMatch(mol,query,matches,true,useChirality,useQueryQueryMatches);
+    {
+      NOGIL gil;
```
Comment (greglandrum) [inline Code/GraphMol/Wrap/Mol.cpp]: How about modifying the NOGIL definition so that it only does anything if the thread safety flag (RDK_BUILD_THREADSAFE_SSS) is set?

Comment (bp-kelley) [inline Code/GraphMol/Wrap/Mol.cpp]: That's my plan.

----
Brian Kelley
