### PR TITLE
Fix Mol block parser by resetting atomic number to 0 for COMPOSITE_OR query atoms (#6349)

### LINKED ISSUE #6349: Query Features: Different input format leads to a different molecule
**Describe the bug**
When I load a simple query molecule with a single atom being a "atom list", the generated Mol behaves differently with a different import fomat, eg  different behavior when loading from Smarts vs molfile. even when round-tripping.

When loading from Smarts then writing Smiles, the query atom always is a dummy atom, "*".
When loading from molfile then writing Smiles, the query atom is always the first atom in the list. with a list of [Cl,F,Br] it will be "Cl" while for a list of [F,Cl,Br] it will be "F". 

**To Reproduce**

```python
m = Chem.MolFromSmarts("C-C(-[Cl,F,Br])-C")
Chem.MolToSmiles(m)
# *C(C)C

mb = Chem.MolToMolBlock(m, forceV3000=True)
m2 = Chem.MolFromMolBlock(mb)
Chem.MolToSmiles(m2)
# CC(C)Cl
```

image

**Expected behavior**
Both cases should behave the same, preferably with the "*" as the "molblock behavior" loses completely the information that it is a query.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.05
 - OS: Windows 10
 - Python version (if relevant): 3.10
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 
EDIT:
it seems that the issues arises when setting the atomic number. In case of Smarts it is 0, in case of molfile it is the atomic number of the first element in the "query list". simply using SetAtomicNum(0) on the query atom when read from molfile "fixes" the issue.
Therefore the issue probably arises in the Molfileparser when Atomic number is set.

### PR DESCRIPTION
**Pull request by MarioAndWario**
#### Reference Issue

Fixes #6349 

#### What does this implement/fix? Explain your changes.

For a query with OR atoms, such as `[C,N]`, we can construct a Mol object from either a SMARTS (via `MolFromSmarts`) or a Mol block (via `MolFromMolBlock`), but the exported SMILES (via `MolToSmiles`) from these two approaches are inconsistent:

```python
from rdkit import Chem
m = Chem.MolFromSmarts("[C,N]")
print(Chem.MolToSmiles(m)) # *
mb = Chem.MolToMolBlock(m)
m2 = Chem.MolFromMolBlock(mb)
print(Chem.MolToSmiles(m2)) # C
```
where `*` is the expected output. There is a bug in Mol block parser that always logs the atomic number of the first atom (i.e., `C` in `[C,N]`) as that of the query atom. 

The fix is very straightfoward. When we load the first atom (e.g., `C`), the atomic number of the query atom is set to 6. If there are OR atoms in the brackets (e.g., `[C,N]`), the atomic number of the query atom is reset to 0, corresponding to `*`. This is the behavior of `MolFromSmarts`.

```python
m = Chem.MolFromSmarts("[C]")
print(Chem.MolToSmiles(m)) # C
mb = Chem.MolToMolBlock(m)
m2 = Chem.MolFromMolBlock(mb)
print(Chem.MolToSmiles(m2)) # C
```

A unittest `testGithub6349` is added to `Code/GraphMol/SmilesParse/test.cpp`.

#### Any other comments?

I also find out that the query atom from these two approaches are in different representations:
1. `MolFromSmarts` uses `AtomType`, while
2. `MolFromMolBlock` uses `AtomAtomicNum`.

```python
m1 = Chem.MolFromSmarts("[C,N]")
at1 = m1.GetAtomWithIdx(0)
print(at1.DescribeQuery())
# AtomOr
#   AtomType 6 = val
#   AtomType 7 = val

mb = Chem.MolToMolBlock(m1)
m2 = Chem.MolFromMolBlock(mb)
at2 = m2.GetAtomWithIdx(0)
print(at2.DescribeQuery())
# AtomOr
#   AtomAtomicNum 6 = val
#   AtomAtomicNum 7 = val
```

Not sure if they should be the same or not, but it seems to be out of the scope of this bug fix.

### CODE REVIEW

**Comment by MarioAndWario** [comment]
By fixing the atomic number issue of Mol block parser, I also broke two unittests: `test23MolFileParsing` and `testRGroupDecomp`. This is because the definition of a dummy atom in the implement of R-group decomposition and substruct match functions still relies on the atomic number being 0.

To fix these two tests, I applied a new definition of a dummy atom as
```
auto isDummyAtom = [](const Atom &atom) {
      return (!atom.hasQuery() && atom.getAtomicNum() == 0) ||
             (atom.hasQuery() &&
              atom.getQuery()->getDescription() == "AtomNull");
};
```
which applies to `"*"` in either SMILES and SMARTS. Note that after my changes in Mol block parser, SMARTS like `"[C,N]"` will also have a zero atomic number for the query atom, and therefore the previous definition of a dummy atom as `atom.getAtomicNum() == 0` does not work.

In addition, I wonder if it is reasonable to define a public method `Atom::isDummyAtom`? I see that there are many places in the codebase where we need to determine whether an atom is dummy or not. Currently I define the lambda function `isDummyAtom` at two places, which does violate the DRY principle...

File: Code/GraphMol/SmilesParse/test.cpp [hunk 1]
```diff
@@ -4382,6 +4382,36 @@ void testGithub3967() {
...
 
+void testGithub6349() {
+  BOOST_LOG(rdInfoLog) << "-------------------------------------" << std::endl;
+  BOOST_LOG(rdInfoLog)
+      << "Testing Github Issue 6349: Different SMARTS input formats lead to different SMILES outputs."
+      << std::endl;
+
+  auto checkSmartsToSmiles = [](const std::string &sma,
+                                const std::string &refSmi) {
+    ROMol *molFromSmarts = SmartsToMol(sma);
```
Comment (greglandrum) [inline Code/GraphMol/SmilesParse/test.cpp:4393]: Please use an std::unique_ptr here so that the memory gets automatically released

File: Code/GraphMol/SmilesParse/test.cpp [hunk 2]
```diff
@@ -4382,6 +4382,36 @@ void testGithub3967() {
...
+    {
+      std::string smi = MolToSmiles(*molFromSmarts);
+      TEST_ASSERT(smi == refSmi);
+    }
+
+    std::string molBlock = MolToMolBlock(*molFromSmarts);
+    ROMol *molFromBlock =
```
Comment (greglandrum) [inline Code/GraphMol/SmilesParse/test.cpp:4400]: Please use an std::unique_ptr here so that the memory gets automatically released

File: Code/GraphMol/Aromaticity.cpp [hunk 3]
```diff
@@ -809,12 +809,18 @@ int aromaticityHelper(RWMol &mol, const VECT_INT_VECT &srings,
       continue;
     }
 
+    auto isDummyAtom = [](const Atom &atom) {
```
Comment (greglandrum) [inline Code/GraphMol/Aromaticity.cpp:812]: This is a generally useful function, please put it in QueryOps.h

File: Code/GraphMol/Substruct/SubstructUtils.cpp [hunk 4]
```diff
@@ -246,11 +246,14 @@ std::vector<MatchVectType> sortMatchesByDegreeOfCoreSubstitution(
...
 bool isAtomTerminalRGroupOrQueryHydrogen(const Atom *atom) {
-  return atom->getDegree() == 1 &&
-         (atom->getAtomicNum() == 0 ||
-          (atom->hasQuery() &&
-           describeQuery(atom).find("AtomAtomicNum 1 = val") !=
-               std::string::npos));
+  auto isDummyAtom = [](const Atom &atom) {
+    return (!atom.hasQuery() && atom.getAtomicNum() == 0) ||
+           (atom.hasQuery() && atom.getQuery()->getDescription() == "AtomNull");
+  };
```
Comment (greglandrum) [inline Code/GraphMol/Substruct/SubstructUtils.cpp:252]: please use the version of this in QueryOps.h (assuming you make that suggested change)

**Review by greglandrum — CHANGES_REQUESTED** [review]
Thanks for the contribution. I made a couple of small requests, but otherwise this looks good to me.

**Comment by greglandrum** [comment]
@MarioAndWario I'm very sorry for how long it took for me to review this.

File: Code/GraphMol/SmilesParse/test.cpp (hunk 1 above)
Comment (MarioAndWario) [reply Code/GraphMol/SmilesParse/test.cpp]: Nice catch! Fixed.

File: Code/GraphMol/Aromaticity.cpp (hunk 3 above)
Comment (MarioAndWario) [reply Code/GraphMol/Aromaticity.cpp]: Added.

File: Code/GraphMol/Substruct/SubstructUtils.cpp (hunk 4 above)
Comment (MarioAndWario) [reply Code/GraphMol/Substruct/SubstructUtils.cpp]: Done.

**Comment by MarioAndWario** [comment]
> @MarioAndWario I'm very sorry for how long it took for me to review this.

No problem! I have addressed your comments in the latest two commits.

File: Code/GraphMol/SmilesParse/test.cpp (hunk 2 above)
Comment (MarioAndWario) [reply Code/GraphMol/SmilesParse/test.cpp]: Fixed.

File: Code/GraphMol/QueryOps.h [hunk 5]
```diff
@@ -1084,6 +1084,17 @@ RDKIT_GRAPHMOL_EXPORT bool isAtomListQuery(const Atom *a);
...
 
+// Checks if an atom is dummy or not.
+// 1. A dummy non-query atom (e.g., "*" in SMILES) is defined by its zero atomic 
+//    number. This rule breaks for query atoms because a COMPOSITE_OR query atom 
+//    also has a zero atomic number (#6349).
+// 2. A dummy query atom (e.g., "*" in SMARTS) is defined by its explicit 
+//    description: "AtomNull".
+inline bool isAtomDummy(const Atom *a) {
+  return (!a->hasQuery() && a->getAtomicNum() == 0) ||
+         (a->hasQuery() && a->getQuery()->getDescription() == "AtomNull");
```
Comment (greglandrum) [inline Code/GraphMol/QueryOps.h:1095]: I should have noticed this before, but you want to check for negation here:
```suggestion
         (a->hasQuery() && !a->getQuery()->getNegation() && a->getQuery()->getDescription() == "AtomNull");
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
One minor correction requested

File: Code/GraphMol/QueryOps.h (hunk 5 above)
Comment (MarioAndWario) [reply Code/GraphMol/QueryOps.h]: Nice catch! Fixed.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@MarioAndWario thanks for the bug fix!
One piece of feedback: It's easier to review PRs if you update your forks with normal pushes (instead of force pushes). With a normal push I can use the github UI to easily see what has changed since my last review. I don't think this is possible when a force push is done.

**Comment by MarioAndWario** [comment]
> @MarioAndWario thanks for the bug fix!
> 
> One piece of feedback: It's easier to review PRs if you update your forks with normal pushes (instead of force pushes). With a normal push I can use the github UI to easily see what has changed since my last review. I don't think this is possible when a force push is done.

Sorry for the inconvenience! I will avoid force pushes as much as possible in the future.
