### PR TITLE
Fix the way carbon is handed in cleanupOrganometallics()

### LINKED ISSUE #8312: Explicit valence of carbon > 4 not permitted
The molfile at the end for a regular organometallic compound [Pd(CH3)2(cod)] results in an error message

`Explicit valence for atom # 0 C, 5, is greater than permitted`

although it is properly processed for example by the [InChI Web Demo](https://iupac-inchi.github.io/InChI-Web-Demo/):

Image

I also tried with multi-attachment lines like `M  V30 21 1 9 23 ENDPTS=(2 6 5) ATTACH=ANY` but it also fails.

I need the metal-connected structure since I want to count the ring size involving the Pt atoms, which should be 2x3 and 2x5

```
  ChemDraw03012503262D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 21 24 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -1.822529 0.405221 0.000000 0 VAL=5
M  V30 2 C -1.822529 -0.419779 0.000000 0 VAL=5
M  V30 3 C -1.239167 -1.003142 0.000000 0
M  V30 4 C -0.414167 -1.003142 0.000000 0
M  V30 5 C 0.169196 -0.419779 0.000000 0 VAL=5
M  V30 6 C 0.169196 0.405221 0.000000 0 VAL=5
M  V30 7 C -0.414167 0.988584 0.000000 0
M  V30 8 C -1.239167 0.988584 0.000000 0
M  V30 9 Pt 1.335541 -0.028481 0.000000 0 VAL=6
M  V30 10 C 1.697726 0.712766 0.000000 0
M  V30 11 C 1.796387 -0.712766 0.000000 0
M  V30 12 H 2.520757 0.769729 0.000000 0
M  V30 13 H 1.236879 1.397051 0.000000 0
M  V30 14 H 2.059910 1.454013 0.000000 0
M  V30 15 H 2.619419 -0.655803 0.000000 0
M  V30 16 H 1.434203 -1.454013 0.000000 0
M  V30 17 H 2.257234 -1.397051 0.000000 0
M  V30 18 H -2.619419 0.618747 0.000000 0
M  V30 19 H -2.619419 -0.633305 0.000000 0
M  V30 20 H 0.382722 1.202110 0.000000 0
M  V30 21 H 0.581696 -1.134250 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 2 1 2
M  V30 2 1 2 3
M  V30 3 1 3 4
M  V30 4 1 4 5
M  V30 5 2 5 6
M  V30 6 1 6 7
M  V30 7 1 7 8
M  V30 8 1 8 1
M  V30 9 1 9 10
M  V30 10 1 9 11
M  V30 11 1 10 12
M  V30 12 1 10 13
M  V30 13 1 10 14
M  V30 14 1 11 15
M  V30 15 1 11 16
M  V30 16 1 11 17
M  V30 17 1 9 6
M  V30 18 1 9 5
M  V30 19 1 9 1
M  V30 20 1 9 2
M  V30 21 1 1 18
M  V30 22 1 2 19
M  V30 23 1 6 20
M  V30 24 1 5 21
M  V30 END BOND
M  V30 END CTAB
M  END
```

### PR DESCRIPTION
**Pull request by greglandrum**
In the current master the logic in `cleanupOrganometallics()` for converting single bonds from hypervalent atoms to metals into dative bonds essentially doesn't work for carbon.

For example, eta-3 propene represented with the SMILES `[CH2-]1-[CH]2=[CH2]3.[Fe]123`:
image
Should be converted to:
image

Even worse is the handling of this: `[cH]12[cH]3[cH]4[cH]5[cH]6[cH]17.[Fe]234567`, which ends up losing the aromatic bonds:
image
It should be converted to:
image

This fixes that problem.

There's also a change to disable `cleanupOrganometallics()` when parsing mol2 files. Given the semantics encoded by the atoms types on those files, this kind of cleanup operation doesn't really make sense for them.

Fixes #8312

### CODE REVIEW

**Comment by greglandrum** [comment]
@DavidACosgrove given that you did the original work on this, it would be good know what you think of the change.

**Review by DavidACosgrove — APPROVED** [review]
LGTM.

**Comment by greglandrum** [comment]
@ptosco Dave C has already reviewed this, but do you have the time to do a quick look through from a maintainer's perspective?

File: Code/GraphMol/MolOps.cpp [hunk 1]
```diff
@@ -207,14 +208,17 @@ bool isHypervalentNonMetal(Atom *atom) {
...
-  // obey the octet rule (2*ev <= 8).  If it doesn't, don't set the bond to
-  // dative, so the molecule is later flagged as having bad valence.
-  // [CH4]-[Na] being a case in point, line 1800 of
-  // FileParsers/file_parsers_catch.cpp.
+  // atom is a non-metal. If its explicit valence is greater than the
+  // maximum allowed valence then it is hypervalent.
+  //  We have a special case in here for aromatic atoms where the explicit
+  //  valence matches the max allowed and the degree is 4. This is there for
+  //  cases like cyclopentadienyl - metal systems. We need this special case
+  //  because the explicit on the C atoms there ends up being 4
```
Comment (ptosco) [inline Code/GraphMol/MolOps.cpp:216]:
```suggestion
  //  because the explicit valence on the C atoms there ends up being 4
```

**Review by ptosco — APPROVED** [review]
LGTM, I only added a suggestion to add a missing word. Thanks for taking care of this!
