### PR TITLE
Fixes #3755

### LINKED ISSUE #3755: Inconsistent canonical tautomer on repeated application
**Describe the bug**
Tautomer canonicalization seems to be occasionally inconsistent, repeated canonicalizations will produce different results.

**To Reproduce**

Repeatedly pick the canonical tautomer for Serine.

```python
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

enumerator = rdMolStandardize.TautomerEnumerator()

mol1 = Chem.MolFromSmiles('C([C@@H](C(=O)O)N)O')
mol2 = enumerator.Canonicalize(mol1)
mol3 = enumerator.Canonicalize(mol2)

print('\n'.join([
    Chem.MolToSmiles(mol1),
    Chem.MolToSmiles(mol2),
    Chem.MolToSmiles(mol3)
]))
```

Output:
```
N[C@@H](CO)C(=O)O
NC(CO)C(=O)O
NC(C=O)C(O)O
```
**Expected behavior**

I would expect mol2 to be the same as mol3.  The canonical tautomer of the canonical tautomer should still be the original canonical tautomer (unless we hit MaxTautomers or something like that, which is not occurring here).

Instead mol2 and mol3 differ in where they've put the double bond.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.7.9
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

### PR DESCRIPTION
**Pull request by ptosco**
#3755 is caused by two separate problems:

1) There is an inconsistency in the exhaustiveness of the tautomer enumeration between the chiral and the non-chiral versions of serine. This is caused by a bug in the logic that checks when the enumeration should be considered as complete.
As a consequence, the enumeration for the chiral molecule is quit too early, and the hydrate tautomer is not generated. Therefore, the expected carboxylic acid tautomer is generated, and the result appears to be correct (because the competing hydrate tautomer is not generated).
Instead, for the achiral molecule the enumeration is indeed complete, the hydrate tautomer scores the same as the carboxylic acid tautomer, but the hydrate tautomer is preferred as its SMILES comes first in lexicographic order.<br/>
This PR fixes the bug in the logic, so the enumeration is now complete also for the chiral molecule case.
<ol>

* I also fixed the debug build with `VERBOSE_ENUMERATION` defined (which was failing to build)
* I moved the comments around to make them more useful during debugging
* I removed an unnecessary copying of the molecule
* I removed the `done` stack altogether

<br/>The two latter points should result in improved performance.
</ol>

2) The hydrate tautomer scores the same as the carboxylic acid tautomer. This already happened in the original Python implementation of MolVS:
<ol>

```
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage
from rdkit.Chem.MolStandardize import tautomer

orig_vs_expected = [
    ("OC(=O)C(N)CO", "NC(CO)C(=O)O"),
    ("C([C@@H](C(=O)O)N)O", "NC(CO)C(=O)O"),
    ("OC(=O)C(N)CN", "NCC(N)C(=O)O"),
    ("NC(=O)C(N)CO", "NC(=O)C(N)CO"),
    ("NC(=N)C(N)CO", "N=C(N)C(N)CO"),
    ("NC(=N)NC(N)CO", "N=C(N)NC(N)CO")
]

enumerator = tautomer.TautomerCanonicalizer()
orig_vs_canonical_mols = []
for orig, expected in orig_vs_expected:
    orig_mol = Chem.MolFromSmiles(orig)
    orig_vs_canonical_mols.append(orig_mol)
    canonical = enumerator.canonicalize(orig_mol)
    orig_vs_canonical_mols.append(canonical)

MolsToGridImage(orig_vs_canonical_mols, molsPerRow=2, subImgSize=(200,100))
```
image
<br/>As you may see, there are a number of molecules which are converted to hydrates or aminals.
This PR fixes this issue by adding an additional substructure rule:
```
{"C(=hetero)-hetero", "[C](=[!#1;!#6])[!#1;!#6]", 2},
```
which gives a higher score to carboxylic acids/amides/amidines vs their reduced counterparts.
</ol>

### CODE REVIEW

File: Code/GraphMol/MolStandardize/testTautomer.cpp [hunk 1]
```diff
@@ -715,9 +715,9 @@ void testCanonicalize() {
   TautomerEnumerator te(new TautomerCatalog(tautparams.get()));
 
   for (const auto &itm : canonTautomerData) {
-    std::unique_ptr<ROMol> mol{SmilesToMol(itm.first)};
+    ROMOL_SPTR mol{SmilesToMol(itm.first)};
```
Comment (greglandrum) [inline Code/GraphMol/MolStandardize/testTautomer.cpp:718]: I don't understand the reason for the changes from unique_ptr to ROMOL_SPTR that you made in this file. The pointers aren't being shared or used elsewhere so I don't think there's any reason to make them shared. Did I miss something?

**Review by greglandrum — CHANGES_REQUESTED** [review]
Nice fix, and thanks for adding the scoring term too.
There's one question about changes to the test file, but otherwise looks good.

File: Code/GraphMol/MolStandardize/testTautomer.cpp (hunk 1 above)
Comment (ptosco) [reply Code/GraphMol/MolStandardize/testTautomer.cpp]: No reason other than `ROMOL_SPTR` reads nicer and there is no `ROMOL_UPTR` `typedef`, and the fact that in the context of that test both would work. But you are right, no serious reason, so I reverted them. I am also going to write 100 times "You shall not make useless and confusing changes to existing tests that waste reviewers' time".

**Review by greglandrum — APPROVED** [review]
