### PR TITLE
Fix segfault in mol zip

### LINKED ISSUE #5334: Molzip segfaults instead of throwing an error when multiple bonds are formed to the same pairs of atoms
**Describe the bug**
Molzip segfaults instead of throwing an error when multiple bonds are formed to the same pairs of atoms when chirality is explicitly expressed for one of the atoms.

**To Reproduce**
```python
from rdkit import Chem
Chem.molzip(Chem.MolFromSmiles('C([*:1])[*:2].[C@@H](Cl)([1*:1])[2*:2]'))
```

**Expected behavior**
Expected either an error to be thrown or all but one of the bonds to be ignored (which is what usually happens when chirality is not specified).

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: [e.g. Ubuntu 20.04] Windows
 - Python version (if relevant): 3.10.4
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #5334 

FragmentOnBonds allows multiple links with the same label, everything else does not.  This caused issues when looking at the ordering for chirality.

This fixes both issues.

### CODE REVIEW

File: Code/GraphMol/ChemTransforms/MolFragmenter.cpp [hunk 1]
```diff
@@ -715,12 +716,22 @@ struct ZipBond {
...
       return false;
     }
+    
+    // Fragment on bonds allows multiple links to the same atom
+    // i.e. C.[1C].[1C]
+    //  otherwise throw an invariant error
+    if (!(params.label == MolzipLabel::FragmentOnBonds) &&  a->getOwningMol().getBondBetweenAtoms(a->getIdx(), b->getIdx())) {
+      CHECK_INVARIANT(!a->getOwningMol().getBondBetweenAtoms(a->getIdx(), b->getIdx()),
+                      "molzip: zipped Bond already exists, perhaps labels are duplicated");
+    }
```
Comment (greglandrum) [inline Code/GraphMol/ChemTransforms/MolFragmenter.cpp:732]: wouldn't this work as:
```suggestion
    CHECK_INVARIANT(params.label == MolzipLabel::FragmentOnBonds || !a->getOwningMol().getBondBetweenAtoms(a->getIdx(), b->getIdx()),
                      "molzip: zipped Bond already exists, perhaps labels are duplicated");
```

File: Code/GraphMol/ChemTransforms/catch_tests.cpp [hunk 2]
```diff
@@ -227,6 +227,8 @@ TEST_CASE("molzip", "[]") {
         if (i != j) {
           std::vector<unsigned int> bonds{i, j};
           auto resa = RDKit::MolFragmenter::fragmentOnBonds(*m, bonds);
+          auto smiles = MolToSmiles(*resa);
```
Comment (greglandrum) [inline Code/GraphMol/ChemTransforms/catch_tests.cpp:230]: do we still need this debug output?

File: Code/GraphMol/ChemTransforms/catch_tests.cpp [hunk 3]
```diff
@@ -327,6 +329,7 @@ TEST_CASE("molzip", "[]") {
         }
         MolzipParams p;
         p.label = MolzipLabel::FragmentOnBonds;
+          std::cout << smiles << std::endl;
```
Comment (greglandrum) [inline Code/GraphMol/ChemTransforms/catch_tests.cpp:332]: do we still need this debug output?

**Review by greglandrum — CHANGES_REQUESTED** [review]
some small suggestions

File: Code/GraphMol/ChemTransforms/catch_tests.cpp (hunk 2 above)
Comment (bp-kelley) [reply Code/GraphMol/ChemTransforms/catch_tests.cpp:230]: Nope

**Comment by bp-kelley** [comment]
@greglandrum should be okay once the tests pass

**Review by greglandrum — APPROVED** [review]
LGTM
