### PR TITLE
Fixes #7642

### LINKED ISSUE #7642: Multithreaded InPlace standardization functions seg fault if there's a duplicate molecule
**Describe the bug**
Here's the reproducible
```
In [4]: from rdkit import Chem
   ...: from rdkit.Chem.MolStandardize.rdMolStandardize import *
   ...: 
   ...: mols = [
   ...:     Chem.MolFromSmiles('Cc1c2no[n+]([O-])c2c(C)[n+]([O-])[n+]1[O-]'),
   ...:     Chem.MolFromSmiles('C')
   ...: ]
   ...: 
   ...: TautomerParentInPlace([mols[0],mols[0]], numThreads=2)
Segmentation fault (core dumped)
```

Discovered while investigating #7613 

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.5 and master
 - OS: ubuntu 22.04

### PR DESCRIPTION
**Pull request by greglandrum**
adds a test that all the mol pointers are unique to each of the `InPlace` functions that take a vector of pointers

### CODE REVIEW

File: Code/GraphMol/MolStandardize/MolStandardize.cpp [hunk 1]
```diff
@@ -177,6 +195,7 @@ void cleanupInPlace(RWMol &mol, const CleanupParameters &params) {
 
 void cleanupInPlace(std::vector<RWMol *> &mols, int numThreads,
                     const CleanupParameters &params) {
+  throwIfMolPtrListContainsDuplicates(mols);
```
Comment (bp-kelley) [inline Code/GraphMol/MolStandardize/MolStandardize.cpp:198]: You could also  just eliminate the duplicates and work on the rest.

```
  std::set<RWMol*> unique(mols.begin(), mols.end());
  std::vector<RWMol*> work_mols(unique.begin(), unique.end())
   standardizeMultipleMolsInPlace(
       static_cast<void (*)(RWMol &, const CleanupParameters &)>(cleanupInPlace),
       work_mols, numThreads, params);
```

Comment (greglandrum) [reply Code/GraphMol/MolStandardize/MolStandardize.cpp:198]: That's an option, but I think it's an error in the input.
Going that route also would require even more work if/when we add option of returning a list of "success,fail" values from the various InPlace functions

Comment (bp-kelley) [reply Code/GraphMol/MolStandardize/MolStandardize.cpp:198]: You could still use the set as a faster version of the N**2 comparisons.

```
 if (std::unordered_set<RWMol*>(mols.begin(), mols.end()).size() != mols.size()) {
  throw ...
}
```

**Review by bp-kelley — APPROVED** [review]
