### PR TITLE
Check for correctly sized propertylists to avoid dropping molecules

### LINKED ISSUE #8918: Atom properties as SDF file data break if the array is too long
They check if an array is too short, but not if it is too long;

```
from io import BytesIO
from rdkit import Chem

mb = """43
     RDKit          3D

  2  0  0  0  0  0  0  0  0  0999 V2000
   -6.3694   12.3608  -12.0100 C   0  0  0  0  0  0  0  0  0  0  0  0
   -6.5170   11.8053  -10.7333 C   0  0  0  0  0  0  0  0  0  0  0  0
M  END
>  <atom.dprop.PartialCharge>  (1) 
-0.157697 1 2

$$$$"""

stream = BytesIO(mb.encode("ascii"))
list(Chem.ForwardSDMolSupplier(stream))
```

This unfortunately raises an exception and skips the molecule

```
[16:17:34] 

****
Range Error
idx
Violation occurred on line 209 in file D:\bld\rdkit-meta_1751349675470\work\Code\GraphMol\ROMol.cpp
Failed Expression: 2 < 2
****

[16:17:34] Unexpected error hit on line 10
[16:17:34] ERROR: moving to the beginning of the next molecule
```
```

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #8918

### CODE REVIEW

File: Code/GraphMol/FileParsers/FileParserUtils.h [hunk 1]
```diff
@@ -136,6 +137,12 @@ void applyMolListProp(ROMol &mol, const std::string &pn,
     BOOST_LOG(rdWarningLog) << "Missing value marker for property " << pn
                             << " is empty." << std::endl;
   }
+  if(tokens.size() - first_token != nItems) {
```
Comment (bp-kelley) [inline Code/GraphMol/FileParsers/FileParserUtils.h:134]: We could drop the first check in favor of this one.

Comment (bp-kelley) [reply Code/GraphMol/FileParsers/FileParserUtils.h:134]: This adds a simple sanity check so we don't try to access an invalid atom or bond index.  I've seen a few of these in the wild.

Comment (greglandrum) [reply Code/GraphMol/FileParsers/FileParserUtils.h:134]: > We could drop the first check in favor of this one.

I think it's worth making that change as part of this PR

**Comment by bp-kelley** [comment]
With a little more digging, this is happening when properties are added to hydrogens and are being removed by the readers:

```
from rdkit import Chem
from io import StringIO, BytesIO

p = Chem.SmilesParserParams()
p.removeHs = False
m = Chem.MolFromSmiles("[H]C", p)
for atom in m.GetAtoms(): atom.SetIntProp("foo", atom.GetIdx())
Chem.CreateAtomIntPropertyList(m, "foo")
m.SetProp("shouldbehere", "here")

stream = StringIO()
with Chem.SDWriter(stream) as writer:
    writer.write(m)

istream = BytesIO(stream.getvalue().encode("ascii"))
for m in Chem.ForwardSDMolSupplier(istream):
    if m.GetAtomWithIdx(0).GetProp("foo") != "1":
        print("Failed index with remove hs")
    
print("-"*44)
istream = BytesIO(stream.getvalue().encode("ascii"))
for m in Chem.ForwardSDMolSupplier(istream, removeHs=False):
    if m.GetAtomWithIdx(0).GetProp("foo") != "0":
        print("Failed proplist")
    if m.GetAtomWithIdx(1).GetProp("foo") != "1":
        print("Failed proplist")
```

It strikes me that the properties should be added before hydrogens are removed, otherwise the indices can be completely borked as the above shows.

**Comment by bp-kelley** [comment]
This one fell off my radar, I'll put the changes in.
