### PR TITLE
Fixes #2984

### LINKED ISSUE #2984: RDKit misplaces stereochemistry/chirality information for small ring
**Configuration:**
- RDKit Version: 2019.09.02 and 2020.03.1dev1
- Operating system: Linux and Mac
- Python version (if relevant): 3.6.2
- Are you using conda? Nope
- If you are not using conda: Local build and Schrodinger bundled build of 2019.09.02.

**Description:**
RDKit seems to misplace the stereochemical descriptions of this moeity. In this example, a bond stereochemistry is required to break symmetry for an atom parity, and the atom parity is required to break symmetry for the bond stereochemistry. One of the double bond's stereoatoms needs to be in a ring.

examples3

```
>>> from rdkit import Chem
>>> Chem.MolToSmiles(Chem.MolFromSmiles(r'CCC=C1CC(O)C1'))
'CCC=C1CC(O)C1'
# this seems incorrect to me, and disagrees with Marvin and Canvas
>>> Chem.MolToSmiles(Chem.MolFromSmiles(r'CC/C=C1\C[C@H](O)C1'))
'CCC=C1CC(O)C1'
>>> Chem.MolToSmiles(Chem.MolFromSmiles(r'CC/C=C1\CC[C@H]1O'))
'CC/C=C1\\CC[C@H]1O'
```

### PR DESCRIPTION
**Pull request by ricrogz**
This fixes #2984.

This issue has been sitting there for a long time, and now, with the new version of `AssignStereochemistry()`, we finally have the required infrastructure to fix it!

Also, I added a couple of fixture functions to manage the Legacy Stereo Perception and Allow Non Tetrahedral Chirality settings, since there was one test ("useLegacyStereoPerception feature flag") that was leaving the new stereo algorithm enabled.

I haven't been able to find a way to automatically apply a fixture to all tests in the file, though, so we still need to manually invoke the fixture in all tests that might require it. I either haven't been able to find a way of rerunning the same test sections with a different value for one variable, so I had to add the `for (auto use_legacy : {false, true})` loops to the new test I added.

### CODE REVIEW

File: Code/GraphMol/FindStereo.cpp [hunk 1]
```diff
@@ -385,6 +385,64 @@ inline std::string getAtomCompareSymbol(const Atom &atom) {
...
+      continue;
+    }
+
+    auto ring = ring_info->atomRings().at(*it1);
+    if (ring.size() % 2) {
+      // Ring is odd-sized
+      continue;
+    }
+
+    for (auto bond_end : {bond.getBeginAtomIdx(), bond.getEndAtomIdx()}) {
```
Comment (greglandrum) [inline Code/GraphMol/FindStereo.cpp:426]: Nice. I like this pattern

File: Code/GraphMol/FindStereo.cpp [hunk 2]
```diff
@@ -385,6 +385,64 @@ inline std::string getAtomCompareSymbol(const Atom &atom) {
   return std::to_string(atom.getIsotope()) + atom.getSymbol() +
          std::to_string(atom.getFormalCharge());
 }
+
+bool are_stereobond_controlling_atoms_dupes(
```
Comment (greglandrum) [inline Code/GraphMol/FindStereo.cpp:389]: The style here is inconsistent with the rest of the RDKit, which doesn't use underscores.
It's not the end of the world since this is internal code, but I would rather not start mixing styles like this.

File: Code/GraphMol/FindStereo.cpp [hunk 3]
```diff
@@ -501,9 +561,22 @@ void flagRingStereo(ROMol &mol,
         // find the index of the atom on the opposite side of the even-sized
         // ring
         auto oppositeidx = aring[(ai + half_sz) % sz];
+        bool to_atom_opposite_possible = false;
+        auto opposite_atom = mol.getAtomWithIdx(oppositeidx);
+        for (auto bond : mol.atomBonds(opposite_atom)) {
+          auto bidx = bond->getIdx();
+          if (std::find(bring.begin(), bring.end(), bidx) == bring.end() &&
+              (knownBonds[bidx] ||
+               (possibleBonds && possibleBonds->test(bidx)))) {
```
Comment (greglandrum) [inline Code/GraphMol/FindStereo.cpp:570]: It's probably better to do the cheap tests first:
```suggestion
          if ( (knownBonds[bidx] ||
               (possibleBonds && possibleBonds->test(bidx))) &&
               std::find(bring.begin(), bring.end(), bidx) == bring.end()) {
```

File: Code/GraphMol/FindStereo.cpp [hunk 4]
```diff
@@ -472,20 +530,22 @@ void initBondInfo(ROMol &mol, bool flagPossible, bool cleanIt,
...
   //    2) atoms sharing a bond which fuses two or more rings, like the
   //    central
   //       bond in C1CCC2CCCCC2C1
-  boost::dynamic_bitset<> possibleAtomsInRing(mol.getNumAtoms());
 
-  for (unsigned int ridx = 0; ridx < mol.getRingInfo()->atomRings().size();
-       ++ridx) {
-    // FIX: deal with findPossible and ring stereo
-    const auto &aring = mol.getRingInfo()->atomRings()[ridx];
+  auto ring_info = mol.getRingInfo();
```
Comment (greglandrum) [inline Code/GraphMol/FindStereo.cpp:544]: same comment/request about code style here

**Review by greglandrum — CHANGES_REQUESTED** [review]
Thanks for digging back into the old issues and fixing this one!
The substance of the PR looks good (and the test fixtures are nice), but I would prefer if the code were stylistically similar to the (majority of the) rest of the RDKit code.

File: Code/GraphMol/FindStereo.cpp (hunk 2 above)
Comment (ricrogz) [reply Code/GraphMol/FindStereo.cpp:389]: Ok, will do.

**Review by greglandrum — APPROVED** [review]
LGTM
