### PR TITLE
Fixes #5324

### LINKED ISSUE #5324: Runtime error when writing reaction with substance group to V3000 rxnblock
**To Reproduce**

When I try to write this reaction to a v3000 rxn block:
```
from rdkit.Chem import rdChemReactions

rxn = rdChemReactions.ReactionFromSmarts("[#8]-C-C-C-C-C(-[#8])=O>>O=C-1-C-C-C-C-O-1 |Sg:n:12:n:ht,Sg:n:2:n:ht|")
v2000mb = rdChemReactions.ReactionToRxnBlock(rxn) # works fine
v3000mb = rdChemReactions.ReactionToRxnBlock(rxn, forceV3000=True) # raises RuntimeError 
```

I get this error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-2c5a5d8774ba> in <module>
      1 rxn = rdChemReactions.ReactionFromSmarts("[#8]-C-C-C-C-C(-[#8])=O>>O=C-1-C-C-C-C-O-1 |Sg:n:12:n:ht,Sg:n:2:n:ht|")
      2 v2000mb = rdChemReactions.ReactionToRxnBlock(rxn) # works fine
----> 3 v3000mb = rdChemReactions.ReactionToRxnBlock(rxn, forceV3000=True) # cannot

RuntimeError: Neither beginning nor ending atoms of bond 2 is in this SubstanceGroup.
```

**Screenshots**
Here is a screenshot of the reaction:

image

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: mac
 - Are you using conda? No

### PR DESCRIPTION
**Pull request by bp-kelley**
I believe this fixes the sgroup writing issue.

It appears that the headCrossing and tailCrossing were being filled with proper bond indices from getBondBetweenAtoms, but then looking these up in the bondIndexMap as if they were the index of the bond order when being parsed.   This was causing bad lookups when trying to get the bondType.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum hopefully this won't break any tests...

File: Code/GraphMol/SmilesParse/CXSmilesOps.cpp [hunk 1]
```diff
@@ -272,36 +272,14 @@ void finalizePolymerSGroup(RWMol &mol, SubstanceGroup &sgroup) {
     // we tried... nothing more we can do
     return;
   }
-  // bondIndexMap uses the position in the vector for the SMILES index and
-  // the value in that position as the actual bond index.
-  std::vector<int> bondIndexMap(mol.getNumBonds(), -1);
-  for (const auto bond : mol.bonds()) {
-    unsigned int smilesIdx;
-    if (bond->getPropIfPresent("_cxsmilesBondIdx", smilesIdx)) {
-      bondIndexMap[smilesIdx] = bond->getIdx();
```
Comment (bp-kelley) [inline Code/GraphMol/SmilesParse/CXSmilesOps.cpp:281]: smilesIdx could be > than mol.getNumBonds, probably due to closures.  Fortunately the code is vestigial and unused currently.

File: Code/GraphMol/ChemReactions/catch_tests.cpp [hunk 2]
```diff
@@ -1198,5 +1202,14 @@ TEST_CASE("V3K rxn blocks") {
     CHECK(rxn->getNumReactantTemplates()==rxn2->getNumReactantTemplates());
     CHECK(rxn->getNumProductTemplates()==rxn2->getNumProductTemplates());   
   }
+     
+  SECTION("githubXXXX") {
```
Comment (bp-kelley) [inline Code/GraphMol/ChemReactions/catch_tests.cpp:1206]: Add  the proper github number :)

**Comment by bp-kelley** [comment]
@greglandrum just a gentle reminder for this bug fix PR

**Comment by greglandrum** [comment]
> @greglandrum just a gentle reminder for this bug fix PR

Yep; I’m on it.

File: Code/GraphMol/ChemReactions/catch_tests.cpp [hunk 3]
```diff
@@ -1198,5 +1202,15 @@ TEST_CASE("V3K rxn blocks") {
...
   }
+     
+  SECTION("github5324") {
+    // Test sgroup in a ring - this example failed with improperr tail crossings
+    auto mol = "C-1-C-C-C-C-O-1 |Sg:n:4:n:ht|"_smarts;
+    MolOps::findSSSR(*mol);
+    auto mbk = FileParserUtils::getV3000CTAB(*mol, -1);
+    std::unique_ptr<ChemicalReaction> rxn(RxnSmartsToChemicalReaction(
+      				          ">>C-1-C-C-C-C-O-1 |Sg:n:4:n:ht|"));
+    auto rxnb = ChemicalReactionToV3KRxnBlock(*rxn);
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/catch_tests.cpp:1213]: I think it makes sense to include a correctness test here too:
```suggestion
    auto rxnb = ChemicalReactionToV3KRxnBlock(*rxn);
    CHECK(rxnb.find("ATOMS=(1 5) XBONDS=(2 4 5) XBHEAD=(1 4) XBCORR=(2 4 5)")!=std::string::npos);
```

File: Code/GraphMol/ChemReactions/catch_tests.cpp [hunk 4]
```diff
@@ -1198,5 +1202,15 @@ TEST_CASE("V3K rxn blocks") {
     CHECK(rxn->getNumReactantTemplates()==rxn2->getNumReactantTemplates());
     CHECK(rxn->getNumProductTemplates()==rxn2->getNumProductTemplates());   
   }
+     
+  SECTION("github5324") {
+    // Test sgroup in a ring - this example failed with improperr tail crossings
+    auto mol = "C-1-C-C-C-C-O-1 |Sg:n:4:n:ht|"_smarts;
+    MolOps::findSSSR(*mol);
+    auto mbk = FileParserUtils::getV3000CTAB(*mol, -1);
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/catch_tests.cpp:1210]: Please add a correctness test:
```
```
```suggestion
    auto mbk = FileParserUtils::getV3000CTAB(*mol, -1);
    CHECK(mbk.find("ATOMS=(1 5) XBONDS=(2 4 5) XBHEAD=(1 4) XBCORR=(2 4 5)")!=std::string::npos);
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
small changes to make the tests more strict

**Review by greglandrum — APPROVED** [review]
LGTM
