### PR TITLE
Fixes #4787

### LINKED ISSUE #4787: [Cartridge]: qmol_from_ctab and qmol_from_smiles are sanitizing molecules
**Describe the bug**

The cartridge functions `qmol_from_ctab()` and `qmol_from_smiles()` sanitize the molecules as they read them in. This shouldn't be done with queries.

**Configuration (please complete the following information):**
 - RDKit version: current releases and master
 - OS: all

Here's the mailing list thread: https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg10899.html

### PR DESCRIPTION
**Pull request by greglandrum**
The problem here was that `qmol_from_ctab()` and `qmol_from_smiles()` were sanitizing the molecules.

This gets rid of the sanitization and just does a property cache update and aromaticity perception.

### CODE REVIEW

File: Code/PgSQL/rdkit/adapter.cpp [hunk 1]
```diff
@@ -2108,7 +2111,7 @@ extern "C" char *findMCSsmiles(char *smiles, char *params) {
   while (*s && *s <= ' ') {
     s++;
   }
-  while (s < s_end && *s > ' ') {
+  while (s<s_end && * s> ' ') {
```
Comment (ptosco) [inline Code/PgSQL/rdkit/adapter.cpp:2114]:
```suggestion
  while (s < s_end && *s > ' ') {
```
This change seems unintentional (`clang-format` gone wrong?)

**Review by ptosco — APPROVED** [review]
LGTM, thanks for taking care of this.

File: Code/PgSQL/rdkit/adapter.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/PgSQL/rdkit/adapter.cpp:2114]: Indeed. Thanks for noticing that.
