### PR TITLE
Fix issue 9165 & 9166

### LINKED ISSUE #9165: DistGeom: disulfide pattern matches non-disulfide *S-S* (e.g., disulfite)
Within the 1-4 distance calculation, the current code assumes any S-S to be a disulfide, i.e., a torsion angle of 90 degrees, which should not be the case, for example, for disulfate.

### PR DESCRIPTION
**Pull request by kabu00002**
#### Reference Issue
Fixes #9165 & #9166 

#### What does this implement/fix? 
#9165: Detect disulfide by checking for adjacent S with each a degree of 2

#9166: Higher-order distance bounds now cannot overwrite lower-order ones (e.g., 1-2 distance bounds cannot be overwritten by 1-3, 1-4, and 1-5 distance bounds); however, for bounds of the same level/order, the less strict upper and lower bounds are chosen. Note that this might be changed such that the stricter ones are chosen, but this should only be done if one is sure that the bond (and torsion angles) and bond lengths are consistent.

### CODE REVIEW

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 1]
```diff
@@ -7,21 +7,22 @@
...
-#include <DistGeom/BoundsMatrix.h>
 #include "BoundsMatrixBuilder.h"
-#include <GraphMol/ForceFieldHelpers/UFF/AtomTyper.h>
+#include <DistGeom/BoundsMatrix.h>
 #include <ForceField/UFF/BondStretch.h>
 #include <Geometry/Utils.h>
+#include <GraphMol/Chirality.h>
+#include <GraphMol/ForceFieldHelpers/UFF/AtomTyper.h>
+#include <GraphMol/RDKitBase.h>
+#include <bitset>
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: I don't think you need this.

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 2]
```diff
@@ -7,21 +7,22 @@
 //  which is included in the file license.txt, found at the root
 //  of the RDKit source tree.
 //
-#include <GraphMol/RDKitBase.h>
-#include <GraphMol/Chirality.h>
-#include <DistGeom/BoundsMatrix.h>
 #include "BoundsMatrixBuilder.h"
-#include <GraphMol/ForceFieldHelpers/UFF/AtomTyper.h>
+#include <DistGeom/BoundsMatrix.h>
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp:12]: General comment for future PRs: I guess you have something installed that automatically reorders headers. Please don't do this in our code. It doesn't make code significantly more maintainable, but it does make PRs trickier to review.

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 3]
```diff
@@ -33,6 +34,7 @@ const double GEN_DIST_TOL = 0.06;  //  a general distance tolerance
 const double DIST15_TOL = 0.08;
 const double VDW_SCALE_15 = 0.7;
 const double MAX_UPPER = 1000.0;
+constexpr bool OVERWRITE_IF_BETTER_14 = false;
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: You aren't using this variable.
```suggestion
```

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 4]
```diff
@@ -75,17 +83,40 @@ class ComputedData {
...
+    //   case DistType::DIST12:
+    //     return visited12Bounds[pid];
+    //   case DistType::DIST13:
+    //     return visited12Bounds[pid] || visited13Bounds[pid];
+    //   case DistType::DIST14:
+    //     return visited12Bounds[pid] || visited13Bounds[pid] ||
+    //            visited14Bounds[pid];
+    //   default:
+    //     return false;
+    // }
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: Please remove the unused code

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 5]
```diff
@@ -174,27 +205,44 @@ void setLowerBoundVDW(const ROMol &mol, DistGeom::BoundsMatPtr mmat,
...
   CHECK_INVARIANT(ub > lb, "upper bound not greater than lower bound");
   CHECK_INVARIANT(lb > DIST12_DELTA || clb > DIST12_DELTA, "bad lower bound");
 
-  if (clb <= DIST12_DELTA) {
-    mmat->setLowerBound(i, j, lb);
-  } else {
-    if ((lb < clb) && (lb > DIST12_DELTA)) {
-      mmat->setLowerBound(i, j, lb);  // conservative bound setting
+  // Note: setIfBetter should ONLY be set if the distances are consistent;
+  // currently this is not the case, therefore, for now, we are persimistic on
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]:
```suggestion
  // currently this is not the case, therefore, for now, we are pessimistic on
```

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 6]
```diff
@@ -315,6 +367,8 @@ void _set13BoundsHelper(unsigned int aid1, unsigned int aid, unsigned int aid3,
   }
   auto du = dl + distTol;
   dl -= distTol;
+  // mmat->setLowerBoundIfBetter(aid1, aid3, dl);
+  // mmat->setUpperBoundIfBetter(aid1, aid3, du);
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: Please remove unused code

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 7]
```diff
@@ -697,12 +790,15 @@ void _setInRing14Bounds(const ROMol &mol, const Bond *bnd1, const Bond *bnd2,
       dl -= GEN_DIST_TOL;
       du += GEN_DIST_TOL;
     }
-    path14.type = Path14Configuration::OTHER;
   }
-
   // std::cerr << "7: " << aid1 << "-" << aid4 << std::endl;
+
+  // Note: we do not set visitedBounds here since 1-4 can be overwritten by
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: This comment is no longer correct

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 8]
```diff
@@ -788,10 +892,16 @@ void _setTwoInSameRing14Bounds(const ROMol &mol, const Bond *bnd1,
     }
     path14.type = Path14Configuration::OTHER;
   }
+
   // std::cerr << "1: " << aid1 << "-" << aid4 << ": " << dl << " -> " << du
   //           << std::endl;
   _checkAndSetBounds(aid1, aid4, dl, du, mmat);
+  // Note: we do not set visitedBounds here since 1-4 can be overwritten by
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: this comment is no longer correct

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 9]
```diff
@@ -1184,8 +1302,11 @@ void _setChain14Bounds(const ROMol &mol, const Bond *bnd1, const Bond *bnd2,
       dl -= GEN_DIST_TOL;
       du += GEN_DIST_TOL;
     }
+    // mmat->setLowerBoundIfBetter(aid1, aid4, dl);
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: please remove unused code

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 10]
```diff
@@ -1328,7 +1457,10 @@ void _setMacrocycleTwoInSameRing14Bounds(const ROMol &mol, const Bond *bnd1,
   // std::cerr << "1: " << aid1 << "-" << aid4 << ": " << dl << " -> " << du
   //           << std::endl;
   _checkAndSetBounds(aid1, aid4, dl, du, mmat);
+  // mmat->setLowerBoundIfBetter(aid1, aid4, dl);
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: please remove unused code

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 11]
```diff
@@ -1426,7 +1566,8 @@ void _setMacrocycleAllInSameRing14Bounds(const ROMol &mol, const Bond *bnd1,
       }
       break;
     case Bond::SINGLE:
-      if ((atm2->getAtomicNum() == 16) && (atm3->getAtomicNum() == 16)) {
+      if ((atm2->getAtomicNum() == 16) && (atm3->getAtomicNum() == 16) &&
+          (atm2->getDegree() == 2) && (atm3->getDegree() == 2)) {
         // this is *S-S* situation
         // FIX: this cannot be right is sulfur has more than two coordinated
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: I think this FIX can now be removed, right?

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 12]
```diff
@@ -1056,7 +1173,8 @@ void _setChain14Bounds(const ROMol &mol, const Bond *bnd1, const Bond *bnd2,
...
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp]: I think this FIX is no longer correct and can be removed?

File: Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp [hunk 13]
```diff
@@ -1982,6 +2145,14 @@ void _set15BoundsHelper(const ROMol &mol, unsigned int bid1, unsigned int bid2,
         continue;
       }
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp:2114]: Please remove unused code

File: Code/GraphMol/DistGeomHelpers/catch_tests.cpp [hunk 14]
```diff
@@ -1236,6 +1240,231 @@ TEST_CASE("allenes and cumulenes") {
...
+
+      // 1-3 to angle
+      // double distAngl12 = (bm->getUpperBound(0, 3) + bm->getLowerBound(0, 3))
+      // / 2; double distAngl23 = (bm->getUpperBound(2, 5) +
+      // bm->getLowerBound(2, 5)) / 2;
+
+      // std::cout << std::pow(bl1, 2) + std::pow(bl2, 2) - std::pow(distAngl12,
+      // 2) << "; " << 2*bl1*bl2 << std::endl;
+
+      // TODO change this
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/catch_tests.cpp:1307]: ???

File: Code/GraphMol/DistGeomHelpers/catch_tests.cpp [hunk 15]
```diff
@@ -1236,6 +1240,231 @@ TEST_CASE("allenes and cumulenes") {
...
+    {
+      auto m = "C1CC1"_smiles;
+      REQUIRE(m);
+      MolOps::addHs(*m);
+
+      DistGeom::BoundsMatPtr bm{new DistGeom::BoundsMatrix(m->getNumAtoms())};
+      DGeomHelpers::initBoundsMat(bm, 0.0, 1000.0);
+
+      // setting 1-3 distances
+      DGeomHelpers::setTopolBounds(*m, bm, false, false, false, true, false,
```
Comment (greglandrum) [inline Code/GraphMol/DistGeomHelpers/catch_tests.cpp]: it's friendlier to define constants with sensible names for all of the bool arguments here. Something like:
```
const bool set15bounds = false;
const bool scaleVDW = false;
...
DGeomHelpers::setTopolBounds(*m, bm2, set15bounds, scaleVDW, ...
```

Comment (greglandrum) [reply Code/GraphMol/DistGeomHelpers/catch_tests.cpp]: This suggestion applies to all of your calls to setTopolBounds

**Comment by greglandrum** [comment]
Thanks @kabu00002 
I'll merge this after the CI builds go through.
