### PR TITLE
Fixes issue 1761

### LINKED ISSUE #1761: Casting int to uint in MorganFingerprintHelper leads to unexpected behaviour.
Using python (probably using c++ too), you can pass a negative value for _radius_ and _nBits_ through to the function _MorganFingerprintHelper_ in _rdMolDescriptors.cpp_ . This leads to them being casted to the max value of int minus the passed value. This might be unintended behaviour. I suggest throwing an error at one point of the chain, to let the user know, that he put a negative value there. 
Currently, passing a negative value for _radius_ or _nBits_ just leads to the program freezing (or taking extremely long to finish) without any feedback to the user that something might have gone wrong.

### PR DESCRIPTION
**Pull request by MaxGreil**
#### Reference Issue
Fixes #1761

#### What does this implement/fix? Explain your changes.
- Changed the types of arguments radius and nBits from function MorganFingerprintHelper from int to unsigned int. 
- The C++ MorganFingerprint code now throws a ValueErrorException
- Implemented new test for control

#### Any other comments?
I also checked fingeprint functions `GetAtomPairFingerprint, GetHashedAtomPairFingerprint, GetHashedAtomPairFingerprintAsBitVect, GetTopologicalTorsionFingerprint, GetHashedTopologicalTorsionFingerprint, GetHashedTopologicalTorsionFingerprintAsBitVect` and `GetMorganFingerprintBV` and changed int to unsigned int when found.

However, I have a question: 
In `rdkit/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp` in line 469 function `MorganFingerprintHelper` is called with `nBits = -1`. This variable is then used in line 382 to call either function `RDKit::MorganFingerprints::getFingerprint` if `nBits < 0` or function `RDKit::MorganFingerprints::getHashedFingerprint` otherwise. 

With my changes from int to unsigned int for `nBits` now `nBits` is always greater 0 and therefore function `RDKit::MorganFingerprints::getHashedFingerprint` is always used. But with this behavior parameter `useCounts` is always set to `true`.

This leads to the change in `rdkit/Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py` line 173 because now parameter `useCounts` can not be set to `false`.

What should I do about this?

### CODE REVIEW

**Comment by MaxGreil** [comment]
I think I solved my question above with the changes in my last commit.

File: Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp [hunk 1]
```diff
@@ -512,8 +512,9 @@ ExplicitBitVect *GetMorganFingerprintBV(
   }
   ExplicitBitVect *res;
   res = RDKit::MorganFingerprints::getFingerprintAsBitVect(
-      mol, static_cast<unsigned int>(radius), nBits, invars, froms.get(),
-      useChirality, useBondTypes, false, bitInfoMap,
+      mol, static_cast<unsigned int>(radius), static_cast<unsigned int>(nBits),
```
Comment (greglandrum) [inline Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp:515]: since radius and nBits are both unsigned now, you shouldn't need these casts at all:
```suggestion
      mol, radius, nBits,
```

File: Code/GraphMol/Fingerprints/MorganFingerprints.cpp [hunk 2]
```diff
@@ -315,6 +316,9 @@ SparseIntVect<uint32_t> *getHashedFingerprint(
     std::vector<uint32_t> *invariants, const std::vector<uint32_t> *fromAtoms,
     bool useChirality, bool useBondTypes, bool onlyNonzeroInvariants,
     BitInfoMap *atomsSettingBits, bool includeRedundantEnvironments) {
+  if(nBits == 0) {
```
Comment (greglandrum) [inline Code/GraphMol/Fingerprints/MorganFingerprints.cpp:319]: You've added a test for this in the Python wrapper (which is great, thanks!), but it would also not be bad to add one in the C++ tests.
This isn't necessary, but if you want to do it, the logical place would be to add a new `TEST_CASE` to `Code/Fingerprints/catch_tests.cpp`

**Review by greglandrum — CHANGES_REQUESTED** [review]
One cleanup request and one suggestion for a new test.

File: Code/GraphMol/Fingerprints/MorganFingerprints.cpp (hunk 2 above)
Comment (MaxGreil) [reply Code/GraphMol/Fingerprints/MorganFingerprints.cpp:319]: Hi Greg, I created a new C++ test case. Can you have a look at it?

**Review by greglandrum — APPROVED** [review]

**Comment by greglandrum** [comment]
Thanks @MaxGreil
