### PR TITLE
fixes #4345

### LINKED ISSUE #4345: MolBlock writer gives non-stereo double bonds "unspecified" parity
**Describe the bug**
When writing to molblock or sdf or sd or whatever you call the format :), double bonds with no stereochemistry are given the "either" bond parity. I think that this is misleading - non-stereo bonds are distinct from stereogenic bonds for which we don't know whether the bond is _E_ or _Z_.

**To Reproduce**

unexpected_cross_bond

The generated molblock is:

```
     RDKit          2D

  6  5  0  0  0  0  0  0  0  0999 V2000
    0.4304    1.2508    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.4326    0.2508    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2996   -0.2474    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.4326   -0.2508    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4304   -1.2508    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -1.2996    0.2474    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  2  3
  4  5  1  0
  4  6  1  0
M  END
```

**Expected behavior**
I'd expect both of these to have flat bonds in the depiction rather than a crossed bond. I'd expect the parity of the bond between atoms 2 & 4 to be 0.

**Configuration (please complete the following information):**
 - RDKit version: 2053a98ffa93ab7e7
 - OS: Mac
 - Python version (if relevant): 3.7
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Built from source

### PR DESCRIPTION
**Pull request by greglandrum**
we will also eventually need a version of this which works with the newer stereo perception code.

### CODE REVIEW

File: Code/GraphMol/FileParsers/MolFileWriter.cpp [hunk 1]
```diff
@@ -800,27 +800,60 @@ void GetMolFileBondStereoInfo(const Bond *bond, const INT_MAP_INT &wedgeBonds,
             ROMol::OEDGE_ITER beg, end;
             boost::tie(beg, end) =
                 bond->getOwningMol().getAtomBonds(bond->getBeginAtom());
+            bool atomHasDuplicateRanks = false;
```
Comment (ricrogz) [inline Code/GraphMol/FileParsers/MolFileWriter.cpp:803]: I'm being picky here, but since it's not the same atom that has duplicate ranks, I'd name this `nbrsHaveDuplicateRanks`.

File: Code/GraphMol/FileParsers/MolFileWriter.cpp [hunk 2]
```diff
@@ -800,27 +800,60 @@ void GetMolFileBondStereoInfo(const Bond *bond, const INT_MAP_INT &wedgeBonds,
...
+            std::vector<int> nbrRanks;
             while (beg != end && !nbrHasDir) {
```
Comment (ricrogz) [inline Code/GraphMol/FileParsers/MolFileWriter.cpp:805]: While you are here, would you mind turning this into a boost range iterator?

File: Code/GraphMol/FileParsers/MolFileWriter.cpp [hunk 3]
```diff
@@ -800,27 +800,60 @@ void GetMolFileBondStereoInfo(const Bond *bond, const INT_MAP_INT &wedgeBonds,
...
-              const Bond *nbrBond = bond->getOwningMol()[*beg];
-              if (nbrBond->getBondType() == Bond::SINGLE &&
-                  (nbrBond->getBondDir() == Bond::ENDUPRIGHT ||
-                   nbrBond->getBondDir() == Bond::ENDDOWNRIGHT)) {
-                nbrHasDir = true;
+              const auto nbrBond = bond->getOwningMol()[*beg];
```
Comment (ricrogz) [inline Code/GraphMol/FileParsers/MolFileWriter.cpp:806]: We are doing the same for the begin and the end atom, right? For the sake of maintainability, I think this has reached the point where it is worth abstracting into a separate function and calling it on each end.

**Review by ricrogz — CHANGES_REQUESTED** [review]

**Review by ricrogz — APPROVED** [review]
