### PR TITLE
Fixes #8284

### LINKED ISSUE #8284: Multithreaded mol reader can hang when not iterating through the whole file
**Describe the bug**
When breaking out of a loop reading multi threaded mol reader early, an exception can be thrown or the program can hang.

**To Reproduce**
As reported in #8279 

```
from rdkit.Chem import MultithreadedSDMolSupplier
import os
lib = os.path.join(
    os.getenv("RDBASE"), "Data", "NCI",  "first_200.props.sdf")

for c in range(2):
    with MultithreadedSDMolSupplier(lib) as supplier:
        for i,m in enumerate(supplier):
            if i>=3: break
        
        print("done", c)
```

When it doesn't hang, it throws a pre condition violation

```
****
Pre-condition Violation
no stream
Violation occurred on line 242 in file C:\rdkit\build\temp.win-amd64-cpython-312\Release\rdkit\Code\GraphMol\FileParsers\MultithreadedSDMolSupplier.cpp
Failed Expression: dp_inStream
****
```

**Configuration (please complete the following information):**
 - RDKit version: 
 - OS: windows
 - 2024.09.5

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #8284 

The MultiThreadedMolSupplier wasn't properly clearing the input queue before ending threads.  This caused a deadlock in the inputQueue where a thread was blocking because the queue was full and couldn't properly end.

The solution was to add a df_forceStop atomic boolean (although we could probably reuse df_started) and to stop the readers when this is set and also stop the writers.

So the procedure is:

1. df_forceStop = true
2. pop items of the inputQueue
4. endThreads
6. now we can clear the input queue and output queue
8. finally close any input stream.

One issue is that we can't close the SDMolSupplier streams until the threads are shut down and destructors are called last to first, so we add a closeStreams protected virtual function that the base destructor can call.

As a cherry on top, we place all of this in the virtual "close" function overridden from MolSupplier since calling the base one would cause hangs and seg faults.

Testing code:

```
from rdkit import Chem

large_file = "/Users/brian/devel/rdkit/External/pubchem_shape/test_data/bulk.pubchem.sdf"
try:
    # this used to segfault
    for mol in Chem.MultithreadedSDMolSupplier("fakefile"):
        pass
except:
    pass

for mol in Chem.MultithreadedSDMolSupplier(large_file):
    break

suppl = Chem.MultithreadedSDMolSupplier(large_file)
it = iter(suppl)

next(it)
del suppl
while next(it):
    print("*",end="")

suppl = Chem.MultithreadedSDMolSupplier(large_file)
it = iter(suppl)

next(it)
asdf
```

### CODE REVIEW

**Comment by greglandrum** [comment]
I believe that was fixed

**Comment by bp-kelley** [comment]
@greglandrum it's better, but still chasing a 1/1000 threading bug though.

File: Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h [hunk 1]
```diff
@@ -30,7 +30,7 @@ class RDKIT_FILEPARSERS_EXPORT MultithreadedSDMolSupplier
       const MolFileParserParams &parseParams = MolFileParserParams());
 
   MultithreadedSDMolSupplier();
-  ~MultithreadedSDMolSupplier() override;
+  virtual ~MultithreadedSDMolSupplier() {close();}
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h:33]: I think the dtor here only needs to be virtual if you are planning on inheriting from this class, which I don't think we are.

File: Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h [hunk 2]
```diff
@@ -28,7 +28,7 @@ class RDKIT_FILEPARSERS_EXPORT MultithreadedSmilesMolSupplier
       const Parameters &params = Parameters(),
       const SmilesMolSupplierParams &parseParams = SmilesMolSupplierParams());
   MultithreadedSmilesMolSupplier();
-  ~MultithreadedSmilesMolSupplier() override;
+  virtual ~MultithreadedSmilesMolSupplier() {close();};
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h:31]: I think the dtor here only needs to be virtual if you are planning on inheriting from this class, which I don't think we are.

File: Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp [hunk 3]
```diff
@@ -69,9 +104,16 @@ void MultithreadedMolSupplier::writer() {
...
   }
-  if (d_threadCounter != d_params.numWriterThreads) {
+
+  // we need a lock here otherwise two threads
+  //  can increment d_threadCounter even though it's
+  //  atomic.
+  d_threadCounterMutex.lock();
+  if (d_threadCounter < d_params.numWriterThreads) {
     ++d_threadCounter;
+    d_threadCounterMutex.unlock();
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp:116]: can't this (and the same code two lines below) move outside the if?

File: Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp [hunk 4]
```diff
@@ -45,22 +79,23 @@ void MultithreadedMolSupplier::reader() {
       }
     }
     auto r = std::make_tuple(record, lineNum, index);
-    d_inputQueue->push(r);
+    if (!df_forceStop) d_inputQueue->push(r);
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp]:
```suggestion
    if (!df_forceStop) {
      d_inputQueue->push(r);
    }
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
small suggestions and questions

File: Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h:33]: If the parent classes destructor is virtual, any child destructor will also be virtual.  That being said, any class with a virtual function needs a virtual destructor so I like to be explicit.  Also you can't really override a virtual destructor, as they all are have to be called on the destruction chain.

tldr; it's not necessary to specify but the destructor needs to be virtual

File: Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h (hunk 2 above)
Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h:31]: See previous comment

File: Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp (hunk 3 above)
Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp:116]: No, you need to unlock the threadCounterMutex before you call setDone as this notifies the queue.  Doing it the other way can deadlock I think.

Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp:116]: It's worth a comment here I think

File: Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h:33]: I believe that at least some of this is not true.
If you derive from a class, then the dtor of the base needs to be virtual, but the derived class does not need to have a virtual dtor.
Simple example:
```
#include <iostream>

class Base {
 public:
  virtual ~Base() { std::cerr << "Base destructor called" << std::endl; };
};

class Derived : public Base {
 public:
  ~Derived() override {
    std::cerr << "Derived destructor called" << std::endl;
  };
};

int main() {
  Base* b = new Derived();
  std::cerr << "delete b;" << std::endl;
  delete b;  // This will call the Derived destructor, followed by the Base
             // destructor
}
```

This outputs:
```
delete b;
Derived destructor called
Base destructor called
```
with both g++ and MSVC++

Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h:33]: It doesn’t need to be declared virtual but if the parent class has a virtual destructor it is virtual by default.  I got into the habit of always declaring virtual destructors mainly when the parent class doesn’t define one then the destructor becomes non virtual which is no bueno.

Comment (bp-kelley) [reply Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h:33]: But this is semantics, in this case they both have the same behavior so if it bugs you I can remove it.

Comment (greglandrum) [reply Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h:33]: Na, if you are sure that it's correct then I'm fine with it.

File: Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp (hunk 3 above)
Comment (greglandrum) [reply Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp:116]: > It's worth a comment here I think

I think the PR is ready to merge once this note is in.
