### PR TITLE
fixes #6416

### LINKED ISSUE #6416: V3000 structure segfaults when converting to SVG
RDKit 2023 Q1 Release via PyPi, Python 3.10.11 Windows 11 x64.

The following V3000 structure segfaults when converting to SVG.

Code:

mol = Chem.MolFromMolBlock(moldata)
d2d = MolDraw2DSVG(300, 300)
d2d.DrawMolecule(mol)
d2d.FinishDrawing()
svg = d2d.GetDrawingText()

If moldata equals the following V3000, it segfaults. The same happens when using the mol_to_svg() function of the cartridge built from the 2023 Q1 sources.

Marvin JS online, for example, can display it without problems.
-----------------------------------------------------------------------------------------------------------

```
168010013
     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 35 36 0 0 1
M  V30 BEGIN ATOM
M  V30 1 F 11.000000 -1.318000 0.000000 0
M  V30 2 F 12.000000 -2.318000 0.000000 0
M  V30 3 F 11.000000 -3.318000 0.000000 0
M  V30 4 O 6.207100 2.719200 0.000000 0
M  V30 5 O 6.500000 0.280000 0.000000 0
M  V30 6 O 6.500000 -1.452000 0.000000 0
M  V30 7 N 8.000000 -0.586000 0.000000 0
M  V30 8 C 3.500000 2.012100 0.000000 0
M  V30 9 C 4.000000 1.146000 0.000000 0
M  V30 10 C 2.500000 2.012100 0.000000 0
M  V30 11 C 5.500000 2.012100 0.000000 0
M  V30 12 C 4.000000 2.878100 0.000000 0
M  V30 13 C 2.000000 1.146000 0.000000 0
M  V30 14 C 5.000000 1.146000 0.000000 0
M  V30 15 C 5.000000 2.878100 0.000000 0
M  V30 16 C 4.500000 2.012100 0.000000 0
M  V30 17 C 3.000000 1.146000 0.000000 0
M  V30 18 C 5.500000 0.280000 0.000000 0
M  V30 19 C 2.500000 0.280000 0.000000 0
M  V30 20 C 6.465900 1.753200 0.000000 0
M  V30 21 C 5.000000 -0.586000 0.000000 0
M  V30 22 C 2.500000 -1.452000 0.000000 0
M  V30 23 C 3.500000 -1.452000 0.000000 0
M  V30 24 C 2.000000 -0.586000 0.000000 0
M  V30 25 C 4.000000 -0.586000 0.000000 0
M  V30 26 C 3.500000 0.280000 0.000000 0
M  V30 27 C 3.000000 -0.586000 0.000000 0
M  V30 28 C 7.000000 -0.586000 0.000000 0
M  V30 29 C 8.500000 -1.452000 0.000000 0
M  V30 30 C 9.500000 -1.452000 0.000000 0
M  V30 31 C 8.000000 -2.318000 0.000000 0
M  V30 32 C 10.000000 -2.318000 0.000000 0
M  V30 33 C 8.500000 -3.184100 0.000000 0
M  V30 34 C 9.500000 -3.184100 0.000000 0
M  V30 35 C 11.000000 -2.318000 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 35
M  V30 2 1 2 35
M  V30 3 1 3 35
M  V30 4 1 4 11
M  V30 5 1 5 18
M  V30 6 1 5 28
M  V30 7 2 6 28
M  V30 8 1 7 28
M  V30 9 1 7 29
M  V30 10 1 8 9
M  V30 11 1 8 10
M  V30 12 1 8 12
M  V30 13 1 9 16
M  V30 14 1 9 17
M  V30 15 1 10 13
M  V30 16 1 11 14
M  V30 17 1 11 15
M  V30 18 1 11 20
M  V30 19 2 12 15 CFG=2
M  V30 20 1 13 19
M  V30 21 1 14 18
M  V30 22 1 18 21
M  V30 23 2 19 24 CFG=2
M  V30 24 1 19 26
M  V30 25 2 21 25 CFG=2
M  V30 26 1 22 23
M  V30 27 1 22 24
M  V30 28 1 23 25
M  V30 29 1 25 27
M  V30 30 2 29 30
M  V30 31 1 29 31
M  V30 32 1 30 32
M  V30 33 2 31 33
M  V30 34 2 32 34
M  V30 35 1 32 35
M  V30 36 1 33 34
M  V30 END BOND
M  V30 END CTAB
M  END
```
[crash_svg.mol.txt](https://github.com/rdkit/rdkit/files/11610183/crash_svg.mol.txt)

### PR DESCRIPTION
**Pull request by ptosco**
Small PR to fix #6416, which was caused by dereferencing a `nullptr` returned by `otherNeighbor()` without checking it.
After this PR the molecule is rendered as expected without segfaulting:
image

### CODE REVIEW

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 1]
```diff
@@ -2913,7 +2913,7 @@ void DrawMol::bondNonRing(const Bond &bond, double offset, Point2D &l2s,
     const Atom *thirdAtom = nullptr;
     for (auto i = 1u; i < at1->getDegree(); ++i) {
       thirdAtom = otherNeighbor(at1, at2, i, *drawMol_);
-      if (!areBondsParallel(atCds_[at1->getIdx()], atCds_[at2->getIdx()],
+      if (thirdAtom && !areBondsParallel(atCds_[at1->getIdx()], atCds_[at2->getIdx()],
```
Comment (DavidACosgrove) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:2916]: Ooops. Sorry!

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @ptosco... you saved me from the debugging exercise myself.
