### PR TITLE
Fixes #5433

### LINKED ISSUE #5433: Pre-condition Violation - Failed Expression: dir == Bond::ENDUPRIGHT || dir == Bond::ENDDOWNRIGHT
**Describe the bug**
Trying to open a specific molfile (with sanitize=True) raises:
```
****
Pre-condition Violation
bad dir
Violation occurred on line 382 in file /project/build/temp.linux-x86_64-cpython-310/rdkit/Code/GraphMol/Chirality.cpp
Failed Expression: dir == Bond::ENDUPRIGHT || dir == Bond::ENDDOWNRIGHT
****

``` 

**To Reproduce**
I simplified the failing molecule. This python code should trigger the error:
```python
from rdkit import Chem
mol_file = """
  SomeFailingMolFile

  8  8  0  0  1  0            999 V2000
   -0.7145    1.2375    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.8250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -1.6500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  6  0  0  0
  2  3  2  0  0  0  0
  3  4  1  4  0  0  0
  3  8  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  2  0  0  0  0
M  END
"""

Chem.MolFromMolBlock(mol_file, sanitize=False)  # This works

Chem.MolFromMolBlock(mol_file, sanitize=True) # This doesn't
``` 

**Expected behavior**
Expecting a specific error if the molfile is invalid (which is possible), but not an un-catchable error.

**Configuration (please complete the following information):**
 - RDKit version: Master and 2022.3.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 - OS: Ubuntu 20.04 and 22.04
 - Python version (if relevant): Not relevant, seen the bug both in c++ and Python 3.10
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Pip, but same error with c++ code using rdkit from master

### PR DESCRIPTION
**Pull request by greglandrum**
This should have been handled as part of #2696, but I missed it then.

Also includes a minor bit of refactoring so this kind of oversight doesn't happen again

### CODE REVIEW

File: Code/GraphMol/Chirality.cpp [hunk 1]
```diff
@@ -429,52 +429,34 @@ bool isLinearArrangement(const RDGeom::Point3D &v1, const RDGeom::Point3D &v2) {
...
-
-  Bond *bond1 = nullptr, *obond1 = nullptr;
-  bool squiggleBondSeen = false;
-  bool doubleBondSeen = false;
-  for (const auto tBond : mol.atomBonds(dblBond->getBeginAtom())) {
+void controllingBondFromAtom(ROMol &mol, boost::dynamic_bitset<> &needsDir,
+                             std::vector<unsigned int> &singleBondCounts,
+                             Bond *dblBond, Atom *atom, Bond *&bond,
+                             Bond *&obond, bool &squiggleBondSeen,
+                             bool &doubleBondSeen) {
```
Comment (ricrogz) [inline Code/GraphMol/Chirality.cpp:436]: I think `mol`, `needsDir`, `singleBondCounts`, `dblBond` and `atom` could be `const`.

**Review by ricrogz — APPROVED** [review]
I just have a minor suggestion; looks good otherwise.
