### PR TITLE
Recursive Substructure Search Deadlock

### LINKED ISSUE #4651: Subsequent call to rdChemReactions.ChemicalReaction.RunReactants will block indefinitely.
**Describe the bug**
Calling `rdChemReactions.ChemicalReaction` with the following SMIRKS will make any subsequent calls to `RunReactants` reusing the same `rdChemReactions.ChemicalReaction` object block indefinitely. 
Work-around for now is to reinitialize a reaction before every use.

**To Reproduce**
```python
import numpy as np
import rdkit
from rdkit.Chem import rdChemReactions
from rdkit.Chem.rdChemReactions import PreprocessReaction 
from rdkit.Chem import MolFromSmarts, MolFromSmiles
from rdkit.Chem import MolToSmarts, MolToSmiles

from typing import Tuple

def load_smirks(smirks: str) -> rdChemReactions.ChemicalReaction:
    func = rdChemReactions.ReactionFromSmarts(smirks)

    rdChemReactions.SanitizeRxn(func)
    func.Initialize()

    n_warnings, n_errors, n_reactants, n_products, labels = PreprocessReaction(func)
    if n_errors != 0:
        raise ValueError("Error in reaction initialization")
    return func

mol_sulfonylchloride = MolFromSmiles("Nc1c(CCCSNCC)cc(cc1)S(=O)(=O)Cl")
mol_amine = MolFromSmiles("Nc2cc(C)on2")
mol_sulfonamide = MolFromSmiles("CCNSCCCc1cc(S(=O)(=O)Nc2cc(C)on2)ccc1N")

smirks_fwd = (
    "[S;$(S(=O)(=O)[C,c,N]):1](=O)(=O)(-[Cl])"
     "."
     "[N;$([N&H2&D1,N&H1&D2])"
     # N aliphatic and not aromatic bond to carbon
     "&$(N(-&!@[#6]))"
     "&!$(N-C=[O,N,S]):2]"
     ">>"
     "[S:1](=O)(=O)-[N+0:2]"
)

smirks_reverse = ">>".join(smirks_fwd.split(">>")[::-1])

reaction_fwd = load_smirks(smirks_fwd)
reaction_reverse = load_smirks(smirks_reverse)


product = reaction_fwd.RunReactants((mol_sulfonylchloride, mol_amine))[0][0]
print("reaction_fwd", MolToSmiles(product))

reagent_sulfonylchloride, reagent_amine = reaction_reverse.RunReactants((mol_sulfonamide,))[0]

# trigger bug
print("trigger bug and mess up reaction_fwd object")
try:
    product = reaction_fwd.RunReactants((reagent_sulfonylchloride, reagent_amine))[0]
except RuntimeError as e:
    print(e)

print("call messed up reaction_fwd, this will inf loop")
# this will now lead to unstable behavior and never return
product = reaction_fwd.RunReactants((mol_sulfonylchloride, mol_amine))[0][0]
print(MolToSmiles(product))
```

**Expected behavior**
`product = reaction_fwd.RunReactants((mol_sulfonylchloride, mol_amine))[0][0]`
Should return.

**Configuration (please complete the following information):**
```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
OSX, 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
Python 3.8.6
rdkit                     2021.03.5        py38h0bd8f9b_0    conda-forge
```

Cheers,
Jacob

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #4651 

This is a simple fix to a nasty issue.   If an exception is thrown in the recursive bowels of a substructure search, the mutexes are not cleared.  This creates a deadlock on the second call.

### CODE REVIEW

**Comment by greglandrum** [comment]
> The test failures don't appear to be related.

yeah, there seems to be some problem with the windows CI builds 
<sigh>

File: Code/GraphMol/Substruct/SubstructMatch.cpp [hunk 1]
```diff
@@ -427,6 +427,25 @@ void ResSubstructMatchHelper_(const ResSubstructMatchHelperArgs_ &args,
     delete mol;
   }
 };
+
+struct RecursiveLocker {
+  std::vector<RecursiveStructureQuery *> locked;
+  RecursiveLocker(const ROMol &query, const bool recursionPossible) :
+    locked() {
```
Comment (greglandrum) [inline Code/GraphMol/Substruct/SubstructMatch.cpp:434]: I don't think the empty initialization is necessary.
```suggestion
  RecursiveLocker(const ROMol &query, const bool recursionPossible) {
```

File: Code/GraphMol/Substruct/SubstructMatch.cpp [hunk 2]
```diff
@@ -439,58 +458,50 @@ std::vector<MatchVectType> SubstructMatch(
...
     detail::SUBQUERY_MAP subqueryMap;
     ROMol::ConstAtomIterator atIt;
     for (atIt = query.beginAtoms(); atIt != query.endAtoms(); atIt++) {
       if ((*atIt)->getQuery()) {
-        // std::cerr<<"recurse from atom "<<(*atIt)->getIdx()<<std::endl;
-        detail::MatchSubqueries(mol, (*atIt)->getQuery(), params, subqueryMap,
-                                locked);
+	// std::cerr<<"recurse from atom "<<(*atIt)->getIdx()<<std::endl;
+	detail::MatchSubqueries(mol, (*atIt)->getQuery(), params, subqueryMap,
+				locker.locked);
```
Comment (greglandrum) [inline Code/GraphMol/Substruct/SubstructMatch.cpp:471]: I guess your code formatter did this automatically, but it's not correct: these two lines should be indented as they were before

File: Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py [hunk 3]
```diff
@@ -1035,6 +1034,46 @@ def testReactionInPlace(self):
...
+    product = reaction_fwd.RunReactants((mol_sulfonylchloride, mol_amine))[0][0]
+    print("reaction_fwd", Chem.MolToSmiles(product))
+
+    reagent_sulfonylchloride, reagent_amine = reaction_reverse.RunReactants((mol_sulfonamide,))[0]
+
+    # trigger bug
+    print("trigger bug and mess up reaction_fwd object")
+    try:
+        product = reaction_fwd.RunReactants((reagent_sulfonylchloride, reagent_amine))[0]
+    except RuntimeError as e:
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py:1068]: if you're expecting the exceptions to be thrown here, and I guess you are, then it seems like you should be testing for the exception and not just ignoring it.

File: Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py [hunk 4]
```diff
@@ -1035,6 +1034,46 @@ def testReactionInPlace(self):
...
+        print(e)
+
+    print("call messed up reaction_fwd, this will inf loop")
+    # this used to deadlock
+    try:
+      product = reaction_fwd.RunReactants((mol_sulfonylchloride, mol_amine))
+    except RuntimeError as e:
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py:1075]: Same comment about testing for the exception

File: Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py [hunk 5]
```diff
@@ -1035,6 +1034,46 @@ def testReactionInPlace(self):
...
+    )
+
+    smirks_reverse = ">>".join(smirks_fwd.split(">>")[::-1])
+
+    reaction_fwd = rdChemReactions.ReactionFromSmarts(smirks_fwd)
+    reaction_reverse = rdChemReactions.ReactionFromSmarts(smirks_reverse)
+
+
+    product = reaction_fwd.RunReactants((mol_sulfonylchloride, mol_amine))[0][0]
+    print("reaction_fwd", Chem.MolToSmiles(product))
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py:1060]: I guess this print and the others below were there for debugging/development. They can be removed now.

**Review by greglandrum — CHANGES_REQUESTED** [review]
RAII FTW!
some small suggestions here

File: Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py (hunk 3 above)
Comment (bp-kelley) [reply Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py:1068]: I'll add that but for clarification the test was don't block and timeout, the exception is secondary.

**Review by greglandrum — APPROVED** [review]
