### PR TITLE
Fix a pathological slow case with the new getMolFrags()

### LINKED ISSUE #7104: Merging #7056 make the canonicalization tests REALLY slow
I think it's not just canonicalization (and more data are coming), but here's what I observe.

Pre-merge of #7056
```
(py311_build) glandrum@gambia:/localhome/glandrum/RDKit_git/build$ git checkout b3cb9cab212a89c2744
Previous HEAD position was eb2606d61 fragmentation of mol loses any sgroups (#7056)
HEAD is now at b3cb9cab2 refactoring of MolStandardize validation module (#7085)
(py311_build) glandrum@gambia:/localhome/glandrum/RDKit_git/build$ make -j12 hanoiTest &> /dev/null && time ./Code/GraphMol/hanoiTest 

real	0m1.148s
user	0m1.116s
sys	0m0.032s
```
and post-merge:
```
(py311_build) glandrum@gambia:/localhome/glandrum/RDKit_git/build$ git checkout eb2606d617c30af2
HEAD is now at eb2606d61 fragmentation of mol loses any sgroups (#7056)
(py311_build) glandrum@gambia:/localhome/glandrum/RDKit_git/build$ make -j12 hanoiTest &> /dev/null && time ./Code/GraphMol/hanoiTest 

real	0m51.695s
user	0m51.632s
sys	0m0.060s
```

### PR DESCRIPTION
**Pull request by greglandrum**
Fixes #7104

The new implementation of `getMolFrags()` was amazingly inefficient for molecules with a bunch of very small fragments, like a protein with crystallographic waters.

This fixes that.

There was some discussion of performance in the comments on the PR, so here are some numbers.

Here's a mol file for a recent protein + ligands + waters I pulled down from the PDB this morning. [pdb_8jhl.mol.txt](https://github.com/rdkit/rdkit/files/14162327/pdb_8jhl.mol.txt) That structure has 128 fragments, most of which are water.

Here's the same structure with the single atom fragments (water and Mg) stripped: 
[pdb_8jhl.stripped.mol.txt](https://github.com/rdkit/rdkit/files/14162369/pdb_8jhl.stripped.mol.txt) That structure only has two fragments.

Here's timing info with v2023.09.3 of the RDKit (which is before the change which made this PR necessary):
```
In [10]: %timeit Chem.GetMolFrags(m,asMols=True,sanitizeFrags=False)
1.32 ms ± 5.56 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [11]: %timeit Chem.GetMolFrags(sm,asMols=True,sanitizeFrags=False)
773 µs ± 1.76 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
Here's master just before this PR:
```
In [4]: %timeit Chem.GetMolFrags(m,asMols=True,sanitizeFrags=False)
5.52 s ± 25.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit Chem.GetMolFrags(sm,asMols=True,sanitizeFrags=False)
35.1 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
And then with this PR applied:
```
In [10]: %timeit Chem.GetMolFrags(m,asMols=True,sanitizeFrags=False)
9.15 ms ± 25.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [11]: %timeit Chem.GetMolFrags(sm,asMols=True,sanitizeFrags=False)
34.6 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
We can no doubt do more to improve the performance of this, but the performance for `getMolFrags()` is no longer quite so horribly slow, both for cases with a lot of very small fragments (the full molecule) and those with <3 fragments (when the special case I added for this PR is not used).

### CODE REVIEW

File: Code/GraphMol/MolOps.cpp [hunk 1]
```diff
@@ -683,15 +680,99 @@ std::vector<ROMOL_SPTR> getMolFrags(const ROMol &mol, bool sanitizeFrags,
...
+          for (auto atom : stereoGroup.getAtoms()) {
+            if (atomsInFrag[atom->getIdx()]) {
+              return true;
+            }
+          }
+        }
+        return false;
+      };
+      if (comp.size() == 1 ||
+          (nFrags > 3 && !fragmentHasChallengingFeatures(comp, atomsInFrag))) {
```
Comment (ricrogz) [inline Code/GraphMol/MolOps.cpp:727]: So, if we have a protein with, lets say, a DAT SGroup containing some label (which is something I could see happening), we'll still hit the pathologically slow case.

Seeing that general case may be pathologically slow, and that we need to write special treatment for specific cases to avoid it, I wonder if the change in #7056 was really worth it.

Comment (bp-kelley) [reply Code/GraphMol/MolOps.cpp:727]: I think the issue is that removeAtomFromGroups is an N**2 op called for every atom removal.  I think I could make it work with batch edit operations that would be a lot more efficient.

Should I give it a go?

File: Code/GraphMol/CMakeLists.txt [hunk 2]
```diff
@@ -147,8 +147,9 @@ rdkit_test(graphmoltestPicklerGlobalSetting testPicklerGlobalSettings.cpp
 
 rdkit_test(graphmolIterTest itertest.cpp LINK_LIBRARIES SmilesParse GraphMol)
 
+find_package(Boost COMPONENTS timer REQUIRED)
```
[the remark this answers is not in the document]
Comment (greglandrum) [reply Code/GraphMol/CMakeLists.txt:150]: ah, no, sorry. I had included that as part of tracking down what was slow

File: Code/GraphMol/MolOps.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/MolOps.cpp:727]: > So, if we have a protein with, lets say, a DAT SGroup containing some label (which is something I could see happening), we'll still hit the pathologically slow case.

If there's a protein with DAT SGroups on a bunch of smaller fragments (i.e. waters) you'll hit the super slow case. If it's the protein itself, or the ligand, everything should be fine. I'll add a test for that to demonstrate and to be sure

> Seeing that general case may be pathologically slow, and that we need to write special treatment for specific cases to avoid it, I wonder if the change in #7056 was really worth it.

The primary reason for the change in #7056 was to allow S groups to be preserved in `getMolFrags()` when some of their atoms are removed. The code to do that was quite complex, this combined with the the complexity already present in `getMolFrags()`  seemed like too much to me. I think the new version is faster in the most common case, small molecules that don't have tens or hundreds of fragments, and it is still simpler.

Comment (greglandrum) [reply Code/GraphMol/MolOps.cpp:727]: > I think the issue is that removeAtomFromGroups is an N**2 op called for every atom removal. 

I don't believe that this is actually the slow part.

Comment (bp-kelley) [reply Code/GraphMol/MolOps.cpp:727]: I'll run a profile on this MR to verify.

Comment (bp-kelley) [reply Code/GraphMol/MolOps.cpp:727]: Interestingly, the removal of computed properties is high on the profile, and removeAtomsFromGroups is nowhere to be seen.

image

Comment (bp-kelley) [reply Code/GraphMol/MolOps.cpp:727]: This might be an avenue for a future optimization.  I was surprised to see it this high (might be a build for profile issue though)

Comment (bp-kelley) [reply Code/GraphMol/MolOps.cpp:727]: @greglandrum and I will address this in a separate MR.

**Review by bp-kelley — APPROVED** [review]
