### PR TITLE
Kekulization error create scaffold network

### LINKED ISSUE #3153: Kekulization error from CreateScaffoldNetwork
**Configuration:**

- RDKit Version: 2020.03.2 (also master)
- Operating system: all
- Python version (if relevant): all

**Description:**
```
In [10]: m = Chem.MolFromSmiles('[O-][C+]1C=CC(CC2=CC=CC2)=CC=C1')

In [11]: ps = rdScaffoldNetwork.ScaffoldNetworkParams()

In [12]: rdScaffoldNetwork.CreateScaffoldNetwork([m],ps)
---------------------------------------------------------------------------
KekulizeException                         Traceback (most recent call last)
<ipython-input-12-1e83c5d98959> in <module>
----> 1 rdScaffoldNetwork.CreateScaffoldNetwork([m],ps)

KekulizeException: Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 6 7
```
Using a more "standard" representation of the molecule works fine:
```
In [13]: m = Chem.MolFromSmiles('O=C1C=CC(CC2=CC=CC2)=CC=C1')

In [14]: rdScaffoldNetwork.CreateScaffoldNetwork([m],ps)
Out[14]: <rdkit.Chem.Scaffolds.rdScaffoldNetwork.ScaffoldNetwork at 0x23733a1e5d0>
```

Thanks to an anonymous reviewer of the scaffold network application note for pointing this out. :-)

### PR DESCRIPTION
**Pull request by manangoel99**
Fixes #3153 
The pull request fixes Kekulization error that comes up on creating Scaffold Networks in which molecules contain aromatic C+ atoms by adding logic to add explicit Hs to the C+ similar to heteroatoms.

### CODE REVIEW

File: Code/GraphMol/ScaffoldNetwork/catch_tests.cpp [hunk 1]
```diff
@@ -763,6 +763,55 @@ TEST_CASE("Github #3177: seg fault with null molecules", "[bug]") {
   }
 }
 
+TEST_CASE("GitHub #3153: Kekulization error in molecules with aromatic C+", "[bug]") {
```
Comment (greglandrum) [inline Code/GraphMol/ScaffoldNetwork/catch_tests.cpp:766]: The tests that you've added are good in the sense that they make sure that you can add these molecules to the scaffold network, but they aren't looking at the correctness of the result.

Please add, to each of the SECTIONS, a check that the expected results are there.
For example, in the aromatic carbocation example, you should check that the canonical SMILES corresponding to `[CH+]1C=CC(CC2=CC=CC2)=CC=C1` is in the `net.nodes` vector.

**Comment by greglandrum** [comment]
Thanks @manangoel99 !
