### PR TITLE
Don't register FilterMatcherBase twice

### LINKED ISSUE #7585: Import FilterCatalog displays runtime warning for release 2024.3.3
**Describe the bug**
Runtime warning is displayed when importing FilterCatalog

**To Reproduce**
```
/app/src# python
Python 3.11.9 (main, Jul  2 2024, 21:59:07) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit.Chem import FilterCatalog
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for boost::shared_ptr<RDKit::FilterMatcherBase> already registered; second conversion method ignored.
```
**Expected behavior**
No RuntimeWarning

**Configuration (please complete the following information):**
 - RDKit version: 2024.3.3
 - OS: python:3.11-slim-bullseye
 - Python version (if relevant): 3.11
 - Are you using conda? No (rdkit installed using pip install)
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #7585 

Missed for years, this prevents the warning the FilterMatcherBase is already registered.

### CODE REVIEW

File: Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp [hunk 1]
```diff
@@ -348,7 +348,7 @@ struct filtercat_wrapper {
         .def("GetName", &FilterMatcherBase::getName, python::args("self"))
         .def("__str__", &FilterMatcherBase::getName, python::args("self"));
 
-    python::register_ptr_to_python<boost::shared_ptr<FilterMatcherBase>>();
+    //python::register_ptr_to_python<boost::shared_ptr<FilterMatcherBase>>();
```
Comment (greglandrum) [inline Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp:351]: I think you probably meant to just delete this line. :-)

Comment (bp-kelley) [reply Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp]: I did in the version I didn't push :)

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by phonglam3103** [comment]
Hi @bp-kelley and @greglandrum , thanks for your help on fixing this problem in the previous versions. I found that it was fixed in 2024.9.1. However, on the versions after that one, the problem seems to come back:
So far I have tested it with 2024.9.3, 2024.9.5:
To reproduce:
`from rdkit import Chem
from rdkit.Chem.FilterCatalog import FilterCatalog, FilterCatalogParams`

returns:
`<frozen importlib._bootstrap>:488: RuntimeWarning: to-Python converter for boost::shared_ptr<RDKit::FilterHierarchyMatcher> already registered; second conversion method ignored.
<frozen importlib._bootstrap>:488: RuntimeWarning: to-Python converter for boost::shared_ptr<RDKit::FilterCatalogEntry> already registered; second conversion method ignored.`
