### PR TITLE
fix #6958

### LINKED ISSUE #6958: GetAtomPairFingerprint yields different rooted FP from generator
**Describe the bug**
Rooted `AtomPair` fingerprints computed with `rdMolDescriptors.GetAtomPairFingerprint()` differ from those computed with `rdFingerprintGenerator.GetAtomPairGenerator`.

**To Reproduce**
```
import rdkit
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator, rdMolDescriptors

ZINC36905137 = Chem.MolFromSmiles("Nc1nncc(-c2ccc(OC(F)F)cc2)n1")
fp_from_func = rdMolDescriptors.GetAtomPairFingerprint(ZINC36905137, fromAtoms=[12, 13])
fp_from_func = tuple(sorted((k, v) for k, v in fp_from_func.GetNonzeroElements().items()))
fp_gen = rdFingerprintGenerator.GetAtomPairGenerator()
fp_from_gen = fp_gen.GetSparseCountFingerprint(ZINC36905137, fromAtoms=[12, 13])
fp_from_gen = tuple(sorted((k, v) for k, v in fp_from_gen.GetNonzeroElements().items()))
fp_from_func == fp_from_gen
False

for i, t in enumerate(fp_from_func):
    if t != fp_from_gen[i]:
        print(f"fp_from_func: {t}, fp_from_gen {fp_from_gen[i]}")
fp_from_func: (2117666, 2), fp_from_gen (2117666, 1)
```

**Expected behavior**
The fingerprints should be identical.

### PR DESCRIPTION
**Pull request by ptosco**
This PR fixes #6958.
The old implementation was not checking that pairs involving atoms from the `fromAtoms` list had not already been computed before. The fix for the old implementation would have been the following:
```diff
diff --git a/Code/GraphMol/Fingerprints/AtomPairs.cpp b/Code/GraphMol/Fingerprints/AtomPairs.cpp
index 46eb924..879ca10 100644
--- a/Code/GraphMol/Fingerprints/AtomPairs.cpp
+++ b/Code/GraphMol/Fingerprints/AtomPairs.cpp
@@ -119,6 +120,9 @@ SparseIntVect<std::int32_t> *getAtomPairFingerprint(
                                        j) != ignoreAtoms->end()) {
             continue;
           }
+          if (i > j && std::find(fromAtoms->begin(), fromAtoms->end(), i) != fromAtoms->end()) {
+            continue;
+          }
           setAtomPairBit(i, j, nAtoms, atomCodes, dm, res, minLength, maxLength,
                          includeChirality);
         }

```
However, I think it makes more sense to rather use the new generator implementation, as was already happening for the hashed version, to avoid maintaining different implementations and avoid code duplication.

### CODE REVIEW

File: Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp [hunk 1]
```diff
@@ -2423,6 +2423,46 @@ void testBulkFP() {
...
+  std::sort(fpFromFreeFuncAsVectOfPairs.begin(),
+            fpFromFreeFuncAsVectOfPairs.end());
+  const auto &fpFromGeneratorNonZero = fpFromGenerator->getNonzeroElements();
+  std::vector<std::pair<std::uint32_t, int>> fpFromGeneratorAsVectOfPairs(
+      fpFromGeneratorNonZero.begin(), fpFromGeneratorNonZero.end());
+  std::sort(fpFromGeneratorAsVectOfPairs.begin(),
+            fpFromGeneratorAsVectOfPairs.end());
+  if (fpFromFreeFuncAsVectOfPairs != fpFromGeneratorAsVectOfPairs) {
+    for (const auto &fpFromFreeFuncPair : fpFromFreeFuncAsVectOfPairs) {
+      auto i = &fpFromFreeFuncPair - &fpFromFreeFuncAsVectOfPairs.front();
```
Comment (greglandrum) [inline Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp:2453]: I think this is kind of a gross pattern. What about:
```suggestion
    for (auto i = 0u; i < fpFromFreeFuncAsVectOfPairs.size(); ++i) {
      const auto &fpFromFreeFuncPair = fpFromFreeFuncAsVectOfPairs.at(i);
```

File: Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp [hunk 2]
```diff
@@ -2423,6 +2423,46 @@ void testBulkFP() {
   BOOST_LOG(rdErrorLog) << "  done" << std::endl;
 }
 
+void testAtomPairFPDifference() {
```
Comment (greglandrum) [inline Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp:2426]: it's fine to add tests to the old-school testing code, but it is simpler if you add catch tests instead.

File: Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp [hunk 3]
```diff
@@ -2423,6 +2423,46 @@ void testBulkFP() {
...
+  std::vector<std::pair<std::uint32_t, int>> fpFromGeneratorAsVectOfPairs(
+      fpFromGeneratorNonZero.begin(), fpFromGeneratorNonZero.end());
+  std::sort(fpFromGeneratorAsVectOfPairs.begin(),
+            fpFromGeneratorAsVectOfPairs.end());
+  if (fpFromFreeFuncAsVectOfPairs != fpFromGeneratorAsVectOfPairs) {
+    for (const auto &fpFromFreeFuncPair : fpFromFreeFuncAsVectOfPairs) {
+      auto i = &fpFromFreeFuncPair - &fpFromFreeFuncAsVectOfPairs.front();
+      const auto &fpFromGeneratorPair = fpFromGeneratorAsVectOfPairs.at(i);
+      if (fpFromFreeFuncPair != fpFromGeneratorPair) {
+        std::cerr << "fpFromFreeFuncPair (" << fpFromFreeFuncPair.first << ", "
```
Comment (greglandrum) [inline Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp:2456]:
```suggestion
        BOOST_LOG(rdErrorLog) << "fpFromFreeFuncPair (" << fpFromFreeFuncPair.first << ", "
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
A couple of minor changes suggested

File: Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp (hunk 1 above)
Comment (ptosco) [reply Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp]: @greglandrum _Gross_? That’s _art_ of pointer arithmetic. Anyway, I’ll commit the change. Only because it’s you ;-)

**Comment by ptosco** [comment]
@greglandrum I applied the changes you suggested - thanks for reviewing!
