### PR TITLE
Fixes #2830

### LINKED ISSUE #2830: Trusted Smiles holder doesn't handle ring queries
**Description:**
Trusted smiles holder doesn't initialize RingInfo and fails on ring based smarts queries.

```
from rdkit import Chem
from rdkit.Chem import rdSubstructLibrary
pat = Chem.MolFromSmarts("[C&R1]")
holder = rdSubstructLibrary.CachedTrustedSmilesMolHolder()
lib = rdSubstructLibrary.SubstructLibrary(holder)
lib.AddMol(Chem.MolFromSmiles("C1CC1"))
lib.GetMatches(pat)
```

Results in
```
****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 37 in file /Users/bkelley/anaconda3/conda-bld/rdkit_1566353253706/work/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****
```

### PR DESCRIPTION
**Pull request by bp-kelley**
The fix checks the query for ring based queries, and performs a full sanitization if necessary.

Also, when using the external API, all molecules are returned in their fully sanitized form.

### CODE REVIEW

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp [hunk 1]
```diff
@@ -87,12 +88,30 @@ unsigned int SubstructLibrary::addMol(const ROMol &m) {
 }
 
 namespace {
+//  Return true if the pattern contains a ring query
+bool query_needs_rings(const ROMol &in_query) {
+  for (auto &atom: in_query.atoms()) {
+    if(atom->hasQuery()) {
+      if (describeQuery(atom).find("Ring") != std::string::npos) {
```
Comment (bp-kelley) [inline Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp]: Is there a better way?  this feels dirty :)

**Comment by bp-kelley** [comment]
The failure here is in sim div pickers on one version of windows.  A bit odd!

**Comment by greglandrum** [comment]
That’s an intermittent failure that we may want to look into since it’s irritating

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp]: There's not really

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h [hunk 2]
```diff
@@ -213,10 +218,13 @@ class RDKIT_SUBSTRUCTLIBRARY_EXPORT CachedTrustedSmilesMolHolder
     return size() - 1;
   }
 
-  virtual boost::shared_ptr<ROMol> getMol(unsigned int idx) const {
+  virtual boost::shared_ptr<ROMol> getMol(unsigned int idx, bool sanitize=true) const {
     if (idx >= mols.size()) throw IndexErrorException(idx);
 
     RWMol *m = SmilesToMol(mols[idx], 0, false);
+    if (sanitize) { // only need ring info for sanitiation
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/SubstructLibrary.h]:
```suggestion
    if (sanitize) { // only need ring info for sanitization
```

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h [hunk 3]
```diff
@@ -559,7 +568,8 @@ class RDKIT_SUBSTRUCTLIBRARY_EXPORT SubstructLibrary {
   boost::shared_ptr<ROMol> operator[](unsigned int idx) {
     // expects implementation to throw IndexError if out of range
     PRECONDITION(mols, "molholder is null in SubstructLibrary");
-    return mols->getMol(idx);
+    const bool sanitize=true;
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/SubstructLibrary.h]: Isn't setting `sanitize` to true here changing the current behavior?
There aren't that many circumstances where it's necessary, so I disagree with it being the default.

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h [hunk 4]
```diff
@@ -549,7 +557,8 @@ class RDKIT_SUBSTRUCTLIBRARY_EXPORT SubstructLibrary {
   boost::shared_ptr<ROMol> getMol(unsigned int idx) const {
     // expects implementation to throw IndexError if out of range
     PRECONDITION(mols, "molholder is null in SubstructLibrary");
-    return mols->getMol(idx);
+    const bool sanitize=true;
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/SubstructLibrary.h]: Isn't setting `sanitize` to true here changing the current behavior?
There aren't that many circumstances where it's necessary, so I disagree with it being the default.

File: Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp [hunk 5]
```diff
@@ -44,13 +44,13 @@ const char *MolHolderBaseDoc =
     "The API is quite simple: \n"
     "  AddMol(mol) -> adds a molecule to the molecule holder, returns index of "
     "molecule\n"
-    "  GetMol(idx) -> return the molecule at index idx\n";
+    "  GetMol(idx,sanitize=True) -> return the molecule at index idx\n";
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp]: why is the `sanitize=True` here in the docs?

File: Code/GraphMol/SubstructLibrary/Wrap/rough_test.py [hunk 6]
```diff
@@ -309,6 +309,24 @@ def testBinaryCache(self):
       res = slib.GetMatches(core)
       self.assertEqual(len(res),
                        len([x for x in mols if x.HasSubstructMatch(core, useChirality=True)]))
-        
+
+  def testRingSmartsWithTrustedSmiles(self):
```
Comment (greglandrum) [inline Code/GraphMol/SubstructLibrary/Wrap/rough_test.py]: I think you need more tests that just this one. Please include tests for `r` as well on the atoms, `@` on bonds, and at least one test to make sure your checks also work with recursive SMARTS.

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h (hunk 3 above)
Comment (bp-kelley) [reply Code/GraphMol/SubstructLibrary/SubstructLibrary.h]: This is the user facing API.  I think when the user calls getMol they should always get sanitized molecules.

File: Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp (hunk 5 above)
Comment (bp-kelley) [reply Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp]: It shouldn't be, that was from a previous iteration.

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h (hunk 2 above)
Comment (bp-kelley) [reply Code/GraphMol/SubstructLibrary/SubstructLibrary.h]: It shouldn't be the default behavior.  When the user calls getMol, they do get a sanitized molecule.  Internally, sanitize is only set to true for a ring query, or at least that is the intention.

File: Code/GraphMol/SubstructLibrary/Wrap/rough_test.py (hunk 6 above)
Comment (bp-kelley) [reply Code/GraphMol/SubstructLibrary/Wrap/rough_test.py]: Agreed, we should also have C++ tests as well.

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h (hunk 4 above)
Comment (bp-kelley) [reply Code/GraphMol/SubstructLibrary/SubstructLibrary.h]: This is in the SubstructLibrary.getMol function which is only called by the user.  I made the decision to always return sanitized molecules when the user calls a function to avoid future bug reports :)

File: Code/GraphMol/SubstructLibrary/SubstructLibrary.h (hunk 3 above)
Comment (greglandrum) [reply Code/GraphMol/SubstructLibrary/SubstructLibrary.h]: I'm not sure I agree with that, particularly since you aren't actually sanitizing the molecules - there are a number of properties that sanitization sets that won't be set here.
If it's in the end-user API and called "sanitize" then it should make sure you get back the equivalent of a molecule that's actually been sanitized.
I would prefer to just return the molecule in the state that it was being used during the search

File: Code/GraphMol/SubstructLibrary/Wrap/rough_test.py (hunk 6 above)
Comment (bp-kelley) [reply Code/GraphMol/SubstructLibrary/Wrap/rough_test.py]: There is a ring bond check, btw:  "C@C"

**Comment by bp-kelley** [comment]
@greglandrum Fun, travis failed installing condo on osx :)

**Comment by greglandrum** [comment]
Yeah, that’s been a problem for the last couple of days. I just ignore it.
I’m more than halfway tempted to just disable the Travis builds anyway

**Comment by bp-kelley** [comment]
@greglandrum  I think this is ready again.
