### PR TITLE
Fixes #962

### LINKED ISSUE #962: Kekulization issues post successful smiles parsing
This was reported by Peter Gedeck.

Wildcards are parseable in smiles, but sometimes can't be kekulized

Fails:
cid:image002.png@01D1C623.0F26EFA0

>>> from rdkit import Chem
>>> s = 'C2*c1ccccc1C2'
>>> mol = Chem.MolFromSmiles(s)
>>> Chem.MolToMolBlock(mol)
[09:50:35] Can't kekulize mol
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Sanitization error: Can't kekulize mol
 
This works:
 
>>> s = 'C2*Cc1ccccc12'
 
And writing the aromatic ring as single/double bonds too:
 
>>> s = 'C2*C1=CC=CC=C1C2'
>>> mol = Chem.MolFromSmiles(s)
>>> Chem.MolToMolBlock(mol)
 
Breakdown:

kekulization

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

File: Code/GraphMol/Kekulize.cpp [hunk 1]
```diff
@@ -347,6 +348,13 @@ bool kekulizeWorker(RWMol &mol, const INT_VECT &allAtms,
           // mol.debugMol(std::cerr);
           numBT++;
         } else {
+          // undo any remaining changes we made while here
```
Comment (bp-kelley) [inline Code/GraphMol/Kekulize.cpp]: Just to be clear, this is triggered when we can't add double bonds and we also can't backtrack?

Comment (greglandrum) [inline Code/GraphMol/Kekulize.cpp]: Yeah, it's when the addition of double bonds has failed, but no choices have been made that can be backtracked from.

**Comment by greglandrum** [comment]
@bp-kelley : ok to go ahead and merge this?
