### PR TITLE
Address issue #2890

### LINKED ISSUE #2860: QED bigger 1
- RDKit Version: 2018.09.1

**Description:**

In the paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3524573/ describing QED, the authors state that "QED values can range between zero (all properties unfavourable) and one (all properties favourable)." However, the rdkit function returns qed values bigger 1 for many molecules.

### LINKED ISSUE #2890: EnumerateStereoisomers cannot handle STEREOANY bonds
When running this minimal example,
```
from rdkit import Chem
from rdkit.Chem.EnumerateStereoisomers import EnumerateStereoisomers

mol = Chem.MolFromSmiles('CC=CC')
mol.GetBondWithIdx(1).SetStereo(Chem.rdchem.BondStereo.STEREOANY)

list(EnumerateStereoisomers(mol))
```

Release 2019.09.2 of RDKit dies with:
```
****
Pre-condition Violation
Stereo atoms should be specified before specifying CIS/TRANS bond stereochemistry
Violation occurred on line 288 in file /tmp/rdkit/build/rdkit/Code/GraphMol/Bond.h
Failed Expression: what <= STEREOE || getStereoAtoms().size() == 2
****

Traceback (most recent call last):
  File "minimal.py", line 8, in <module>
    list(EnumerateStereoisomers(mol))
  File "/tmp/lib/python3.6/site-packages/rdkit/Chem/EnumerateStereoisomers.py", line 321, in EnumerateStereoisomers
    flippers[i].flip(flag)
  File "/tmp/lib/python3.6/site-packages/rdkit/Chem/EnumerateStereoisomers.py", line 49, in flip
    self.bond.SetStereo(Chem.BondStereo.STEREOTRANS)
RuntimeError: Pre-condition Violation
	Stereo atoms should be specified before specifying CIS/TRANS bond stereochemistry
	Violation occurred on line 288 in file Code/GraphMol/Bond.h
	Failed Expression: what <= STEREOE || getStereoAtoms().size() == 2
	RDKIT: 2019.09.2
	BOOST: 1_68

```
The problem seems to be that `EnumerateStereoisomers` tries to flip these stereo bonds, but, since Stereo Atoms haven't been set, it fails. This is especially relevant since the reactions code does now set STEREOANY on some product stereo bonds under certain circumstances.

I can think of two ways of considering STEREOANY bonds: they could either be ignored, being treated like if they were marked as STEREONONE, or, which seems the more reasonable to me, `EnumerateStereoisomers` could produce the two possible stereoisomers for the bond (CIS and TRANS).

### PR DESCRIPTION
**Pull request by ricrogz**
I have patched `FindPotentialStereoBonds()` to check that bonds marked as STEREOANY have stereo bonds. If they have, the bond is skipped, but if not, then the bond is rechecked in order to have stereo atoms assigned, or be relabeled as STEREONONE.

This fixes #2890: `EnumerateStereoisomers()` was failing because the input STEREOANY bond did not have stereoatoms assigned. Once it gets them, the enumeration succeeds.

### CODE REVIEW

File: Code/GraphMol/Chirality.cpp [hunk 1]
```diff
@@ -1637,14 +1637,18 @@ void findPotentialStereoBonds(ROMol &mol, bool cleanIt) {
...
-            dblBond->getStereo() == Bond::STEREOANY) {
+            (dblBond->getStereo() == Bond::STEREOANY &&
+             dblBond->getStereoAtoms().size() == 2)) {
           continue;
         }
-        // proceed only if we either want to clean the stereocode on this bond
-        // or if none is set on it yet
-        if (cleanIt || dblBond->getStereo() == Bond::STEREONONE) {
+        // proceed only if we either want to clean the stereocode on this bond,
+        // if none is set on it yet, or it is STEREOANY and we need to find
```
Comment (d-b-w) [inline Code/GraphMol/Chirality.cpp]: What if it's EITHER and we need the adjacent atoms? would we run into the same bug?

Comment (greglandrum) [reply Code/GraphMol/Chirality.cpp]: My two cents: given that EITHER is a direction and not a stereo value, I think it can be ignored. When we revisit the stereo representation I think it would behoove us to remove that direction option anyway.

Comment (d-b-w) [reply Code/GraphMol/Chirality.cpp]: oh, of course.

Comment (ricrogz) [reply Code/GraphMol/Chirality.cpp]: Yeah, that was my impression about the EITHER bond: if it is not marked as stereo, ignore it.

**Comment by greglandrum** [comment]
@ricrogz : looks like I waited a bit too long to merge this one and now there's a conflict. Would you mind resolving that and then I'll merge?

**Comment by ricrogz** [comment]
Sure, @greglandrum. Here you are.

**Comment by greglandrum** [comment]
Thanks!
