### PR TITLE
fixes #5902

### LINKED ISSUE #5902: DetermineBondOrders running out of memory on medium-sized disconnected structure
This XYZ file is perhaps a bit pathological but it was in our test set.  It has 13 disconnected fragments that have the same connectivity.

image

`DetermineConnectivity` has no problem with this molecule, but `DetermineBondOrders` runs away, consuming more and more memory, and is killed by the shell:

```
>>> mol = rdmolfiles.MolFromXYZFile('/Users/jasonb/test_13_components.txt')
>>> rdDetermineBonds.DetermineConnectivity(mol)
>>> rdDetermineBonds.DetermineBondOrders(mol)
zsh: killed     python

```
If I take one isolated fragment from the input file and run that through (see attached `test_1_component.txt`) it can determine bond orders, although it does return a charge-separated molecule that isn't quite right (see #5888).

I have run `DetermineBondOrders` on structures with many more atoms than this, even disconnected structures with more atoms: make a 3D table of ~50 benzene molecules translated in space and write them to an XYZ file, no issue with `DetermineBondOrders`.  But this one fails.  

Is the code somehow considering permutations of bond orders between fragments? I assumed `DetermineBondOrders` would work as if it iterated over the disconnected fragments.

[test_1_component.txt](https://github.com/rdkit/rdkit/files/10311222/test_1_component.txt)
[test_13_components.txt](https://github.com/rdkit/rdkit/files/10311224/test_13_components.txt)

### PR DESCRIPTION
**Pull request by jasondbiggs**
lazily generate the combinations of possible atom valences rather than computing them up front

The number of possible combinations is still very large, and so the `determineBondOrders` function can take a very long time to finish, but it won't grab all the virtual memory it can find now.

### CODE REVIEW

**Comment by jasondbiggs** [comment]
@gosreya - this is the fix I mentioned in the bug report

**Comment by bp-kelley** [comment]
We should have a sanity limit for the number of enumerations we support or at least a timeout here.

In addition, we use lazy Cartesian products a few places, it might be worthwhile to make this a general utility at some point.

**Comment by jasondbiggs** [comment]
@bp-kelley I was aware of the reaction enumeration class `CartesianProductStrategy`, but didn't see any clear way to use that same code here.  

Now I see the `CartesianProduct` struct in the RGroup decomposition module, which looks like it would work here but I don't know if a dependency between the DetermineBonds and RGroupDecomposition modules makes sense.  

The RGroup code doesn't use the clever dividends/moduli trick used here (I have no idea if it actually makes a difference), and the `\\ might overflow` comment is concerning because I did find a few XYZ files where this happened.  Put enough oxygens and nitrogens in there and the number of combinations grows.   I agree that if the max_combinations is too big, you are unlikely to want to keep iterating past `ULLONG_MAX`, but I would rather check for overflow than let it happen.

Regarding the timeout or max_iterations options, I would prefer giving `determineBondOrders` a parameters struct like the FMCS code - to avoid adding more positional arguments.  You could have members for the current `determineBondOrders` options as well as `max_iterations` and `Timeout`, and just like in the FMCS code there would be a `ProgressCallback` parameter.

My intention was to open a github issue requesting these features/enhancements, and just fix the memory consumption bug in this PR, but I could implement the above here and see what people think.

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 1]
```diff
@@ -18,9 +18,104 @@
...
+// see http://phrogz.net/lazy-cartesian-product
+template <typename T>
+struct LazyCartesianProduct {
+  std::vector<std::vector<T>> listOfLists;
+  std::vector<uint1024_t> divs;
+  std::vector<uint1024_t> mods;
+  uint1024_t max_size;
+  uint1024_t currentPos;
+
+  explicit LazyCartesianProduct(std::vector<std::vector<T>> &input)
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:39]: `input` argument can (and should) be const

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 2]
```diff
@@ -18,9 +18,104 @@
...
     Graph;
+using boost::multiprecision::uint1024_t;
+
+namespace {
+
+
+// see http://phrogz.net/lazy-cartesian-product
+template <typename T>
+struct LazyCartesianProduct {
+  std::vector<std::vector<T>> listOfLists;
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:33]: Please prefix the names of all data members with `d_` to make the rest of the code a bit easier to read

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 3]
```diff
@@ -18,9 +18,104 @@
...
+  std::vector<uint1024_t> divs;
+  std::vector<uint1024_t> mods;
+  uint1024_t max_size;
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:36]:
```suggestion
  uint1024_t maxSize;
```

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 4]
```diff
@@ -18,9 +18,104 @@
...
+  uint1024_t currentPos;
+
+  explicit LazyCartesianProduct(std::vector<std::vector<T>> &input)
+      : listOfLists(input), currentPos(0) {
+    unsigned int size = listOfLists.size();
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:41]:
```suggestion
    auto size = listOfLists.size();
```

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 5]
```diff
@@ -18,9 +18,104 @@
...
+  bool atEnd() const { return currentPos >= max_size; }
+};
+
+template <typename T>
+std::vector<T> LazyCartesianProduct<T>::entry_at(uint1024_t pos) const {
+  auto length = listOfLists.size();
+  std::vector<T> res(length);
+  for (auto i = 0; i < length; ++i) {
+    res[i] = listOfLists[i][(unsigned long long)((uint1024_t)(pos / divs[i]) %
+                                                 mods[i])];
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:65]: We avoid c-style casts whenever possible
```suggestion
    res[i] = listOfLists[i][static_cast<size_t>(static_cast<uint1024_t>(pos / divs[i]) %
                                                 mods[i])];
```

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 6]
```diff
@@ -18,9 +18,104 @@
...
+
+std::vector<unsigned int> possibleValences(
+    const RDKit::Atom *atom,
+    const std::unordered_map<int, std::vector<unsigned int>> &atomicValence) {
+  auto atomNum = atom->getAtomicNum();
+  auto numBonds = atom->getDegree();
+  std::vector<unsigned int> valences;
+  try {
+    valences = atomicValence.at(atomNum);
+  } catch (const std::out_of_range &) {
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:78]: It would be clearer and probably faster (there is some overhead in doing the exception handling) to handle this using iterators. Something like:
```
auto pos = atomValence.find(atomNum);
if(pos == atomValence.end()){
   error message
   throw ValueError 
} 
success conditions
```

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp [hunk 7]
```diff
@@ -18,9 +18,104 @@
...
+    }
+  }
+
+  std::vector<T> entry_at(uint1024_t pos) const;
+  std::vector<T> next() { return entry_at(currentPos++); }
+  bool atEnd() const { return currentPos >= max_size; }
+};
+
+template <typename T>
+std::vector<T> LazyCartesianProduct<T>::entry_at(uint1024_t pos) const {
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/DetermineBonds.cpp:60]: Please rename this to either `at()` (like many STL containers) or `entryAt()` (to follow the usual RDKit naming scheme)

File: Code/GraphMol/DetermineBonds/DetermineBonds.cpp (hunk 6 above)
Comment (greglandrum) [reply Code/GraphMol/DetermineBonds/DetermineBonds.cpp:78]: And, yeah, I know this isn't your code, but we might as well fix it now

File: Code/GraphMol/DetermineBonds/catch_tests.cpp [hunk 8]
```diff
@@ -225,4 +225,118 @@ H     -1.187721   -0.949657    0.563607
     CHECK(m->getAtomWithIdx(1)->getChiralTag() ==
           Atom::ChiralType::CHI_TETRAHEDRAL_CCW);
   }
+}
+
+TEST_CASE("Github #5902: memory-hungry iterating") {
```
Comment (greglandrum) [inline Code/GraphMol/DetermineBonds/catch_tests.cpp:230]: a question since I haven't run this myself: do you have a sense of how long it takes to run this test?
I'm concerned about adding something which takes a long time to run to the standard test suite.

**Review by greglandrum — CHANGES_REQUESTED** [review]
Thanks @jasondbiggs! I like the approach and think this will definitely help.

A number of suggested changes and questions in the review.

File: Code/GraphMol/DetermineBonds/catch_tests.cpp (hunk 8 above)
Comment (jasondbiggs) [reply Code/GraphMol/DetermineBonds/catch_tests.cpp:230]: For this case the algorithm finds a usable set of valences almost immediately, maybe even even the first entry in the list, which is why it was a shame to spend so much memory making the list of lists.  If the fix here works this returns very quickly.

If the fix it is testing doesn't work, the failure mode would be consuming a large amount of memory and....well on my machine it crashes, but I guess if a test machine had enough memory the test would still work.  So maybe this is a bad test?  I can remove it, I can't think of another test though.

I think I addressed the comments - let me know if I missed anything

Comment (greglandrum) [reply Code/GraphMol/DetermineBonds/catch_tests.cpp:230]: My primary concern was adding a test which makes the CI builds take forever. If this runs quickly then I'm not worried about it.

**Review by greglandrum — APPROVED** [review]
LGTM
