### PR TITLE
Fixes Memory leak in enumerate library python wrapper

### LINKED ISSUE #3702: Memory leak in EnumerateLibrary
**Describe the bug**
Calling Chem.rdChemReactions.EnumerateLibrary in a loop increases the memory usage even if there are no future references to the EnumerationLibrary object.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import rdChemReactions

@profile
def run_once(rxn, mols):
    library = Chem.rdChemReactions.EnumerateLibrary(rxn, [mols, ])
  
@profile
def run_10000(rxn, mols):
    for _ in range(10000):
        library = Chem.rdChemReactions.EnumerateLibrary(rxn, [mols, ])
  
rxn = rdChemReactions.ReactionFromSmarts("[C:1]-[C:2]>>[C:1].[C:2]")
mols = [Chem.MolFromSmarts("[C]-[C]")]*10000
run_once(rxn, mols)
run_10000(rxn, mols)
```

**Expected behavior**
I would expect the memory footprint of both functions to be the same, but they are not. Here is the output of running this code with memory_profiler:

```
python -m memory_profiler minimal_example.py
```

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
     5   74.211 MiB   74.211 MiB           1   @profile
     6                                         def run_once(rxn, mols):
     7   75.699 MiB    1.488 MiB           1       library = Chem.rdChemReactions.EnumerateLibrary(rxn, [mols, ])

Filename: minimal_example.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
     9   75.699 MiB   75.699 MiB           1   @profile
    10                                         def run_10000(rxn, mols):
    11 6261.906 MiB    0.000 MiB       10001       for _ in range(10000):
    12 6261.906 MiB 6186.207 MiB       10000           library = Chem.rdChemReactions.EnumerateLibrary(rxn, [mols, ])

The system monitor also shows an increased memory usage.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3
 - OS: Ubuntu 18.04
 - Python version (if relevant): Python 3.8.2
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
I have noticed this in a much more complicated piece of code, but this minimal example seems to reproduce the problem.
Thank you for any help!

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #3702

The EnumerateLibrary destructors were not being called.

Validated with valgrind

### CODE REVIEW

File: Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp [hunk 1]
```diff
@@ -293,8 +294,7 @@ library2.InitFromString(s)\n\
 for result in itertools.islice(libary2, 1000):\n\
     # do something with the next 1000 samples\n\
 ";
-    python::class_<EnumerateLibraryWrap,
-                   EnumerateLibraryWrap*,EnumerateLibraryWrap&,
+    python::class_<EnumerateLibraryWrap, boost::noncopyable,
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp:297]: curiosity question: why is the `boost::noncopyable` needed here?

**Review by greglandrum — APPROVED** [review]

File: Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp:297]: I was just making changes until it worked.  It wasn’t the virtual destructor which was the obvious thing to fix.  I think it was the ref and pointer definitions in the boost python  class definition that were causing the issue.   I’ll try a run without noncopyable.
