### PR TITLE
Fixes #8726

### LINKED ISSUE #8726: Hydrides in organometallics removed import
Hi,
We are facing the following issue: when we try to import organometallics that include hydrides, these hydrides get removed through the sanitization process. Example:

Image

Upon import:

Image

The overall charge also ends up being +1 instead of 0.

In our view, this should not happen, since it is not a hydrogen that can be inferred through a valence model.

When setting sanitize to False, this doesn't happen, but since we are using these structures directly out of our corporate database, setting sanitize to False might end up having other consequences. We also cannot replace the dative bond with a covalent bond.

Code to reproduce:

```
m5 = '''
Mrv2501 08222513042D            

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 17 16 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Ru 10.8721 -10.9691 0 0 CHG=2
M  V30 2 P 13.328 -12.3887 0 0
M  V30 3 P 6.9694 -13.2568 0 0
M  V30 4 P 10.8721 -8.134 0 0
M  V30 5 C 8.0369 -10.9691 0 0 CHG=-1
M  V30 6 Cl 13.328 -9.5535 0 0 CHG=-1
M  V30 7 H 10.8721 -13.8082 0 0 CHG=-1
M  V30 8 O 6.6174 -10.9691 0 0 CHG=1
M  V30 9 C 14.5559 -11.6808 0 0
M  V30 10 C 13.328 -13.8082 0 0
M  V30 11 C 15.295 -13.5072 0 0
M  V30 12 C 5.7415 -12.5491 0 0
M  V30 13 C 5.0179 -14.4026 0 0
M  V30 14 C 6.9694 -14.6764 0 0
M  V30 15 C 12.1001 -7.4222 0 0
M  V30 16 C 10.8721 -5.8698 0 0
M  V30 17 C 9.6442 -7.4222 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 9 2 1
M  V30 2 9 3 1
M  V30 3 9 4 1
M  V30 4 9 5 1
M  V30 5 9 6 1
M  V30 6 9 7 1
M  V30 7 1 2 9
M  V30 8 1 2 10
M  V30 9 1 2 11
M  V30 10 1 3 12
M  V30 11 1 3 13
M  V30 12 1 3 14
M  V30 13 1 4 15
M  V30 14 1 4 16
M  V30 15 1 4 17
M  V30 16 3 5 8
M  V30 END BOND
M  V30 END CTAB
M  END
'''
m5b = Chem.MolFromMolBlock(m5)
m5b
```
Thank you for your help

**Configuration (please complete the following information):**
 - RDKit version: 2025.03.5
 - OS: Windows and Linux
 - Python version (if relevant): 
 - Are you using conda? Both Conda and Pip
 - If you are using conda, which channel did you install the rdkit from? Conda-forge
 - If you are not using conda: how did you install the RDKit?

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #8726 by changing the default options of H removal so that hydrides are not removed by default.

### CODE REVIEW

**Comment by greglandrum** [comment]
Damn... this was going to be my easy fix for the afternoon!
;-)

File: Code/GraphMol/AddHs.cpp [hunk 1]
```diff
@@ -902,7 +902,8 @@ bool shouldRemoveH(const RWMol &mol, const Atom *atom,
     }
   }
 
-  if (!ps.removeHydrides && atom->getFormalCharge() == -1) {
+  if (!ps.removeHydrides && atom->getFormalCharge() == -1 &&
+      atom->getDegree() < 2) {
```
Comment (greglandrum) [inline Code/GraphMol/AddHs.cpp]: I think this condition is wrong because it doesn't allow removing higher degree hydrides. Removing the H in `F[H-]F` should be possible if both `removeHydrides` and `removeHigherDegrees` are true.

I've done a PR against your branch with suggested updates.

**Review by greglandrum — CHANGES_REQUESTED** [review]
see comment about `removeHigherDegrees`

File: Code/GraphMol/AddHs.cpp (hunk 1 above)
Comment (ricrogz) [reply Code/GraphMol/AddHs.cpp]: Ok. Merged!
