### PR TITLE
Fix for #1478

### LINKED ISSUE #1478: Aromatic rings composed solely of dummy atoms should not be kekulized
**Description:**

- RDKit Version: 2017.03
- Platform: Any

Kekulization is applied oddly to dummy atoms in a mol block.  This causes some weird issues when substructure matching.

```
from rdkit import Chem

data = """ 
  MJ150720                      

  8  8  0  0  0  0  0  0  0  0999 V2000
   -0.4242   -1.4883    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2901   -1.0758    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0046    0.9865    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
    1.0046    0.1614    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
    0.2901   -0.2508    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4243    0.1614    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4243    0.9865    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
    0.2901    1.3990    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  7  6  4  0  0  0  0
  8  7  4  0  0  0  0
  6  5  4  0  0  0  0
  5  4  4  0  0  0  0
  5  2  1  0  0  0  0
  4  3  4  0  0  0  0
  8  3  4  0  0  0  0
  2  1  2  0  0  0  0
M  END

"""

class TestAromaticA(unittest.TestCase):
    def test_aromatic_A(self):
        from rdkit.Chem import AllChem
        
        pattern = Chem.MolFromMolBlock(data)
        print (Chem.MolToSmarts(pattern))

        m = Chem.MolFromSmiles("c1ccccc1C=O")
        assert m.HasSubstructMatch(pattern)
        

if __name__ == '__main__':
    unittest.main()
```

### PR DESCRIPTION
**Pull request by greglandrum**
#### Reference Issue
Fixes #1478

#### What does this implement/fix? Explain your changes.
Simple one: detect rings made up solely of dummy atoms and do not kekulize them.

### CODE REVIEW

File: Code/GraphMol/Kekulize.cpp [hunk 1]
```diff
@@ -512,17 +512,41 @@ void Kekulize(RWMol &mol, bool markAtomsBonds, unsigned int maxBackTracks) {
...
   // - all aromatic atoms return true for "getIsAromatic"
 
-  // first find the all the simple rings in the molecule
+  // first find the all the simple rings in the molecule that are not
+  // completely composed of dummy atoms
   VECT_INT_VECT arings;
-  if (mol.getRingInfo()->isInitialized()) {
-    arings = mol.getRingInfo()->atomRings();
+  boost::dynamic_bitset<> dummyAts(mol.getNumAtoms());
+  for (ROMol::AtomIterator atit = mol.beginAtoms(); atit != mol.endAtoms();
```
Comment (bp-kelley) [inline Code/GraphMol/Kekulize.cpp]: I think we can make the assumption that rings are initialized, mainly since kekulize is called after SANITIZE_KEKULIZE.

We might gain an optimization if we assign allrings before dummyAts and then only add dummy atoms  to dummyAts that are indeed in rings.

Comment (bp-kelley) [inline Code/GraphMol/Kekulize.cpp]: Other than that, I'm happy to merge.

**Comment by bp-kelley** [comment]
@greglandrum Might check out a small optimization, but I think it's worth merging as is right now.

File: Code/GraphMol/Kekulize.cpp (hunk 1 above)
Comment (greglandrum) [inline Code/GraphMol/Kekulize.cpp]: Kekulize can be called at any point though, so I think having the test is necessary.

W.r.t. The dummy ats optimization: wouldn't that either require construction of a dynamic bitset of atoms that are in rings or a lot of searching. (Note: this isn't the place where a lot of time is spent anyway, so this may all be premature optimization).

**Comment by bp-kelley** [comment]
I agree that the test is necessary, I was just saying that putting it at
the top of the function would not (in general) be a performance hit and
allow you to not add dummy atoms that weren't in rings which could be a
potential optimization.
