### PR TITLE
atropisomer bond atoms are checked explicitly for SP2 hybridization

### LINKED ISSUE #8973: Atropisomer bond is found in N-S(=O)C system
**Describe the bug**
Warning of `The 2 defining bonds for an atropisomer are co-planar` for a molecule that chemically does not have an atropisomer bond.

**To Reproduce**
```
from contextlib import redirect_stderr
from io import BytesIO, StringIO
from operator import xor
from rdkit import Chem
from rdkit.rdBase import WrapLogs

sdf = """double-bond-O-R
  ChemDraw11262512372D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 8 7 0 0 1
M  V30 BEGIN ATOM
M  V30 1 C -1.071690 0.825057 0.000000 0
M  V30 2 C -0.357230 0.412538 0.000000 0
M  V30 3 N -0.357230 -0.412500 0.000000 0
M  V30 4 S 0.357229 -0.825019 0.000000 0
M  V30 5 O 0.357229 -1.650057 0.000000 0
M  V30 6 C 1.071690 -0.412500 0.000000 0
M  V30 7 C 0.357247 0.825029 0.000000 0
M  V30 8 C -1.071668 1.650057 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3 CFG=1
M  V30 3 1 3 4
M  V30 4 2 4 5
M  V30 5 1 4 6 CFG=1
M  V30 6 1 2 7
M  V30 7 1 1 8
M  V30 END BOND
M  V30 END CTAB
M  END
$$$$
single-bond-O-R-doesntwarn
  ChemDraw11262512372D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 8 7 0 0 1
M  V30 BEGIN ATOM
M  V30 1 C -1.071690 0.825057 0.000000 0
M  V30 2 C -0.357230 0.412538 0.000000 0
M  V30 3 N -0.357230 -0.412500 0.000000 0
M  V30 4 S 0.357229 -0.825019 0.000000 0 CHG=1
M  V30 5 O 0.357229 -1.650057 0.000000 0 CHG=-1
M  V30 6 C 1.071690 -0.412500 0.000000 0
M  V30 7 C 0.357247 0.825029 0.000000 0
M  V30 8 C -1.071668 1.650057 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3 CFG=1
M  V30 3 1 3 4
M  V30 4 1 4 5 CFG=1
M  V30 5 1 4 6
M  V30 6 1 2 7
M  V30 7 1 1 8
M  V30 END BOND
M  V30 END CTAB
M  END
$$$$
single-bond-O-S
  ChemDraw11262512382D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 8 7 0 0 1
M  V30 BEGIN ATOM
M  V30 1 C -1.071690 0.825057 0.000000 0
M  V30 2 C -0.357230 0.412538 0.000000 0
M  V30 3 N -0.357230 -0.412500 0.000000 0
M  V30 4 S 0.357229 -0.825019 0.000000 0 CHG=1
M  V30 5 O 0.357229 -1.650057 0.000000 0 CHG=-1
M  V30 6 C 1.071690 -0.412500 0.000000 0
M  V30 7 C 0.357247 0.825029 0.000000 0
M  V30 8 C -1.071668 1.650057 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3 CFG=1
M  V30 3 1 3 4
M  V30 4 1 4 5 CFG=3
M  V30 5 1 4 6
M  V30 6 1 2 7
M  V30 7 1 1 8
M  V30 END BOND
M  V30 END CTAB
M  END
$$$$
"""
WrapLogs()
out_buf = StringIO()
err_buf = StringIO()
with redirect_stderr(err_buf):
    for mol_ix, mol in enumerate(Chem.ForwardSDMolSupplier(BytesIO(sdf.encode()))):
        # mols 0 and 2 warn, mol 1 does not
        assert xor(("co-planar" in err_buf.getvalue()), mol_ix == 1)
        mol.Debug(False)
        assert "SP3" in err_buf.getvalue()
        for line in err_buf.getvalue().splitlines():
            if " N " not in line or " S " not in line:
                continue
            assert "SP2" not in line
        err_buf.truncate(0)
```

**Expected behavior**
The bond should not be recognized as an atrop isomer bond. None of the atoms are sp2.

**Screenshots**
Image

**Configuration (please complete the following information):**
 - RDKit version: 2025.9.2
 - OS: Ubuntu 24
 - Python version (if relevant): 3.13
 - Are you using conda? no
 - If you are using conda, which channel did you install the rdkit from? n/a
 - If you are not using conda: how did you install the RDKit? built manually

**Additional context**
Docs says that centers need to be sp2
https://github.com/rdkit/rdkit/blob/f2e0e5c440e91115cda09429ad3fb9e336fad5e4/Docs/Book/RDKit_Book.rst?plain=1#L2391
The code only checks on degree
https://github.com/rdkit/rdkit/blob/f2e0e5c440e91115cda09429ad3fb9e336fad5e4/Code/GraphMol/Atropisomers.cpp#L550-L553

### PR DESCRIPTION
**Pull request by pechersky**
#### Reference Issue
Fixes #8973

#### What does this implement/fix?
atrop bonds are considered with a more strict check on atoms

before, we checked only on totalDegree = 2 or 3,
but this causes false positives for something like a chiral sulfoxide since the S is tetrahedral (sp3) but has only 3 substituents. the hybridization code relies on totalDegree,
but modified to include and making sure to include conjugation so while this is more expensive per molecule, it is closer to intent

### CODE REVIEW

File: Code/GraphMol/FileParsers/testAtropisomers.cpp [hunk 1]
```diff
@@ -567,6 +569,32 @@ void testLookForAtropisomersInSDdfFiles(std::string fileName,
...
+  rdWarningLog->SetTee(warningCapture);
+  for (const auto &file : controlFiles) {
+    auto fName = rdbase +
+                 "/Code/GraphMol/FileParsers/test_data/atropisomers/" +
+                 file;
+    BOOST_LOG(rdInfoLog) << "Validating absence of atropisomers in " << file
+                         << std::endl;
+    auto mol = std::unique_ptr<RWMol>(MolFileToMol(fName, true, false, false));
+    TEST_ASSERT(mol);
+    const Conformer *conf =
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/testAtropisomers.cpp]: The molecule must have a conformer at this point.
You don't need to use the ternary operator here.

File: Code/GraphMol/Atropisomers.cpp [hunk 2]
```diff
@@ -538,19 +538,35 @@ void detectAtropisomerChirality(ROMol &mol, const Conformer *conf) {
...
   }
 
+  bool needsHybridization = false;
   for (auto bondToTry : bondsToTry) {
-    if (bondToTry->getBeginAtom()->needsUpdatePropertyCache()) {
-      bondToTry->getBeginAtom()->updatePropertyCache(false);
+    // defer cache update on the whole mol unless we actually have bonds to try
+    // we need to do an update on the whole mol and not just incident atoms
+    // because we need to calculate hybridization, which is non-local
+    for (const auto atom : mol.atoms()) {
```
Comment (greglandrum) [inline Code/GraphMol/Atropisomers.cpp]: I don't think you need to do this loop for every bond that's being considered for atropisomerism.
It can be moved outside of the loop on line 542

File: Code/GraphMol/Atropisomers.cpp [hunk 3]
```diff
@@ -538,19 +538,35 @@ void detectAtropisomerChirality(ROMol &mol, const Conformer *conf) {
...
+        continue;  // dummy atoms stay unspecified
+      }
+      if (atom->getHybridization() == Atom::HybridizationType::UNSPECIFIED) {
+        needsHybridization = true;
+        break;
+      }
     }
-    if (bondToTry->getEndAtom()->needsUpdatePropertyCache()) {
-      bondToTry->getEndAtom()->updatePropertyCache(false);
+    if (mol.needsUpdatePropertyCache() || needsHybridization) {
```
Comment (greglandrum) [inline Code/GraphMol/Atropisomers.cpp]: Once the search for atoms that need hybridization assigned has been moved out of the loop, this can go directly underneath it.

File: Code/GraphMol/Atropisomers.cpp (hunk 2 above)
Comment (pechersky) [reply Code/GraphMol/Atropisomers.cpp]: Do we have an early return on when `bondsToTry` is empty and not iterated? I agree that this loop is misplaced, since it would run on every bond. Would you prefer I place it outside _and_ add an early return on bondsToTry empty prior?

Comment (greglandrum) [reply Code/GraphMol/Atropisomers.cpp]: That makes sense.
We haven't had the test before since it was unnecessary

**Comment by greglandrum** [comment]
@tadhurst-cdd does the logic here also make sense to you?

**Comment by tadhurst-cdd** [comment]
> @tadhurst-cdd does the logic here also make sense to you?

The logic is good.  It could force calculation of delocalization and hybridization for any molecule with a wedge bond, which could be costly.   If we become concerned about that, we could do the check to see if any bondsToTry pass the simple check (TotalDegree) and if any bondsToTry pass that, then do the delocalization and hybridization check.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@pechersky thanks for the contribution.
Sorry I forgot to merge it for so long!
