### PR TITLE
ReactionFromRxnBlock fails on bond with reacting center status set 

### LINKED ISSUE #6195: ReactionFromRxnBlock fails on bond with reacting center status set
**Describe the bug**

When parsing a RXN block containing  a molecule has has a bond with a `reacting center status` flag an exception is raised.  This is an important issue as ChemDraw will set that flag when a sketched reaction makes or breaks a bond.

**To Reproduce**

```python
import sys
from rdkit import Chem
from rdkit.Chem import AllChem

block = """$RXN
ACS Document 1996
  ChemDraw03132312282D

  1  1
$MOL



  4  3  0  0  0  0  0  0  0  0999 V2000
   -0.0000    0.6187    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
   -0.0000   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
   -0.7145   -0.6187    0.0000 C   0  0  0  0  0  0  0  0  0  3  0  0
    0.7145   -0.6187    0.0000 O   0  0  0  0  0  0  0  0  0  4  0  0
  1  2  2  0        0
  2  3  1  0        0
  2  4  1  0        0
M  END
$MOL



  5  4  0  0  0  0  0  0  0  0999 V2000
   -0.3572    0.6187    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
   -0.3572   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
   -1.0717   -0.6187    0.0000 C   0  0  0  0  0  0  0  0  0  3  0  0
    0.3572   -0.6187    0.0000 O   0  0  0  0  0  0  0  0  0  4  0  0
    1.0717   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0        0
  2  3  1  0        0
  2  4  1  0        0
  4  5  1  0        4
M  END
"""
```
The above code raises this error:
```python
ValueError: ChemicalReactionParserException: Cannot parse product 0. The error was:
	Unrecognized bond topology specifier: 4 on line 32
```

**Expected behavior**

I expect the reaction to parse.

**Configuration (please complete the following information):**
 - RDKit version:  master as of 3/13/23
 - OS: [e.g. Ubuntu 20.04] Ubuntu 20.04

**Additional context**

This is the offending bond line and the bond block format:

```
  4  5  1  0        4
111222tttsssxxxrrrccc
```

This bond has a `reacting center status` flag set to 4 (`ccc`), to indicate that a bond has been made.  It looks like the RDKit is mistakenly reading that flag as a `bond topology` flag (`rrr`) and crashing as that flag cannot be 4.

I'll take a look and see if I can fix it.

### PR DESCRIPTION
**Pull request by jones-gareth**
#### Reference Issue

Fixes #6195

#### What does this implement/fix? Explain your changes.

There is a bug in ` MolFileParser::toInt` that this PR fixes.  Here
```C++
  // remove leading spaces
  txt = input.data();
  unsigned int sz = input.size();
  if (acceptSpaces) {
    while (*txt == ' ') {
      ++txt;
      --sz;
    }
  }
  int res = 0;
  std::from_chars(txt, txt + sz, res);

  return res;

```
`sz` can end up being negative if the `input` string view is all spaces.

This is what happens when parsing the topology entry for the bond line
```
  4  5  1  0        4
```

The topology entry is all spaces and `txt` ends up pointing to 4 (the bond reaction center) with `sz` negative. 4 is returned and an exception thrown.

### CODE REVIEW

**Comment by jones-gareth** [comment]
In theory the same thing could happen to ` MolFileParser::toUnsigned`, so I have also patched that function though there is no associated test.

File: Code/GraphMol/FileParsers/MolFileParser.cpp [hunk 1]
```diff
@@ -79,10 +79,17 @@ int toInt(const std::string_view input, bool acceptSpaces) {
     while (*txt == ' ') {
       ++txt;
       --sz;
+      // have we run off the end of the view?
+      if (sz < 1U) {
+        // If we have a blank input string, should this throw or return 0?
+        // throw boost::bad_lexical_cast();
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MolFileParser.cpp:85]: I believe that the docs say that empty strings are zero, so what you have is right.
```suggestion
```

File: Code/GraphMol/FileParsers/MolFileParser.cpp [hunk 2]
```diff
@@ -109,6 +116,12 @@ unsigned int toUnsigned(const std::string_view input, bool acceptSpaces) {
...
```
Comment (greglandrum) [inline Code/GraphMol/FileParsers/MolFileParser.cpp:122]: same as above:
```suggestion
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
Code change looks good. Only suggestion is to remove the comments with questions.

**Comment by greglandrum** [comment]
Hmm, this was due to a coverage problem in our tests - there was nothing there making sure that `molReactStatus` is properly read. 
Good to have that covered now. Thanks @jones-gareth

**Comment by jones-gareth** [comment]
I had originally changed `toInt` and `toUnsigned` to throw `bad_lexical_cast` when parsing a blank string.

This was causing errors when parsing mol files during testing.

For example reading `Code/GraphMol/DistGeomHelpers/test_data/Issue3483968.mol` , `RDKit::ParseMolFileAtomLine` throws `FileParseException`  as the first atom line has `text.substr(54, 3) == "   "`

```c++
  if (text.size() >= 57 && text.substr(54, 3) != "  0") {
    int rxnRole = 0;
    try {
      rxnRole = FileParserUtils::toInt(text.substr(54, 3), true);
    } catch (boost::bad_lexical_cast &) {
      std::ostringstream errout;
      errout << "Cannot convert '" << text.substr(54, 3) << "' to int on line "
             << line;
      delete res;
      throw FileParseException(errout.str());
    }
```

Similarly in `RDKit::MolDataStreamToMol` when parsing the header line this throws when blank and the remaining settings on the header line are ignored:

```C++
    spos = 18;
    if (tempStr.size() >= spos + 3) {
      nRxnComponents =
          FileParserUtils::toUnsigned(tempStr.substr(spos, 3), true);
    }

```

So now when parsing mol block headers and atom lines a default value of 0 is used if field is blank.  Not sure how correct that is,
but it is presumably better than using the next non blank field.

If this is incorrect and the parsing code needs to change I'm happy to do that, but need some guidance.

**Comment by jones-gareth** [comment]
Ignore my last comment- yours came through while I was typing it.

**Comment by jones-gareth** [comment]
> Code change looks good. Only suggestion is to remove the comments with questions.

I've removed those comments.
