### PR TITLE
Fixes #6944

### LINKED ISSUE #6944: With new stereo, removing H from an Imine double bond does not remove bond stereo
Minimal example:
```python
In [1]: # Enable the new stereo algo 
   ...: Chem.SetUseLegacyStereoPerception(False)                                                                                            

In [2]: m = Chem.MolFromMolBlock(""" 
   ...:   Mrv2311 11272321162D           
   ...:  
   ...:   0  0  0     0  0            999 V3000 
   ...: M  V30 BEGIN CTAB 
   ...: M  V30 COUNTS 5 4 0 0 0 
   ...: M  V30 BEGIN ATOM 
   ...: M  V30 1 O -9.1458 6.4583 0 0 
   ...: M  V30 2 C -8.1154 5.3139 0 0 
   ...: M  V30 3 C -8.5913 3.8493 0 0 
   ...: M  V30 4 N -6.609 5.6341 0 0 
   ...: M  V30 5 H -6.1331 7.0987 0 0 
   ...: M  V30 END ATOM 
   ...: M  V30 BEGIN BOND 
   ...: M  V30 1 1 2 3 
   ...: M  V30 2 2 2 4 
   ...: M  V30 3 1 4 5 
   ...: M  V30 4 1 1 2 
   ...: M  V30 END BOND 
   ...: M  V30 END CTAB 
   ...: M  END 
   ...: """)                                                                                                                                

In [3]: m.Debug()                                                                                                                           
Atoms:
	0 8 O chg: 0  deg: 1 exp: 1 imp: 1 hyb: 3 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 3 arom?: 0 chi: 0
	2 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
	3 7 N chg: 0  deg: 2 exp: 3 imp: 0 hyb: 3 arom?: 0 chi: 0
	4 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 1 arom?: 0 chi: 0
Bonds:
	0 1->2 order: 1 dir: 3 conj?: 0 aromatic?: 0
	1 1->3 order: 2 stereo: 5 stereoAts: (2 4) conj?: 1 aromatic?: 0
	2 3->4 order: 1 dir: 4 conj?: 0 aromatic?: 0
	3 0->1 order: 1 dir: 3 conj?: 1 aromatic?: 0

In [4]: # Doing just 'RemoveHs' won't remove the H, since it defines the bond stereo 
   ...: m2 = Chem.RemoveAllHs(m)                                                                                                            

In [5]: # Neither the stereo nor the bond directions have been cleaned up 
   ...: m2.Debug()
Atoms:
	0 8 O chg: 0  deg: 1 exp: 1 imp: 1 hyb: 3 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 3 arom?: 0 chi: 0
	2 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
	3 7 N chg: 0  deg: 1 exp: 2 imp: 1 hyb: 3 arom?: 0 chi: 0
Bonds:
	0 1->2 order: 1 dir: 3 conj?: 0 aromatic?: 0
	1 1->3 order: 2 stereo: 5 conj?: 1 aromatic?: 0
	2 0->1 order: 1 dir: 3 conj?: 1 aromatic?: 0

In [6]: # ... and now this doesn't work 
   ...: Chem.AssignStereochemistry(m2)                                                                                                      
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-acec08a98022> in <module>
      1 # ... and now this doesn't work
----> 2 Chem.AssignStereochemistry(m2)

ValueError: only can support 2 stereo neighbors
```

### PR DESCRIPTION
**Pull request by ricrogz**
This fixes #6944.

The fix is simple: when removing H atoms, just check if they are defining bond stereo, and if so, clear the stereo on the bond.

### CODE REVIEW

File: Code/GraphMol/test_fixtures.h [hunk 1]
```diff
@@ -1,3 +1,13 @@
+//
+//  Copyright (C) 2023 Greg Landrum and other RDKit contributors
```
Comment (greglandrum) [inline Code/GraphMol/test_fixtures.h:2]: I think you were the original author of this code, but we can merge it this way way if you don't want to change it.

Comment (ricrogz) [reply Code/GraphMol/test_fixtures.h:2]: Oh, I'm okay with being one of the "other RDKit contributors", no need to mention me by name :)

**Review by greglandrum — APPROVED** [review]
LGTM
