### PR TITLE
Fixes #1735

### LINKED ISSUE #1735: rdmolfiles.CanonicalRankAtoms segfaults on 0 atom molecules.
**Description:**

- RDKit Version:2017.09.01
- Platform:64 bit linux ubuntu installed through conda install -c rdkit rdkit=2017.09.01

``` python
from rdkit import Chem
from rdkit.Chem import rdmolfiles
from rdkit.Chem import rdmolops

mol = Chem.MolFromSmiles("")
print(mol) # <rdkit.Chem.rdchem.Mol object at 0x7fa4e203c670>
new_order = rdmolfiles.CanonicalRankAtoms(mol) # This segfaults
mol = rdmolops.RenumberAtoms(mol, new_order)
```

rdmolfiles.CanonicalRankAtoms(mol) segfaults upon 0 atom molecules.  I think it should either return an empty list or throw a ValueError.

### PR DESCRIPTION
**Pull request by bp-kelley**
#### Reference Issue

Fixes #1735

#### What does this implement/fix? Explain your changes.

I’m unsure if this is the correct solution, it appears empty molecules can't initialize their rings so we need to check for that when using ring information.

### CODE REVIEW

**Comment by bp-kelley** [comment]
This apparently fixes the OS X issue, but not linux.  I expect it is a 0 byte allocation issue on linux.

File: Code/GraphMol/new_canon.cpp [hunk 1]
```diff
@@ -567,6 +567,9 @@ void updateAtomNeighborNumSwaps(
 
 void rankMolAtoms(const ROMol &mol, std::vector<unsigned int> &res,
                   bool breakTies, bool includeChirality, bool includeIsotopes) {
+  if (!mol.getNumAtoms())
```
Comment (greglandrum) [inline Code/GraphMol/new_canon.cpp]: Should probably move the `res.resize(mol.getNumAtoms());` that's a few lines lower to be the first line in the function. That way it will be returned with the appropriate size, even if there are zero atoms.

File: Code/GraphMol/new_canon.cpp [hunk 2]
```diff
@@ -595,7 +598,9 @@ void rankFragmentAtoms(const ROMol &mol, std::vector<unsigned int> &res,
   PRECONDITION(bondsInPlay.size() == mol.getNumBonds(), "bad bondsInPlay size");
   PRECONDITION(!atomSymbols || atomSymbols->size() == mol.getNumAtoms(),
                "bad atomSymbols size");
-
+  if (!mol.getNumAtoms())
```
Comment (greglandrum) [inline Code/GraphMol/new_canon.cpp]: Same comment about `res.resize(mol.getNumAtoms())` applies here

File: Code/GraphMol/new_canon.cpp [hunk 3]
```diff
@@ -618,6 +623,9 @@ void rankFragmentAtoms(const ROMol &mol, std::vector<unsigned int> &res,
 }  // end of rankFragmentAtoms()
 
 void chiralRankMolAtoms(const ROMol &mol, std::vector<unsigned int> &res) {
+  if(!mol.getNumAtoms())
```
Comment (greglandrum) [inline Code/GraphMol/new_canon.cpp]: Same comment about `res.resize(mol.getNumAtoms())` applies here
