### PR TITLE
Check for duplicate bond creation during closure

### LINKED ISSUE #2556: MolFromSmiles failure causes memory leak/double free
**Description:**

There appears to be a double free() in MolFromSmiles if the underlying topology is in error, as with "C1C1". In an older version of RDKit, there is no double free, but there is a memory leak.

I tested this under 2018.03.4, 2019_03_3, and git HEAD as of 22 July 2019.

- RDKit Version:  '2019.09.1dev1'
- Platform: macOS Mojave 10.14.4

In RDKit-2019_03_3 and git HEAD, MolFromSmiles("C1CC1") causes a free() error, saying "pointer being freed was not allocated".

```
>>> from rdkit import Chem
>>> Chem.MolFromSmiles("C1C1")
[11:16:02]

****
Pre-condition Violation
bond already exists
Violation occurred on line 386 in file /Users/dalke/cvses/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: !(boost::edge(bond_pin->getBeginAtomIdx(), bond_pin->getEndAtomIdx(), d_graph) .second)
****

python(16524,0x112cec5c0) malloc: *** error for object 0x7fef7b890298: pointer being freed was not allocated
python(16524,0x112cec5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort
```

In RDKit-2018.03.4 it correctly gives the "Pre-condition Violation" (just like the newer versions) but it does not have the double free. Instead, it has a memory leak.

I assume the change causing the above was part of trying to fix that leak, but that's only a guess.

The reproducible is:
```
from rdkit import Chem
Chem.MolFromSmiles("C1C1")
```

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #2556

### CODE REVIEW

File: Code/GraphMol/SmilesParse/test.cpp [hunk 1]
```diff
@@ -4188,12 +4188,23 @@ void testGithub1972() {
...
+  TEST_ASSERT(!m);
+  BOOST_LOG(rdInfoLog) << "done" << std::endl;
+}
+
 int main(int argc, char *argv[]) {
   (void)argc;
   (void)argv;
   RDLog::InitLogs();
 // boost::logging::enable_logs("rdApp.debug");
-#if 0
```
Comment (greglandrum) [inline Code/GraphMol/SmilesParse/test.cpp]: Crap. That shouldn’t have been checked in like that. Thanks for catching it.
