### PR TITLE
Fixes #2229

### LINKED ISSUE #2229: problem round-tripping mol files that include bond topology info
**Description:**

- RDKit Version: 2018.09.1
- Platform: Linux

Hello,

Here is another unexpected behavior we observed in relation to the management of query features in mol files. Round-tripping a mol block may result in the replacement of a bond with specified topology, with a bond of type "any".

```
from rdkit import Chem

ctab0 = '''
  MJ150720          2D          

  9  9  0  0  0  0  0  0  0  0999 V2000
   -3.1027    0.2335    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8171   -0.1789    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8171   -1.0040    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1027   -1.4165    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3882   -1.0040    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3882   -0.1789    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1027    1.0585    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8172    1.4710    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5316    1.0584    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  1  1  0  0  0  0
  1  7  1  0  0  0  0
  7  8  1  0  0  2  0
  8  9  1  0  0  0  0
M  END
'''

print(ctab0)

m0 = Chem.MolFromMolBlock(ctab0)

ctab1 = Chem.MolToMolBlock(m0)

print(ctab1)

```

### PR DESCRIPTION
**Pull request by greglandrum**
Another one to fix the logic of how queries are written

### CODE REVIEW

File: Code/GraphMol/FileParsers/MolFileWriter.cpp [hunk 1]
```diff
@@ -50,12 +50,15 @@ int getQueryBondTopology(const Bond *bond) {
       qry->endChildren() - qry->beginChildren() == 2) {
     auto child1 = qry->beginChildren();
     auto child2 = child1 + 1;
-    if ((*child1)->getDescription() == "BondOr" &&
-        (*child2)->getDescription() == "BondInRing") {
-      qry = child2->get();
-    } else if ((*child1)->getDescription() == "BondInRing" &&
-               (*child2)->getDescription() == "BondOr") {
-      qry = child1->get();
+    if (((*child1)->getDescription() == "BondInRing") !=
```
Comment (bp-kelley) [inline Code/GraphMol/FileParsers/MolFileWriter.cpp]: I'm not quite sure what the integer value for getQueryBondTopology means.

My guess:

```
0: no topology
1: query matches a bond in ring
2: query does not match a bond in ring
```

Why is this test only one level deep, couldn't this be in a lower tree?  It is unclear to me what BondOr or BondOrder goes to the deeper node.  I'm assuming this is a bit greedy and is specific to what can happen in an SDF file.

Comment (greglandrum) [reply Code/GraphMol/FileParsers/MolFileWriter.cpp]: Yeah, the int values are what one finds in a CTAB.

These specific tests are, as you guess, there to recognize particular things that happen in CTABs and some SMARTS queries.

Having a set of general predicates that allow us to recognize particularly query formulations would be a good thing. But that's a bigger change.
