### PR TITLE
Fix a couple of problems with MolStandardize

### LINKED ISSUE #5317: MolStandardize: uncharger failing in molecules with zwitterionic sulfone
**Describe the bug**

```
In [46]: m = Chem.MolFromSmiles("C[S+2]([O-])([O-])C([O-])C(=O)O")

In [47]: uc = rdMolStandardize.Uncharger()

In [48]: Chem.MolToSmiles(uc.uncharge(m))
Out[48]: 'C[S+2]([O-])([O-])C([O-])C(=O)O'
```
That should be `C[S+2]([O-])([O-])C(O)C(=O)O`

**Configuration (please complete the following information):**
 - RDKit version: 2022.03 and master
 - OS: all

### PR DESCRIPTION
**Pull request by greglandrum**
This fixes #5317, #5318, and #5320

### CODE REVIEW

File: Code/GraphMol/MolStandardize/Charge.cpp [hunk 1]
```diff
@@ -355,6 +360,14 @@ ROMol *Uncharger::uncharge(const ROMol &mol) {
   unsigned int n_matched = SubstructMatch(*omol, *(this->neg), n_matches);
   unsigned int a_matched = SubstructMatch(*omol, *(this->neg_acid), a_matches);
 
+  // count the total number of negative atoms
+  unsigned int n_neg = 0;
+  for (const auto atom : omol->atoms()) {
+    if (atom->getFormalCharge() < 0) {
+      n_neg += 1;
+    }
+  }
```
Comment (ptosco) [inline Code/GraphMol/MolStandardize/Charge.cpp:369]:
```suggestion
  unsigned int n_neg = std::count_if(
      omol->atoms().begin(), omol->atoms().end(),
      [](const auto atom) { return (atom->getFormalCharge() < 0); });
```

**Review by ptosco — APPROVED** [review]
LGTM, I only made a cosmetic suggestion.
