### PR TITLE
Fixes #6640

### LINKED ISSUE #6640: Simple imine-containing molecule causes an infinite loop in FindStereo.cpp
With current RDKit master, the following Python snippet causes an infinite loop:

```
from rdkit import Chem

Chem.SetUseLegacyStereoPerception(False)
mol = Chem.MolFromSmiles('NC1=NC(=N)N=C(N)C1C')
```

`gdb` shows that the infinite loop takes place in `runCleanup` at line 1053 inside `FindStereo.cpp`, as `updateBonds()` always returns `true`:
```
#5  RDKit::Chirality::(anonymous namespace)::updateBonds (mol=..., aranks=..., bondSymbols=..., possibleAtoms=..., possibleBonds=..., knownAtoms=..., knownBonds=..., fixedBonds=..., sinfos=...)
    at /scratch/toscopa1/src/rdkit/Code/GraphMol/FindStereo.cpp:827
#6  0x00007fffec6a1213 in RDKit::Chirality::(anonymous namespace)::runCleanup (mol=..., flagPossible=<optimized out>, cleanIt=<optimized out>) at /scratch/toscopa1/src/rdkit/Code/GraphMol/FindStereo.cpp:1053
#7  0x00007fffec6a17e6 in RDKit::Chirality::findPotentialStereo (mol=..., cleanIt=cleanIt@entry=true, findPossible=findPossible@entry=true) at /scratch/toscopa1/src/rdkit/Code/GraphMol/FindStereo.cpp:1073
#8  0x00007fffec64e32b in RDKit::Chirality::stereoPerception (mol=..., cleanIt=<optimized out>, flagPossibleStereoCenters=<optimized out>) at /scratch/toscopa1/src/rdkit/Code/GraphMol/Chirality.cpp:2175
#9  0x00007fffec65ff06 in RDKit::MolOps::assignStereochemistry (mol=..., cleanIt=<optimized out>, force=<optimized out>, flagPossibleStereoCenters=<optimized out>) at /scratch/toscopa1/src/rdkit/Code/GraphMol/Chirality.cpp:2206
#10 0x00007fffec7a3388 in RDKit::SmilesToMol (smiles=..., params=...) at /scratch/toscopa1/src/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:454
#11 0x00007fffec13dacf in RDKit::SmilesToMol (replacements=0x7fffffff9520, sanitize=true, debugParse=0, smi=...) at /scratch/toscopa1/src/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:81
#12 RDKit::MolFromSmiles (ismiles=..., sanitize=<optimized out>, replDict=...) at /scratch/toscopa1/src/rdkit/Code/GraphMol/Wrap/rdmolfiles.cpp:74
```

I managed to track down the cause of the regression, which was introduced by #6473 and the follow-up PR #6527.
@ricrogz Would you have time to take a look? Many thanks in advance!

### PR DESCRIPTION
**Pull request by ricrogz**
This Fixes #6640.

This is the structure that is causing the infinite loop:
NC1=NC(=N)N=C(N)C1C

The cause of the loop is the dependency between the potential stereochemistries of atom 8 and  the imide double bond at the opposite side of the ring. Given that the imide bond does not have any "real" neighbors (just an implicit H), it can never be resolved to cis or trans, and would stay undersolved after https://github.com/rdkit/rdkit/pull/6473 and https://github.com/rdkit/rdkit/pull/6527. The reason we didn't see this after any of these patches is that none of the structures we looked at there did have a dependency on the newly added (and fixed) imine bonds.

This fix solves the infinite loop problem by catching the neighborless imine bonds in `updateBonds()` and definitively marking them as "Unknown", since the lack of neighbors on one side prevents us from ever resolving the bond into cis or trans. Once the imine bond is no longer indetermined, the dependency does no longer trigger an infinite loop.

### CODE REVIEW

File: Code/GraphMol/FindStereo.cpp [hunk 1]
```diff
@@ -770,6 +770,20 @@ bool updateBonds(ROMol &mol, const std::vector<unsigned int> &aranks,
...
+      if ((sinfo.controllingAtoms[0] == Chirality::StereoInfo::NOATOM &&
+           sinfo.controllingAtoms[1] == Chirality::StereoInfo::NOATOM) ||
+          (sinfo.controllingAtoms[2] == Chirality::StereoInfo::NOATOM &&
+           sinfo.controllingAtoms[3] == Chirality::StereoInfo::NOATOM)) {
+        // we have a bond with no neighbors on one side, which means it must
+        // have a single implicit H on that side. Since the H is implicit,
+        // there is no way to know whether it is cis or trans.
+        ASSERT_INVARIANT(
+            sinfo.specified == StereoSpecified::Unknown,
+            "stereo bond without neighbors can only be unspecified");
```
Comment (greglandrum) [inline Code/GraphMol/FindStereo.cpp:783]: We generally use `ASSERT_INVARIANT` for things which should never ever happen (i.e. are due to egregious programming errors). It will either throw or assert, so the next line will never be called.
I think this should be, at most, a warning.

**Review by greglandrum — CHANGES_REQUESTED** [review]
minor suggested change

File: Code/GraphMol/FindStereo.cpp (hunk 1 above)
Comment (ricrogz) [reply Code/GraphMol/FindStereo.cpp:783]: I added the assert as a guard for future changes, to force us to come back to this check if we ever change the way these double bonds without neighbors are handled.

I think a warning doesn't make sense here because after #6527 `getStereoInfo()` should set stereo bonds with no neighbors (only an implicit H) on at least one one side to `sinfo.specified` to `StereoSpecified::Unknown`, so having any other value here doesn't seem possible.

**Review by greglandrum — APPROVED** [review]

**Comment by ptosco** [comment]
@ricrogz Thanks a lot for the quick fix!

**Comment by ricrogz** [comment]
No problem!
