### PR TITLE
Fixes #6592

### LINKED ISSUE #6592: SIGSEGV while calculating molecular descriptors after using salt remover.
**Describe the bug**
SIGSEGV while calculating molecular descriptors after using salt remover.

**To Reproduce**
```
def getMolDescriptors(mol, missingVal=None):
    from rdkit.Chem import Descriptors
    res = {}
    for nm,fn in Chem.Descriptors._descList:
        try:
            val = fn(mol)
        except:
            import traceback
            traceback.print_exc()
            val = missingVal
        res[nm] = val
    return res


mol = Chem.MolFromSmiles("CS(=O)(=O)O")
remover = SaltRemover()
stripped = remover.StripMol(mol)
getMolDescriptors(stripped)
```

**Expected behavior**
Calculate descriptors.

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2, pip installed
 - OS: Ubuntu 22.04
 - Python version (if relevant): 3.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**
If visualised, the stripped mol is empty.

### PR DESCRIPTION
**Pull request by bp-kelley**
BCUT segfaults on empty molecules

### CODE REVIEW

File: Code/GraphMol/Descriptors/BCUT.cpp [hunk 1]
```diff
@@ -101,10 +103,13 @@ std::pair<double, double> BCUT2D(const ROMol &m,
 }
 
 std::vector<double> BCUT2D(const ROMol &m) {
+  unsigned int num_atoms = m.getNumAtoms();
+  PRECONDITION(num_atoms > 0,
```
Comment (greglandrum) [inline Code/GraphMol/Descriptors/BCUT.cpp:107]: I think these should be ValueErrors, not  preconditions.
It's caused by the user providing bad input, it's not a catastrophic programming error.

Comment (bp-kelley) [reply Code/GraphMol/Descriptors/BCUT.cpp]: I switched it to return a vector of zeros, seems the right thing to do and now no one has to worry about try...catch

File: Code/GraphMol/Descriptors/BCUT.cpp [hunk 2]
```diff
@@ -66,6 +66,10 @@ std::unique_ptr<Eigen::MatrixXd> make_burden(const ROMol &m) {
 
 std::pair<double, double> BCUT2D(std::unique_ptr<Eigen::MatrixXd> &burden,
                                  const std::vector<double> &atom_props) {
+  if(atom_props.size() == 0) {
```
Comment (greglandrum) [inline Code/GraphMol/Descriptors/BCUT.cpp:69]:
```suggestion
  if(atom_props.empty()) {
```

File: Code/GraphMol/Descriptors/BCUT.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/Descriptors/BCUT.cpp]: I'm ok with this, but callers still need to do a try...catch since this function with throw if any of the atoms don't have a gasteiger charge property

File: Code/GraphMol/Descriptors/BCUT.cpp [hunk 3]
```diff
@@ -101,10 +105,14 @@ std::pair<double, double> BCUT2D(const ROMol &m,
 }
 
 std::vector<double> BCUT2D(const ROMol &m) {
+  unsigned int num_atoms = m.getNumAtoms();
+  if(num_atoms == 0) {
+        return {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
```
Comment (greglandrum) [inline Code/GraphMol/Descriptors/BCUT.cpp:110]: there's something about this list of 0's that makes me nervous.
How about something like this (not tested)?
```suggestion
        constexpr size_t bcutSize=8;
        return std::vector<double>(8,0.0);
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
a couple of minor suggestions

File: Code/GraphMol/Descriptors/BCUT.cpp (hunk 3 above)
Comment (bp-kelley) [reply Code/GraphMol/Descriptors/BCUT.cpp:110]: This is what I use in the test, so it's fine.  I might make the 8 a non-magic number though.

File: Code/GraphMol/Descriptors/BCUT.cpp (hunk 2 above)
Comment (bp-kelley) [reply Code/GraphMol/Descriptors/BCUT.cpp]: done

File: Code/GraphMol/Descriptors/BCUT.cpp (hunk 3 above)
Comment (bp-kelley) [reply Code/GraphMol/Descriptors/BCUT.cpp]: done

File: Code/GraphMol/Descriptors/BCUT.cpp [hunk 4]
```diff
@@ -18,6 +18,8 @@
 
 namespace RDKit {
 namespace Descriptors {
+const int NUM_BCUTS = 8;
```
Comment (greglandrum) [inline Code/GraphMol/Descriptors/BCUT.cpp:21]:
```suggestion
constexpr int NUM_BCUTS = 8;
```

**Comment by bp-kelley** [comment]
@greglandrum this might be ready to go now.

**Review by greglandrum — APPROVED** [review]
LGTM
