### PR TITLE
Fixes #1090

### LINKED ISSUE #1090: MolsToGridImage barfs on '&' in labels, at least with useSVG=True
My env:
```
> conda list rdkit
# packages in environment at /usr/local/anaconda2/envs/rdk0:
#
Using Anaconda Cloud api site https://api.anaconda.org
rdkit-postgresql95        2016.03.4                py27_1    greglandrum
rdkit                     2016.03.4           np111py27_1    rdkit
```

---------------------------------------------------------------
The following renders fine:
```
from rdkit.Chem.Draw import MolsToGridImage
from rdkit.Chem import MolFromSmiles
gridImage = MolsToGridImage([MolFromSmiles('C')], legends=['methane'], useSVG=True)
gridImage
```
However, the following, which simply changes the definition of legends to  ['methane &'], fails as shown below.
```
from rdkit.Chem.Draw import MolsToGridImage
from rdkit.Chem import MolFromSmiles
gridImage = MolsToGridImage([MolFromSmiles('C')], legends=['methane &'], useSVG=True)
gridImage
```
ExpatError                                Traceback (most recent call last)
<ipython-input-63-ec2ece08dfc2> in <module>()
      1 from rdkit.Chem.Draw import MolsToGridImage
      2 from rdkit.Chem import MolFromSmiles
----> 3 gridImage = MolsToGridImage([MolFromSmiles('C')], legends=['methane&'], useSVG=True)
      4 gridImage

/usr/local/anaconda2/envs/rdk0/lib/python2.7/site-packages/rdkit/Chem/Draw/IPythonConsole.pyc in ShowMols(mols, **kwargs)
    202     res = fn(mols,**kwargs)
    203     if kwargs['useSVG']:
--> 204         return SVG(res)
    205     else:
    206         return res

/usr/local/anaconda2/envs/rdk0/lib/python2.7/site-packages/IPython/core/display.pyc in __init__(self, data, url, filename)
    388                 data = None
    389 
--> 390         self.data = data
    391         self.url = url
    392         self.filename = None if filename is None else unicode_type(filename)

/usr/local/anaconda2/envs/rdk0/lib/python2.7/site-packages/IPython/core/display.pyc in data(self, svg)
    496         from xml.dom import minidom
    497         svg = cast_bytes_py2(svg)
--> 498         x = minidom.parseString(svg)
    499         # get svg tag (should be 1)
    500         found_svg = x.getElementsByTagName('svg')

/usr/local/anaconda2/envs/rdk0/lib/python2.7/xml/dom/minidom.pyc in parseString(string, parser)
   1926     if parser is None:
   1927         from xml.dom import expatbuilder
-> 1928         return expatbuilder.parseString(string)
   1929     else:
   1930         from xml.dom import pulldom

/usr/local/anaconda2/envs/rdk0/lib/python2.7/xml/dom/expatbuilder.pyc in parseString(string, namespaces)
    938     else:
    939         builder = ExpatBuilder()
--> 940     return builder.parseString(string)
    941 
    942 

/usr/local/anaconda2/envs/rdk0/lib/python2.7/xml/dom/expatbuilder.pyc in parseString(self, string)
    221         parser = self.getParser()
    222         try:
--> 223             parser.Parse(string, True)
    224             self._setup_subset(string)
    225         except ParseEscape:

ExpatError: not well-formed (invalid token): line 10, column 183

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

File: Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp [hunk 1]
```diff
@@ -259,6 +260,16 @@ void MolDraw2DSVG::getStringSize(const std::string &label, double &label_width,
   }
 }
 
+namespace {
+void escape_xhtml(std::string &data) {
```
Comment (bp-kelley) [inline Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp]: This code is fine, but there is also:

https://www.tena-sda.org/doc/5.2.1/boost/d3/df1/namespaceboost_1_1spirit_1_1xml.html

And we already use the spirit library.

Comment (greglandrum) [inline Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp]: Where do we use spirit? (At the airport and unable to search code)
It seems silly to add a dependency here for something so simple though

Comment (bp-kelley) [inline Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp]: I wasn't paying attention it was in a regression test: testFeatures

```
#include <boost/spirit/core.hpp>
```

So we would be adding a run-time dependency.
