### PR TITLE
Fixes #7689

### LINKED ISSUE #7689: RDKitValidation doesn't catch some valence issues
**Describe the bug**
The `RDKitValidation` class doesn't return an error for some valence violations that are not detected by `Atom::calcExplicitValence`.

**To Reproduce**

    In [1]: from rdkit import Chem
    
    In [2]: from rdkit.Chem.MolStandardize import rdMolStandardize
    
    In [3]: vm = rdMolStandardize.RDKitValidation()
    
    In [4]: mol = Chem.MolFromMolBlock('''
       ...:   MJ240300                      
       ...: 
       ...:   2  1  0  0  0  0  0  0  0  0999 V2000
       ...:    -4.8993    1.8410    0.0000 Br  0  5  0  0  0  0  0  0  0  0  0  0
       ...:    -5.6138    1.4285    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
       ...:   2  1  1  0  0  0  0
       ...: M  END
       ...: ''', sanitize=False)
    
    In [5]: vm.validate(mol)
    Out[5]: []

**Expected behavior**
The validation should fail with an error message like `Explicit valence for atom # 0 Br greater than permitted`

**Configuration (please complete the following information):**
 - RDKit version: current master branch
 - OS: [e.g. Ubuntu 20.04] Fedora 40
 - Python version (if relevant): not relevant
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? from source code

**Additional context**
The expected behavior would be easily produced if, in addition to `atom->calcExplicitValence()`, `RDKitValidation` also called `atom->calcImplicitValence()` (just like I think `Atom::hasValenceViolation` does). If this is the desired solution, I would be happy to create a small PR implementing it, but I found it a bit surprising that an "Explicit valence .." error was reported by `Atom::calcImplicitValence` and is not detected by `Atom::calcExplicitValence` and wondered if I am missing something.

Moreover, the behavior apparently depends on the input format, and `C[Br-]` is sanitized without errors.

### PR DESCRIPTION
**Pull request by greglandrum**
A typo in `calculateExplicitValence()` was causing things that should fail not to fail.

Fixing this turned up that we were still accepting two coordinate `[H-]` after the isoelectronic valence fix. We probably should not accept this, but removing it breaks a bunch of tests and I'm reluctant to do this just before a release.

We should revisit whether or not we think accepting `C[H-]C` is a good idea as part of the 2025.03 release cycle.

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco @ricrogz @bp-kelley I think that it would be good to merge this one before the 2024.09.1 release goes out there and people start seeing the isoelectronic valence code.
What's your take?

File: Code/GraphMol/Atom.cpp [hunk 1]
```diff
@@ -413,8 +413,14 @@ int calculateExplicitValence(const Atom &atom, bool strict, bool checkIt) {
...
     }
+    // we have historically accepted two-coordinate [H-] as a valid atom. This
+    // is highly questionable, but changing it requires some thought. For now we
+    // will just keep accepting it
+    if (atom.getAtomicNum() == 1 && atom.getFormalCharge() == -1) {
+      maxValence = 2;
+    }
     // maxValence == -1 signifies that we'll take anything at the high end
-    if (maxValence > 0 && ovalens.back() > 0 && (res + offset) > maxValence) {
+    if (maxValence >= 0 && ovalens.back() >= 0 && (res + offset) > maxValence) {
```
Comment (ptosco) [inline Code/GraphMol/Atom.cpp:423]: I totally agree with this fix; I already have it as part of my work-in-progress PR on dative bonds.

File: Code/GraphMol/Atom.cpp [hunk 2]
```diff
@@ -413,8 +413,14 @@ int calculateExplicitValence(const Atom &atom, bool strict, bool checkIt) {
       maxValence = ovalens.back();
       offset -= atom.getFormalCharge();
     }
+    // we have historically accepted two-coordinate [H-] as a valid atom. This
+    // is highly questionable, but changing it requires some thought. For now we
+    // will just keep accepting it
+    if (atom.getAtomicNum() == 1 && atom.getFormalCharge() == -1) {
+      maxValence = 2;
+    }
```
Comment (ptosco) [inline Code/GraphMol/Atom.cpp:421]: I also stumbled on `H-` while testing my PR and was a bit surprised. I am not quite sure why we do this, but I may be missing the historical background. Are you sure you need the above change, though? I do not think there were any tests failing before your proposed change.

**Review by ptosco — APPROVED** [review]
I agree with the `>=` changes - I already had those in my WIP dative bond PR. I am not sure you need the other change though - were there any tests failing without it?

**Review by ricrogz — APPROVED** [review]
Makes sense to me too.

File: Code/GraphMol/Atom.cpp (hunk 2 above)
Comment (greglandrum) [reply Code/GraphMol/Atom.cpp:421]: > I also stumbled on `H-` while testing my PR and was a bit surprised. I am not quite sure why we do this, but I may be missing the historical background. Are you sure you need the above change, though? I do not think there were any tests failing before your proposed change.

A bunch of tests (I think 6 or 7) were failing if I didn't add this. I started fixing them instead of adding this workaround, but then realized that it was maybe a step too far, so I added the "let's keep accepting `C[H-]C` for now" workaround.

I think it's worth coming back to this at some point since it doesn't fit the way we normally do things, but that would be for the 2025.03.1 release.

File: Code/GraphMol/MolStandardize/catch_tests.cpp [hunk 3]
```diff
@@ -1706,4 +1707,27 @@ TEST_CASE(
                   ValueErrorException);
   CHECK_THROWS_AS(MolStandardize::superParentInPlace(mols, numThreads),
                   ValueErrorException);
+}
+
+TEST_CASE("github #7689 RDKitValidation does not catch some valence issues") {
+  SECTION("basics") {
+    std::string mb = R"CTAB(foo
```
Comment (bp-kelley) [inline Code/GraphMol/MolStandardize/catch_tests.cpp:1714]: This test already  gets flagged on rdkit, so it does not appear to be sufficient for the fix

```
>>> rdkit.__version__
'2024.03.5'
```

```
mb = """foo
  MJ240300                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -4.8993    1.8410    0.0000 Br  0  5  0  0  0  0  0  0  0  0  0  0
   -5.6138    1.4285    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0  0  0  0
M  END"""
>>> Chem.MolFromMolBlock(mb)
[13:02:54] Explicit valence for atom # 0 Br, 2, is greater than permitted
```

Comment (bp-kelley) [reply Code/GraphMol/MolStandardize/catch_tests.cpp:1714]: Or is this coming from somewhere else?

Comment (ptosco) [reply Code/GraphMol/MolStandardize/catch_tests.cpp:1714]: @bp-kelley I believe the isoelectronic valence changes in `2024.09.1b1` suppressed the warnings; they were indeed there in 2024.03.5. The test is against `2024.09.1b1`.

Comment (greglandrum) [reply Code/GraphMol/MolStandardize/catch_tests.cpp:1714]: Yes, this was a bug introduced with the isoelectronic valence changes

Comment (bp-kelley) [reply Code/GraphMol/MolStandardize/catch_tests.cpp:1714]: Ok,  the regression was added here:  https://github.com/rdkit/rdkit/pull/7491

I'm up to speed.  Looks like a necessary fix!

File: Code/GraphMol/Atom.cpp (hunk 2 above)
Comment (bp-kelley) [reply Code/GraphMol/Atom.cpp:421]: I'm sure some solar chemist will want their hydride, but I, for one, can do without.  :)

**Review by bp-kelley — COMMENTED** [review]
LGTM

File: Code/GraphMol/Atom.cpp (hunk 2 above)
Comment (greglandrum) [reply Code/GraphMol/Atom.cpp:421]: > I'm sure some solar chemist will want their hydride, but I, for one, can do without. :)

It's not just a hydride, it's a hypervalent hydride!

Comment (ptosco) [reply Code/GraphMol/Atom.cpp:421]: > A bunch of tests (I think 6 or 7) were failing if I didn't add this. I started fixing them instead of adding this workaround, but then realized that it was maybe a step too far, so I added the "let's keep accepting `C[H-]C` for now" workaround.

I see; I also started doing exactly the same with the tests and then thought you would have hated that (you are always in my thoughts), so I also put in some countermeasure :)
