### PR TITLE
Shape overlay initial start aligned to principal axes

### LINKED ISSUE #8513: rdShapeAlign is sensitive to starting conformation
**Describe the bug**
rdShapeAlign.AlignMol produces significantly different output based on the rigid body transformation of the input.

**To Reproduce**
I have attached an ipython notebook which illustrates the issue by aligning omeprazole back to itself and showing success only 75% of the time

**Expected behavior**
Alignment should be robust to rigid body transforms.

**Screenshots**
n/a

**Configuration (please complete the following information):**
* RDKit version: rdkit==2024.9.6
* OS: macOS Sequoia 15.4.1
* Python version : 3.12
* Are you using conda? Yes
* If you are using conda, which channel did you install the rdkit from? Via pip install dependency listed as "rdkit>=2024.9.5"
* If you are not using conda: how did you install the RDKit? n/a

**Additional context**
This obviously could be a bug in thr underlying library or the wrapping code in rdkit. I have filed bug
https://github.com/ncbi/pubchem-align3d/issues/2
at pubchem-align3d

[2025-05-08 pubchem align bug.ipynb.gz](https://github.com/user-attachments/files/20102404/2025-05-08.pubchem.align.bug.ipynb.gz)

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
Fixes #8513 (hopefully).

#### What does this implement/fix? Explain your changes.
This sets up the shape overlay to start with the probe and reference both centred on the origin and aligned along their principal axes.  This is important for consistency of results with different relative positions and orientations of the 2 molecules.

#### Any other comments?
 A few of the test results have changed for the better, with one exception.  In the "re-entrant", "real example" the scores and overlay are noticeably worse than previously.  I have checked with the current master branch, explicitly putting the molecules into their canonical orientation and doing the overlay and I get the same result.  So I think this is a feature of the shape overlay rather than these changes.

FWIW, Roshambo2 does a better job with these 2 molecules.  I haven't attempted to hunt down the cause as I am intending to switch the shape overlay to use the Roshambo2 engine in any case.

### CODE REVIEW

**Comment by DavidACosgrove** [comment]
@greglandrum The failure in macOS_x64 is the SimDivPicker test.

File: External/pubchem_shape/test.cpp [hunk 1]
```diff
@@ -656,4 +644,25 @@ TEST_CASE("Score No Overlay") {
...
+  REQUIRE(tagrisso);
+  auto iressa =
+      "COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1 |(11.4672,-0.467948,5.63989;12.0133,0.532631,6.49693;11.2039,1.5801,6.81985;11.2014,2.71958,6.00975;10.3926,3.81652,6.29699;10.4038,4.90395,5.50623;9.58889,5.91871,5.85946;8.76443,5.96486,6.91838;8.77814,4.86059,7.68868;7.92337,4.86224,8.81914;7.44878,5.8925,9.64622;8.22182,7.03851,9.85619;7.75051,8.06265,10.6777;6.50441,7.94546,11.2936;6.06567,8.93802,12.0809;5.72932,6.80403,11.0875;4.19056,6.65372,11.8447;6.20047,5.78015,10.2656;9.57161,3.74547,7.43436;9.56851,2.60328,8.25407;10.3868,1.52933,7.93769;10.3797,0.419365,8.74203;11.3064,0.402096,9.81907;10.7104,-0.399165,10.9685;9.40938,0.22121,11.4678;9.64205,1.59049,11.9223;8.38006,2.22985,12.3199;8.64991,3.65266,12.8011;9.56883,3.64192,13.8942;10.8103,3.05101,13.5078;10.5931,1.61394,13.0425)|"_smiles;
+  REQUIRE(iressa);
+  std::vector<float> matrix(12, 0.0);
+  auto sims =
+      AlignMolecule(*tagrisso, *iressa, matrix, -1, -1, true, 0.5, 10, 30);
+  RDGeom::Point3D ave1;
```
Comment (greglandrum) [inline External/pubchem_shape/test.cpp]: you don't actually end up doing anything with ave1, right?

**Comment by greglandrum** [comment]
I haven't dug into this yet, and don't have time right now, but I just noticed a significant difference in results for some molecule pairs when I calculate the shape overlap with and without having done a principal axis alignment first:
```
nms1 = ['5TF_A_1-3ZCL.sdf',
 'JBA_A_301-6MAE.sdf',
 'ZZD_B_1365-2WOG.sdf',
 '4FM_A_301-4YQ0.sdf',
 '3KG_A_1003-3WYK.sdf',
 'IJQ_A_803-5SF8.sdf',
 'EHI_B_803-7QPV.sdf',
 'IJQ_A_803-5SF8.sdf',
 '5AY_A_803-5DH5.sdf',
 'LMS_A_302-6C7W.sdf']
nms2 = ['0J8_A_1401-4GG7.sdf',
 '5EM_A_303-5DRQ.sdf',
 '3QC_A_370-2FME.sdf',
 'SAM_A_301-1UAK.sdf',
 'II5_A_803-5SEW.sdf',
 '5AY_A_803-5DH5.sdf',
 'J2L_C_803-5SH3.sdf',
 'K5F_D_803-5SJT.sdf',
 'IJQ_A_803-5SF8.sdf',
 '3TV_A_306-4WW6.sdf']
for n1,n2 in zip(nms1,nms2):
    m1 = Chem.MolFromMolFile(f'/home/glandrum/Datasets/LOBSTER_112024/all_ligands/{n1}')
    m2 = Chem.MolFromMolFile(f'/home/glandrum/Datasets/LOBSTER_112024/all_ligands/{n2}')
    
    m1c1 = Chem.Mol(m1)
    m2c1 = Chem.Mol(m2)
    rdMolTransforms.CanonicalizeConformer(m1c1.GetConformer())
    rdMolTransforms.CanonicalizeConformer(m2c1.GetConformer())
    
    st1,ct1 = rdShapeAlign.AlignMol(m1c1,m2c1,opt_param=0.5)
    
    m1c2 = Chem.Mol(m1)
    m2c2 = Chem.Mol(m2)
    st2,ct2 = rdShapeAlign.AlignMol(m1c2,m2c2,opt_param=0.5)
    print(st1,st2)
    print(ct1,ct2)
    print('-------')
```
output:
```
0.5662140699037356 0.3235939159191495
0.09821394044728637 0.13278055983448173
-------
0.7196533520583176 0.5456840845943012
0.19788095092544558 0.06804197246387535
-------
0.6628638647106768 0.5217784178436775
0.05955511258596992 0.11979096147758268
-------
0.46164531572695755 0.5688836393941498
0.20552895483870598 0.2543418042570269
-------
0.6041889300631473 0.48861943322184626
0.032340745012027494 0.15618619897255956
-------
0.5747209454697664 0.4517494388509711
0.05740139119673974 0.19801141550156834
-------
0.827926257939421 0.7096341482904829
0.4070551497814733 0.2937445710669352
-------
0.6117797000092468 0.7126588349630073
0.16106441606563748 0.4120548153501665
-------
0.617447580533061 0.45099679440882395
0.12663099067609013 0.18764849001129894
-------
0.5520452265129094 0.6656496274036808
0.07685979781238907 0.03291021802261164
```

The input data is from the LOBSTER paper: https://link.springer.com/article/10.1007/s10822-024-00581-1

**Comment by DavidACosgrove** [comment]
@greglandrum Thanks, I'll have dig.

**Comment by DavidACosgrove** [comment]
I get different results on my Mac, but showing the same effect.  Taking the pair
ZZD_B_1365-2WOG.sdf 3QC_A_370-2FME.sdf
I get the same answers as you.  Looking at the output from PrepareConformer for the pair where I compute the canonical transformation first, and the pair where I just go straight in, I get these CXSMILES and similarities:
```
N[C@@H](CSC(c1ccccc1)(c1ccccc1)c1ccccc1)C(=O)O |(-3.62327,1.18888,-2.20202;-3.42849,-0.0757723,-1.48576;-2.22203,0.0890055,-0.566498;-0.63738,0.297919,-1.49833;0.736644,0.0869732,-0.237175;2.17141,0.262899,-0.781322;3.22637,0.571508,0.0898259;4.5516,0.656767,-0.36404;4.83935,0.441501,-1.71535;3.80016,0.103274,-2.58861;2.48022,-0.0120843,-2.10962;0.380764,1.1914,0.743876;0.625405,2.51815,0.382578;0.206683,3.54584,1.21726;-0.531647,3.23981,2.36114;-0.843366,1.9222,2.68101;-0.37865,0.901932,1.86566;0.684162,-1.31748,0.402514;-0.0872062,-2.31688,-0.186875;-0.145583,-3.58841,0.387141;0.572871,-3.86508,1.53944;1.3718,-2.8855,2.11875;1.41789,-1.60921,1.55768;-4.72555,-0.371238,-0.712534;-4.74643,-1.3617,0.0560411;-5.69573,0.38528,-0.954776),wU:1.0|
Cc1ccc2c(c1C)CN(C(=O)N(C)C)C[C@@H]2c1cccc(O)c1 |(4.8195,2.40798,-0.592757;3.44036,2.00108,-0.228342;2.39645,2.98271,-0.113102;1.09633,2.57454,0.318233;0.876285,1.17838,0.601315;1.91111,0.214031,0.437719;3.20374,0.620457,0.0410457;4.26198,-0.378746,-0.0834226;1.67757,-1.24285,0.617792;0.304287,-1.63117,0.816954;-0.227116,-2.82036,0.412238;-1.0694,-3.37541,1.11325;0.168359,-3.39805,-0.763502;0.783244,-2.75681,-1.93992;-0.0824165,-4.83492,-0.842962;-0.361657,-0.727229,1.7433;-0.44988,0.564058,0.92801;-1.70404,0.866815,0.187269;-1.6826,1.06337,-1.25857;-2.8584,1.41816,-2.01319;-4.07539,1.53752,-1.27292;-4.13454,1.31502,0.164081;-5.35313,1.44135,0.800684;-2.94064,0.980058,0.926799),wD:16.18|
sims2 : 0.662864, 0.0595551
N[C@@H](CSC(c1ccccc1)(c1ccccc1)c1ccccc1)C(=O)O |(-3.62327,1.18888,-2.20202;-3.42849,-0.0757723,-1.48576;-2.22203,0.0890055,-0.566498;-0.63738,0.297919,-1.49833;0.736644,0.0869732,-0.237175;2.17141,0.262899,-0.781322;3.22637,0.571508,0.0898259;4.5516,0.656767,-0.36404;4.83935,0.441501,-1.71535;3.80016,0.103274,-2.58861;2.48022,-0.0120843,-2.10962;0.380764,1.1914,0.743876;0.625405,2.51815,0.382578;0.206683,3.54584,1.21726;-0.531647,3.23981,2.36114;-0.843366,1.9222,2.68101;-0.37865,0.901932,1.86566;0.684162,-1.31748,0.402514;-0.0872062,-2.31688,-0.186875;-0.145583,-3.58841,0.387141;0.572871,-3.86508,1.53944;1.3718,-2.8855,2.11875;1.41789,-1.60921,1.55768;-4.72555,-0.371238,-0.712534;-4.74643,-1.3617,0.0560411;-5.69573,0.38528,-0.954776),wU:1.0|
Cc1ccc2c(c1C)CN(C(=O)N(C)C)C[C@@H]2c1cccc(O)c1 |(4.8195,-2.40798,0.592757;3.44036,-2.00108,0.228342;2.39645,-2.98271,0.113102;1.09633,-2.57454,-0.318233;0.876285,-1.17838,-0.601315;1.91111,-0.214031,-0.437719;3.20374,-0.620457,-0.0410457;4.26198,0.378746,0.0834226;1.67757,1.24285,-0.617792;0.304287,1.63117,-0.816954;-0.227116,2.82036,-0.412238;-1.0694,3.37541,-1.11325;0.168359,3.39805,0.763502;0.783244,2.75681,1.93992;-0.0824165,4.83492,0.842962;-0.361657,0.727229,-1.7433;-0.44988,-0.564058,-0.92801;-1.70404,-0.866815,-0.187269;-1.6826,-1.06337,1.25857;-2.8584,-1.41816,2.01319;-4.07539,-1.53752,1.27292;-4.13454,-1.31502,-0.164081;-5.35313,-1.44135,-0.800684;-2.94064,-0.980058,-0.926799),wU:16.18|
sims1 : 0.521778, 0.119791
```
The 2nd molecule is aligned in the opposite sense along the y and z axes:
Screenshot 2025-12-10 at 16 18 47
I've checked, this isn't the inversion bug, rdMolAlign.AlignMol gives an RMSD of 0.0 for the pair.
If I take the output from the 2nd overlay, do the canonical transformation on that and redo the overlay, I get a 3rd set of results:
```
N[C@@H](CSC(c1ccccc1)(c1ccccc1)c1ccccc1)C(=O)O |(-3.62327,1.18888,-2.20202;-3.42849,-0.0757723,-1.48576;-2.22203,0.0890055,-0.566498;-0.63738,0.297919,-1.49833;0.736644,0.0869732,-0.237175;2.17141,0.262899,-0.781322;3.22637,0.571508,0.0898259;4.5516,0.656767,-0.36404;4.83935,0.441501,-1.71535;3.80016,0.103274,-2.58861;2.48022,-0.0120843,-2.10962;0.380764,1.1914,0.743876;0.625405,2.51815,0.382578;0.206683,3.54584,1.21726;-0.531647,3.23981,2.36114;-0.843366,1.9222,2.68101;-0.37865,0.901932,1.86566;0.684162,-1.31748,0.402514;-0.0872062,-2.31688,-0.186875;-0.145583,-3.58841,0.387141;0.572871,-3.86508,1.53944;1.3718,-2.8855,2.11875;1.41789,-1.60921,1.55768;-4.72555,-0.371238,-0.712534;-4.74643,-1.3617,0.0560411;-5.69573,0.38528,-0.954776),wU:1.0|
Cc1ccc2c(c1C)CN(C(=O)N(C)C)C[C@@H]2c1cccc(O)c1 |(-4.8195,-2.40798,-0.592757;-3.44036,-2.00108,-0.228342;-2.39645,-2.98271,-0.113102;-1.09633,-2.57454,0.318233;-0.876285,-1.17838,0.601315;-1.91111,-0.214031,0.437719;-3.20374,-0.620457,0.0410457;-4.26198,0.378746,-0.0834226;-1.67757,1.24285,0.617792;-0.304287,1.63117,0.816954;0.227116,2.82036,0.412238;1.0694,3.37541,1.11325;-0.168359,3.39805,-0.763502;-0.783244,2.75681,-1.93992;0.0824166,4.83492,-0.842962;0.361657,0.727229,1.7433;0.44988,-0.564058,0.92801;1.70404,-0.866815,0.187269;1.6826,-1.06337,-1.25857;2.8584,-1.41816,-2.01319;4.07539,-1.53752,-1.27292;4.13454,-1.31502,0.164081;5.35313,-1.44135,0.800684;2.94064,-0.980058,0.926799),wD:16.18|
sims3 : 0.544878, 0.0594923

```
So it seems that the optimiser is going to different minima depending on the input orientation.  IIUC, it should be rotating them about the principal axes to 4 different start points to negate that effect, but that doesn't seem to be happening.

**Comment by greglandrum** [comment]
> So it seems that the optimiser is going to different minima depending on the input orientation. IIUC, it should be rotating them about the principal axes to 4 different start points to negate that effect, but that doesn't seem to be happening.

The thing that's confusing me is that I believe that the input orientations should be the same since I'm using the code from your PR (at least I *think* I am).
In once instance I am putting the molecules into the principal axis frame before handing it over to your modified code and in the second instance I am not doing so. In each case your code should be putting the molecules into the principal axis frame before calling into the Pubchem code.

What am i missing?

**Comment by DavidACosgrove** [comment]
I _think_ that what is happening is that the principal axes define axes but not directions. A molecule can be lined up along an axis with atom 1 in the -x direction and atom 2 in the +x direction or with atom 1 in the +x direction and atom 2 in the -x direction.  Both are equally valid and both are seen in these cases. I have put one of these molecules into the canonical transform, taken a new canonical transform on that and applied it and seen exactly this effect. That’s what the picture is trying to show. 

I believe that the overlay code should deal with this by applying 4 180 degree rotations to the input structure about the origin.  My suspicion is that it isn’t.

File: External/pubchem_shape/Wrap/test_rdshapealign.py [hunk 2]
```diff
@@ -58,13 +58,13 @@ def test5_ShapeShapeOverlay(self):
     probeShp = rdShapeAlign.PrepareConformer(self.probe, -1)
     tpl = rdShapeAlign.AlignShapes(refShp, probeShp)
     probeCp = Chem.Mol(self.probe)
-    rdShapeAlign.TransformConformer(refShp.shift, tpl[2], probeShp, probeCp.GetConformer(-1))
+    rdShapeAlign.TransformConformer(refShp.shift, refShp.inertialRot, tpl[2], probeShp, probeCp.GetConformer(-1))
```
Comment (greglandrum) [inline External/pubchem_shape/Wrap/test_rdshapealign.py:61]: please add a test for at least a couple of the values in `refShp.inertialRot` to make sure that your getter is working correctly

File: External/pubchem_shape/Wrap/cshapealign.cpp [hunk 3]
```diff
@@ -428,6 +447,9 @@ Returns
                      &ShapeInput::volumeAtomIndexVector)
       .add_property("shift", &helpers::get_shapeShift, &helpers::set_shapeShift,
                     "Translation of centre of shape coordinates to origin.")
+      .add_property(
+          "inertialRot", &helpers::get_inertialRot, &helpers::set_inertialRot,
```
Comment (greglandrum) [inline External/pubchem_shape/Wrap/cshapealign.cpp]: Are you sure that we actually need a setter for this one?
Is there a use case for being able to change this transformation from the Python side?

**Review by greglandrum — CHANGES_REQUESTED** [review]
small changes and questions

File: External/pubchem_shape/Wrap/cshapealign.cpp (hunk 3 above)
Comment (DavidACosgrove) [reply External/pubchem_shape/Wrap/cshapealign.cpp]: Force of habit, I guess.  I've taken it out.
