### PR TITLE
Fixes #1929

### LINKED ISSUE #1929: Using the coordgen library seems to cause a seg fault
Using the new CoordGen library to generate 2D coordinates seems to cause a seg fault

Version information:
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from rdkit import rdBase
In [2]: rdBase.rdkitVersion
Out[2]: '2018.03.2'
In [3]: rdBase.boostVersion
Out[3]: '1_65_1'`
```

Running Mac OS 10.11.6 having installed rdkit using conda

```
In [1]: from rdkit import Chem
   ...: from rdkit.Chem import rdDepictor
   ...: rdDepictor.SetPreferCoordGen(True)
   ...: m = Chem.MolFromSmiles('c1ccc(CC(=O)C)cc1O')
   ...: conf_num = rdDepictor.Compute2DCoords(m)
   ...: conf = m.GetConformer(conf_num)
   ...: print(conf.GetPositions())
   ...:
   ...:
Segmentation fault: 11
```

I may be using this functionality incorrectly, but it seems that generating 2D coordinates using schrodingers coordgen library is causing a segfault. If I comment out the line `rdDepictor.SetPreferCoordGen(True)`, this code runs okay.

### PR DESCRIPTION
**Pull request by greglandrum**
This does two things:
1) Remove the cause of the segfault
2) start setting `$RDBASE` on the Python side when `RDPaths` is being used.

### CODE REVIEW

File: External/CoordGen/CoordGen.h [hunk 1]
```diff
@@ -60,8 +63,9 @@ unsigned int addCoords(T& mol, const CoordGenParams* params = nullptr) {
 
   // FIX: only do this check once.
   std::cerr << "  TEMPLATES: " << templateFileDir << std::endl;
-  minimizer.setTemplateFileDir(templateFileDir);
-
+  if (templateFileDir != "") {
+    minimizer.setTemplateFileDir(templateFileDir);
```
Comment (bp-kelley) [inline External/CoordGen/CoordGen.h]: Is there any utility to ensure that the template file exists and throw an exception if not?

Comment (greglandrum) [reply External/CoordGen/CoordGen.h]: Given that we (==RDKit) don't "own" the file, we'd be making an assumption, possibly an incorrect one, about what that file name is.

Comment (greglandrum) [reply External/CoordGen/CoordGen.h]: Or did you mind check that the directory exists?

Comment (bp-kelley) [reply External/CoordGen/CoordGen.h]: The latter.  I'm assuming if the templatefileDir doesn't exist then bad things will happen.

Comment (greglandrum) [reply External/CoordGen/CoordGen.h]: I just checked this on my windows machine and everything seems fine.
That's fortunate since `std::filesystem` is a C++17 thing and I'd rather not add the `boost::filesystem` dependency here.
What I will do is add a test to make sure that the coordgen stuff still works when a bogus directory name is provided.

Comment (greglandrum) [reply External/CoordGen/CoordGen.h]: ok, that's now in
