### PR TITLE
Fixes bond index parsing for w/c/t/ctu labels in CXSMILES/CXSMARTS

### LINKED ISSUE #5683: SMILES and SMARTS parse bonds in a different order
This is a relevant issue when parsing strings with CX extensions, since these may include specifications that depend on bond indexes.

I noticed the issue because of a "incorrect" SMILES string:
```
from rdkit import Chem

# Note atom 3 is not connected to bond 1.
cxsmiles = 'O=C(C=CCC1CCCCC1)N1N=Cc2ccccc2C1c1ccccc1 |w:3.1|'

# This is the right behavior: the CX extension is incorrect, and since strictCXSMILES==true by default it should fail parsing
m1 = Chem.MolFromSmiles(cxsmiles)
# [10:01:43] atom 3 is not associated with bond 1 in w block

m1 is None
# True


# This is not right: this should fail too, but it doesn't!
m2 = Chem.MolFromSmarts(cxsmiles)
m2
# <rdkit.Chem.rdchem.Mol at 0x7f4f08145c40>
```

The `smiles` string should also fail to parse as SMARTS, but it doesn't, we get a mol back!

Looking into it, I stripped the CX extension from the string, and tried to parse it again, both as SMILES and SMARTS, and noticed the order of the bonds in the mol is different. Also, notice that bond 1 in the SMARTS is a double bond, so it doesn't make sense that it is wiggly (probably the parsed should check that too):

```
mol_smiles.Debug()
# [...]
# Bonds:
# 	0 0->1 order: 2 conj?: 1 aromatic?: 0
# 	1 1->2 order: 1 conj?: 1 aromatic?: 0
# 	2 2->3 order: 2 conj?: 1 aromatic?: 0
# 	3 3->4 order: 1 conj?: 0 aromatic?: 0
# 	4 4->5 order: 1 conj?: 0 aromatic?: 0
# 	5 5->6 order: 1 conj?: 0 aromatic?: 0
# 	6 6->7 order: 1 conj?: 0 aromatic?: 0
# 	7 7->8 order: 1 conj?: 0 aromatic?: 0
# 	8 8->9 order: 1 conj?: 0 aromatic?: 0
# 	9 9->10 order: 1 conj?: 0 aromatic?: 0
# 	10 1->11 order: 1 conj?: 1 aromatic?: 0

mol_smarts.Debug()
# [...]
# Bonds:
# 	0 0->1 order: 2 conj?: 0 aromatic?: 0
# 	1 2->3 order: 2 conj?: 0 aromatic?: 0
# 	2 3->4 order: 1 conj?: 0 aromatic?: 0
# 	3 4->5 order: 1 conj?: 0 aromatic?: 0
# 	4 5->6 order: 1 conj?: 0 aromatic?: 0
# 	5 6->7 order: 1 conj?: 0 aromatic?: 0
# 	6 7->8 order: 1 conj?: 0 aromatic?: 0
# 	7 8->9 order: 1 conj?: 0 aromatic?: 0
# 	8 9->10 order: 1 conj?: 0 aromatic?: 0
# 	9 2->1 order: 1 conj?: 0 aromatic?: 0
# 	10 1->11 order: 1 conj?: 0 aromatic?: 0
```

Note how the bond between atoms 1 and 2 has moved from index 1 in the SMILES to index 9 in the SMARTS. I think this doesn't have any impact on the Mol itself, but it breaks parsing the CX extensions (either for SMILES or for SMARTS, depending how the mol was generated), since the indexes of the bonds might no longer match the order in the literal string.

### PR DESCRIPTION
**Pull request by ricrogz**
In functions `parse_coordinate_bonds()`, `parse_doublebond_stereo()` and `parse_wedged_bonds()` we attempt to apply the corresponding features on bonds which have the specified indexes in the RDKit mol, instead of those that in the SMILES string. These do match for simple SMILES, but in cases where rings are involved, these might not match.

The issue was discovered and described for wiggly bonds, since these are specified using both an atom and a bond, and an error was raised when bond wasn't connected to the atom.

This is an example of the issue:
```python
mb = """
     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 9 10 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 2.366025 0.000000 0.000000 0
M  V30 2 C 0.866025 0.000000 0.000000 0
M  V30 3 C -0.433013 0.750000 0.000000 0
M  V30 4 N -0.433013 -0.750000 0.000000 0
M  V30 5 C -1.183013 -2.049038 0.000000 0
M  V30 6 C -2.683013 -2.049038 0.000000 0
M  V30 7 C -3.433013 -3.348076 0.000000 0
M  V30 8 C -3.433013 -4.848076 0.000000 0
M  V30 9 C -4.732051 -4.098076 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3
M  V30 3 1 3 4
M  V30 4 1 4 5
M  V30 5 2 5 6 CFG=2
M  V30 6 1 6 7
M  V30 7 1 7 8
M  V30 8 1 8 9
M  V30 9 1 4 2
M  V30 10 1 9 7
M  V30 END BOND
M  V30 END CTAB
M  END
"""

m = Chem.MolFromMolBlock(mb)

# The crossed double bond will be encoded as "w:" CX extension
# which requires an atom and a bond index.
b = m.GetBondWithIdx(4)
assert b.GetBondType() == Chem.BondType.DOUBLE
assert b.HasProp('_MolFileBondCfg')
assert b.GetIntProp('_MolFileBondCfg') == 2

m.RemoveAllConformers()  # Don't write coords to CXSMILES
cxsmi = Chem.MolToCXSmiles(m)
print(cxsmi)
# CC1CN1C=CC1CC1 |w:4.5|

m2 = Chem.MolFromSmiles(cxsmi)
# [11:32:52] atom 4 is not associated with bond 5 in w block
```

The issue is easily fixed if we can find the indexes of the bonds in the original SMILES string.

Note that the test for "t:" and "c:" labels make use of the new stereo algorithm. This is because with the legacy one these stereo labels are reset during the "clean up" stage of `assignStereochemistry()`: since there isn't a conformation available, these bonds never receive bond directions in https://github.com/rdkit/rdkit/blob/812568eb29a28ba6d0fbf40f8c4fca5d909d04ed/Code/GraphMol/SmilesParse/SmilesParse.cpp#L440-L446

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
This does fix a bug, but I don't think that it's actually #5683.
This still happens even with this change:
```
In [2]: cxsmiles = 'O=C(C=CCC1CCCCC1)N1N=Cc2ccccc2C1c1ccccc1 |w:3.1|'

In [3]: Chem.MolFromSmiles(cxsmiles)
[06:52:48] atom 3 is not associated with bond 1 in w block

In [4]: Chem.MolFromSmarts(cxsmiles)
Out[4]: <rdkit.Chem.rdchem.Mol at 0x7f03f5c02c70>
```

Rather than trying to fix both problems at the same time, I would suggest just changing the title of this and adjusting the description. Then we can fix the SMILES/SMARTS difference (which requires a modification to the SMARTS parser) separately

**Comment by ricrogz** [comment]
> Rather than trying to fix both problems at the same time, I would suggest just changing the title of this and adjusting the description. Then we can fix the SMILES/SMARTS difference (which requires a modification to the SMARTS parser) separately

Done!

File: Code/GraphMol/SmilesParse/catch_tests.cpp [hunk 1]
```diff
@@ -2278,3 +2278,44 @@ TEST_CASE("ring bond stereochemistry in CXSMILES") {
   }
   Chirality::setUseLegacyStereoPerception(oval);
 }
+
+TEST_CASE("Github #5683", "[SMILES][bug]") {
```
Comment (greglandrum) [inline Code/GraphMol/SmilesParse/catch_tests.cpp:2282]: This is no longer #5683 , you could call it #5722 or just briefly describe the bug (which is a good practice anyway)

File: Code/GraphMol/SmilesParse/CXSmilesOps.cpp [hunk 2]
```diff
@@ -467,15 +478,7 @@ bool parse_coordinate_bonds(Iterator &first, Iterator last, RDKit::RWMol &mol,
     if (read_int_pair(first, last, aidx, bidx)) {
       if (VALID_ATIDX(aidx) && bidx >= startBondIdx &&
           bidx < startBondIdx + mol.getNumBonds()) {
```
Comment (greglandrum) [inline Code/GraphMol/SmilesParse/CXSmilesOps.cpp:480]: I know this isn't part of your PR, but I think this could be:
```
      if (VALID_ATIDX(aidx) && VALID_BNDIDX(bondIdx)) {
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
A couple of small suggestions.

File: Code/GraphMol/SmilesParse/catch_tests.cpp (hunk 1 above)
Comment (ricrogz) [reply Code/GraphMol/SmilesParse/catch_tests.cpp:2282]: Oh, sure, I forgot about that one.

File: Code/GraphMol/SmilesParse/CXSmilesOps.cpp (hunk 2 above)
Comment (ricrogz) [reply Code/GraphMol/SmilesParse/CXSmilesOps.cpp:480]: Ok, I'll update it.

**Review by greglandrum — APPROVED** [review]
LGTM
