### PR TITLE
Fixes #4410

### LINKED ISSUE #4410: RDKit reaction produces wrong double bond stereochemistry
For a quite basic reaction RDKit since 2020.09 produces wrong stereochemistry on double bond. Last know version that worked correctly is 2020.03.

In following reaction latest RDKit (2021.03) is producing chlorines in cis position instead of trans.
image

Code to reproduce
```python
from rdkit.Chem import AllChem
from rdkit import Chem
rxn = AllChem.ReactionFromSmarts('[N:4][C:6](/[Cl:9])=[C:7](\\[Cl:10])[C:11].[Br:5]>>[N:4].[Br:5][CX3:6](\\[Cl:9])=[CX3:7](/[Cl:10])[C:11]')
res = rxn.RunReactants((Chem.MolFromSmiles('C\\C(Cl)=C(\\N)Cl'), Chem.MolFromSmiles('[Br]')))
assert Chem.MolToSmiles(res[0][1]) == 'C/C(Cl)=C(\\Cl)Br'
```

Version info:
 - RDKit version: 2021.03
 - OS: MacOS Big Sur
 - Python version (if relevant): 3.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

Pinging @ricrogz

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #4410

A simple fix for a silly mistake: in the reaction code, the part that calculates stereochemistry from product bond directions did not consider the possibility of reversed bonds, which effectively "flips" the direction.

This had been hidden from some time, until the stereo refactoring in 19bdd21de1c90f01f630b28ff72b3af9176d886f started recalculating bond directions even for bonds that already had them.

### CODE REVIEW

File: Code/GraphMol/ChemReactions/testReaction.cpp [hunk 1]
```diff
@@ -7624,6 +7625,29 @@ void testGithub4183() {
...
+  std::vector<ROMOL_SPTR> mol{R"(C\C(Cl)=C(\N)Cl)"_smiles};
+  auto prods = rxn->runReactants(mol);
+  TEST_ASSERT(prods.size() == 1);
+  TEST_ASSERT(prods[0].size() == 1);
+
+  auto dblBnd = prods[0][0]->getBondBetweenAtoms(1, 3);
+
+  TEST_ASSERT(dblBnd->getBondType() == Bond::DOUBLE);
+  TEST_ASSERT(dblBnd->getStereoAtoms() == std::vector<int>({2, 4}));
+  TEST_ASSERT(dblBnd->getStereo() == Bond::STEREOTRANS);
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/testReaction.cpp:7648]: I think it would also be helpful to test the SMILES for the output molecule, just to be doubly sure that everything is right.

**Review by greglandrum — APPROVED** [review]
