### PR TITLE
Fixes #2954:Rxn Smarts with Dative Bonds not parsed

### LINKED ISSUE #2954: cannot parse reaction SMILES/SMARTS with dative bonds
- RDKit Version: master (and released versions)
- Operating system: all

**Description:**

```
>>> rxn = AllChem.ReactionFromSmarts('[O:1].[H+]>>[O:1]->[H+]')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-06f8a10b5869> in <module>()
----> 1 rxn = AllChem.ReactionFromSmarts('[O:1].[H+]>>[O:1]->[H+]')

ValueError: ChemicalReactionParserException: multi-step reactions not supported
```

The reaction SMILES/SMARTS parser is being a bit too mechanical when it does what it does.

From this mailing list thread:
https://sourceforge.net/p/rdkit/mailman/message/36922354/

### PR DESCRIPTION
**Pull request by manangoel99**
Fixes #2954 
Implemented an approach which does not use std::string::find to find ">" occurrences. The new implementation checks the chracters around ">" and seperates the reactants and products accordingly. Corresponding tests have also been implemented.

### CODE REVIEW

File: Code/GraphMol/ChemReactions/DaylightParser.cpp [hunk 1]
```diff
@@ -105,12 +105,33 @@ ROMol *constructMolFromString(const std::string &txt,
 ChemicalReaction *RxnSmartsToChemicalReaction(
     const std::string &text, std::map<std::string, std::string> *replacements,
     bool useSmiles) {
-  std::size_t pos1 = text.find('>');
-  std::size_t pos2 = text.rfind('>');
-  if (pos1 == std::string::npos) {
+
+  std::size_t pos1;
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/DaylightParser.cpp]: no need to declare these up here, you can declare them when you use them

File: Code/GraphMol/ChemReactions/DaylightParser.cpp [hunk 2]
```diff
@@ -105,12 +105,33 @@ ROMol *constructMolFromString(const std::string &txt,
...
         "a reaction requires at least one reactant and one product");
   }
+
+  for (std::size_t i = 0; i < pos.size(); i++) {
+    if (text[pos[i] - 1] != '-') {
+      rxnDelimiterPos.push_back(pos[i]);
+    }
+  }
+
+  pos1 = rxnDelimiterPos[0];
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/DaylightParser.cpp]: You can declare `pos1` and `pos2` here

File: Code/GraphMol/ChemReactions/catch_tests.cpp [hunk 3]
```diff
@@ -222,4 +222,18 @@ TEST_CASE("negative charge queries. Part of testing changes for github #2604",
     CHECK(nWarnings == 1);
     CHECK(nErrors == 0);
   }
+}
+
+TEST_CASE("GithHub #2954: Reaction Smarts with Dative Bonds not parsed",
+          "[Reaction, Bug]") {
+  
+  SECTION("Rxn Smart Processing with Dative Bond") {
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/catch_tests.cpp]: Please add two additional SECTIONs that show that this also works if the dative bond is in the reactant (reaction SMARTS `[O:1]->[H+]>>[O:1].[H+]`) or in the agents (reaction SMARTS `[O:1][H]>N->[Cu]>[O:1].[H]`)

File: Code/GraphMol/ChemReactions/DaylightParser.cpp [hunk 4]
```diff
@@ -105,12 +105,33 @@ ROMol *constructMolFromString(const std::string &txt,
...
-  std::size_t pos2 = text.rfind('>');
-  if (pos1 == std::string::npos) {
+
+  std::size_t pos1;
+  std::size_t pos2;
+
+  std::vector<std::size_t> pos;
+  std::vector<std::size_t> rxnDelimiterPos;
+
+  for (std::size_t i = 0; i < text.length(); i++) {
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/DaylightParser.cpp]: You don't need to do both loops (the one here and the one at line 126). They can both be condensed into one:
```
for (std::size_t i = 1; i < text.length(); i++) {
    if (text[i] == '>' && text[i-1]!='-') {
      pos.push_back(i);
    }
}

```

File: Code/GraphMol/ChemReactions/DaylightParser.cpp [hunk 5]
```diff
@@ -105,12 +105,33 @@ ROMol *constructMolFromString(const std::string &txt,
...
+    if (text[i] == '>') {
+      pos.push_back(i);
+    }
+  }
+
+  if (pos.size() == 0) {
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/DaylightParser.cpp]: If you make change I suggested above to go to a single loop, then you can change this to:
```
if(pos.size() <2) {
```

File: Code/GraphMol/ChemReactions/DaylightParser.cpp [hunk 6]
```diff
@@ -105,12 +105,33 @@ ROMol *constructMolFromString(const std::string &txt,
...
     throw ChemicalReactionParserException(
         "a reaction requires at least one reactant and one product");
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/DaylightParser.cpp]: This message is no longer accurate, it should be something like: `"a reaction definition requires at least two '>' characters"`

File: Code/GraphMol/ChemReactions/DaylightParser.cpp [hunk 7]
```diff
@@ -105,12 +105,33 @@ ROMol *constructMolFromString(const std::string &txt,
...
+  for (std::size_t i = 0; i < pos.size(); i++) {
+    if (text[pos[i] - 1] != '-') {
+      rxnDelimiterPos.push_back(pos[i]);
+    }
+  }
+
+  pos1 = rxnDelimiterPos[0];
+  pos2 = rxnDelimiterPos[1];
+
   if (text.find('>', pos1 + 1) != pos2) {
```
Comment (greglandrum) [inline Code/GraphMol/ChemReactions/DaylightParser.cpp]: This condition is no longer correct. It should be: `if(pos.size()>2)`

**Comment by manangoel99** [comment]
@greglandrum I've made the suggested changes. I did not take into consideration the case where there would be agents in the smarts.
