### PR TITLE
Bug/github5613

### LINKED ISSUE #5613: RGD Stereochemistry in decomposed structure is not copied to the matching core
**Describe the bug**

Given a core query that does not specify stereochemistry and a matching structure with stereochemistry the stereochmistry is not copied to the matching core output in the decomposition.

**To Reproduce**

```python
# %%
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.rdRGroupDecomposition import RGroupDecomposition, RGroupDecompositionParameters, \
    RGroupMatching, RGroupScore, RGroupLabels, RGroupCoreAlignment, RGroupLabelling
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG = True
from rdkit.Chem import PandasTools
from rdkit.Chem import Draw
from IPython.display import HTML
import pandas as pd

# %%
core = Chem.MolFromSmarts('[*:1]C(=O)NC1CCN([*:3])C1')
core

# %%
mol = Chem.MolFromSmiles('Cc1c(c(c([nH]1)C(=O)N[C@H]2CCN(C2)c3cc(nc(n3)Cl)C(=O)O)Cl)Cl')
mol

# %%
options = RGroupDecompositionParameters()
decomp = RGroupDecomposition([core], options)
decomp.Add(mol)
decomp.Process()
groups = decomp.GetRGroupsAsColumns()
df = PandasTools.RGroupDecompositionToFrame(groups, [mol], include_core=True)
PandasTools.ChangeMoleculeRendering(df)
HTML(df.to_html())

```

**Expected behavior**

I expect to see the chiral center in the molecule appear in the matching core.

**Screenshots**

The core query does not have a chiral center specified:

image

The molecule does on the Pyrrolidine N:

image

but the matching core does not contain the chiral center:

image

**Configuration (please complete the following information):**

 - RDKit version: master as of 9/2022
 - OS: [e.g. Ubuntu 20.04] Ubuntu 20.04
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

While bond and atom information is copied from the input core to the output/matching core, stereochemistry is not.

I can take a look, but if anyone could point me to existing code that does something similar that would be helpful.  I guess the issue would be that the parity/atom ordering round the chiral center in the input core and matching core could be different.

### PR DESCRIPTION
**Pull request by jones-gareth**
#### Reference Issue

Fixes #5613 

#### What does this implement/fix? Explain your changes.

Copies the target molecule onto the core template preserving stereochemistry, aromaticity and explicit hydrogens.

New routine is in `RCore::extractCoreFromMolMatch`.  I also expanded the *allowMultipleRGroupsOnUnlabelled* option so that
there is an explicit bond to an attachment point for all free valence in the core template.  This necessitated changes to  
`RCore::matchTerminalUserRGroups` to better handle matching.  There are a bunch of other changes as the matching core for each target now has an explicit hydrogen model.

I've put the test results in [this gist](https://gist.github.com/jones-gareth/40383fc76313e0365d4058e48d6f2193)

#### Any other comments?

There is one wierdness- one of the expected smiles has changed for `allowMultipleRGroupsOnUnlabelled` from `C1SC2CC([*:1])NC(N([*:2])[*:4])C2C1[*:6]` to `C1C2SCC([*:6])C2C(N([*:2])[*:4])NC1[*:1]`. But this is the same structure:

```
mol1 = Chem.MolFromSmiles('C1SC2CC([*:1])NC(N([*:2])[*:4])C2C1[*:6]')
# new expected
mol2 = Chem.MolFromSmiles('C1C2SCC([*:6])C2C(N([*:2])[*:4])NC1[*:1]')
Draw.MolsToGridImage([mol1, mol2], 2)
```
image

I'm wondering if I'm not updating properties, re-initializing after editing molecules or have otherwise created a corrupt structure.  I anybody can point me in the right direction that would be great.

### CODE REVIEW

**Comment by jones-gareth** [comment]
Many of the tests in `Code/GraphMol/RGroupDecomposition/catch_rgd.cpp` have failed because the results for core decomps no longer contain SMARTS patterns and may contain stereochemistry.  I'll fix them up.

**Comment by bp-kelley** [comment]
@jones-gareth I'll have a lot more time to look at this over the holidays in a few weeks.

**Comment by jones-gareth** [comment]
I've updated [the gist](https://gist.github.com/jones-gareth/40383fc76313e0365d4058e48d6f2193) to include changes I made to `catch_rgd.cpp`.

**Comment by jones-gareth** [comment]
> @jones-gareth I'll have a lot more time to look at this over the holidays in a few weeks.

Sounds good.

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp [hunk 1]
```diff
@@ -32,7 +32,6 @@
 #include <RDGeneral/BadFileException.h>
 #include <GraphMol/ChemTransforms/ChemTransforms.h>
 namespace RDKit {
-namespace {
 void updateSubMolConfs(const ROMol &mol, RWMol &res,
```
Comment (bp-kelley) [inline Code/GraphMol/ChemTransforms/ChemTransforms.cpp:35]: If we are exposing this to the public API, I think we need quite a bit more error checking in this code.

I can see a few paths where there might be unforeseen consequences and the name might be confusing as it's update SubMolConfs but takes removed atoms where I would expect it to take the submol atoms instead.

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp [hunk 2]
```diff
@@ -628,6 +628,10 @@ ROMol *replaceCore(const ROMol &mol, const ROMol &core,
             if (switchIt) {
               sidechainAtom->invertChirality();
             }
+            // the neighbor count needs to be decremented, in case an additional
+            // bond to the core is present at this chiral center (unlikely!),
+            // because this bond will now be at the end of the neighbor list.
+            --whichNbr;
```
Comment (bp-kelley) [inline Code/GraphMol/ChemTransforms/ChemTransforms.cpp:634]: Is there a test for this fix?

File: Code/GraphMol/ChemTransforms/ChemTransforms.h [hunk 3]
```diff
@@ -265,6 +265,15 @@ RDKIT_CHEMTRANSFORMS_EXPORT void parseQueryDefText(
     std::map<std::string, ROMOL_SPTR> &queryDefs, bool standardize = true,
     const std::string &delimiter = "\t", const std::string &comment = "//",
     unsigned int nameColumn = 0, unsigned int smartsColumn = 1);
-}  // namespace RDKit
+//! \brief Updates conformer coordinates in res from those in mol
```
Comment (bp-kelley) [inline Code/GraphMol/ChemTransforms/ChemTransforms.h:268]: I think this needs some more explanation, i.e. the atoms must be in the same order (except for the removed atoms) and the output is undefined is res wasn't created from mol.  I don't think this function is suitable for the public API (I can change my mind of course)

I would rather have an updatesubmol(mol, res, INT_MAP_INT) function ala PathToSubmol with maybe a helper, updatesubmol(mol, res, pathFromDeletedAtoms(mol, res, deleted_atoms))

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp [hunk 4]
```diff
@@ -54,6 +64,197 @@ void RCore::findIndicesWithRLabel() {
   }
 }
 
+RWMOL_SPTR RCore::extractCoreFromMolMatch(
+    bool &hasCoreDummies, const ROMol &mol, const MatchVectType &match,
```
Comment (bp-kelley) [inline Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:68]: I think in general we have the const refs at the beginning of the function definition in the code.  Is this a style issue anyone cares about?  @greglandrum

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp [hunk 5]
```diff
@@ -54,6 +64,197 @@ void RCore::findIndicesWithRLabel() {
...
+    const RGroupDecompositionParameters &params) const {
+  auto extractedCore = boost::make_shared<RWMol>(mol);
+  std::set<int> atomIndicesToKeep;
+  std::vector<Bond *> newBonds;
+  std::map<Atom *, int> dummyAtomMap;
+  for (auto &pair : match) {
+    const auto queryAtom = core->getAtomWithIdx(pair.first);
+    auto const targetAtom = extractedCore->getAtomWithIdx(pair.second);
+    if (int rLabel; queryAtom->getPropIfPresent(RLABEL, rLabel)) {
```
Comment (bp-kelley) [inline Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:77]: Go c++17

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp [hunk 6]
```diff
@@ -54,6 +64,197 @@ void RCore::findIndicesWithRLabel() {
...
+      targetAtom->setProp(RLABEL, rLabel);
+    }
+    if (int rLabelType; queryAtom->getPropIfPresent(RLABEL_TYPE, rLabelType)) {
+      targetAtom->setProp(RLABEL_TYPE, rLabelType);
+    }
+
+    if (queryAtom->getAtomicNum() == 0) {
```
Comment (bp-kelley) [inline Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:84]: Maybe if(!hasCoreDummies && queryAtom->getAtomicNum() == 0) for a possibly useless optimization.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp [hunk 7]
```diff
@@ -54,6 +64,197 @@ void RCore::findIndicesWithRLabel() {
...
+        extractedCore->getConformer(static_cast<int>((*citer)->getId()));
+    for (const auto &[fst, snd] : dummyAtomMap) {
+      newConf.setAtomPos(fst->getIdx(), (*citer)->getAtomPos(snd));
+    }
+  }
+
+  // If the molecule has no coordinates and the core does, copy those over
+  if (!mol.getNumConformers() && core->getNumConformers()) {
+    ROMol molCopy(mol);
+    for (auto citer = core->beginConformers(); citer != core->endConformers();
```
Comment (bp-kelley) [inline Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:225]: This is the function that I think should be in the public api.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp [hunk 8]
```diff
@@ -54,6 +64,197 @@ void RCore::findIndicesWithRLabel() {
...
+#ifdef VERBOSE
+  std::cerr << "Extracted core smiles " << MolToSmiles(*extractedCore)
+            << std::endl;
+  std::cerr << "Extracted core smarts " << MolToSmarts(*extractedCore)
+            << std::endl;
+#endif
+
+  try {
+    unsigned int failed;
+    MolOps::sanitizeMol(*extractedCore, failed,
```
Comment (bp-kelley) [inline Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:251]: Stopping here for now, this might be causing the issue you referenced with the same structure and different canonicalization.

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp (hunk 1 above)
Comment (jones-gareth) [reply Code/GraphMol/ChemTransforms/ChemTransforms.cpp:35]: > If we are exposing this to the public API, I think we need quite a bit more error checking in this code.
> 
> I can see a few paths where there might be unforeseen consequences and the name might be confusing as it's update SubMolConfs but takes removed atoms where I would expect it to take the submol atoms instead.

 I agree. I was trying to avoid code duplication but I think the inputs for this function are too obscure to be exposed. Do you think that we could make `updateSubConfs` a private function in ChemTransforms then make `RCore::extractCoreFromMolMatch` a friend (does that work across libraries?).  Alternatively, I can just copy the function over.

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp (hunk 2 above)
Comment (jones-gareth) [reply Code/GraphMol/ChemTransforms/ChemTransforms.cpp:634]: > Is there a test for this fix?

Not in this PR.  I found this same issue in `RCore::extractCoreFromMolMatch` for which there are new tests.  I'll look into using the same structures to test `replaceCore`.  Maybe it's best to comment out the line here and do it in a new PR.

File: Code/GraphMol/ChemTransforms/ChemTransforms.h (hunk 3 above)
Comment (jones-gareth) [reply Code/GraphMol/ChemTransforms/ChemTransforms.h:268]: I'm inclined not to make `updateSubConfs` public, unless there are other scenarios where it might be useful.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp (hunk 6 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:84]: > Maybe if(!hasCoreDummies && queryAtom->getAtomicNum() == 0) for a possibly useless optimization.

I'll change that.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp (hunk 8 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:251]: > Stopping here for now, this might be causing the issue you referenced with the same structure and different canonicalization.

Not sure about that- I was trying sanitization here to try and fix the canonicalization issues- but I have made many changes since.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp (hunk 4 above)
Comment (greglandrum) [reply Code/GraphMol/RGroupDecomposition/RGroupCore.cpp:68]: I just kind of do it automatically, but haven't really thought about it as something important.
Since `hasCoreDummies` is really part of the return value anyway, maybe it makes sense to return an `std::pair<RWMOL_SPTR,bool>` from this function?

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/ChemTransforms/ChemTransforms.cpp:35]: How about putting it in the `details` namespace?
That's kind of a signal for "internal use" code.

File: Code/GraphMol/ChemTransforms/ChemTransforms.h (hunk 3 above)
Comment (greglandrum) [reply Code/GraphMol/ChemTransforms/ChemTransforms.h:268]: I'm definitely in favor of putting it in a `details` namespace.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.h [hunk 9]
```diff
@@ -50,15 +50,17 @@ struct RCore {
...
                                             const MatchVectType &match) const;
 
-  // Final core returned to user with dummy atoms and bonds set to those in the
-  // match
-  RWMOL_SPTR coreWithMatches(const ROMol &coreReplacedAtoms) const;
+  // Final core returned to user, created by extracting core from target
+  // molecule
+  RWMOL_SPTR extractCoreFromMolMatch(
+      bool &hasCoreDummies, const ROMol &mol, const MatchVectType &match,
+      const RGroupDecompositionParameters &params) const;
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupCore.h:63]: I commented elsewhere on this, but I think it makes more sense to declare this as:
```suggestion
  std::pair<RWMOL_SPTR,bool> extractCoreFromMolMatch(
      const ROMol &mol, const MatchVectType &match,
      const RGroupDecompositionParameters &params) const;
```

File: Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp [hunk 10]
```diff
@@ -444,58 +444,89 @@ std::vector<std::string> RGroupDecomposition::getRGroupLabels() const {
...
+      if (usedLabelMap.has(label) && usedLabelMap.isUserDefined(label)) {
+        // coordinates of user defined R groups should already be copied over
+        continue;
+      }
+      const auto neighbor = *coreWithMatches->atomNeighbors(atom).begin();
+      const auto &mapping = data->finalRlabelMapping;
+      const auto oldLabel =
+          std::find_if(mapping.begin(), mapping.end(),
+                       [label = label](const auto &p) { return p.second == label; });
+      if (auto iter = match.rgroups.find(oldLabel->first);
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp:515]: don't you need to check whether or not the `find_if` succeeded before you use `oldLabel` here?

File: Code/GraphMol/RGroupDecomposition/RGroupDecompData.h [hunk 11]
```diff
@@ -286,9 +311,31 @@ struct RGroupDecompData {
...
   }
 
+  bool replaceHydrogenCoreDummy(const RGroupMatch &match, RWMol &core,
+                                const Atom &atom, const int currentLabel,
+                                const int rLabel) {
+    // if the R group is just a hydrogen then the attachment point should
+    // replace an existing hydrogen neighbor since all hydrogen neighbors
+    // are copied from the input molecule to the extracted core.
+    if (const auto group = match.rgroups.find(currentLabel);
+        group != match.rgroups.end()) {
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupDecompData.h:321]: @bp-kelley already commented on it, but this may well become one of my favorite C++17-isms.

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp [hunk 12]
```diff
@@ -310,50 +315,66 @@ void RGroupDecompositionParameters::addDummyAtomsToUnlabelledCoreAtoms(
...
-        hasTerminalDummyNeighbor = true;
-        break;
+      auto valances =
+          PeriodicTable::getTable()->getValenceList(atom->getAtomicNum());
+      auto valence = *std::max_element(valances.begin(), valances.end());
+      // round up aromatic contributions
+      dummiesToAdd = valence - (int)(bondOrder + .51);
+      if (dummiesToAdd > maxNumDummies) {
+        dummiesToAdd = maxNumDummies;
       }
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:356]:
```suggestion
      dummiesToAdd = std::min(dumiesToAdd,maxNumDummies);
```

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp [hunk 13]
```diff
@@ -310,50 +315,66 @@ void RGroupDecompositionParameters::addDummyAtomsToUnlabelledCoreAtoms(
...
+        }
+        bondOrder += contrib;
+      }
 
-    while (nbrIdx != endNbrs) {
-      const auto neighbor = core.getAtomWithIdx(*nbrIdx);
-      if (neighbor->getAtomicNum() == 0 && neighbor->getDegree() == 1) {
-        hasTerminalDummyNeighbor = true;
-        break;
+      auto valances =
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:349]:
```suggestion
      const auto &valances =
```

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp [hunk 14]
```diff
@@ -310,50 +315,66 @@ void RGroupDecompositionParameters::addDummyAtomsToUnlabelledCoreAtoms(
...
+    int dummiesToAdd;
+    int maxNumDummies = 4 - static_cast<int>(atom->getDegree());
 
-    auto [nbrIdx, endNbrs] = core.getAtomNeighbors(atom);
-    bool hasTerminalDummyNeighbor = false;
+    // figure out the number of dummies to add
+    if (atom->getAtomicNum() == 0) {
+      dummiesToAdd = maxNumDummies;
+    } else {
+      double bondOrder = 0;
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:340]: I'm not sure I follow the logic of the below code.
Can't you just use the total number of implicit Hs here?

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp [hunk 15]
```diff
@@ -310,50 +315,66 @@ void RGroupDecompositionParameters::addDummyAtomsToUnlabelledCoreAtoms(
...
+      }
 
-    while (nbrIdx != endNbrs) {
-      const auto neighbor = core.getAtomWithIdx(*nbrIdx);
-      if (neighbor->getAtomicNum() == 0 && neighbor->getDegree() == 1) {
-        hasTerminalDummyNeighbor = true;
-        break;
+      auto valances =
+          PeriodicTable::getTable()->getValenceList(atom->getAtomicNum());
+      auto valence = *std::max_element(valances.begin(), valances.end());
```
Comment (greglandrum) [inline Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:351]: It feels like this is going to give weird/wrong answers for things like S and P, which have multiple possible valences, can be aromatic, and often appear in aromatic rings in a valence which is not their highest. For example `c1ccsc1 or `c1cccp1C`

**Review by greglandrum — CHANGES_REQUESTED** [review]
I like the idea.
Apologies that I somehow ended up making all my suggestions as individual comments and not one coherent review

File: Code/GraphMol/ChemTransforms/ChemTransforms.cpp (hunk 1 above)
Comment (jones-gareth) [reply Code/GraphMol/ChemTransforms/ChemTransforms.cpp:35]: I've moved this function to details

File: Code/GraphMol/RGroupDecomposition/RGroupCore.h (hunk 9 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupCore.h:63]: > I commented elsewhere on this, but I think it makes more sense to declare this as:

I've made that change

File: Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp (hunk 10 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp:515]: > don't you need to check whether or not the `find_if` succeeded before you use `oldLabel` here?

I've made that check.

File: Code/GraphMol/RGroupDecomposition/RGroupDecompData.h (hunk 11 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupDecompData.h:321]: > @bp-kelley already commented on it, but this may well become one of my favorite C++17-isms.

It's the best new feature I've found

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp (hunk 14 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:340]: Not if there is a query bond on the atom and the default smarts bond is single or aromatic.  In this core (from *testGibhub5613*) `C(=O)*C1~C~C~*~*~C~1` there are no implicit hydrogens on the atoms with query bonds.   I guess we could use number of implicit hydrogens if none of the neighbor bonds were queries.

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp (hunk 15 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:351]: It shouldn't do.  The dummy atom does not have to match an RGroup, but any RGroup has to match a dummy atom.  If the core query contains `[#6][#16][#6]` then I add 2 dummies and it can match both `csc` (no R groups) and `CS(=O)(=O)C` (two `=O` R groups).
I try to add the smallest number of dummies here as there is an overhead to having unmatched dummies.

File: Code/GraphMol/RGroupDecomposition/RGroupCore.cpp (hunk 4 above)
Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupCore.cpp]: Now returns `std::pair<RWMOL_SPTR, bool>`

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp (hunk 15 above)
Comment (bp-kelley) [reply Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:351]: Do we still have the same issue with S versus SH?  One will have an rgroup and one won’t.

Comment (jones-gareth) [reply Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:351]: > Do we still have the same issue with S versus SH? One will have an rgroup and one won’t.

That will also work fine.  Extending the previous example, a core query of `[#6][#16][#6]` can also match `c[sH][c]` (assuming for the sake of argument such a thing could exist!).  In that case one dummy is mapped to an RGroup and the other is ignored.

File: Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp (hunk 14 above)
Comment (greglandrum) [reply Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp:340]: ah, right, that makes sense.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@bp-kelley : this looks good to me. What's your take on the latest changes?

**Comment by jones-gareth** [comment]
This latest commit removes bond stereo settings when an r group is attached to the core by a cis/trans double bond.  This caused a memory error in C#, but I was unable to reproduce directly in C++.  In any case, there is no point retaining the bond stereochemistry without the atoms to define it.

**Comment by bp-kelley** [comment]
We keep the chirality in this case, my reasoning is that you should always be able to recreate the original molecule from the decomposition, this seems to violate that.

**Comment by bp-kelley** [comment]
Other than the cis/trans question, this is a great improvement.

**Comment by jones-gareth** [comment]
This latest commit removes bond stereo settings when an r group is attached to the core by a cis/trans double bond.  This caused a memory error in C#, but I was unable to reproduce directly in C++.  In any case, there is no point retaining the bond stereochemistry without the atoms to define it.

> We keep the chirality in this case, my reasoning is that you should always be able to recreate the original molecule from the decomposition, this seems to violate that.

I completely agree, but I don't see any easy solution so I think it would be best to tackle in a new PR rather than extend this one.  I'll create an issue once this gets merged.  Fortunately, an R group attached by a stereo double bond is an edge case.

I'm thinking that `ChemTransforms::replaceCore` will need to convert trans/cis to absolute E/Z when a side chain is connected to the core with a stereo double bond.  Still not sure why retaining trans/cis caused C# to crash.

**Comment by greglandrum** [comment]
> 
> > We keep the chirality in this case, my reasoning is that you should always be able to recreate the original molecule from the decomposition, this seems to violate that.
> 
> I completely agree, but I don't see any easy solution so I think it would be best to tackle in a new PR rather than extend this one. I'll create an issue once this gets merged. Fortunately, an R group attached by a stereo double bond is an edge case.

Agreed. This is a separate issue.
Looks like we're all happy with this one, so I'll go ahead and merge.

@jones-gareth : thanks for fixing another complex one!

**Comment by bp-kelley** [comment]
This is good stuff @jones-gareth
