### PR TITLE
Fixes #7300

### LINKED ISSUE #7300: incorrect chiral carbon perception in `Chem.FindMolChiralCenters` new implementation
`Chem.FindMolChiralCenters` with `includeUnassigned=True` and `useLegacyImplementation=False` parameters seems to return Unassigned chiral carbons that shouldn't. In the example below 2 substituents with phosphorus are identical.
cc: @FionaEBI, @mdeveij

**To Reproduce**

```
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole

IPythonConsole.ipython_useSVG=True
IPythonConsole.molSize = (500, 500)

molfile = """
  Mrv2311 03262415422D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 12 11 0 0 0
M  V30 BEGIN ATOM
M  V30 1 N -3.2103 4.3298 0 0
M  V30 2 C -3.2103 1.6625 0 0
M  V30 3 P -1.6703 1.6625 0 0
M  V30 4 O -7.0603 5.6635 0 0
M  V30 5 O -7.624 3.5598 0 0
M  V30 6 O -0.1303 1.6625 0 0
M  V30 7 O -1.6703 0.1225 0 0
M  V30 8 C -3.9803 2.9961 0 0
M  V30 9 P -6.2903 4.3298 0 0
M  V30 10 C -5.5203 2.9961 0 0
M  V30 11 O -4.9566 5.0998 0 0
M  V30 12 O -1.6703 3.2025 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 2 8
M  V30 2 1 8 1
M  V30 3 1 8 10
M  V30 4 1 9 4
M  V30 5 1 9 5
M  V30 6 1 9 10
M  V30 7 2 9 11
M  V30 8 1 2 3
M  V30 9 1 3 6
M  V30 10 1 3 7
M  V30 11 2 3 12
M  V30 END BOND
M  V30 END CTAB
M  END
"""

mol = Chem.MolFromMolBlock(molfile)

for cc in Chem.FindMolChiralCenters(mol, force=True, includeUnassigned=True, useLegacyImplementation=False):
    at = mol.GetAtomWithIdx(cc[0])
    at.SetProp("atomLabel", cc[1])

mol
```

Using `useLegacyImplementation=True` returns no chiral carbons as expected.

**Expected behavior**
No chiral carbons found with new implementation

**Screenshots**

Screenshot 2024-03-26 at 16 11 42

p.s. is there a cleaner way to depict the molecules showing the unassigned (?) centers?

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.5 (pip installed)
 - OS: OS X 14.4
 - Python version (if relevant): 3.11

### PR DESCRIPTION
**Pull request by greglandrum**
The logic which was automatically assigning square planar stereo to 4-coordinate atoms was incorrect.

### CODE REVIEW

File: Code/GraphMol/FindStereo.cpp [hunk 1]
```diff
@@ -326,7 +326,8 @@ StereoInfo getStereoInfo(const Atom *atom) {
       if (stereo == Atom::CHI_UNSPECIFIED) {
         switch (atom->getTotalDegree()) {
           case 4:
-            stereo = Atom::ChiralType::CHI_SQUAREPLANAR;
+            // don't assume non-tetrahedral chirality
+            stereo = Atom::ChiralType::CHI_TETRAHEDRAL;
```
Comment (ricrogz) [inline Code/GraphMol/FindStereo.cpp:330]: Doesn't this make exactly the opposite assumption we were making, especially because this is under a `if (getAllowNontetrahedralChirality() &&
               isAtomPotentialNontetrahedralCenter(atom)) ` check? Is there some check we can add here to distinguish between a tetrahedral (3D) and a square planar (2D) configuration?

Comment (greglandrum) [reply Code/GraphMol/FindStereo.cpp:330]: > Doesn't this make exactly the opposite assumption we were making, especially because this is under a `if (getAllowNontetrahedralChirality() && isAtomPotentialNontetrahedralCenter(atom)) ` check? Is there some check we can add here to distinguish between a tetrahedral (3D) and a square planar (2D) configuration?

Yes, this is making exactly the opposite assumption: previously if an atom was four coordinate and *could* have non tetrahedral stereo, we assumed that it *did* have non-tetrahedral stereo. Now we're assuming tetrahedral unless there's some information otherwise (i.e. you have to explicitly state that the thing is square planar if you want the RDKit to treat it that way).

Given the relevant prevalence if tetrahedral geometries in the systems the RDKit is usually used with, I think defaulting to tetrahedral is better.

Without actually looking at coordinates, I don't think we can make an informed decision.

Comment (ricrogz) [reply Code/GraphMol/FindStereo.cpp:330]: OK, let's make this assumption then. We can always come back to this if we find it problematic.

**Review by ricrogz — APPROVED** [review]
