### PR TITLE
Propagate query features from reacting molecules to products

### LINKED ISSUE #6015: Reactions do not propagate query information to products
**Describe the bug**
Reactions end up stripping all query information from reacting molecules. This includes both atoms directly involved in the reaction (i.e. those in the template) and other atoms. Here's a demo:
```
In [87]: rxn = rdChemReactions.ReactionFromSmarts("[C:1]>>[C:1]")

In [88]: m = Chem.MolFromSmarts("[C&R&X3][OR]")

In [89]: ps = rxn.RunReactants((m,))

In [90]: len(ps)
Out[90]: 1

In [91]: ps[0][0].GetAtomWithIdx(0).HasQuery()
Out[91]: False

In [92]: ps[0][0].GetAtomWithIdx(1).HasQuery()
Out[92]: False
```
It would be very helpful if this were not the case.

**Configuration (please complete the following information):**
 - RDKit version: current release and master
 - OS: all
 -

### PR DESCRIPTION
**Pull request by greglandrum**
When reactions were applied to molecules with query features (e.g. constructed from SMARTS), none of the query features were being propagated to the products. This remedies that.

This fixes #6015 and #6014

### CODE REVIEW

File: Code/GraphMol/ChemReactions/ReactionRunner.cpp [hunk 1]
```diff
@@ -874,16 +898,20 @@ void addMissingProductBonds(const Bond &origB, RWMOL_SPTR product,
...
-                     origB.getBondType());
+    addBondToProduct(origB, *product, prodBeginIdxs.at(i), prodEndIdxs.at(i));
   }
 }
 
 void addMissingProductAtom(const Atom &reactAtom, unsigned reactNeighborIdx,
                            unsigned prodNeighborIdx, RWMOL_SPTR product,
                            const ROMol &reactant,
                            ReactantProductAtomMapping *mapping) {
-  auto *newAtom = new Atom(reactAtom);
```
Comment (bp-kelley) [inline Code/GraphMol/ChemReactions/ReactionRunner.cpp:886]: couldn't this be:

```
auto *newAtom = reactAtom.copy();
```

**Review by bp-kelley — APPROVED** [review]

File: Code/GraphMol/ChemReactions/ReactionRunner.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/ChemReactions/ReactionRunner.cpp:886]: > couldn't this be:
> 
> ```
> auto *newAtom = reactAtom.copy();
> ```

yeah, that would be exactly equivalent. Feels less explicit though.

Comment (bp-kelley) [reply Code/GraphMol/ChemReactions/ReactionRunner.cpp:886]: I'm happy either way, it's probably "faster" as the query atom copy can do a static cast.

Comment (bp-kelley) [reply Code/GraphMol/ChemReactions/ReactionRunner.cpp:886]: It does feel more future proof though but I can't imagine a new Atom subclass so...
