### PR TITLE
Fix/smiles parser memleak

### LINKED ISSUE #3139: Memory leak
~~The build for #3128 is [failing](https://dev.azure.com/rdkit-org/RDKit-main-build/_build/results?buildId=1178&view=logs&j=d42b4615-9c42-5e39-433b-1455f2661188&t=252d3907-1082-5b31-96c1-a55ede2a1791&l=63) due to a memory leak.~~

**Configuration:**

- RDKit Version: master, 39bcee635e0ee8bc5da6798318fdcd4602c4baa6
- Operating system: Linux
- Are you using conda? No
- If you are not using conda: how did you install the RDKit? Self-built using Cmake

**Description:**

Either build https://github.com/rdkit/rdkit/pull/3128 or use the binary I provide here:
[smiles_string_to_mol_fuzzer.txt](https://github.com/rdkit/rdkit/files/4577096/smiles_string_to_mol_fuzzer.txt)
**Remove the extension/`chmod +x` it**
You can also just compile https://github.com/rdkit/rdkit/blob/44d47ef1a2ef65922945756b71f4395c0973841e/Code/Fuzz/smiles_string_to_mol_fuzzer.cc using `-fsanitize=address`.

The input that is being used for the program is ~~`COc(c1)cccc1C#N`~~ `COc(c1)cccc1C#`

Run this command
```
./rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer ./rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer/300e696782d50f5a92a02dbb37b1e14b33bb7bfb
```

```
Running: ./rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer/300e696782d50f5a92a02dbb37b1e14b33bb7bfb

=================================================================
==7418==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 160 byte(s) in 2 object(s) allocated from:
    #0 0x572862 in operator new(unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x572862)
    #1 0x73be9f in RDKit::RWMol::createPartialBond(unsigned int, RDKit::Bond::BondType) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/RWMol.cpp:444:13
    #2 0x63f1e5 in yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) /home/sg/dev/google-rewards/rdkit/build/Code/GraphMol/SmilesParse/smiles.yy:215:20
    #3 0x585941 in RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:112:11
    #4 0x57d70e in RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:149:10
    #5 0x576d4c in RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:215:5
    #6 0x57a789 in RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:363:9
    #7 0x575d8e in SmilesToMol /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:79:10
    #8 0x575d8e in LLVMFuzzerTestOneInput /home/sg/dev/google-rewards/rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer.cc:30
    #9 0x47d66a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x47d66a)
    #10 0x46ffac in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x46ffac)
    #11 0x475431 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x475431)
    #12 0x497a52 in main (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x497a52)
    #13 0x7fd4c669909a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x572862 in operator new(unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x572862)
    #1 0x59b15b in allocate /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h:111:27
    #2 0x59b15b in allocate /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h:436
    #3 0x59b15b in _M_allocate /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:296
    #4 0x59b15b in void std::vector<RDKit::Dict::Pair, std::allocator<RDKit::Dict::Pair> >::_M_realloc_insert<RDKit::Dict::Pair>(__gnu_cxx::__normal_iterator<RDKit::Dict::Pair*, std::vector<RDKit::Dict::Pair, std::allocator<RDKit::Dict::Pair> > >, RDKit::Dict::Pair&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc:427
    #5 0x5fccb6 in emplace_back<RDKit::Dict::Pair> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc:109:4
    #6 0x5fccb6 in push_back /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:1091
    #7 0x5fccb6 in void RDKit::Dict::setPODVal<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:259
    #8 0x63f668 in setVal /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:268:51
    #9 0x63f668 in setProp<int> /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/RDProps.h:81
    #10 0x63f668 in yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) /home/sg/dev/google-rewards/rdkit/build/Code/GraphMol/SmilesParse/smiles.yy:218
    #11 0x585941 in RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:112:11
    #12 0x57d70e in RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:149:10
    #13 0x576d4c in RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:215:5
    #14 0x57a789 in RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:363:9
    #15 0x575d8e in SmilesToMol /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:79:10
    #16 0x575d8e in LLVMFuzzerTestOneInput /home/sg/dev/google-rewards/rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer.cc:30
    #17 0x47d66a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x47d66a)
    #18 0x46ffac in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x46ffac)
    #19 0x475431 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x475431)
    #20 0x497a52 in main (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x497a52)
    #21 0x7fd4c669909a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 36 byte(s) in 2 object(s) allocated from:
    #0 0x572862 in operator new(unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x572862)
    #1 0x5fc73e in _M_construct<char *> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc:219:14
    #2 0x5fc73e in _M_construct_aux<char *> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:236
    #3 0x5fc73e in _M_construct<char *> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:255
    #4 0x5fc73e in basic_string /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:440
    #5 0x5fc73e in void RDKit::Dict::setPODVal<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:259
    #6 0x63f668 in setVal /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:268:51
    #7 0x63f668 in setProp<int> /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/RDProps.h:81
    #8 0x63f668 in yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) /home/sg/dev/google-rewards/rdkit/build/Code/GraphMol/SmilesParse/smiles.yy:218
    #9 0x585941 in RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:112:11
    #10 0x57d70e in RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:149:10
    #11 0x576d4c in RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:215:5
    #12 0x57a789 in RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:363:9
    #13 0x575d8e in SmilesToMol /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:79:10
    #14 0x575d8e in LLVMFuzzerTestOneInput /home/sg/dev/google-rewards/rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer.cc:30
    #15 0x47d66a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x47d66a)
    #16 0x46ffac in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x46ffac)
    #17 0x475431 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x475431)
    #18 0x497a52 in main (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x497a52)
    #19 0x7fd4c669909a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 292 byte(s) leaked in 6 allocation(s).
```

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #3139 a memory leak in the smiles parser

A trailing bond with an end atom would leak, i.e.

"C#"

this is because the bond bookmarks were cleared before an invariant was thrown which means that the cleanup code couldn't see the dancing bond.

This should be validated with valgrind before inclusion.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum - this is the memory leak that the fuzzing caught.  I think, I'll run valgrind on it tomorrow.

File: Code/GraphMol/SmilesParse/SmilesParseOps.cpp [hunk 1]
```diff
@@ -489,6 +485,12 @@ void CloseMolRings(RWMol *mol, bool toleratePartials) {
             swapBondDirIfNeeded(bond2, bond1);
             delete bond1;
           }
+
```
Comment (greglandrum) [inline Code/GraphMol/SmilesParse/SmilesParseOps.cpp:488]: This change doesn't make sense to me. It isn't connected to the memory leak found in the fuzzing (you fix that elsewhere) and leads to valgrind errors galore. Here's one of them:
```
==66850== Invalid read of size 4
==66850==    at 0x4A94320: RDKit::Bond::getIdx() const (Bond.h:164)
==66850==    by 0x50D98F3: RDKit::ROMol::clearBondBookmark(int, RDKit::Bond const*) (ROMol.cpp:264)
==66850==    by 0x4D560E9: SmilesParseOps::CloseMolRings(RDKit::RWMol*, bool) (SmilesParseOps.cpp:491)
==66850==    by 0x4D378E0: RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (SmilesParse.cpp:218)
==66850==    by 0x4D38811: RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) (SmilesParse.cpp:363)
==66850==    by 0x1C1ED9: RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*) (SmilesParse.h:79)
==66850==    by 0x13D4B2: testPass() (test.cpp:119)
==66850==    by 0x1BDA96: main (test.cpp:4321)
==66850==  Address 0x637e610 is 48 bytes inside a block of size 80 free'd
==66850==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==66850==    by 0x509305B: RDKit::Bond::~Bond() (Bond.cpp:42)
==66850==    by 0x4D55F7A: SmilesParseOps::CloseMolRings(RDKit::RWMol*, bool) (SmilesParseOps.cpp:472)
==66850==    by 0x4D378E0: RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (SmilesParse.cpp:218)
==66850==    by 0x4D38811: RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) (SmilesParse.cpp:363)
==66850==    by 0x1C1ED9: RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*) (SmilesParse.h:79)
==66850==    by 0x13D4B2: testPass() (test.cpp:119)
==66850==    by 0x1BDA96: main (test.cpp:4321)
==66850==  Block was alloc'd at
==66850==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==66850==    by 0x50F1F17: RDKit::RWMol::createPartialBond(unsigned int, RDKit::Bond::BondType) (RWMol.cpp:444)
==66850==    by 0x4DB6484: yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) (smiles.yy:215)
==66850==    by 0x4D36E33: RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) (SmilesParse.cpp:112)
==66850==    by 0x4D37214: RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) (SmilesParse.cpp:149)
==66850==    by 0x4D3789A: RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (SmilesParse.cpp:215)
==66850==    by 0x4D38811: RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) (SmilesParse.cpp:363)
==66850==    by 0x1C1ED9: RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*) (SmilesParse.h:79)
==66850==    by 0x13D4B2: testPass() (test.cpp:119)
==66850==    by 0x1BDA96: main (test.cpp:4321)

```

**Comment by greglandrum** [comment]
@bp-kelley : I ran this in valgrind and, after reverting the change to `SmilesParseOps.cpp` everything looks good.

File: Code/GraphMol/SmilesParse/SmilesParseOps.cpp (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/SmilesParse/SmilesParseOps.cpp:488]: I think this might have been checked in by accident.

**Comment by bp-kelley** [comment]
@greglandrum I'll revert the changes to SmilesParseOps and then add the fixes to smarts.yy.  I'll rerun flex-bison as well.

Also, d_partialBonds is never used.  Should we remove this?

Finally:       mol->finishPartialBond(...); is also never used or tested.  Is it vestigial?

**Comment by greglandrum** [comment]
> @greglandrum I'll revert the changes to SmilesParseOps and then add the fixes to smarts.yy. I'll rerun flex-bison as well.

Thanks
 
> Also, d_partialBonds is never used. Should we remove this?
> 
> Finally: mol->finishPartialBond(...); is also never used or tested. Is it vestigial?

Yeah, removing both of those makes sense. Should be in a separate PR though.

**Comment by bp-kelley** [comment]
no leaks on smarts or smiles

```
==00:00:00:00.000 4212== Memcheck, a memory error detector
==00:00:00:00.000 4212== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==00:00:00:00.000 4212== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==00:00:00:00.000 4212== Command: /home/bkelley/working/learning/build/Code/GraphMol/SmilesParse/smiTest1
==00:00:00:00.000 4212== Parent PID: 4211
==00:00:00:00.000 4212== 
==00:00:00:06.621 4212== 
==00:00:00:06.621 4212== HEAP SUMMARY:
==00:00:00:06.621 4212==     in use at exit: 0 bytes in 0 blocks
==00:00:00:06.621 4212==   total heap usage: 869,131 allocs, 869,131 frees, 49,326,602 bytes allocated
==00:00:00:06.621 4212== 
==00:00:00:06.621 4212== All heap blocks were freed -- no leaks are possible
==00:00:00:06.621 4212== 
==00:00:00:06.621 4212== For counts of detected and suppressed errors, rerun with: -v
==00:00:00:06.621 4212== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by bp-kelley** [comment]
Doing a flex/bison build, one this passes we can merge.

**Comment by bp-kelley** [comment]
bison/flex build also passes.  I think we're good to merge.
