### PR TITLE
Fixes #8065

### LINKED ISSUE #8065: Adding Hs to a linear molecule throws "Cannot normalize a zero length vector"
Example:

```python
In [1]: mb = """
   ...:   Mrv1908 06032010402D          
   ...: 
   ...:   0  0  0     0  0            999 V3000
   ...: M  V30 BEGIN CTAB
   ...: M  V30 COUNTS 3 2 0 0 0
   ...: M  V30 BEGIN ATOM
   ...: M  V30 1 C -19.8317 16.5 0 1 CHG=-1
   ...: M  V30 2 N -18.2917 16.5 0 2 CHG=1
   ...: M  V30 3 N -16.7517 16.5 0 3
   ...: M  V30 END ATOM
   ...: M  V30 BEGIN BOND
   ...: M  V30 1 1 1 2
   ...: M  V30 2 3 2 3
   ...: M  V30 END BOND
   ...: M  V30 END CTAB
   ...: M  END
   ...: """

In [2]: m = Chem.MolFromMolBlock(mb)

In [3]: Chem.AddHs(m, explicitOnly=False, addCoords=True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 Chem.AddHs(m, explicitOnly=False, addCoords=True)

RuntimeError: Cannot normalize a zero length vector

```

### PR DESCRIPTION
**Pull request by ricrogz**
This is caused by #8008. I missed that edge case in my PR.

### CODE REVIEW

File: Code/GraphMol/AddHs.cpp [hunk 1]
```diff
@@ -275,6 +275,17 @@ void setTerminalAtomCoords(ROMol &mol, unsigned int idx,
...
+                // if nbr1 and nbr2 are aligned, the perpendicular will be null,
+                // so fall back to the default calculation
+                if (perpVect.lengthSq() < sq_dist_zero_tol) {
+                  // we need to pick a different perpendicular
+                  if ((*cfi)->is3D()) {
+                    perpVect = nbr1Vect.getPerpendicular();
+                  } else {
+                    perpVect.z = 1.0;
+                  }
+                }
```
Comment (greglandrum) [inline Code/GraphMol/AddHs.cpp:288]: Simplification: 
```suggestion
                auto crossProd = nbr2Vect.crossProduct(nbr1Vect);

                // if nbr1 and nbr2 are aligned, the perpendicular will be null,
                // and we'll just keep the default calculated above. Otherwise
                // we use the cross product
                if (crossProd.lengthSq() >= sq_dist_zero_tol) {
                  perpVect = crossProd;
                }
```

**Review by greglandrum — CHANGES_REQUESTED** [review]
A suggested simplification

**Review by greglandrum — APPROVED** [review]
LGTM
