### PR TITLE
Fixes #5763

### LINKED ISSUE #5763: `R` atom label information lost in molfile if not backed by a `M RGP` entry
**Describe the bug**

We've encountered some molfiles in ChEBI with `R` atoms that are not backed by a `M RGP` entry. 
RDKit replaces the `R` with a star `*` and it is not possible to know, even with the `mol.Debug()` function that the original molfile had that `R` symbol/label there

**To Reproduce**

```python
from rdkit import Chem

molfile = """
  MJ221900                      

  4  3  0  0  0  0  0  0  0  0999 V2000
    2.1433    1.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    2.0625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8578    2.0625    0.0000 R   0  0  0  0  0  0  0  0  0  0  0  0
    2.1433    0.8250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  4  1  2  0  0  0  0
M  END"""

mol = Chem.MolFromMolBlock(molfile)
mol.Debug()
```

```
Atoms:
	0 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 3 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
	2 0 * chg: 0  deg: 1 exp: 1 imp: 0 hyb: 0 arom?: 0 chi: 0
	3 8 O chg: 0  deg: 1 exp: 2 imp: 0 hyb: 3 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 0->2 order: 1 conj?: 0 aromatic?: 0
	2 3->0 order: 2 conj?: 0 aromatic?: 0
```

**Expected behavior**
Ideally the atom symbol/label would be kept as an `R`. If this is not acceptable for any reason the original label in the molfile should be preserved somewhere.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.01
 - OS: [e.g. Ubuntu 20.04] MacOS
 - Python version (if relevant): 3.10
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? `pip install rdkit`

**Additional context**
I'm writting a library able to deal with ChEBI's way of dealing with chemistry. Current workaround is to parse the molecule twice (1 with RDKit and 1 manually).

### PR DESCRIPTION
**Pull request by greglandrum**
Small fix to make sure that information about R labels is always saved.

### CODE REVIEW

File: Code/GraphMol/FileParsers/file_parsers_catch.cpp [hunk 1]
```diff
@@ -5107,4 +5107,89 @@ TEST_CASE("Github #5433: PRECONDITION error with nonsense molecule") {
...
+M  V30 2 1 1 2
+M  V30 END BOND
+M  V30 END CTAB
+M  END)CTAB"_ctab;
+    REQUIRE(m);
+    CHECK(m->getAtomWithIdx(2)->hasProp(common_properties::dummyLabel));
+    CHECK(m->getAtomWithIdx(2)->getProp<std::string>(
+              common_properties::dummyLabel) == "R");
+  }
+  SECTION("V3000 with #") {
```
Comment (bp-kelley) [inline Code/GraphMol/FileParsers/file_parsers_catch.cpp:5172]: Should we add a check for R# the title here is a bit misleading in that # means number in the section heading.

Comment (greglandrum) [reply Code/GraphMol/FileParsers/file_parsers_catch.cpp:5172]: You're right; I set this test up wrong. Will fix it

**Review by bp-kelley — APPROVED** [review]
