### PR TITLE
Fix a couple of smarts bugs

### LINKED ISSUE #2814: Hybridization queries on dummy atoms not written properly to SMARTS
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: all
- Python version (if relevant): N/A
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit

**Description:**
Here's the demo:
```
In [6]: Chem.MolToSmarts(Chem.MolFromSmarts('[*^4]'))                                                                                     
Out[6]: '^4'
```

### PR DESCRIPTION
**Pull request by greglandrum**
This fixes #2814 and #2815 
Both are simple fixes

### CODE REVIEW

File: Code/GraphMol/SmilesParse/SmartsWrite.cpp [hunk 1]
```diff
@@ -260,6 +260,7 @@ std::string getAtomSmartsSimple(const QueryAtom *qatom,
         res << "5";
         break;
     }
+    needParen = true;
```
Comment (bp-kelley) [inline Code/GraphMol/SmilesParse/SmartsWrite.cpp]: Is there a test for this?

Comment (bp-kelley) [reply Code/GraphMol/SmilesParse/SmartsWrite.cpp]: And actually the others now I looked for them.

**Comment by bp-kelley** [comment]
These changes make sense, if there are tests that I've missed feel free to merge.

File: Code/GraphMol/SmilesParse/SmartsWrite.cpp (hunk 1 above)
Comment (greglandrum) [reply Code/GraphMol/SmilesParse/SmartsWrite.cpp]: The tests I added at l126 of smatest.cpp, which output the SMARTS and then make sure it can be read back in again, exercise this.
