### PR TITLE
Fixes #8890

### LINKED ISSUE #8890: Whitespace mangled in `GetPropsAsDict()`
**Describe the bug**
Regression in 2025.09.1: `Atom.GetPropsAsDict()` returns a dict with the empty string for properties whose value is only whitespace. 2025.03.6 returned the correct string.

**To Reproduce**

In 2025.09.1:

```python
>>> import rdkit.Chem
>>> atom  = rdkit.Chem.Atom(1)
>>> atom.SetProp("test", " \t\n")
>>> atom.GetProp("test")
' \t\n'
>>> atom.GetPropsAsDict()
{'test': ''}
```

**Expected behavior**

The full string should be in the dict.

In 2025.03.6:

```python
>>> import rdkit.Chem
>>> atom  = rdkit.Chem.Atom(1)
>>> atom.SetProp("test", " \t\n")
>>> atom.GetProp("test")
' \t\n'
>>> atom.GetPropsAsDict()
{'test': ' \t\n'}
```

**Screenshots**

Image

**Configuration (please complete the following information):**
 - RDKit version: 2025.09.1
 - OS: Arch Linux
 - Python version (if relevant): Observed on 3.12, 3.13, 3.14.
 - Are you using conda? Yes
 - Which channel did you install the rdkit from? Conda Forge

**Additional context**

Thanks for all your work on RDKit!!

### PR DESCRIPTION
**Pull request by greglandrum**
stop stripping string properties
updates doc string
adds a test for autoConvertStrings

### CODE REVIEW

File: Code/GraphMol/Wrap/props.hpp [hunk 1]
```diff
@@ -113,16 +117,17 @@ boost::python::dict GetPropsAsDict(const T &obj, bool includePrivate,
           break;
         case RDTypeTag::StringTag: {
           auto value = from_rdvalue<std::string>(rdvalue.val);
-	  boost::trim(value);
           if (autoConvertStrings) {
+            auto trimVal = value;
```
Comment (bp-kelley) [inline Code/GraphMol/Wrap/props.hpp:121]: I think this is what I meant to do anyway, good fix.
