### PR TITLE
fixes #4128

### LINKED ISSUE #4128: SEGV from unsigned integer overflow in Conformer::setAtomPos
**Describe the bug**
There is an unsigned integer overflow bug in `Conformer::setAtomPos`:
```cpp
inline void setAtomPos(unsigned int atomId, const RDGeom::Point3D &position) {
  if (atomId >= d_positions.size()) {
    d_positions.resize(atomId + 1, RDGeom::Point3D(0.0, 0.0, 0.0));
  }
  d_positions[atomId] = position;
}
```
`atomId + 1` can overflow in the argument to `d_positions.resize`.

**To Reproduce**
This is reproducible in C++ and Python. The index `0xffffffff` overflows and `Conformer::setAtomPos` calls `d_positions.resize(0,...)` which succeeds.
```cpp
#include <Geometry/point.h>
#include <GraphMol/Conformer.h>

int main() {
    RDKit::Conformer *conf = new RDKit::Conformer();
    RDGeom::Point3D *point = new RDGeom::Point3D();
    conf->setAtomPos(0xffffffff, *point);
}
```
```py
import rdkit

conf = rdkit.Chem.Conformer()
point = rdkit.Geometry.Point3D()
conf.SetAtomPosition(0xffffffff, point)
```

**Expected behavior**
This should fail with an out-of-bounds error message.

**Configuration (please complete the following information):**
 - RDKit version: current master branch (92b52f1988c6e155cdf5629edc4d40e275473e1f) but should be the same on 2021.03.01
 - OS: Ubuntu 18.04
 - Python version (if relevant): 3.9.2 (but will work in any version)

**Additional context**
The C++ example produces the following ASAN report:
```
==20==ERROR: AddressSanitizer: SEGV on unknown address 0x00047fff7ffd (pc 0x00000051aeff bp 0x7ffcb0bfd450 sp 0x7ffcb0bfd3e0 T0)
==20==The signal is caused by a READ memory access.
    #0 0x51aefe in RDGeom::Point3D::operator=(RDGeom::Point3D const&) /src/rdkit/Code/Geometry/point.h:98:7
    #1 0x518818 in RDKit::Conformer::setAtomPos(unsigned int, RDGeom::Point3D const&) /src/rdkit/Code/GraphMol/Conformer.h:111:25
    #2 0x518347 in main poc.cpp:7:11
    #3 0x7f06e76e8bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #4 0x41ba79 in _start (poc+0x41ba79)
```

### PR DESCRIPTION
**Pull request by greglandrum**
adds a check for the possible overflow in `Conformer::setAtomPos()` and throws a ValueError on overflow.

Maybe it should be a PRECONDITION instead to be consistent? Seems like a ValueError though.

### CODE REVIEW

File: Code/GraphMol/Conformer.h [hunk 1]
```diff
@@ -104,7 +105,9 @@ class RDKIT_GRAPHMOL_EXPORT Conformer : public RDProps {
 
   //! Set the position of the specified atom
   inline void setAtomPos(unsigned int atomId, const RDGeom::Point3D &position) {
-    // RANGE_CHECK(0,atomId,d_positions.size()-1);
+    if (atomId == std::numeric_limits<unsigned int>::max()) {
+      throw ValueErrorException("atom index overflow");
+    }
     if (atomId >= d_positions.size()) {
```
Comment (bp-kelley) [inline Code/GraphMol/Conformer.h:111]: Couldn't you solve this by upcasting to int64 when computing the size?  unsigned int::max would still be addressable.

**Review by bp-kelley — CHANGES_REQUESTED** [review]

File: Code/GraphMol/Conformer.h (hunk 1 above)
Comment (bp-kelley) [reply Code/GraphMol/Conformer.h:111]: This won't work on 32 bit builds, but do we care?

Comment (bp-kelley) [reply Code/GraphMol/Conformer.h:111]: I expect this unsigned int issue might exist in a few places, should we look for them?

Comment (greglandrum) [reply Code/GraphMol/Conformer.h:111]: > This won't work on 32 bit builds, but do we care?

nope. There's loads of code that'll break on 32bit builds

Comment (greglandrum) [reply Code/GraphMol/Conformer.h:111]: > I expect this unsigned int issue might exist in a few places, should we look for them?

I don't see any urgency to it. I'm happy to fix these fuzzing-discovered edge cases as they come up

**Comment by greglandrum** [comment]
@bp-kelley : what do you want changed here?

**Comment by bp-kelley** [comment]
It's more of a question than a change, but if we don't target 32 bits, then the change would be:

```
d_positions.resize( std::vector::size_type(atomId) + 1, RDGeom::Point3D(0.0, 0.0, 0.0));
```

**Comment by greglandrum** [comment]
> It's more of a question than a change, but if we don't target 32 bits, then the change would be:
> 
> ```
> d_positions.resize( std::vector::size_type(atomId) + 1, RDGeom::Point3D(0.0, 0.0, 0.0));
> ```

Sure, but I don't see what the benefit in doing that is. It allows the resize to succeed in this one very specific case (where `atomId` == unsigned::max) but doesn't help anywhere else. I mean, I don't really care... I can make this code change, but I wonder if you actually think it's important or if you're just pointing out that there's an alternate solution?

If we want to actually allow 64 bit atom indices (something I *really* question) we need to change large chunks of the API and a bunch of code. And that's not this PR.
