### PR TITLE
Fixes #5704

### LINKED ISSUE #5704: MolDraw2D should automatically set bond highlight color when atom colors are changed
**Describe the bug**
I noticed this while putting a tutorial notebook together.

Here's some code:
```
d2d = Draw.MolDraw2DSVG(250,200)
c1 = (.3,.3,1)
d2d.DrawMolecule(m,highlightAtoms=[0,1,2],highlightAtomColors={0:c1,1:c1,2:c1})
d2d.FinishDrawing()
SVG(d2d.GetDrawingText())
```
And the result:
image

**Expected behavior**
The bonds there should be the same color as the atoms. If the two end atoms are different colors, then it's fine to pick one of them.

**Configuration (please complete the following information):**
 - RDKit version: master
 - OS: all

### PR DESCRIPTION
**Pull request by greglandrum**
This is easy for cases where the begin and end atoms of the bond have the same color, but we need to make an arbitrary decision about which to pick if they differ or if one is color is specified and not the other.

Here we use the following logic to pick the bond highlight color:
1. Use the highlight color of the begin atom if it is set (this also covers the case when both atoms are set)
2. Use the highlight color of the end atom if it is set
3. Otherwise use the default highlight color

### CODE REVIEW

File: Code/GraphMol/MolDraw2D/DrawMol.cpp [hunk 1]
```diff
@@ -3322,15 +3324,36 @@ DrawColour getColourByAtomicNum(int atomic_num,
...
+      // the highlight colors of the begin/end atoms? Ideally these will both be
+      // the same, but we want to set the coloring even if that's not the
+      // case, so we'll use:
+      //  - begin atom color if that is set
+      //  - end atom color if that is set
+      //  - the default highlight color otherwise
+      if (highlightAtomMap.find(bond->getBeginAtomIdx()) !=
+          highlightAtomMap.end()) {
+        col = highlightAtomMap.find(bond->getBeginAtomIdx())->second;
+
```
Comment (DavidACosgrove) [inline Code/GraphMol/MolDraw2D/DrawMol.cpp:3352]: Is this a stray blank line?

**Review by DavidACosgrove — APPROVED** [review]
Looks good.

**Review by bp-kelley — APPROVED** [review]
